include::./index.adoc[]

[[v48-3-0]]
=== Aos Gálatas, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-3-1]]

^<<v48-3-1,1>>^ Ó gálatas insensatos! Quem foi que sujeitou vocês a essa má influência, vocês que receberam uma explicação tão clara sobre a morte de Jesus Cristo na estaca?

[[v48-3-2]]

^<<v48-3-2,2>>^ Há uma coisa que eu quero lhes perguntar:^&#42;1^ Foi por meio de obras exigidas por lei que vocês receberam o espírito, ou foi por causa da fé no que ouviram?

[NOTE]
====
. Lit.: “quero aprender de vocês”.
====

[[v48-3-3]]

^<<v48-3-3,3>>^ Será que vocês são tão insensatos? Depois de terem começado num caminho espiritual,^&#42;1^ estão terminando num caminho carnal?^&#42;2^

[NOTE]
====
. Lit.: “começado em espírito”.
. Lit.: “sendo completados na carne”.
====

[[v48-3-4]]

^<<v48-3-4,4>>^ Será que foi em vão que vocês sofreram tantas coisas? Tenho certeza de que não foi em vão!

[[v48-3-5]]

^<<v48-3-5,5>>^ Portanto, será que aquele que lhes fornece o espírito e realiza obras poderosas entre vocês faz isso por causa das suas obras exigidas por lei, ou por causa da sua fé no que ouviram?

[[v48-3-6]]

^<<v48-3-6,6>>^ É como aconteceu com Abraão: ele “depositou fé em Jeová,^&#42;1^ e isso lhe foi creditado como justiça”.^&#42;2^

[NOTE]
====
. Veja Ap. A5.
. Ou: “e foi considerado justo”.
====

[[v48-3-7]]

^<<v48-3-7,7>>^ Certamente vocês sabem que os que têm^&#42;1^ fé é que são filhos de Abraão.

[NOTE]
====
. Ou: “aderem à”.
====

[[v48-3-8]]

^<<v48-3-8,8>>^ Certa passagem das Escrituras, prevendo que Deus declararia justas pessoas das nações por meio da fé, declarou com antecedência as boas novas a Abraão, dizendo: “Por meio de você todas as nações serão abençoadas.”

[[v48-3-9]]

^<<v48-3-9,9>>^ Portanto, os que têm^&#42;1^ fé são abençoados junto com Abraão, que tinha fé.

[NOTE]
====
. Ou: “aderem à”.
====

[[v48-3-10]]

^<<v48-3-10,10>>^ Todos os que confiam em obras exigidas por lei estão sob maldição, pois está escrito: “Maldito é todo aquele que não continua em todas as coisas escritas no rolo da Lei, deixando de fazê-las.”

[[v48-3-11]]

^<<v48-3-11,11>>^ Além disso, é evidente que por lei ninguém é declarado justo diante de Deus, pois “o justo viverá em razão da fé”.

[[v48-3-12]]

^<<v48-3-12,12>>^ Ora, a Lei não se baseia em fé. Em vez disso, “quem fizer estas coisas viverá por meio delas”.

[[v48-3-13]]

^<<v48-3-13,13>>^ Cristo nos comprou, livrando-nos da maldição da Lei por se tornar maldição em nosso lugar, pois está escrito: “Maldito é todo aquele pendurado num madeiro.”

[[v48-3-14]]

^<<v48-3-14,14>>^ Isso aconteceu para que a bênção de Abraão se estendesse às nações por meio de Cristo Jesus, a fim de que recebêssemos o espírito prometido por meio da nossa fé.

[[v48-3-15]]

^<<v48-3-15,15>>^ Irmãos, falo usando uma ilustração humana: uma vez que um pacto é validado, mesmo que por um simples homem, ninguém o anula nem faz acréscimos a ele.

[[v48-3-16]]

^<<v48-3-16,16>>^ Ora, as promessas foram feitas a Abraão e ao seu descendente.^&#42;1^ As Escrituras não dizem “e aos seus descendentes”,^&#42;2^ como se fossem muitos. Em vez disso, dizem “e ao seu descendente”,^&#42;3^ indicando um só, que é Cristo.

[NOTE]
====
. Lit.: “à sua semente”.
. Lit.: “às sementes”.
. Lit.: “à sua semente”.
====

[[v48-3-17]]

^<<v48-3-17,17>>^ Além disso, digo o seguinte: A Lei, que veio à existência 430 anos depois, não invalida o pacto anteriormente feito por Deus, de modo a anular a promessa.

[[v48-3-18]]

^<<v48-3-18,18>>^ Pois, se a herança se baseia numa lei, não se baseia mais numa promessa; mas Deus a deu bondosamente a Abraão por meio de uma promessa.

[[v48-3-19]]

^<<v48-3-19,19>>^ Por que, então, a Lei? Ela foi acrescentada para tornar conhecidas as transgressões, até que chegasse o descendente^&#42;1^ a quem a promessa havia sido feita; e ela foi transmitida por meio de anjos, pela mão de um mediador.

[NOTE]
====
. Lit.: “a semente”.
====

[[v48-3-20]]

^<<v48-3-20,20>>^ Ora, não há mediador quando apenas uma pessoa está envolvida, mas Deus é apenas um.

[[v48-3-21]]

^<<v48-3-21,21>>^ Será que a Lei, então, é contra as promessas de Deus? De modo algum! Pois, se tivesse sido dada uma lei que fosse capaz de dar vida, a justiça teria realmente vindo por meio de lei.

[[v48-3-22]]

^<<v48-3-22,22>>^ Mas as Escrituras entregaram tudo à custódia do pecado, para que a promessa resultante da fé em Jesus Cristo fosse dada aos que exercessem fé.

[[v48-3-23]]

^<<v48-3-23,23>>^ No entanto, antes de chegar a fé, estávamos sendo guardados debaixo de lei, entregues à custódia, aguardando a fé que estava para ser revelada.

[[v48-3-24]]

^<<v48-3-24,24>>^ A Lei, portanto, tornou-se o nosso tutor,^&#42;1^ conduzindo a Cristo, para que fôssemos declarados justos por meio da fé.

[NOTE]
====
. Ou: “guardião”.
====

[[v48-3-25]]

^<<v48-3-25,25>>^ Mas, agora que chegou a fé, não estamos mais debaixo de um tutor.^&#42;1^

[NOTE]
====
. Ou: “guardião”.
====

[[v48-3-26]]

^<<v48-3-26,26>>^ Todos vocês são, de fato, filhos de Deus, por meio da sua fé em Cristo Jesus.

[[v48-3-27]]

^<<v48-3-27,27>>^ Pois todos vocês, que foram batizados em Cristo, se revestiram de Cristo.

[[v48-3-28]]

^<<v48-3-28,28>>^ Não há nem judeu nem grego, nem escravo nem homem livre, nem homem nem mulher; pois todos vocês são um só em união com Cristo Jesus.

[[v48-3-29]]

^<<v48-3-29,29>>^ Além disso, se vocês pertencem a Cristo, são realmente a descendência^&#42;1^ de Abraão, herdeiros segundo uma promessa.

[NOTE]
====
. Lit.: “semente”.
====

'''

xref:048-galatas/048-galatas-002.adoc#v48-2-0[&#60; Capítulo Anterior] | <<v48-3-0,Topo>> | xref:048-galatas/048-galatas-004.adoc#v48-4-0[Próximo Capítulo &#62;]