include::./index.adoc[]

[[v48-1-0]]
=== Aos Gálatas, 1
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v48-1-1]]

^<<v48-1-1,1>>^ Paulo, apóstolo não da parte de homens nem por homem algum, mas por Jesus Cristo e por Deus, o Pai, que o levantou dentre os mortos,

[[v48-1-2]]

^<<v48-1-2,2>>^ e todos os irmãos comigo, às congregações da Galácia:

[[v48-1-3]]

^<<v48-1-3,3>>^ Que vocês tenham bondade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v48-1-4]]

^<<v48-1-4,4>>^ Ele se entregou pelos nossos pecados a fim de nos livrar deste mundo mau,^&#42;1^ segundo a vontade do nosso Deus e Pai;

[NOTE]
====
. Ou: “sistema de coisas mau; época má”. Veja o Glossário.
====

[[v48-1-5]]

^<<v48-1-5,5>>^ a Ele seja dada a glória para todo o sempre. Amém.

[[v48-1-6]]

^<<v48-1-6,6>>^ Estou admirado de que vocês estejam se afastando^&#42;1^ tão depressa Daquele que os chamou com a bondade imerecida de Cristo, para seguirem outro tipo de boas novas.

[NOTE]
====
. Ou: “estejam sendo removidos”.
====

[[v48-1-7]]

^<<v48-1-7,7>>^ Não que haja outras boas novas, mas há alguns que estão perturbando vocês e querendo distorcer as boas novas a respeito do Cristo.

[[v48-1-8]]

^<<v48-1-8,8>>^ No entanto, mesmo que um de nós ou um anjo do céu lhes declare como boas novas algo além das boas novas que lhes declaramos, que ele seja amaldiçoado.

[[v48-1-9]]

^<<v48-1-9,9>>^ Como acabamos de dizer, digo agora novamente: Quem quer que esteja lhes declarando como boas novas algo além daquilo que vocês aceitaram, seja amaldiçoado.

[[v48-1-10]]

^<<v48-1-10,10>>^ É, de fato, a homens que estou buscando persuadir agora, ou é a Deus? Ou estou tentando agradar a homens? Se eu ainda estivesse agradando a homens, não seria escravo de Cristo.

[[v48-1-11]]

^<<v48-1-11,11>>^ Pois quero que saibam, irmãos, que as boas novas que eu declarei a vocês não são de origem humana;

[[v48-1-12]]

^<<v48-1-12,12>>^ porque não as recebi de um homem, e ninguém as ensinou a mim, mas elas me foram reveladas por Jesus Cristo.

[[v48-1-13]]

^<<v48-1-13,13>>^ Vocês, naturalmente, ouviram falar da minha conduta anterior no judaísmo, que eu perseguia intensamente^&#42;1^ a congregação de Deus e a devastava,

[NOTE]
====
. Lit.: “que até o excesso eu perseguia”.
====

[[v48-1-14]]

^<<v48-1-14,14>>^ e que eu fazia mais progresso no judaísmo do que muitos da minha nação que tinham a minha idade, visto que eu era muito mais zeloso das tradições de meus pais.

[[v48-1-15]]

^<<v48-1-15,15>>^ Mas, quando Deus, que causou o meu nascimento^&#42;1^ e me chamou por meio da Sua bondade imerecida, achou bom

[NOTE]
====
. Ou: “que me pôs à parte desde o nascimento”.
====

[[v48-1-16]]

^<<v48-1-16,16>>^ revelar o seu Filho por meu intermédio, para que eu declarasse às nações as boas novas a respeito dele, não fui imediatamente consultar homem algum;^&#42;1^

[NOTE]
====
. Lit.: “consultar carne e sangue”.
====

[[v48-1-17]]

^<<v48-1-17,17>>^ nem fui a Jerusalém, aos que eram apóstolos antes de mim, mas fui para a Arábia e depois voltei a Damasco.

[[v48-1-18]]

^<<v48-1-18,18>>^ Então, três anos depois, subi a Jerusalém para visitar Cefas^&#42;1^ e fiquei com ele 15 dias.

[NOTE]
====
. Também chamado de Pedro.
====

[[v48-1-19]]

^<<v48-1-19,19>>^ Mas não vi nenhum dos outros apóstolos, a não ser Tiago, o irmão do Senhor.

[[v48-1-20]]

^<<v48-1-20,20>>^ Quanto às coisas que estou escrevendo a vocês, eu lhes garanto, perante Deus, que não estou mentindo.

[[v48-1-21]]

^<<v48-1-21,21>>^ Depois disso, fui para as regiões da Síria e da Cilícia.

[[v48-1-22]]

^<<v48-1-22,22>>^ Mas as congregações da Judeia, que estavam em união com Cristo, não me conheciam pessoalmente.

[[v48-1-23]]

^<<v48-1-23,23>>^ Apenas ouviam dizer: “O homem que antes nos perseguia está agora declarando as boas novas a respeito da fé que antes devastava.”

[[v48-1-24]]

^<<v48-1-24,24>>^ De modo que começaram a glorificar a Deus por minha causa.

'''

xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[&#60; Capítulo Anterior] | <<v48-1-0,Topo>> | xref:048-galatas/048-galatas-002.adoc#v48-2-0[Próximo Capítulo &#62;]