include::./index.adoc[]

[[v50-2-0]]
=== Aos Filipenses, 2
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v50-2-1]]

^<<v50-2-1,1>>^ Se há, pois, algum encorajamento em Cristo, algum consolo de amor, algum companheirismo espiritual,^&#42;1^ algum terno sentimento e compaixão,

[NOTE]
====
. Lit.: “algum compartilhamento de espírito”.
====

[[v50-2-2]]

^<<v50-2-2,2>>^ tornem plena a minha alegria por terem o mesmo modo de pensar e o mesmo amor, sendo plenamente unidos,^&#42;1^ tendo o mesmo pensamento.

[NOTE]
====
. Ou: “sendo ajuntados na alma”.
====

[[v50-2-3]]

^<<v50-2-3,3>>^ Não façam nada por rivalidade nem por presunção; mas, com humildade,^&#42;1^ considerem os outros superiores a vocês,

[NOTE]
====
. Ou: “humildade mental”.
====

[[v50-2-4]]

^<<v50-2-4,4>>^ buscando não somente os seus próprios interesses, mas também os interesses dos outros.

[[v50-2-5]]

^<<v50-2-5,5>>^ Mantenham a mesma atitude que Cristo Jesus teve:

[[v50-2-6]]

^<<v50-2-6,6>>^ embora ele existisse em forma de Deus, nem mesmo chegou a pensar na ideia de tentar ser igual a Deus.

[[v50-2-7]]

^<<v50-2-7,7>>^ Pelo contrário, ele abriu mão de tudo que tinha,^&#42;1^ assumiu a forma de escravo e se tornou humano.^&#42;2^

[NOTE]
====
. Ou: “ele se esvaziou”.
. Lit.: “veio a ser na semelhança de homens”.
====

[[v50-2-8]]

^<<v50-2-8,8>>^ Mais do que isso, quando veio como homem,^&#42;1^ ele se humilhou e se tornou obediente a ponto de enfrentar a morte, sim, morte numa estaca.^&#42;2^

[NOTE]
====
. Lit.: “quando foi achado em aparência como um homem”.
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v50-2-9]]

^<<v50-2-9,9>>^ Por essa razão, Deus o enalteceu a uma posição superior e lhe deu bondosamente o nome que está acima de todo outro nome,

[[v50-2-10]]

^<<v50-2-10,10>>^ a fim de que, diante do nome de Jesus, se dobre todo joelho — dos que estão no céu, na terra e debaixo do chão —

[[v50-2-11]]

^<<v50-2-11,11>>^ e toda língua reconheça abertamente que Jesus Cristo é Senhor, para a glória de Deus, o Pai.

[[v50-2-12]]

^<<v50-2-12,12>>^ Portanto, meus amados, assim como vocês sempre obedeceram, não somente durante a minha presença, porém com muito mais prontidão agora durante a minha ausência, persistam em produzir a sua própria salvação com temor e tremor.

[[v50-2-13]]

^<<v50-2-13,13>>^ Pois Deus é aquele que, segundo o que lhe agrada, está agindo em vocês, e lhes dá tanto o desejo como o poder de agir.

[[v50-2-14]]

^<<v50-2-14,14>>^ Continuem fazendo todas as coisas sem queixas nem discussões,

[[v50-2-15]]

^<<v50-2-15,15>>^ para que venham a ser irrepreensíveis e inocentes, filhos de Deus sem defeito no meio de uma geração pervertida e corrompida, no meio da qual vocês estão brilhando como iluminadores no mundo,

[[v50-2-16]]

^<<v50-2-16,16>>^ mantendo-se firmemente agarrados à palavra da vida. Então terei motivo para me alegrar no dia de Cristo, por saber que eu não corri em vão nem me esforcei tanto em vão.

[[v50-2-17]]

^<<v50-2-17,17>>^ Contudo, mesmo que eu esteja sendo derramado como oferta de bebida sobre o sacrifício e o serviço sagrado^&#42;1^ que provém da sua fé,^&#42;2^ me alegro e compartilho a minha alegria com todos vocês.

[NOTE]
====
. Ou: “serviço público”.
. Ou: “serviço sagrado a que a sua fé os conduziu”.
====

[[v50-2-18]]

^<<v50-2-18,18>>^ Do mesmo modo, vocês também devem se alegrar e compartilhar a sua alegria comigo.

[[v50-2-19]]

^<<v50-2-19,19>>^ Espero no Senhor Jesus lhes enviar em breve Timóteo, para que eu fique encorajado ao receber notícias de vocês.

[[v50-2-20]]

^<<v50-2-20,20>>^ Pois não tenho a nenhum outro de disposição igual à dele, que cuidará genuinamente de vocês.

[[v50-2-21]]

^<<v50-2-21,21>>^ Pois todos os outros estão buscando os seus próprios interesses, não os de Jesus Cristo.

[[v50-2-22]]

^<<v50-2-22,22>>^ Mas vocês conhecem a prova que ele deu de si mesmo: ele trabalhou como escravo comigo na promoção das boas novas, como um filho junto ao pai.

[[v50-2-23]]

^<<v50-2-23,23>>^ Portanto, é a ele que espero enviar assim que eu souber o que vai acontecer comigo.

[[v50-2-24]]

^<<v50-2-24,24>>^ De fato, estou confiante no Senhor em que eu mesmo irei também em breve.

[[v50-2-25]]

^<<v50-2-25,25>>^ Mas, no momento, acho necessário lhes enviar Epafrodito, meu irmão, colaborador e companheiro de batalha, aquele que vocês enviaram para servir às minhas necessidades pessoais,

[[v50-2-26]]

^<<v50-2-26,26>>^ visto que ele deseja muito ver a todos vocês e está deprimido por terem ouvido que ele ficou doente.

[[v50-2-27]]

^<<v50-2-27,27>>^ De fato, ele adoeceu quase a ponto de morrer. Mas Deus teve misericórdia dele; na verdade, não só dele, mas também de mim, para que eu não tivesse uma tristeza após outra.

[[v50-2-28]]

^<<v50-2-28,28>>^ Por isso eu o envio com a maior urgência, para que, quando o virem, vocês se alegrem novamente, e eu fique menos ansioso.

[[v50-2-29]]

^<<v50-2-29,29>>^ Portanto, acolham-no como é de costume no Senhor, com toda a alegria, e continuem a prezar homens como ele,

[[v50-2-30]]

^<<v50-2-30,30>>^ porque ele quase morreu por causa da obra de Cristo,^&#42;1^ arriscando a vida^&#42;2^ para compensar o fato de que vocês não estavam aqui para prestar serviço a mim.

[NOTE]
====
. Ou, possivelmente: “do Senhor”.
. Ou: “expondo a sua alma ao perigo”.
====

'''

xref:050-filipenses/050-filipenses-001.adoc#v50-1-0[&#60; Capítulo Anterior] | <<v50-2-0,Topo>> | xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[Próximo Capítulo &#62;]