include::./index.adoc[]

[[v50-1-0]]
=== Aos Filipenses, 1
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v50-1-1]]

^<<v50-1-1,1>>^ Paulo e Timóteo, escravos de Cristo Jesus, a todos os santos em união com Cristo Jesus que estão em Filipos, junto com superintendentes e servos ministeriais:

[[v50-1-2]]

^<<v50-1-2,2>>^ Que vocês tenham bondade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v50-1-3]]

^<<v50-1-3,3>>^ Eu sempre agradeço a meu Deus quando me lembro de vocês,

[[v50-1-4]]

^<<v50-1-4,4>>^ em todas as minhas súplicas a favor de todos vocês. Eu faço cada súplica com alegria,

[[v50-1-5]]

^<<v50-1-5,5>>^ por causa da sua contribuição para^&#42;1^ as boas novas desde o primeiro dia até este momento.

[NOTE]
====
. Ou: “da sua participação em promover”.
====

[[v50-1-6]]

^<<v50-1-6,6>>^ Pois estou confiante no seguinte: aquele que começou uma boa obra em vocês a completará até o dia de Cristo Jesus.

[[v50-1-7]]

^<<v50-1-7,7>>^ É justo que eu pense assim a respeito de todos vocês, pois os tenho no meu coração, sim, vocês que participam comigo na bondade imerecida, tanto nas correntes que me prendem como em defender e estabelecer legalmente as boas novas.

[[v50-1-8]]

^<<v50-1-8,8>>^ Pois Deus é minha testemunha de que tenho muita saudade de todos vocês, com terno amor, como o de Cristo Jesus.

[[v50-1-9]]

^<<v50-1-9,9>>^ E isto é o que continuo a pedir em oração: que o seu amor se torne cada vez mais abundante, com conhecimento exato e pleno discernimento;

[[v50-1-10]]

^<<v50-1-10,10>>^ que vocês se certifiquem de quais são as coisas mais importantes, para que sejam sem defeito e não façam outros tropeçar, até o dia de Cristo;

[[v50-1-11]]

^<<v50-1-11,11>>^ e que fiquem cheios de fruto justo, que vem por meio de Jesus Cristo, para a glória e o louvor de Deus.

[[v50-1-12]]

^<<v50-1-12,12>>^ Quero que vocês saibam, irmãos, que a minha situação tem, na verdade, resultado no progresso das boas novas,

[[v50-1-13]]

^<<v50-1-13,13>>^ de modo que as correntes que me prendem por causa de Cristo se tornaram de conhecimento público entre toda a Guarda Pretoriana e todos os demais.

[[v50-1-14]]

^<<v50-1-14,14>>^ Agora, a maioria dos irmãos no Senhor ganhou confiança por causa das minhas correntes e está mostrando ainda mais coragem para falar destemidamente a palavra de Deus.

[[v50-1-15]]

^<<v50-1-15,15>>^ É verdade que alguns estão pregando o Cristo por inveja e rivalidade, mas outros com boa motivação.

[[v50-1-16]]

^<<v50-1-16,16>>^ Estes últimos estão proclamando o Cristo por amor, pois sabem que fui designado para defender as boas novas;

[[v50-1-17]]

^<<v50-1-17,17>>^ mas os primeiros fazem isso por rivalidade, não com uma motivação pura, pois querem causar problemas para mim enquanto estou preso.

[[v50-1-18]]

^<<v50-1-18,18>>^ Com que resultado? De qualquer maneira, quer em fingimento, quer em verdade, Cristo está sendo proclamado, e disso me alegro. De fato, continuarei a me alegrar,

[[v50-1-19]]

^<<v50-1-19,19>>^ porque sei que o resultado será a minha salvação, por meio das suas súplicas e com a ajuda do espírito de Jesus Cristo.

[[v50-1-20]]

^<<v50-1-20,20>>^ Isso está em harmonia com a minha viva expectativa e esperança de que não me envergonharei em nenhum sentido; mas de que, por eu falar com toda a coragem, Cristo será magnificado agora, como sempre foi, por meio do meu corpo, quer pela vida, quer pela morte.

[[v50-1-21]]

^<<v50-1-21,21>>^ Pois, no meu caso, viver é Cristo e morrer é ganho.

[[v50-1-22]]

^<<v50-1-22,22>>^ Mas, se for para continuar a viver na carne, isso^&#42;1^ é fruto da minha obra; contudo, eu não dou a conhecer qual seria a minha escolha.

[NOTE]
====
. Isto é, a magnificação de Cristo.
====

[[v50-1-23]]

^<<v50-1-23,23>>^ Estou num dilema entre essas duas coisas, pois desejo ser livrado e estar com Cristo, o que, certamente, é muito melhor.

[[v50-1-24]]

^<<v50-1-24,24>>^ No entanto, é mais necessário que eu permaneça na carne, por causa de vocês.

[[v50-1-25]]

^<<v50-1-25,25>>^ Então, convencido disso, sei que permanecerei e continuarei com todos vocês para seu progresso e sua alegria na fé.

[[v50-1-26]]

^<<v50-1-26,26>>^ Assim, a sua alegria transbordará em Cristo Jesus por minha causa, quando eu estiver de novo presente entre vocês.

[[v50-1-27]]

^<<v50-1-27,27>>^ Somente comportem-se^&#42;1^ de uma maneira digna das boas novas a respeito do Cristo, a fim de que, quer eu vá visitá-los, quer esteja ausente, eu ouça notícias suas e saiba que vocês se mantêm firmes em um só espírito, com uma só alma,^&#42;2^ esforçando-se lado a lado pela fé das boas novas,

[NOTE]
====
. Ou: “procedam como cidadãos”.
. Ou: “de comum acordo”.
====

[[v50-1-28]]

^<<v50-1-28,28>>^ sem se deixar intimidar em nada por seus oponentes. Isso, em si, é para eles prova de destruição; mas, para vocês, de salvação. E isso vem de Deus.

[[v50-1-29]]

^<<v50-1-29,29>>^ Porque vocês receberam o privilégio, pela causa de Cristo, não somente de depositar nele a sua fé, mas também de sofrer por ele.

[[v50-1-30]]

^<<v50-1-30,30>>^ Pois vocês estão enfrentando a mesma luta que me viram enfrentar e, como agora sabem, ainda enfrento.

'''

xref:049-efesios/049-efesios-006.adoc#v49-6-0[&#60; Capítulo Anterior] | <<v50-1-0,Topo>> | xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[Próximo Capítulo &#62;]