include::./index.adoc[]

[[v50-3-0]]
=== Aos Filipenses, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v50-3-1]]

^<<v50-3-1,1>>^ Por fim, meus irmãos, continuem a se alegrar no Senhor. Não é incômodo para mim lhes escrever as mesmas coisas, e é para a sua segurança.

[[v50-3-2]]

^<<v50-3-2,2>>^ Cuidado com os cães; cuidado com os que causam dano; cuidado com os que mutilam a carne.

[[v50-3-3]]

^<<v50-3-3,3>>^ Pois os que têm a verdadeira circuncisão somos nós, que prestamos serviço sagrado pelo espírito de Deus e nos orgulhamos em Cristo Jesus, e que não baseamos a nossa confiança na carne,

[[v50-3-4]]

^<<v50-3-4,4>>^ apesar de que eu, mais do que ninguém, tenho motivos para confiar na carne.
Se algum outro homem acha que tem motivos para confiar na carne, eu tenho mais:

[[v50-3-5]]

^<<v50-3-5,5>>^ circuncidado no oitavo dia, da nação de Israel, da tribo de Benjamim, hebreu nascido de hebreus; com respeito à Lei, fariseu;

[[v50-3-6]]

^<<v50-3-6,6>>^ com respeito ao zelo, perseguidor da congregação; com respeito à justiça^&#42;1^ baseada na Lei, alguém que se mostrou irrepreensível.

[NOTE]
====
. Veja o Glossário.
====

[[v50-3-7]]

^<<v50-3-7,7>>^ Contudo, as coisas que para mim eram ganho, eu considerei como perda^&#42;1^ por causa do Cristo.

[NOTE]
====
. Ou, possivelmente: “eu voluntariamente abandonei”.
====

[[v50-3-8]]

^<<v50-3-8,8>>^ Mais do que isso, considero realmente todas as coisas como perda, por causa do valor superior do conhecimento de Cristo Jesus, meu Senhor. Por causa dele aceitei a perda de todas as coisas e as considero simplesmente como lixo,^&#42;1^ para poder ganhar a Cristo

[NOTE]
====
. Ou: “refugo”.
====

[[v50-3-9]]

^<<v50-3-9,9>>^ e ser achado em união com ele, não por causa da minha própria justiça por seguir a Lei, mas por causa da justiça que vem por meio da fé em Cristo, a justiça que procede de Deus e se baseia na fé.

[[v50-3-10]]

^<<v50-3-10,10>>^ O que eu quero é conhecer a ele e o poder da sua ressurreição, e participar nos seus sofrimentos, submetendo-me a uma morte semelhante à dele,

[[v50-3-11]]

^<<v50-3-11,11>>^ para ver se de algum modo consigo alcançar a ressurreição dentre os mortos que ocorrerá mais cedo.

[[v50-3-12]]

^<<v50-3-12,12>>^ Não é que eu já tenha recebido isso, ou que eu já tenha me tornado perfeito, mas me empenho para, se possível, obter aquilo para o qual Cristo Jesus me escolheu.

[[v50-3-13]]

^<<v50-3-13,13>>^ Irmãos, não me considero ainda como o tendo obtido; mas uma coisa é certa: esquecendo-me das coisas atrás e esticando-me para alcançar as coisas à frente,

[[v50-3-14]]

^<<v50-3-14,14>>^ empenho-me para alcançar o alvo, a fim de receber o prêmio da chamada para cima da parte de Deus, por meio de Cristo Jesus.

[[v50-3-15]]

^<<v50-3-15,15>>^ Então, que todos nós que somos maduros tenhamos essa atitude; e, se em algum sentido vocês pensarem de outra maneira, Deus lhes revelará a atitude correta.^&#42;1^

[NOTE]
====
. Ou: “acima”.
====

[[v50-3-16]]

^<<v50-3-16,16>>^ De qualquer modo, seja qual for o progresso que já fizemos, prossigamos andando^&#42;1^ nesse mesmo rumo.

[NOTE]
====
. Ou: “andando ordeiramente”.
====

[[v50-3-17]]

^<<v50-3-17,17>>^ Irmãos, tornem-se unidamente meus imitadores, e observem os que andam de um modo que está de acordo com o exemplo que nós demos a vocês.

[[v50-3-18]]

^<<v50-3-18,18>>^ Pois há muitos — eu os mencionava muitas vezes, mas agora os menciono também chorando — que andam como inimigos da estaca^&#42;1^ do Cristo.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v50-3-19]]

^<<v50-3-19,19>>^ O fim deles é a destruição, o seu deus é o ventre, eles se orgulham do que deveriam se envergonhar e fixam a mente em coisas terrenas.

[[v50-3-20]]

^<<v50-3-20,20>>^ Mas a nossa cidadania está nos céus, de onde aguardamos ansiosamente um salvador, o Senhor Jesus Cristo,

[[v50-3-21]]

^<<v50-3-21,21>>^ que transformará nosso corpo humilde e o tornará como o^&#42;1^ seu corpo glorioso por meio do seu grande poder, que o torna capaz de sujeitar todas as coisas a si mesmo.

[NOTE]
====
. Lit.: “para ser conformado ao”.
====

'''

xref:050-filipenses/050-filipenses-002.adoc#v50-2-0[&#60; Capítulo Anterior] | <<v50-3-0,Topo>> | xref:050-filipenses/050-filipenses-004.adoc#v50-4-0[Próximo Capítulo &#62;]