include::./index.adoc[]

[[v50-4-0]]
=== Aos Filipenses, 4
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v50-4-1]]

^<<v50-4-1,1>>^ Portanto, meus irmãos, a quem eu amo e de quem tenho saudades, minha alegria e coroa, mantenham-se assim firmes no Senhor, meus amados.

[[v50-4-2]]

^<<v50-4-2,2>>^ Exorto Evódia e exorto Síntique a terem a mesma mentalidade no Senhor.

[[v50-4-3]]

^<<v50-4-3,3>>^ E peço a você também, como meu verdadeiro colaborador,^&#42;1^ que persista em ajudar essas mulheres que se esforçaram^&#42;2^ lado a lado comigo pelas boas novas, junto com Clemente e também com os outros colaboradores meus, cujos nomes estão no livro da vida.

[NOTE]
====
. Lit.: “genuíno companheiro de jugo”.
. Ou: “que lutaram arduamente”.
====

[[v50-4-4]]

^<<v50-4-4,4>>^ Alegrem-se sempre no Senhor. Novamente direi: Alegrem-se!

[[v50-4-5]]

^<<v50-4-5,5>>^ Que a sua razoabilidade seja conhecida de todos os homens. O Senhor está perto.

[[v50-4-6]]

^<<v50-4-6,6>>^ Não fiquem ansiosos por causa de coisa alguma, mas em tudo, por orações e súplicas, junto com agradecimentos, tornem os seus pedidos conhecidos a Deus;

[[v50-4-7]]

^<<v50-4-7,7>>^ e a paz de Deus, que está além de toda compreensão,^&#42;1^ guardará o seu coração e a sua mente^&#42;2^ por meio de Cristo Jesus.

[NOTE]
====
. Ou: “que supera todo pensamento”.
. Ou: “as suas faculdades mentais; os seus pensamentos”.
====

[[v50-4-8]]

^<<v50-4-8,8>>^ Por fim, irmãos, tudo que é verdadeiro, tudo que é de séria preocupação, tudo que é justo, tudo que é casto,^&#42;1^ tudo que é amável, tudo de que se fala bem, tudo que é virtuoso e tudo que é digno de louvor, continuem a considerar^&#42;2^ essas coisas.

[NOTE]
====
. Ou: “puro”.
. Ou: “pensar em; meditar em”.
====

[[v50-4-9]]

^<<v50-4-9,9>>^ Pratiquem as coisas que vocês aprenderam, receberam e ouviram de mim, bem como o que me viram fazer, e o Deus de paz estará com vocês.

[[v50-4-10]]

^<<v50-4-10,10>>^ Eu me alegro muito no Senhor de que agora, por fim, vocês renovaram o seu interesse por mim. Embora vocês se preocupassem comigo, faltava-lhes a oportunidade de demonstrar isso.

[[v50-4-11]]

^<<v50-4-11,11>>^ Não estou dizendo isso por estar passando necessidade, pois aprendi a ter contentamento^&#42;1^ em qualquer circunstância.

[NOTE]
====
. Ou: “ser autossuficiente”.
====

[[v50-4-12]]

^<<v50-4-12,12>>^ Eu sei viver com pouco e sei viver com muito. Em tudo e em todas as circunstâncias aprendi o segredo tanto de estar saciado como de ter fome, tanto de ter fartura como de passar necessidade.

[[v50-4-13]]

^<<v50-4-13,13>>^ Para todas as coisas tenho forças graças àquele que me dá poder.

[[v50-4-14]]

^<<v50-4-14,14>>^ Contudo, vocês fizeram bem em me ajudar na minha aflição.

[[v50-4-15]]

^<<v50-4-15,15>>^ De fato, vocês, filipenses, também sabem que, depois de vocês terem ouvido as boas novas pela primeira vez, quando parti da Macedônia, nenhuma congregação tomou parte comigo na questão de dar e receber, a não ser vocês;

[[v50-4-16]]

^<<v50-4-16,16>>^ pois, enquanto eu estava em Tessalônica, vocês me enviaram algo para as minhas necessidades não só uma vez, mas duas.

[[v50-4-17]]

^<<v50-4-17,17>>^ Não é que eu esteja buscando ganhar presentes, mas busco o fruto que resulta em mais crédito para a sua conta.

[[v50-4-18]]

^<<v50-4-18,18>>^ No entanto, tenho tudo de que preciso, e até mais do que isso. Estou suprido, agora que recebi de Epafrodito o que vocês me enviaram — um sacrifício aceitável, de aroma suave, agradável a Deus.

[[v50-4-19]]

^<<v50-4-19,19>>^ Meu Deus, por sua vez, lhes suprirá plenamente todas as necessidades segundo as Suas gloriosas riquezas, por meio de Cristo Jesus.

[[v50-4-20]]

^<<v50-4-20,20>>^ Ao nosso Deus e Pai seja dada a glória para todo o sempre. Amém.

[[v50-4-21]]

^<<v50-4-21,21>>^ Transmitam minhas saudações a todos os santos em união com Cristo Jesus. Os irmãos que estão comigo mandam saudações a vocês.

[[v50-4-22]]

^<<v50-4-22,22>>^ Todos os santos, mas especialmente os da casa de César, lhes mandam saudações.

[[v50-4-23]]

^<<v50-4-23,23>>^ Que a bondade imerecida do Senhor Jesus Cristo esteja com o espírito que vocês mostram.

'''

xref:050-filipenses/050-filipenses-003.adoc#v50-3-0[&#60; Capítulo Anterior] | <<v50-4-0,Topo>> | xref:051-colossenses/051-colossenses-001.adoc#v51-1-0[Próximo Capítulo &#62;]