include::./index.adoc[]

[[v42-18-0]]
=== Segundo Lucas, 18
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-18-1]]

^<<v42-18-1,1>>^ Depois lhes contou uma ilustração a respeito da necessidade de sempre orarem e de nunca desistirem,

[[v42-18-2]]

^<<v42-18-2,2>>^ dizendo: “Em certa cidade havia um juiz que não temia a Deus nem respeitava homem algum.

[[v42-18-3]]

^<<v42-18-3,3>>^ Havia também naquela cidade uma viúva, e ela persistia em ir a ele e a dizer: ‘Faça-me justiça contra o meu adversário.’

[[v42-18-4]]

^<<v42-18-4,4>>^ Pois bem, por um tempo ele não estava disposto a fazer isso, mas depois disse para si mesmo: ‘Eu não temo a Deus nem respeito nenhum homem,

[[v42-18-5]]

^<<v42-18-5,5>>^ mas, visto que essa viúva fica me incomodando, farei justiça a ela para que não continue vindo me importunar com seu pedido até eu não suportar mais.’”^&#42;1^

[NOTE]
====
. Ou: “pedido, esmurrando-me até o fim”.
====

[[v42-18-6]]

^<<v42-18-6,6>>^ O Senhor disse então: “Ouçam o que o juiz, embora injusto, disse!

[[v42-18-7]]

^<<v42-18-7,7>>^ Certamente, então, será que Deus não providenciará que seja feita justiça aos seus escolhidos, que clamam a ele dia e noite, ao passo que é paciente com eles?

[[v42-18-8]]

^<<v42-18-8,8>>^ Eu lhes digo: Ele providenciará que seja feita justiça a eles rapidamente. Contudo, quando o Filho do Homem chegar, achará realmente essa fé^&#42;1^ na terra?”

[NOTE]
====
. Ou: “esse tipo de fé”. Lit.: “a fé”.
====

[[v42-18-9]]

^<<v42-18-9,9>>^ Ele também contou a seguinte ilustração a alguns que confiavam na sua própria justiça e consideravam os outros como nada:

[[v42-18-10]]

^<<v42-18-10,10>>^ “Dois homens subiram ao templo para orar: um era fariseu, o outro era cobrador de impostos.

[[v42-18-11]]

^<<v42-18-11,11>>^ O fariseu ficou em pé e começou a orar o seguinte no íntimo: ‘Ó Deus, eu te agradeço que não sou como todos os outros: extorsores, injustos, adúlteros; nem mesmo como este cobrador de impostos.

[[v42-18-12]]

^<<v42-18-12,12>>^ Jejuo duas vezes por semana, dou o décimo de tudo que adquiro.’

[[v42-18-13]]

^<<v42-18-13,13>>^ Mas o cobrador de impostos, parado à distância, não queria nem levantar os olhos para o céu, mas batia no peito, dizendo: ‘Ó Deus, tem misericórdia de mim,^&#42;1^ um pecador.’

[NOTE]
====
. Ou: “sê benevolente comigo”.
====

[[v42-18-14]]

^<<v42-18-14,14>>^ Eu lhes digo: Este homem desceu para casa mais justo do que aquele fariseu. Porque todo aquele que se enaltecer será humilhado, mas quem se humilhar será enaltecido.”

[[v42-18-15]]

^<<v42-18-15,15>>^ As pessoas também lhe traziam suas crianças de colo, para que ele tocasse nelas; mas, quando viram isso, os discípulos começaram a repreender as pessoas.

[[v42-18-16]]

^<<v42-18-16,16>>^ No entanto, Jesus mandou trazer a si as crianças de colo, dizendo: “Deixem as criancinhas vir a mim e não tentem impedi-las, pois o Reino de Deus pertence aos que são como elas.

[[v42-18-17]]

^<<v42-18-17,17>>^ Eu lhes digo a verdade: Quem não receber o Reino de Deus como uma criancinha, de modo algum entrará nele.”

[[v42-18-18]]

^<<v42-18-18,18>>^ E um dos líderes dos judeus lhe perguntou: “Bom Instrutor, o que devo fazer para herdar a vida eterna?”

[[v42-18-19]]

^<<v42-18-19,19>>^ Jesus lhe disse: “Por que você me chama de bom? Ninguém é bom, a não ser um só, Deus.

[[v42-18-20]]

^<<v42-18-20,20>>^ Você conhece os mandamentos: ‘Não cometa adultério, não assassine, não furte, não dê falso testemunho, honre seu pai e sua mãe.’”

[[v42-18-21]]

^<<v42-18-21,21>>^ O homem disse então: “Tenho cumprido todos esses desde bem jovem.”

[[v42-18-22]]

^<<v42-18-22,22>>^ Ao ouvir isso, Jesus lhe disse: “Ainda há uma coisa que falta a seu respeito: venda tudo o que você tem e distribua o dinheiro aos pobres, e você terá um tesouro nos céus; e venha ser meu seguidor.”

[[v42-18-23]]

^<<v42-18-23,23>>^ Quando ouviu isso, ele ficou profundamente triste, porque era muito rico.

[[v42-18-24]]

^<<v42-18-24,24>>^ Jesus olhou para ele e disse: “Como será difícil para os que têm dinheiro entrar no Reino de Deus!

[[v42-18-25]]

^<<v42-18-25,25>>^ De fato, é mais fácil um camelo passar pelo buraco de uma agulha de costura, do que um rico entrar no Reino de Deus.”

[[v42-18-26]]

^<<v42-18-26,26>>^ Os que ouviram isso disseram: “Quem é que pode ser salvo?”

[[v42-18-27]]

^<<v42-18-27,27>>^ Ele disse: “As coisas impossíveis para os homens são possíveis para Deus.”

[[v42-18-28]]

^<<v42-18-28,28>>^ Mas Pedro disse: “Veja, deixamos tudo que tínhamos e seguimos o senhor.”

[[v42-18-29]]

^<<v42-18-29,29>>^ Ele lhes disse: “Eu lhes garanto: Não há ninguém que tenha deixado casa, esposa, irmãos, pais ou filhos por causa do Reino de Deus

[[v42-18-30]]

^<<v42-18-30,30>>^ que não receba muitas vezes mais neste tempo e, no futuro sistema de coisas,^&#42;1^ a vida eterna.”

[NOTE]
====
. Ou: “na época futura”. Veja o Glossário.
====

[[v42-18-31]]

^<<v42-18-31,31>>^ Então ele chamou os Doze à parte e lhes disse: “Escutem, estamos subindo para Jerusalém, e se realizarão^&#42;1^ todas as coisas escritas por meio dos profetas a respeito do Filho do Homem.

[NOTE]
====
. Ou: “se completarão”.
====

[[v42-18-32]]

^<<v42-18-32,32>>^ Por exemplo, ele será entregue a homens das nações, e zombarão dele, o maltratarão e cuspirão nele.

[[v42-18-33]]

^<<v42-18-33,33>>^ E, depois de açoitá-lo, o matarão, mas no terceiro dia ele será levantado.”

[[v42-18-34]]

^<<v42-18-34,34>>^ No entanto, eles não compreenderam o significado de nada disso, pois o sentido dessas palavras estava escondido deles, e eles não entenderam o que foi dito.

[[v42-18-35]]

^<<v42-18-35,35>>^ Quando Jesus estava chegando perto de Jericó, um cego estava sentado à beira da estrada, mendigando.

[[v42-18-36]]

^<<v42-18-36,36>>^ Visto que ouviu uma multidão passando, ele perguntou o que estava acontecendo.

[[v42-18-37]]

^<<v42-18-37,37>>^ Disseram-lhe: “Jesus, o Nazareno, está passando!”

[[v42-18-38]]

^<<v42-18-38,38>>^ Em vista disso, ele gritou: “Jesus, Filho de Davi, tenha misericórdia de mim!”

[[v42-18-39]]

^<<v42-18-39,39>>^ E os que estavam na frente começaram a censurá-lo, mandando que ficasse calado, mas ele gritava ainda mais: “Filho de Davi, tenha misericórdia de mim!”

[[v42-18-40]]

^<<v42-18-40,40>>^ Jesus parou, então, e ordenou que o homem lhe fosse trazido. Depois que ele se aproximou, Jesus lhe perguntou:

[[v42-18-41]]

^<<v42-18-41,41>>^ “O que você quer que eu faça por você?” Ele disse: “Senhor, deixe-me recuperar a visão.”

[[v42-18-42]]

^<<v42-18-42,42>>^ De modo que Jesus lhe disse: “Recupere a visão. A sua fé fez você ficar bom.”

[[v42-18-43]]

^<<v42-18-43,43>>^ E ele recuperou instantaneamente a visão e começou a segui-lo, glorificando a Deus. Também todas as pessoas, ao verem isso, deram louvor a Deus.

'''

xref:042-lucas/042-lucas-017.adoc#v42-17-0[&#60; Capítulo Anterior] | <<v42-18-0,Topo>> | xref:042-lucas/042-lucas-019.adoc#v42-19-0[Próximo Capítulo &#62;]