include::./index.adoc[]

[[v42-17-0]]
=== Segundo Lucas, 17
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-17-1]]

^<<v42-17-1,1>>^ Então ele disse aos seus discípulos: “É inevitável que surjam motivos para tropeço. Contudo, ai daquele por meio de quem eles surgem!

[[v42-17-2]]

^<<v42-17-2,2>>^ Seria melhor para ele que pendurassem no seu pescoço uma pedra de moinho e que fosse lançado no mar, do que ele fazer tropeçar um destes pequenos.

[[v42-17-3]]

^<<v42-17-3,3>>^ Prestem atenção a si mesmos. Se o seu irmão cometer um pecado, censure-o e, se ele se arrepender, perdoe-lhe.

[[v42-17-4]]

^<<v42-17-4,4>>^ Mesmo que ele peque contra você sete vezes por dia e volte a você sete vezes, dizendo: ‘Eu me arrependo’, você tem de lhe perdoar.”

[[v42-17-5]]

^<<v42-17-5,5>>^ Os apóstolos disseram então ao Senhor: “Dê-nos mais fé.”

[[v42-17-6]]

^<<v42-17-6,6>>^ O Senhor disse então: “Se vocês tivessem fé do tamanho de um grão de mostarda, diriam a esta amoreira-preta: ‘Arranque-se daí e plante-se no mar!’ e ela lhes obedeceria.

[[v42-17-7]]

^<<v42-17-7,7>>^ “Quem de vocês, caso tenha um escravo que esteja arando ou cuidando do rebanho, lhe dirá quando ele chegar do campo: ‘Venha imediatamente à mesa para comer’?

[[v42-17-8]]

^<<v42-17-8,8>>^ Em vez disso, não lhe dirá: ‘Prepare algo para o meu jantar, ponha o avental e sirva-me até eu acabar de comer e beber; depois você pode comer e beber’?

[[v42-17-9]]

^<<v42-17-9,9>>^ Será que ele sentirá gratidão pelo escravo porque este fez o que lhe foi designado?

[[v42-17-10]]

^<<v42-17-10,10>>^ Da mesma forma, quando vocês tiverem feito todas as coisas que lhes foram designadas, digam: ‘Somos escravos imprestáveis. O que fizemos é o que devíamos fazer.’”

[[v42-17-11]]

^<<v42-17-11,11>>^ A caminho de Jerusalém, ele passou entre Samaria e a Galileia.

[[v42-17-12]]

^<<v42-17-12,12>>^ Ao entrar numa aldeia, dez homens com lepra foram ao encontro dele, mas ficaram à distância.

[[v42-17-13]]

^<<v42-17-13,13>>^ E levantaram a voz, dizendo: “Jesus, Instrutor, tenha misericórdia de nós!”

[[v42-17-14]]

^<<v42-17-14,14>>^ Quando os viu, disse-lhes: “Vão se mostrar aos sacerdotes.” Então, enquanto se afastavam, eles foram purificados.

[[v42-17-15]]

^<<v42-17-15,15>>^ Um deles, quando viu que estava curado, voltou, glorificando a Deus em alta voz.

[[v42-17-16]]

^<<v42-17-16,16>>^ E se prostrou com o rosto por terra aos pés de Jesus, agradecendo-lhe. E ele era samaritano.

[[v42-17-17]]

^<<v42-17-17,17>>^ Jesus disse em resposta: “Todos os dez foram purificados, não foram? Então, onde estão os outros nove?

[[v42-17-18]]

^<<v42-17-18,18>>^ Nenhum deles voltou para dar glória a Deus, a não ser este homem de outra nação?”

[[v42-17-19]]

^<<v42-17-19,19>>^ Então ele lhe disse: “Levante-se e vá. A sua fé fez você ficar bom.”

[[v42-17-20]]

^<<v42-17-20,20>>^ Os fariseus lhe perguntaram quando viria o Reino de Deus, e ele lhes respondeu: “O Reino de Deus não vem de modo claramente observável,

[[v42-17-21]]

^<<v42-17-21,21>>^ nem as pessoas dirão: ‘Vejam, está aqui!’ ou: ‘Está ali!’ Pois saibam que o Reino de Deus está no meio de^&#42;1^ vocês.”

[NOTE]
====
. Ou: “está entre”.
====

[[v42-17-22]]

^<<v42-17-22,22>>^ Ele disse então aos discípulos: “Virá o tempo em que vocês desejarão ver um dos dias do Filho do Homem, mas não verão.

[[v42-17-23]]

^<<v42-17-23,23>>^ E as pessoas lhes dirão: ‘Vejam, está ali!’ ou: ‘Vejam, está aqui!’ Não saiam nem corram atrás delas.

[[v42-17-24]]

^<<v42-17-24,24>>^ Pois, assim como o relâmpago ilumina o céu de um lado a outro, assim será o Filho do Homem no seu dia.

[[v42-17-25]]

^<<v42-17-25,25>>^ Primeiro, porém, ele tem de sofrer muitas coisas e ser rejeitado por esta geração.

[[v42-17-26]]

^<<v42-17-26,26>>^ Além disso, assim como ocorreu nos dias de Noé, assim será nos dias do Filho do Homem:

[[v42-17-27]]

^<<v42-17-27,27>>^ as pessoas comiam, bebiam, os homens se casavam, as mulheres eram dadas em casamento, até aquele dia em que Noé entrou na arca, e veio o dilúvio e destruiu a todos.

[[v42-17-28]]

^<<v42-17-28,28>>^ Do mesmo modo, será como ocorreu nos dias de Ló: as pessoas comiam, bebiam, compravam, vendiam, plantavam, construíam.

[[v42-17-29]]

^<<v42-17-29,29>>^ Mas, no dia em que Ló saiu de Sodoma, choveu do céu fogo e enxofre, e destruiu a todos.

[[v42-17-30]]

^<<v42-17-30,30>>^ Acontecerá o mesmo naquele dia em que o Filho do Homem for revelado.

[[v42-17-31]]

^<<v42-17-31,31>>^ “Naquele dia, quem estiver no terraço, mas cujas coisas estiverem na casa, não desça para apanhá-las, e, do mesmo modo, quem estiver no campo não deve voltar para as coisas deixadas atrás.

[[v42-17-32]]

^<<v42-17-32,32>>^ Lembrem-se da mulher de Ló.

[[v42-17-33]]

^<<v42-17-33,33>>^ Quem procurar salvar a sua vida^&#42;1^ a perderá, mas quem perder a sua vida a preservará.

[NOTE]
====
. Ou: “alma”.
====

[[v42-17-34]]

^<<v42-17-34,34>>^ Eu lhes digo: Naquela noite, duas pessoas estarão numa cama; uma será levada, mas a outra será abandonada.

[[v42-17-35]]

^<<v42-17-35,35>>^ Haverá duas mulheres moendo no mesmo moinho: uma será levada, mas a outra será abandonada.”

[[v42-17-36]]

^<<v42-17-36,36>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v42-17-37]]

^<<v42-17-37,37>>^ Em vista disso, disseram-lhe: “Onde, Senhor?” Ele lhes disse: “Onde estiver o corpo, ali também se ajuntarão as águias.”

'''

xref:042-lucas/042-lucas-016.adoc#v42-16-0[&#60; Capítulo Anterior] | <<v42-17-0,Topo>> | xref:042-lucas/042-lucas-018.adoc#v42-18-0[Próximo Capítulo &#62;]