include::./index.adoc[]

[[v42-24-0]]
=== Segundo Lucas, 24
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-24-1]]

^<<v42-24-1,1>>^ No primeiro dia da semana, porém, elas chegaram bem cedo ao túmulo,^&#42;1^ levando os aromas que tinham preparado.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-2]]

^<<v42-24-2,2>>^ Mas viram que a pedra da entrada do túmulo^&#42;1^ havia sido rolada

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-3]]

^<<v42-24-3,3>>^ e, quando entraram, não acharam o corpo do Senhor Jesus.

[[v42-24-4]]

^<<v42-24-4,4>>^ Enquanto estavam perplexas com isso, dois homens de roupa brilhante apareceram ao lado delas.

[[v42-24-5]]

^<<v42-24-5,5>>^ As mulheres ficaram com medo e mantiveram a cabeça voltada para o chão; então os homens lhes disseram: “Por que estão procurando entre os mortos aquele que está vivo?

[[v42-24-6]]

^<<v42-24-6,6>>^ Ele não está aqui, mas foi levantado. Lembrem-se de que, enquanto ainda estava na Galileia, ele lhes disse

[[v42-24-7]]

^<<v42-24-7,7>>^ que o Filho do Homem tinha de ser entregue a pecadores, ser morto na estaca e no terceiro dia ser levantado.”

[[v42-24-8]]

^<<v42-24-8,8>>^ E elas se lembraram das palavras dele;

[[v42-24-9]]

^<<v42-24-9,9>>^ então voltaram do túmulo^&#42;1^ e contaram todas essas coisas aos Onze e a todos os demais.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-10]]

^<<v42-24-10,10>>^ Eram Maria Madalena, Joana e Maria, mãe de Tiago. Também as outras mulheres com elas contaram essas coisas aos apóstolos.

[[v42-24-11]]

^<<v42-24-11,11>>^ No entanto, essas declarações pareciam tolice para eles, e eles se recusavam a acreditar nas mulheres.

[[v42-24-12]]

^<<v42-24-12,12>>^ Mas Pedro se levantou e correu para o túmulo;^&#42;1^ e, inclinando-se para a frente, viu somente os panos de linho. Assim, ele foi embora, perguntando-se o que poderia ter ocorrido.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-13]]

^<<v42-24-13,13>>^ Mas aconteceu, naquele mesmo dia, que dois deles estavam viajando para uma aldeia chamada Emaús, a cerca de 11 quilômetros^&#42;1^ de Jerusalém,

[NOTE]
====
. Lit.: “60 estádios”. Um estádio equivalia a 185 m. Veja Ap. B14.
====

[[v42-24-14]]

^<<v42-24-14,14>>^ e estavam conversando sobre todas as coisas que tinham acontecido.

[[v42-24-15]]

^<<v42-24-15,15>>^ Enquanto conversavam e discutiam essas coisas, o próprio Jesus se aproximou e começou a andar com eles,

[[v42-24-16]]

^<<v42-24-16,16>>^ mas os olhos deles foram impedidos de reconhecê-lo.

[[v42-24-17]]

^<<v42-24-17,17>>^ Ele lhes perguntou: “Sobre o que é que vocês estão conversando^&#42;1^ enquanto caminham?” E eles pararam, com o rosto triste.

[NOTE]
====
. Ou: “discutindo”.
====

[[v42-24-18]]

^<<v42-24-18,18>>^ Em resposta, aquele chamado Cléopas lhe disse: “Será que você é um estrangeiro que vive sozinho em Jerusalém e não sabe^&#42;1^ das coisas que ocorreram lá nestes dias?”

[NOTE]
====
. Ou, possivelmente: “Será que você é o único visitante em Jerusalém que não sabe”.
====

[[v42-24-19]]

^<<v42-24-19,19>>^ Ele lhes perguntou: “Que coisas?” Responderam: “As coisas a respeito de Jesus, o Nazareno, que foi um profeta poderoso em ações e palavras perante Deus e todo o povo;

[[v42-24-20]]

^<<v42-24-20,20>>^ e os nossos principais sacerdotes e os nossos líderes o entregaram para ser condenado à morte e o pregaram na estaca.

[[v42-24-21]]

^<<v42-24-21,21>>^ Mas nós esperávamos que esse homem fosse aquele que ia livrar Israel. E além de tudo isso, este já é o terceiro dia desde que essas coisas ocorreram.

[[v42-24-22]]

^<<v42-24-22,22>>^ Também, algumas mulheres entre nós nos deixaram pasmados, porque foram cedo ao túmulo^&#42;1^

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-23]]

^<<v42-24-23,23>>^ e, quando não acharam o corpo dele, voltaram dizendo que haviam tido também uma visão sobrenatural de anjos, que disseram que ele está vivo.

[[v42-24-24]]

^<<v42-24-24,24>>^ Então, alguns dos que estavam conosco foram ao túmulo^&#42;1^ e encontraram tudo exatamente como as mulheres tinham dito, mas não o viram.”

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-24-25]]

^<<v42-24-25,25>>^ Assim, ele lhes disse: “Como vocês são insensatos e demoram a^&#42;1^ crer em todas as coisas faladas pelos profetas!

[NOTE]
====
. Ou: “e lentos de coração para”.
====

[[v42-24-26]]

^<<v42-24-26,26>>^ Não era necessário que o Cristo sofresse essas coisas e entrasse na sua glória?”

[[v42-24-27]]

^<<v42-24-27,27>>^ E, começando por Moisés e por todos os Profetas, interpretou-lhes as coisas a respeito de si mesmo em todas as Escrituras.

[[v42-24-28]]

^<<v42-24-28,28>>^ Por fim chegaram perto da aldeia para a qual viajavam, e ele fez como se fosse viajar para mais longe.

[[v42-24-29]]

^<<v42-24-29,29>>^ Mas eles insistiram que ele ficasse, dizendo: “Fique conosco, porque já está anoitecendo e o dia está quase terminando.” Em vista disso, entrou para ficar com eles.

[[v42-24-30]]

^<<v42-24-30,30>>^ E, enquanto estava comendo^&#42;1^ com eles, pegou o pão, deu graças,^&#42;2^ partiu-o e começou a dá-lo a eles.

[NOTE]
====
. Ou: “recostado à mesa”.
. Ou: “o abençoou”.
====

[[v42-24-31]]

^<<v42-24-31,31>>^ Com isso os olhos deles foram plenamente abertos e eles o reconheceram; mas ele desapareceu de diante deles.

[[v42-24-32]]

^<<v42-24-32,32>>^ E disseram um ao outro: “Não sentíamos arder o coração dentro de nós quando ele nos falava na estrada, ao nos abrir plenamente^&#42;1^ as Escrituras?”

[NOTE]
====
. Ou: “explicar claramente”.
====

[[v42-24-33]]

^<<v42-24-33,33>>^ Eles se levantaram então naquela mesma hora, voltaram a Jerusalém e encontraram os Onze e os que estavam com eles reunidos;

[[v42-24-34]]

^<<v42-24-34,34>>^ estavam dizendo: “De fato, o Senhor foi levantado e apareceu a Simão!”

[[v42-24-35]]

^<<v42-24-35,35>>^ Então contaram o que tinha acontecido na estrada e como eles o reconheceram quando ele partiu o pão.

[[v42-24-36]]

^<<v42-24-36,36>>^ Enquanto ainda falavam dessas coisas, o próprio Jesus apareceu no meio deles e lhes disse: “Que a paz esteja com vocês.”

[[v42-24-37]]

^<<v42-24-37,37>>^ Mas eles, espantados e com medo, pensaram que estavam vendo um espírito.

[[v42-24-38]]

^<<v42-24-38,38>>^ De modo que ele lhes disse: “Por que estão aflitos e por que surgem dúvidas no seu coração?

[[v42-24-39]]

^<<v42-24-39,39>>^ Vejam minhas mãos e meus pés, que sou eu mesmo. Toquem-me e vejam, pois um espírito não tem carne nem ossos assim como vocês veem que eu tenho.”

[[v42-24-40]]

^<<v42-24-40,40>>^ E, ao dizer isso, mostrou-lhes as mãos e os pés.

[[v42-24-41]]

^<<v42-24-41,41>>^ Mas eles ainda não acreditavam, de tanta alegria e surpresa. Então ele lhes disse: “Vocês têm aqui algo para comer?”

[[v42-24-42]]

^<<v42-24-42,42>>^ Então lhe entregaram um pedaço de peixe assado,

[[v42-24-43]]

^<<v42-24-43,43>>^ e ele o pegou e comeu diante dos olhos deles.

[[v42-24-44]]

^<<v42-24-44,44>>^ Ele lhes disse então: “Estas são as minhas palavras, que lhes falei enquanto ainda estava com vocês, que todas as coisas escritas a meu respeito na Lei de Moisés, nos Profetas e nos Salmos têm de se cumprir.”

[[v42-24-45]]

^<<v42-24-45,45>>^ Então ele abriu a mente deles para que compreendessem o significado das Escrituras

[[v42-24-46]]

^<<v42-24-46,46>>^ e lhes disse: “Está escrito que o Cristo sofreria e no terceiro dia seria levantado dentre os mortos,

[[v42-24-47]]

^<<v42-24-47,47>>^ e que, em seu nome, se pregaria arrependimento para o perdão de pecados em todas as nações, começando por Jerusalém.

[[v42-24-48]]

^<<v42-24-48,48>>^ Vocês serão testemunhas dessas coisas.

[[v42-24-49]]

^<<v42-24-49,49>>^ E saibam que enviarei sobre vocês o que foi prometido pelo meu Pai. Vocês, porém, permaneçam na cidade até serem revestidos de poder vindo do alto.”

[[v42-24-50]]

^<<v42-24-50,50>>^ Então ele os levou para fora, até Betânia, ergueu as mãos e os abençoou.

[[v42-24-51]]

^<<v42-24-51,51>>^ Enquanto os abençoava, foi separado deles e levado para o céu.

[[v42-24-52]]

^<<v42-24-52,52>>^ E se curvaram diante dele^&#42;1^ e voltaram para Jerusalém com grande alegria.

[NOTE]
====
. Ou: “lhe prestaram homenagem”.
====

[[v42-24-53]]

^<<v42-24-53,53>>^ E estavam constantemente no templo, louvando a Deus.

'''

xref:042-lucas/042-lucas-023.adoc#v42-23-0[&#60; Capítulo Anterior] | <<v42-24-0,Topo>> | xref:043-joao/043-joao-001.adoc#v43-1-0[Próximo Capítulo &#62;]