include::./index.adoc[]

[[v42-7-0]]
=== Segundo Lucas, 7
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-7-1]]

^<<v42-7-1,1>>^ Depois que terminou o que tinha a dizer ao povo, ele entrou em Cafarnaum.

[[v42-7-2]]

^<<v42-7-2,2>>^ E o escravo de um oficial do exército estava gravemente doente e prestes a morrer; esse escravo era muito estimado pelo seu senhor.

[[v42-7-3]]

^<<v42-7-3,3>>^ Quando o oficial ouviu falar de Jesus, enviou-lhe alguns anciãos dos judeus para lhe pedirem que viesse e curasse seu escravo.

[[v42-7-4]]

^<<v42-7-4,4>>^ Eles foram a Jesus e começaram a lhe suplicar com insistência: “Ele merece a ajuda do senhor,

[[v42-7-5]]

^<<v42-7-5,5>>^ porque ama a nossa nação e ele mesmo construiu nossa sinagoga.”

[[v42-7-6]]

^<<v42-7-6,6>>^ Assim, Jesus foi com eles. Mas, quando ele estava perto da casa, o oficial do exército enviou amigos para lhe dizer: “Senhor, não se incomode, pois não sou digno de recebê-lo debaixo do meu teto.

[[v42-7-7]]

^<<v42-7-7,7>>^ É por isso que não me considerei digno de ir até o senhor. Mas diga a palavra, e meu servo será curado.

[[v42-7-8]]

^<<v42-7-8,8>>^ Pois eu também sou homem sujeito a autoridade e tenho soldados sob as minhas ordens, e digo a um: ‘Vá!’ e ele vai, e a outro: ‘Venha!’ e ele vem, e ao meu escravo: ‘Faça isto!’ e ele faz.”

[[v42-7-9]]

^<<v42-7-9,9>>^ Quando Jesus ouviu isso, ficou admirado com ele e, virando-se para a multidão que o seguia, disse: “Eu lhes digo: Nem mesmo em Israel encontrei tamanha fé.”

[[v42-7-10]]

^<<v42-7-10,10>>^ E, ao voltarem para casa, os que tinham sido enviados encontraram o escravo com boa saúde.

[[v42-7-11]]

^<<v42-7-11,11>>^ Logo depois disso, ele viajou para uma cidade chamada Naim, e seus discípulos e uma grande multidão viajavam com ele.

[[v42-7-12]]

^<<v42-7-12,12>>^ No momento em que se aproximava do portão da cidade, um morto estava sendo carregado para fora, o filho único^&#42;1^ de sua mãe. Além disso, ela era viúva. Uma multidão considerável da cidade também a acompanhava.

[NOTE]
====
. Lit.: “unigênito”.
====

[[v42-7-13]]

^<<v42-7-13,13>>^ Quando o Senhor a viu, teve pena dela e lhe disse: “Pare de chorar.”

[[v42-7-14]]

^<<v42-7-14,14>>^ Depois se aproximou e tocou no esquife,^&#42;1^ e os carregadores ficaram parados. Então ele disse: “Jovem, eu lhe digo: Levante-se!”

[NOTE]
====
. Ou: “na maca funerária”.
====

[[v42-7-15]]

^<<v42-7-15,15>>^ E o morto se sentou e começou a falar, e Jesus o entregou à sua mãe.

[[v42-7-16]]

^<<v42-7-16,16>>^ Todos foram então tomados de temor e começaram a glorificar a Deus, dizendo: “Um grande profeta surgiu em nosso meio”, e: “Deus voltou sua atenção para seu povo.”

[[v42-7-17]]

^<<v42-7-17,17>>^ E essa notícia sobre ele se espalhou por toda a Judeia e por toda a região ao redor.

[[v42-7-18]]

^<<v42-7-18,18>>^ Então os discípulos de João lhe contaram todas essas coisas.

[[v42-7-19]]

^<<v42-7-19,19>>^ De modo que João convocou dois dos seus discípulos e os enviou ao Senhor para perguntar: “O senhor é Aquele Que Vem, ou devemos esperar outro?”

[[v42-7-20]]

^<<v42-7-20,20>>^ Quando chegaram a ele, os homens disseram: “João Batista nos enviou ao senhor para perguntar: ‘O senhor é Aquele Que Vem, ou devemos esperar outro?’”

[[v42-7-21]]

^<<v42-7-21,21>>^ Naquela hora, ele curou muitas pessoas de suas enfermidades, de doenças graves e de espíritos maus, e concedeu visão a muitos cegos.

[[v42-7-22]]

^<<v42-7-22,22>>^ Ele lhes disse em resposta: “Vão, contem a João o que vocês viram e ouviram: os cegos agora veem, os mancos estão andando, os leprosos estão sendo purificados, os surdos estão ouvindo, os mortos estão sendo levantados e as boas novas estão sendo anunciadas aos pobres.

[[v42-7-23]]

^<<v42-7-23,23>>^ Feliz é aquele que não acha em mim causa para tropeço.”

[[v42-7-24]]

^<<v42-7-24,24>>^ Quando os mensageiros de João partiram, Jesus começou a falar às multidões sobre João: “O que vocês foram ver no deserto? Uma cana sacudida pelo vento?

[[v42-7-25]]

^<<v42-7-25,25>>^ O que, então, foram ver? Um homem vestido de roupas finas? Ora, os que usam roupa esplêndida e têm uma vida de luxo estão nos palácios reais.

[[v42-7-26]]

^<<v42-7-26,26>>^ Realmente, então, o que vocês foram ver? Um profeta? Sim, eu lhes digo, e muito mais do que um profeta.

[[v42-7-27]]

^<<v42-7-27,27>>^ Esse é aquele a respeito de quem se escreveu: ‘Veja! Enviarei o meu mensageiro na sua frente,^&#42;1^ o qual preparará o seu caminho adiante de você!’

[NOTE]
====
. Lit.: “diante da sua face”.
====

[[v42-7-28]]

^<<v42-7-28,28>>^ Eu lhes digo: Entre os nascidos de mulher não há ninguém maior do que João; mas aquele que é menor no Reino de Deus é maior do que ele.”

[[v42-7-29]]

^<<v42-7-29,29>>^ (Quando ouviram isso, todo o povo e os cobradores de impostos declararam que Deus é justo, pois tinham sido batizados com o batismo de João.

[[v42-7-30]]

^<<v42-7-30,30>>^ Mas os fariseus e os peritos na Lei desconsideraram a vontade^&#42;1^ de Deus para eles, pois não tinham sido batizados por ele.)

[NOTE]
====
. Ou: “a orientação; o conselho”.
====

[[v42-7-31]]

^<<v42-7-31,31>>^ “Com quem, portanto, compararei os homens desta geração, e a quem são semelhantes?

[[v42-7-32]]

^<<v42-7-32,32>>^ Eles são semelhantes a crianças sentadas numa praça,^&#42;1^ que gritam umas para as outras: ‘Nós tocamos flauta para vocês, mas vocês não dançaram; nós lamentamos, mas vocês não choraram.’

[NOTE]
====
. Área aberta usada como centro de compras e vendas e como local de reuniões públicas.
====

[[v42-7-33]]

^<<v42-7-33,33>>^ Da mesma maneira, João Batista veio sem comer pão e sem beber vinho, mas vocês dizem: ‘Ele tem demônio.’

[[v42-7-34]]

^<<v42-7-34,34>>^ O Filho do Homem veio comendo e bebendo, mas vocês dizem: ‘Vejam! Um homem glutão e dado a beber vinho, amigo de cobradores de impostos e de pecadores!’

[[v42-7-35]]

^<<v42-7-35,35>>^ No entanto, a sabedoria se prova justa^&#42;1^ por todos os seus filhos.”^&#42;2^

[NOTE]
====
. Ou: “é vindicada”.
. Ou: “resultados”.
====

[[v42-7-36]]

^<<v42-7-36,36>>^ E um dos fariseus lhe pedia com insistência que comesse com ele. Então ele entrou na casa do fariseu e se recostou à mesa.

[[v42-7-37]]

^<<v42-7-37,37>>^ Uma mulher, conhecida na cidade como pecadora, soube que ele estava comendo^&#42;1^ na casa do fariseu e levou um frasco de alabastro com óleo perfumado.

[NOTE]
====
. Ou: “recostado à mesa”.
====

[[v42-7-38]]

^<<v42-7-38,38>>^ Colocando-se atrás dele, aos seus pés, ela chorou e começou a molhar os pés dele com as suas lágrimas, e os enxugou com os seus cabelos. Ela também beijava ternamente os pés dele e derramava neles o óleo perfumado.

[[v42-7-39]]

^<<v42-7-39,39>>^ Ao ver isso, o fariseu que o tinha convidado disse a si mesmo: “Se este homem realmente fosse um profeta, saberia quem o está tocando e que tipo de mulher ela é, que ela é pecadora.”

[[v42-7-40]]

^<<v42-7-40,40>>^ Em vista disso, porém, Jesus lhe disse: “Simão, tenho algo para lhe dizer.” Ele disse: “Diga, Instrutor!”

[[v42-7-41]]

^<<v42-7-41,41>>^ “Dois homens eram devedores de certo credor: um devia 500 denários,^&#42;1^ mas o outro 50.

[NOTE]
====
. Veja Ap. B14.
====

[[v42-7-42]]

^<<v42-7-42,42>>^ Como não tinham nada com que lhe pagar, ele perdoou liberalmente a ambos. Portanto, qual deles o amará mais?”

[[v42-7-43]]

^<<v42-7-43,43>>^ Em resposta, Simão disse: “Suponho que seja aquele a quem ele perdoou mais.” Ele lhe disse: “Você julgou corretamente.”

[[v42-7-44]]

^<<v42-7-44,44>>^ Então, ele se virou para a mulher e disse a Simão: “Está vendo esta mulher? Entrei na sua casa e você não me deu água para os pés. Mas esta mulher molhou os meus pés com as suas lágrimas e os enxugou com os seus cabelos.

[[v42-7-45]]

^<<v42-7-45,45>>^ Você não me deu nenhum beijo, mas esta mulher, desde a hora em que entrei, não parou de beijar ternamente os meus pés.

[[v42-7-46]]

^<<v42-7-46,46>>^ Você não derramou óleo na minha cabeça, mas esta mulher derramou óleo perfumado nos meus pés.

[[v42-7-47]]

^<<v42-7-47,47>>^ Por isso, eu lhe digo: os pecados dela, embora sejam muitos,^&#42;1^ estão perdoados, porque ela amou muito. Mas aquele a quem se perdoa pouco, ama pouco.”

[NOTE]
====
. Ou: “grandes”.
====

[[v42-7-48]]

^<<v42-7-48,48>>^ Então ele disse a ela: “Seus pecados estão perdoados.”

[[v42-7-49]]

^<<v42-7-49,49>>^ Os que se recostavam com ele à mesa começaram a dizer entre si: “Quem é este homem que até mesmo perdoa pecados?”

[[v42-7-50]]

^<<v42-7-50,50>>^ Mas ele disse à mulher: “Sua fé salvou você. Vá em paz.”

'''

xref:042-lucas/042-lucas-006.adoc#v42-6-0[&#60; Capítulo Anterior] | <<v42-7-0,Topo>> | xref:042-lucas/042-lucas-008.adoc#v42-8-0[Próximo Capítulo &#62;]