include::./index.adoc[]

[[v42-8-0]]
=== Segundo Lucas, 8
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-8-1]]

^<<v42-8-1,1>>^ Pouco tempo depois, ele começou a viajar de cidade em cidade e de aldeia em aldeia, pregando e declarando as boas novas do Reino de Deus. E os Doze estavam com ele,

[[v42-8-2]]

^<<v42-8-2,2>>^ bem como algumas mulheres que tinham sido curadas de espíritos maus e de doenças: Maria, que era chamada Madalena, de quem saíram sete demônios;

[[v42-8-3]]

^<<v42-8-3,3>>^ Joana, esposa de Cuza, encarregado da casa de Herodes; Susana; e muitas outras mulheres que, com os seus próprios bens, ajudavam a eles.

[[v42-8-4]]

^<<v42-8-4,4>>^ Quando uma grande multidão se juntou aos que vinham a ele de uma cidade após outra, ele falou por meio de uma ilustração:

[[v42-8-5]]

^<<v42-8-5,5>>^ “Um semeador saiu para semear as suas sementes. Ao passo que semeava, algumas delas caíram à beira da estrada e foram pisadas, e as aves do céu as comeram.

[[v42-8-6]]

^<<v42-8-6,6>>^ Algumas caíram sobre a rocha e, depois de brotar, secaram, porque não tinham umidade.

[[v42-8-7]]

^<<v42-8-7,7>>^ Outras caíram entre os espinhos, e os espinhos que cresceram com elas as sufocaram.

[[v42-8-8]]

^<<v42-8-8,8>>^ Mas outras caíram em solo bom e, depois de brotar, produziram fruto cem vezes mais.” Depois de lhes dizer isso, falou bem alto: “Quem tem ouvidos para escutar, escute.”

[[v42-8-9]]

^<<v42-8-9,9>>^ Mas os seus discípulos lhe perguntaram o que significava essa ilustração.

[[v42-8-10]]

^<<v42-8-10,10>>^ Ele disse: “A vocês é concedido entender os segredos sagrados do Reino de Deus, mas aos demais tudo é apresentado em ilustrações, para que olhem, mas olhem em vão, e ouçam, mas não compreendam.

[[v42-8-11]]

^<<v42-8-11,11>>^ A ilustração significa o seguinte: a semente é a palavra de Deus.

[[v42-8-12]]

^<<v42-8-12,12>>^ Aquelas à beira da estrada representam os que ouviram, e depois vem o Diabo e tira do coração deles a palavra, a fim de que não creiam e não sejam salvos.

[[v42-8-13]]

^<<v42-8-13,13>>^ Aquelas sobre a rocha representam os que, quando ouvem a palavra, a recebem com alegria, mas não têm raiz. Creem por um tempo, mas numa época de prova se desviam.

[[v42-8-14]]

^<<v42-8-14,14>>^ Aquelas que caíram entre os espinhos representam os que ouviram, mas, por se deixarem levar pelas ansiedades, pelas riquezas e pelos prazeres desta vida, ficam completamente sufocados e não produzem frutos maduros.

[[v42-8-15]]

^<<v42-8-15,15>>^ Aquelas em solo bom representam os que, depois de ouvirem a palavra com um coração sincero e bom, a retêm e dão fruto com perseverança.

[[v42-8-16]]

^<<v42-8-16,16>>^ “Ninguém, depois de acender uma lâmpada, a cobre com um recipiente ou a coloca debaixo de uma cama, mas a coloca em cima de um suporte, para que os que entram possam ver a luz.

[[v42-8-17]]

^<<v42-8-17,17>>^ Pois não há nada escondido que não venha a ser revelado, nem há nada cuidadosamente oculto que nunca se torne conhecido e nunca venha à tona.

[[v42-8-18]]

^<<v42-8-18,18>>^ Portanto, prestem atenção a como escutam; pois àquele que tem, mais será dado, mas daquele que não tem, até mesmo o que imagina ter será tirado.”

[[v42-8-19]]

^<<v42-8-19,19>>^ E sua mãe e seus irmãos chegaram, mas não conseguiram se aproximar dele por causa da multidão.

[[v42-8-20]]

^<<v42-8-20,20>>^ Então, foi-lhe dito: “Sua mãe e seus irmãos estão lá fora, querendo vê-lo.”

[[v42-8-21]]

^<<v42-8-21,21>>^ Ele lhes respondeu: “Minha mãe e meus irmãos são estes que ouvem a palavra de Deus e a praticam.”

[[v42-8-22]]

^<<v42-8-22,22>>^ Certo dia, ele e seus discípulos entraram num barco, e ele lhes disse: “Passemos para a outra margem do lago.” Assim, partiram.

[[v42-8-23]]

^<<v42-8-23,23>>^ Mas, enquanto navegavam, ele adormeceu. Então uma violenta tempestade desabou sobre o lago; o barco começou a ficar inundado e estava em perigo.

[[v42-8-24]]

^<<v42-8-24,24>>^ Por isso o acordaram, dizendo: “Instrutor, Instrutor, estamos prestes a morrer!” Ele se levantou e censurou o vento e a fúria da água; eles pararam, e houve uma calmaria.

[[v42-8-25]]

^<<v42-8-25,25>>^ Então ele lhes disse: “Onde está a sua fé?” Mas eles ficaram com muito medo e espantados, e diziam uns aos outros: “Quem é realmente este homem? Pois dá ordens até mesmo aos ventos e à água, e eles lhe obedecem.”

[[v42-8-26]]

^<<v42-8-26,26>>^ E chegaram à margem, na região dos gerasenos, que fica no lado oposto à Galileia.

[[v42-8-27]]

^<<v42-8-27,27>>^ Quando Jesus desembarcou em terra, um homem da cidade possesso de demônios foi ao encontro dele. Fazia bastante tempo que ele não usava roupa, e ele não ficava em uma casa, mas sim entre os túmulos.^&#42;1^

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v42-8-28]]

^<<v42-8-28,28>>^ Ao ver Jesus, gritou e se prostrou diante dele, e disse bem alto: “O que você quer comigo,^&#42;1^ Jesus, Filho do Deus Altíssimo? Eu lhe suplico que não me atormente.”

[NOTE]
====
. Ou: “O que eu tenho a ver com você”.
====

[[v42-8-29]]

^<<v42-8-29,29>>^ (Pois Jesus tinha ordenado ao espírito impuro que saísse do homem. O espírito tinha se apoderado dele em muitas ocasiões,^&#42;1^ e ele havia sido preso repetidas vezes com correntes nas mãos e nos pés, e era vigiado, mas arrebentava as correntes e era levado pelo demônio para os lugares isolados.)

[NOTE]
====
. Ou, possivelmente: “O espírito o tinha segurado por muito tempo”.
====

[[v42-8-30]]

^<<v42-8-30,30>>^ Jesus lhe perguntou: “Qual é o seu nome?” Ele disse: “Legião”, pois muitos demônios haviam entrado nele.

[[v42-8-31]]

^<<v42-8-31,31>>^ E lhe suplicavam que não os mandasse para o abismo.

[[v42-8-32]]

^<<v42-8-32,32>>^ Uma grande manada de porcos estava pastando ali no monte; por isso lhe suplicaram que lhes permitisse entrar nos porcos, e ele lhes deu permissão.

[[v42-8-33]]

^<<v42-8-33,33>>^ Os demônios saíram então do homem e entraram nos porcos, e a manada se jogou despenhadeiro^&#42;1^ abaixo, para dentro do lago, e se afogou.

[NOTE]
====
. Ou: “encosta íngreme”.
====

[[v42-8-34]]

^<<v42-8-34,34>>^ Mas, quando os que cuidavam dos porcos viram o que tinha acontecido, fugiram e contaram isso na cidade e na zona rural.

[[v42-8-35]]

^<<v42-8-35,35>>^ As pessoas saíram então para ver o que havia acontecido. Quando se aproximaram de Jesus, encontraram o homem de quem haviam saído os demônios, vestido e em perfeito juízo, sentado aos pés de Jesus; e ficaram com medo.

[[v42-8-36]]

^<<v42-8-36,36>>^ Os que tinham visto tudo aquilo contaram a eles como o homem possesso de demônios havia ficado bom.

[[v42-8-37]]

^<<v42-8-37,37>>^ E muitas pessoas da região dos gerasenos, ao redor, pediram a Jesus que se afastasse deles, porque estavam tomados de grande medo. Então ele entrou no barco para partir.

[[v42-8-38]]

^<<v42-8-38,38>>^ No entanto, o homem de quem os demônios haviam saído implorava para continuar com ele, mas ele mandou o homem embora, dizendo:

[[v42-8-39]]

^<<v42-8-39,39>>^ “Volte para casa e sempre fale sobre o que Deus fez por você.” Assim, ele foi embora, proclamando em toda a cidade o que Jesus havia feito por ele.

[[v42-8-40]]

^<<v42-8-40,40>>^ Quando Jesus voltou, a multidão o recebeu bondosamente, pois todos o esperavam.

[[v42-8-41]]

^<<v42-8-41,41>>^ Chegou então um homem chamado Jairo; esse homem era presidente da sinagoga. E ele se prostrou aos pés de Jesus e começou a lhe suplicar que fosse à sua casa,

[[v42-8-42]]

^<<v42-8-42,42>>^ porque sua filha única,^&#42;1^ que tinha cerca de 12 anos, estava morrendo.
Enquanto Jesus ia, as multidões se apertavam em volta dele.

[NOTE]
====
. Lit.: “unigênita”.
====

[[v42-8-43]]

^<<v42-8-43,43>>^ Havia uma mulher que por 12 anos sofria de um fluxo de sangue e não havia conseguido cura da parte de ninguém.

[[v42-8-44]]

^<<v42-8-44,44>>^ Ela se aproximou dele por trás e tocou na borda da sua roupa, e o seu fluxo de sangue parou imediatamente.

[[v42-8-45]]

^<<v42-8-45,45>>^ De modo que Jesus perguntou: “Quem me tocou?” Como todos negavam, Pedro disse: “Instrutor, as multidões rodeiam e apertam o senhor.”

[[v42-8-46]]

^<<v42-8-46,46>>^ Mas Jesus disse: “Alguém me tocou, pois eu sei que saiu poder de mim.”

[[v42-8-47]]

^<<v42-8-47,47>>^ Vendo que não havia passado despercebida, a mulher se aproximou trêmula, se prostrou diante dele e declarou perante todos por que o havia tocado e como tinha sido curada imediatamente.

[[v42-8-48]]

^<<v42-8-48,48>>^ Mas ele disse a ela: “Filha, a sua fé fez você ficar boa. Vá em paz.”

[[v42-8-49]]

^<<v42-8-49,49>>^ Enquanto ele ainda falava, chegou um representante do presidente da sinagoga, dizendo: “Sua filha morreu. Não incomode mais o Instrutor.”

[[v42-8-50]]

^<<v42-8-50,50>>^ Ouvindo isso, Jesus lhe respondeu: “Não tenha medo, apenas tenha fé, e ela será salva.”

[[v42-8-51]]

^<<v42-8-51,51>>^ Quando chegou à casa, não deixou ninguém entrar com ele, a não ser Pedro, João e Tiago, e o pai e a mãe da menina.

[[v42-8-52]]

^<<v42-8-52,52>>^ Mas todos choravam e batiam no peito de pesar por ela. De modo que ele disse: “Parem de chorar, pois ela não morreu; está dormindo.”

[[v42-8-53]]

^<<v42-8-53,53>>^ Em vista disso, começaram a rir dele com desprezo, porque sabiam que ela havia morrido.

[[v42-8-54]]

^<<v42-8-54,54>>^ Mas ele a pegou pela mão e a chamou: “Menina, levante-se!”

[[v42-8-55]]

^<<v42-8-55,55>>^ E o espírito^&#42;1^ dela voltou e ela se levantou imediatamente, e ele ordenou que lhe dessem algo para comer.

[NOTE]
====
. Ou: “a força de vida”.
====

[[v42-8-56]]

^<<v42-8-56,56>>^ Os pais dela estavam fora de si, mas ele lhes ordenou que não dissessem a ninguém o que tinha acontecido.

'''

xref:042-lucas/042-lucas-007.adoc#v42-7-0[&#60; Capítulo Anterior] | <<v42-8-0,Topo>> | xref:042-lucas/042-lucas-009.adoc#v42-9-0[Próximo Capítulo &#62;]