include::./index.adoc[]

[[v42-13-0]]
=== Segundo Lucas, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-13-1]]

^<<v42-13-1,1>>^ Naquela ocasião, alguns que estavam presentes lhe contaram sobre os galileus cujo sangue Pilatos havia misturado com os sacrifícios deles.

[[v42-13-2]]

^<<v42-13-2,2>>^ Ele lhes disse em resposta: “Vocês acham que esses galileus eram mais pecadores do que todos os outros galileus, porque sofreram essas coisas?

[[v42-13-3]]

^<<v42-13-3,3>>^ Eu lhes digo que não; mas, a menos que se arrependam, todos vocês serão destruídos do mesmo modo.

[[v42-13-4]]

^<<v42-13-4,4>>^ Ou aqueles 18 sobre os quais caiu a torre de Siloé, matando-os — vocês acham que eles eram mais culpados do que todos os outros homens que moram em Jerusalém?

[[v42-13-5]]

^<<v42-13-5,5>>^ Eu lhes digo que não; mas, a menos que se arrependam, todos vocês serão destruídos, como eles foram.”

[[v42-13-6]]

^<<v42-13-6,6>>^ Então, contou a seguinte ilustração: “Um homem tinha uma figueira plantada no seu vinhedo e foi procurar fruto nela, mas não achou nenhum.

[[v42-13-7]]

^<<v42-13-7,7>>^ Ele disse então ao homem que cuidava do vinhedo: ‘Agora já faz três anos que venho procurar fruto nesta figueira, mas não achei nenhum. Corte-a! Por que ela devia ocupar o solo inutilmente?’

[[v42-13-8]]

^<<v42-13-8,8>>^ Em resposta, o homem lhe disse: ‘Senhor, deixe-a por mais um ano. Eu vou cavar em volta dela e pôr estrume;

[[v42-13-9]]

^<<v42-13-9,9>>^ se no futuro ela produzir fruto, muito bem, mas, se não, pode cortá-la.’”

[[v42-13-10]]

^<<v42-13-10,10>>^ Ele estava ensinando numa das sinagogas, no sábado.

[[v42-13-11]]

^<<v42-13-11,11>>^ E havia ali uma mulher que tinha um espírito de fraqueza^&#42;1^ havia 18 anos; ela estava encurvada e não conseguia de modo algum se endireitar.

[NOTE]
====
. Ou: “um espírito incapacitante”.
====

[[v42-13-12]]

^<<v42-13-12,12>>^ Quando a viu, Jesus lhe dirigiu a palavra, dizendo: “Mulher, você está livre da sua fraqueza.”

[[v42-13-13]]

^<<v42-13-13,13>>^ E ele pôs as mãos sobre ela, e ela se endireitou instantaneamente e começou a glorificar a Deus.

[[v42-13-14]]

^<<v42-13-14,14>>^ Em vista disso, porém, o presidente da sinagoga, indignado porque Jesus havia feito a cura no sábado, disse à multidão: “Há seis dias em que se deve trabalhar; portanto, venham nesses dias e sejam curados, e não no dia de sábado.”

[[v42-13-15]]

^<<v42-13-15,15>>^ O Senhor, porém, respondeu-lhe: “Hipócritas! Cada um de vocês, no sábado, não desata o seu touro ou o seu jumento da baia e o leva para beber água?

[[v42-13-16]]

^<<v42-13-16,16>>^ Não deveria esta mulher, que é filha de Abraão e a quem Satanás manteve presa por 18 anos, ser libertada dessa prisão no dia de sábado?”

[[v42-13-17]]

^<<v42-13-17,17>>^ Quando ele disse isso, todos os seus opositores ficaram envergonhados, mas toda a multidão se alegrava com todas as coisas gloriosas que ele fazia.

[[v42-13-18]]

^<<v42-13-18,18>>^ Assim, ele acrescentou: “A que é semelhante o Reino de Deus, e com que posso compará-lo?

[[v42-13-19]]

^<<v42-13-19,19>>^ Ele é semelhante a um grão de mostarda que um homem pegou e plantou na sua horta; o grão cresceu e se tornou uma árvore, e as aves do céu fizeram ninhos nos seus ramos.”

[[v42-13-20]]

^<<v42-13-20,20>>^ E, novamente, ele disse: “Com que posso comparar o Reino de Deus?

[[v42-13-21]]

^<<v42-13-21,21>>^ Ele é semelhante ao fermento que uma mulher pegou e misturou com três grandes medidas^&#42;1^ de farinha, até que a massa inteira ficou fermentada.”

[NOTE]
====
. Lit.: “três seás”. Um seá equivalia a 7,33 l. Veja Ap. B14.
====

[[v42-13-22]]

^<<v42-13-22,22>>^ E ele viajou de cidade em cidade e de aldeia em aldeia, ensinando e seguindo caminho para Jerusalém.

[[v42-13-23]]

^<<v42-13-23,23>>^ Então, um homem lhe disse: “Senhor, são poucos os que estão sendo salvos?” Ele lhes disse:

[[v42-13-24]]

^<<v42-13-24,24>>^ “Esforcem-se vigorosamente para entrar pela porta estreita, pois eu lhes digo que muitos procurarão entrar, mas não poderão.

[[v42-13-25]]

^<<v42-13-25,25>>^ Depois que o dono da casa tiver se levantado e trancado a porta, vocês ficarão do lado de fora batendo na porta e dizendo: ‘Senhor, abra para nós’; mas ele lhes responderá: ‘Não sei de onde vocês são.’

[[v42-13-26]]

^<<v42-13-26,26>>^ Então vocês começarão a dizer: ‘Comemos e bebemos na sua presença, e o senhor ensinou nas nossas ruas principais.’

[[v42-13-27]]

^<<v42-13-27,27>>^ Mas ele lhes dirá: ‘Não sei de onde vocês são. Afastem-se de mim, todos vocês que fazem o que é injusto!’

[[v42-13-28]]

^<<v42-13-28,28>>^ Ali é que haverá o seu choro e o ranger dos seus dentes, quando vocês virem Abraão, Isaque, Jacó e todos os profetas no Reino de Deus, mas vocês mesmos lançados fora.

[[v42-13-29]]

^<<v42-13-29,29>>^ Além disso, virão pessoas do leste e do oeste, do norte e do sul, e se recostarão à mesa no Reino de Deus.

[[v42-13-30]]

^<<v42-13-30,30>>^ Escutem: Há últimos que serão primeiros, e há primeiros que serão últimos.”

[[v42-13-31]]

^<<v42-13-31,31>>^ Naquela mesma hora, alguns fariseus se aproximaram e lhe disseram: “Saia e vá embora daqui, porque Herodes quer matá-lo.”

[[v42-13-32]]

^<<v42-13-32,32>>^ E ele lhes disse: “Vão dizer àquela raposa: ‘Veja, estou expulsando demônios e curando pessoas hoje e amanhã, e no terceiro dia terei terminado.’

[[v42-13-33]]

^<<v42-13-33,33>>^ Contudo, preciso continuar hoje, amanhã e no dia seguinte, porque é inadmissível^&#42;1^ que um profeta seja morto fora de Jerusalém.

[NOTE]
====
. Ou: “inconcebível”.
====

[[v42-13-34]]

^<<v42-13-34,34>>^ Jerusalém, Jerusalém, que mata os profetas e apedreja os que lhe são enviados . . . Quantas vezes eu quis ajuntar seus filhos, assim como a galinha ajunta sua ninhada de pintinhos debaixo das asas! Mas vocês não quiseram.

[[v42-13-35]]

^<<v42-13-35,35>>^ Agora a sua casa ficará abandonada. Eu lhes digo: Vocês de modo algum me verão, até que digam: ‘Bendito é aquele que vem em nome de Jeová!’”^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

'''

xref:042-lucas/042-lucas-012.adoc#v42-12-0[&#60; Capítulo Anterior] | <<v42-13-0,Topo>> | xref:042-lucas/042-lucas-014.adoc#v42-14-0[Próximo Capítulo &#62;]