include::./index.adoc[]

[[v42-2-0]]
=== Segundo Lucas, 2
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-2-1]]

^<<v42-2-1,1>>^ Naqueles dias César Augusto emitiu um decreto para que toda a população^&#42;1^ se registrasse.

[NOTE]
====
. Lit.: “terra habitada”.
====

[[v42-2-2]]

^<<v42-2-2,2>>^ (Esse primeiro recenseamento ocorreu quando Quirino era governador da Síria.)

[[v42-2-3]]

^<<v42-2-3,3>>^ E todos foram se registrar, cada um na sua própria cidade.

[[v42-2-4]]

^<<v42-2-4,4>>^ Naturalmente, José também subiu da Galileia, da cidade de Nazaré, para a Judeia, à cidade de Davi, que se chama Belém, visto que era membro da casa e família de Davi.

[[v42-2-5]]

^<<v42-2-5,5>>^ Foi se registrar com Maria, que lhe havia sido dada em casamento, conforme prometido, e que já estava perto de dar à luz.

[[v42-2-6]]

^<<v42-2-6,6>>^ Enquanto estavam lá, chegou o tempo de ela dar à luz.

[[v42-2-7]]

^<<v42-2-7,7>>^ E ela deu à luz seu filho primogênito, enrolou-o em panos e o deitou numa manjedoura, porque não havia lugar para eles no alojamento.

[[v42-2-8]]

^<<v42-2-8,8>>^ Havia também na mesma região pastores vivendo ao ar livre e vigiando seus rebanhos à noite.

[[v42-2-9]]

^<<v42-2-9,9>>^ De repente o anjo de Jeová^&#42;1^ apareceu diante deles, e a glória de Jeová^&#42;2^ brilhou em volta deles, e eles ficaram com muito medo.

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v42-2-10]]

^<<v42-2-10,10>>^ Mas o anjo lhes disse: “Não tenham medo, pois estou aqui para lhes declarar boas novas de uma grande alegria que todo o povo terá.

[[v42-2-11]]

^<<v42-2-11,11>>^ Pois hoje lhes nasceu na cidade de Davi um salvador, que é Cristo, o Senhor.

[[v42-2-12]]

^<<v42-2-12,12>>^ E este será o sinal para vocês: acharão um bebê enrolado em panos e deitado numa manjedoura.”

[[v42-2-13]]

^<<v42-2-13,13>>^ De repente, apareceu junto ao anjo uma multidão do exército celestial, louvando a Deus e dizendo:

[[v42-2-14]]

^<<v42-2-14,14>>^ “Glória a Deus nas maiores alturas, e na terra paz entre os homens a quem ele concede o seu favor.”^&#42;1^

[NOTE]
====
. Ou: “homens de boa vontade”.
====

[[v42-2-15]]

^<<v42-2-15,15>>^ Assim, depois que os anjos se afastaram deles para o céu, os pastores começaram a dizer uns aos outros: “Vamos sem falta a Belém e vejamos o que ocorreu, aquilo que Jeová^&#42;1^ nos fez saber.”

[NOTE]
====
. Veja Ap. A5.
====

[[v42-2-16]]

^<<v42-2-16,16>>^ E foram depressa e acharam Maria, bem como José, e o bebê deitado na manjedoura.

[[v42-2-17]]

^<<v42-2-17,17>>^ Quando viram isso, contaram o que lhes havia sido dito a respeito da criancinha.

[[v42-2-18]]

^<<v42-2-18,18>>^ E todos os que ouviram ficaram muito admirados com as coisas que os pastores lhes contaram.

[[v42-2-19]]

^<<v42-2-19,19>>^ Maria, porém, começou a guardar todas essas declarações, tirando conclusões no coração.

[[v42-2-20]]

^<<v42-2-20,20>>^ Os pastores voltaram então, glorificando e louvando a Deus por tudo que tinham ouvido e visto, exatamente como lhes havia sido dito.

[[v42-2-21]]

^<<v42-2-21,21>>^ Depois de oito dias, quando chegou a ocasião de circuncidá-lo, deram-lhe o nome de Jesus, nome dado pelo anjo antes de ele ser concebido.

[[v42-2-22]]

^<<v42-2-22,22>>^ Também, quando chegou o tempo para a purificação deles, segundo a Lei de Moisés, eles o levaram a Jerusalém para apresentá-lo a Jeová,^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v42-2-23]]

^<<v42-2-23,23>>^ assim como está escrito na Lei de Jeová:^&#42;1^ “Todo primogênito do sexo masculino^&#42;2^ tem de ser chamado santo para Jeová.”^&#42;3^

[NOTE]
====
. Veja Ap. A5.
. Lit.: “Todo macho que abre o ventre”.
. Veja Ap. A5.
====

[[v42-2-24]]

^<<v42-2-24,24>>^ E ofereceram um sacrifício segundo o que se diz na Lei de Jeová:^&#42;1^ “Um par de rolas ou dois pombos novos.”

[NOTE]
====
. Veja Ap. A5.
====

[[v42-2-25]]

^<<v42-2-25,25>>^ Havia em Jerusalém um homem chamado Simeão; esse homem era justo e devoto, e esperava o consolo de Israel, e o espírito santo estava sobre ele.

[[v42-2-26]]

^<<v42-2-26,26>>^ Além disso, ele havia recebido a revelação divina, pelo espírito santo, que ele não veria a morte antes de ver o Cristo de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v42-2-27]]

^<<v42-2-27,27>>^ Assim, sob o poder do espírito, ele foi ao templo; e quando os pais levaram o menino Jesus para dentro, a fim de lhe fazer o que era o costume segundo a Lei,

[[v42-2-28]]

^<<v42-2-28,28>>^ ele pegou a criança nos braços, louvou a Deus e disse:

[[v42-2-29]]

^<<v42-2-29,29>>^ “Agora, Soberano Senhor, estás deixando o teu escravo ir em paz, segundo a tua declaração,

[[v42-2-30]]

^<<v42-2-30,30>>^ porque meus olhos viram teu meio de salvação,

[[v42-2-31]]

^<<v42-2-31,31>>^ que preparaste à vista de todos os povos,

[[v42-2-32]]

^<<v42-2-32,32>>^ uma luz para remover o véu das nações e uma glória para o teu povo, Israel.”

[[v42-2-33]]

^<<v42-2-33,33>>^ E o pai e a mãe do menino se admiravam das coisas que se falavam dele.

[[v42-2-34]]

^<<v42-2-34,34>>^ Também, Simeão os abençoou e disse a Maria, a mãe do menino: “Escute, este menino será motivo para a queda e para o levantamento de muitos em Israel, e será um sinal contra o qual falar

[[v42-2-35]]

^<<v42-2-35,35>>^ — e, quanto a você, uma longa espada a atravessará^&#42;1^ —, a fim de que os raciocínios de muitos corações sejam revelados.”

[NOTE]
====
. Ou: “uma longa espada atravessará a sua própria alma”.
====

[[v42-2-36]]

^<<v42-2-36,36>>^ Havia também uma profetisa, Ana, filha de Fanuel, da tribo de Aser. Essa mulher era de idade bem avançada e tinha vivido com seu marido por sete anos, desde o seu casamento.^&#42;1^

[NOTE]
====
. Lit.: “desde a sua virgindade”.
====

[[v42-2-37]]

^<<v42-2-37,37>>^ Ela era viúva e já tinha 84 anos de idade. Nunca estava ausente do templo, prestando serviço sagrado noite e dia, fazendo jejum e súplicas.

[[v42-2-38]]

^<<v42-2-38,38>>^ Ela se aproximou naquela mesma hora e começou a dar graças a Deus e a falar sobre a criança a todos os que estavam aguardando o livramento de Jerusalém.

[[v42-2-39]]

^<<v42-2-39,39>>^ Assim, quando eles haviam cumprido todas as coisas segundo a Lei de Jeová,^&#42;1^ voltaram para a Galileia, para sua cidade, Nazaré.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-2-40]]

^<<v42-2-40,40>>^ E o menino continuou a crescer, ficando forte e cheio de sabedoria; e o favor de Deus continuou sobre ele.

[[v42-2-41]]

^<<v42-2-41,41>>^ De ano em ano, seus pais costumavam ir a Jerusalém para a Festividade da Páscoa.

[[v42-2-42]]

^<<v42-2-42,42>>^ E, quando ele tinha 12 anos de idade, subiram segundo o costume da festividade.

[[v42-2-43]]

^<<v42-2-43,43>>^ Quando a festividade terminou e eles começaram a viagem de volta, o menino Jesus ficou em Jerusalém, mas seus pais não perceberam.

[[v42-2-44]]

^<<v42-2-44,44>>^ Pensando que ele estivesse no grupo que viajava junto, percorreram a distância de um dia e então começaram a procurá-lo entre os parentes e conhecidos.

[[v42-2-45]]

^<<v42-2-45,45>>^ Mas, visto que não o acharam, voltaram a Jerusalém e o procuraram cuidadosamente.

[[v42-2-46]]

^<<v42-2-46,46>>^ Pois bem, depois de três dias, eles o acharam no templo, sentado no meio dos instrutores, escutando-os e fazendo-lhes perguntas.

[[v42-2-47]]

^<<v42-2-47,47>>^ Mas todos os que o escutavam ficavam admirados com o seu entendimento e suas respostas.

[[v42-2-48]]

^<<v42-2-48,48>>^ Assim, seus pais ficaram espantados quando o viram, e sua mãe lhe disse: “Filho, por que você fez isso conosco? Olhe, seu pai e eu estávamos desesperados procurando você.”

[[v42-2-49]]

^<<v42-2-49,49>>^ Mas ele lhes disse: “Por que estavam procurando por mim? Não sabiam que eu devia estar na casa do meu Pai?”

[[v42-2-50]]

^<<v42-2-50,50>>^ No entanto, não compreenderam o que ele estava lhes dizendo.

[[v42-2-51]]

^<<v42-2-51,51>>^ Então ele desceu com eles e voltou a Nazaré, e continuou a estar sujeito^&#42;1^ a eles. Também, sua mãe guardava cuidadosamente todas essas declarações no coração.

[NOTE]
====
. Ou: “continuou obediente”.
====

[[v42-2-52]]

^<<v42-2-52,52>>^ E Jesus progredia em sabedoria e em desenvolvimento físico, e no favor de Deus e dos homens.

'''

xref:042-lucas/042-lucas-001.adoc#v42-1-0[&#60; Capítulo Anterior] | <<v42-2-0,Topo>> | xref:042-lucas/042-lucas-003.adoc#v42-3-0[Próximo Capítulo &#62;]