include::./index.adoc[]

[[v42-14-0]]
=== Segundo Lucas, 14
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-14-1]]

^<<v42-14-1,1>>^ Em outra ocasião, ele foi tomar uma refeição na casa de um líder dos fariseus, no sábado, e eles o estavam observando atentamente.

[[v42-14-2]]

^<<v42-14-2,2>>^ E na frente dele estava um homem que sofria de hidropisia.^&#42;1^

[NOTE]
====
. Ou: “edema”, uma acumulação excessiva de líquido no corpo.
====

[[v42-14-3]]

^<<v42-14-3,3>>^ Em vista disso, Jesus perguntou aos peritos na Lei e aos fariseus: “É permitido ou não curar no sábado?”

[[v42-14-4]]

^<<v42-14-4,4>>^ Mas eles ficaram calados. Assim, ele tocou no homem, o curou e o mandou embora.

[[v42-14-5]]

^<<v42-14-5,5>>^ Então ele lhes disse: “Quem de vocês não puxará imediatamente para fora o seu filho ou o seu touro se ele cair num poço no dia de sábado?”

[[v42-14-6]]

^<<v42-14-6,6>>^ E eles ficaram sem resposta.

[[v42-14-7]]

^<<v42-14-7,7>>^ Ele contou então aos convidados uma ilustração, quando notou que eles escolhiam os lugares mais destacados. Ele lhes disse:

[[v42-14-8]]

^<<v42-14-8,8>>^ “Quando você for convidado por alguém para uma festa de casamento, não se recoste no lugar mais destacado. Talvez uma pessoa de mais destaque do que você também tenha sido convidada.

[[v42-14-9]]

^<<v42-14-9,9>>^ Então aquele que convidou a ambos chegará e dirá a você: ‘Dê o seu lugar a este homem.’ Então você irá, envergonhado, ocupar o último lugar.

[[v42-14-10]]

^<<v42-14-10,10>>^ Mas, quando você for convidado, vá se recostar no último lugar, para que, quando chegar o homem que o convidou, ele lhe diga: ‘Amigo, passe para um lugar mais importante.’ Então você terá honra na frente de todos os outros convidados.

[[v42-14-11]]

^<<v42-14-11,11>>^ Porque todo aquele que se enaltecer será humilhado, e aquele que se humilhar será enaltecido.”

[[v42-14-12]]

^<<v42-14-12,12>>^ A seguir ele disse também ao homem que o havia convidado: “Quando você oferecer um almoço ou um jantar, não chame seus amigos, nem seus irmãos, nem seus parentes, nem seus vizinhos ricos. Pois eles, por sua vez, poderiam convidá-lo também, e isso seria para você uma retribuição.

[[v42-14-13]]

^<<v42-14-13,13>>^ Mas, quando oferecer um banquete, convide os pobres, os aleijados, os mancos, os cegos;

[[v42-14-14]]

^<<v42-14-14,14>>^ e você será feliz, porque eles não têm nada com que recompensá-lo. Pois você será recompensado na ressurreição dos justos.”

[[v42-14-15]]

^<<v42-14-15,15>>^ Ao ouvir essas coisas, um dos outros convidados lhe disse: “Feliz é aquele que participa do banquete^&#42;1^ no Reino de Deus.”

[NOTE]
====
. Lit.: “come pão”.
====

[[v42-14-16]]

^<<v42-14-16,16>>^ Jesus lhe disse: “Um homem estava oferecendo um grande banquete,^&#42;1^ e convidou muitas pessoas.

[NOTE]
====
. Ou: “uma grande ceia”.
====

[[v42-14-17]]

^<<v42-14-17,17>>^ Ele enviou seu escravo, na hora do banquete,^&#42;1^ para dizer aos convidados: ‘Venham, porque já está tudo pronto.’

[NOTE]
====
. Ou: “da ceia”.
====

[[v42-14-18]]

^<<v42-14-18,18>>^ Mas todos, sem exceção, começaram a dar desculpas. O primeiro disse: ‘Comprei um campo, e preciso sair e vê-lo. Peço-lhe que me desculpe.’

[[v42-14-19]]

^<<v42-14-19,19>>^ E outro disse: ‘Comprei cinco juntas^&#42;1^ de bois e vou examiná-las. Peço-lhe que me desculpe.’

[NOTE]
====
. Ou: “pares”.
====

[[v42-14-20]]

^<<v42-14-20,20>>^ Ainda outro disse: ‘Acabei de me casar e por isso não posso ir.’

[[v42-14-21]]

^<<v42-14-21,21>>^ Assim, o escravo voltou e contou essas coisas ao seu senhor. O dono da casa ficou então irado e disse ao seu escravo: ‘Vá depressa às ruas principais e aos becos da cidade, e traga para cá os pobres, os aleijados, os cegos e os mancos.’

[[v42-14-22]]

^<<v42-14-22,22>>^ Mais tarde, o escravo disse: ‘Senhor, foi feito o que ordenou, mas ainda há lugar.’

[[v42-14-23]]

^<<v42-14-23,23>>^ Então o senhor disse ao escravo: ‘Vá para as estradas e os caminhos, e obrigue-os a vir para dentro, a fim de que a minha casa fique cheia.

[[v42-14-24]]

^<<v42-14-24,24>>^ Pois eu digo a vocês: Nenhum daqueles homens que foram convidados provará o meu banquete.’”^&#42;1^

[NOTE]
====
. Ou: “a minha ceia”.
====

[[v42-14-25]]

^<<v42-14-25,25>>^ Grandes multidões viajavam então com ele, e ele se virou e lhes disse:

[[v42-14-26]]

^<<v42-14-26,26>>^ “Se alguém vem a mim e não odeia^&#42;1^ o pai, a mãe, a esposa, os filhos, os irmãos, as irmãs, sim, e até mesmo a própria vida,^&#42;2^ não pode ser meu discípulo.

[NOTE]
====
. Ou: “não ama menos”.
. Ou: “alma”.
====

[[v42-14-27]]

^<<v42-14-27,27>>^ Quem não carrega sua estaca de tortura^&#42;1^ e não me segue, não pode ser meu discípulo.

[NOTE]
====
. Veja o Glossário.
====

[[v42-14-28]]

^<<v42-14-28,28>>^ Por exemplo, quem de vocês, querendo construir uma torre, não se senta primeiro e calcula a despesa, para ver se tem o suficiente para completá-la?

[[v42-14-29]]

^<<v42-14-29,29>>^ Senão, ele lançará o alicerce dela, mas não conseguirá terminá-la, e todos os observadores começarão a zombar dele,

[[v42-14-30]]

^<<v42-14-30,30>>^ dizendo: ‘Este homem começou a construir, mas não conseguiu terminar.’

[[v42-14-31]]

^<<v42-14-31,31>>^ Ou que rei, antes de marchar para guerrear contra outro rei, não se senta e se aconselha para ver se consegue com 10.000 soldados enfrentar o que vem contra ele com 20.000?

[[v42-14-32]]

^<<v42-14-32,32>>^ De fato, se ele vê que não consegue, envia um grupo de embaixadores e propõe um acordo de paz, enquanto o outro ainda está longe.

[[v42-14-33]]

^<<v42-14-33,33>>^ Da mesma forma, podem estar certos de que nenhum de vocês que não se despedir^&#42;1^ de todos os seus bens poderá ser meu discípulo.

[NOTE]
====
. Ou: “não abrir mão”.
====

[[v42-14-34]]

^<<v42-14-34,34>>^ “O sal, certamente, é bom. Mas, se o sal perder a sua força, como se recuperará o seu sabor?

[[v42-14-35]]

^<<v42-14-35,35>>^ Não serve nem para o solo, nem para o estrume. As pessoas o jogam fora. Quem tem ouvidos para escutar, escute.”

'''

xref:042-lucas/042-lucas-013.adoc#v42-13-0[&#60; Capítulo Anterior] | <<v42-14-0,Topo>> | xref:042-lucas/042-lucas-015.adoc#v42-15-0[Próximo Capítulo &#62;]