include::./index.adoc[]

[[v42-12-0]]
=== Segundo Lucas, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-12-1]]

^<<v42-12-1,1>>^ Enquanto isso, quando uma multidão de muitos milhares havia se ajuntado a ponto de atropelarem uns aos outros, ele começou a falar, dirigindo-se primeiro aos discípulos: “Tomem cuidado com o fermento dos fariseus, que é a hipocrisia.

[[v42-12-2]]

^<<v42-12-2,2>>^ Mas não há nada cuidadosamente oculto que não venha a ser revelado, e não há nada secreto que não se torne conhecido.

[[v42-12-3]]

^<<v42-12-3,3>>^ Portanto, tudo que vocês dizem na escuridão será ouvido na luz, e o que sussurram em aposentos reservados será pregado dos terraços das casas.

[[v42-12-4]]

^<<v42-12-4,4>>^ Além disso, eu lhes digo, meus amigos: Não temam os que matam o corpo e depois disso não podem fazer mais nada.

[[v42-12-5]]

^<<v42-12-5,5>>^ Mas eu lhes mostrarei a quem vocês devem temer: temam Aquele que, depois de matar, tem autoridade para lançar na Geena.^&#42;1^ Sim, eu lhes digo, temam a esse.

[NOTE]
====
. Veja o Glossário.
====

[[v42-12-6]]

^<<v42-12-6,6>>^ Não se vendem cinco pardais por duas moedas de pequeno valor?^&#42;1^ Contudo, nem mesmo um deles é esquecido^&#42;2^ por Deus.

[NOTE]
====
. Lit.: “por dois assários”. Veja Ap. B14.
. Ou: “despercebido”.
====

[[v42-12-7]]

^<<v42-12-7,7>>^ Mas até mesmo os cabelos da cabeça de vocês estão todos contados. Não tenham medo; vocês valem mais do que muitos pardais.

[[v42-12-8]]

^<<v42-12-8,8>>^ “Eu lhes digo: Todo aquele que declarar diante dos homens que está em união comigo, o Filho do Homem também declarará, diante dos anjos de Deus, estar em união com ele.

[[v42-12-9]]

^<<v42-12-9,9>>^ Mas quem me negar diante dos homens será negado diante dos anjos de Deus.

[[v42-12-10]]

^<<v42-12-10,10>>^ E todo aquele que disser uma palavra contra o Filho do Homem será perdoado; mas quem blasfemar contra o espírito santo não será perdoado.

[[v42-12-11]]

^<<v42-12-11,11>>^ Quando levarem vocês diante de assembleias públicas,^&#42;1^ funcionários do governo e autoridades, não fiquem preocupados^&#42;2^ com o que falar ou como falar em sua defesa, ou com o que vocês dirão,

[NOTE]
====
. Ou, possivelmente: “diante de sinagogas”.
. Ou: “ansiosos”.
====

[[v42-12-12]]

^<<v42-12-12,12>>^ pois o espírito santo lhes ensinará naquela mesma hora o que devem dizer.”

[[v42-12-13]]

^<<v42-12-13,13>>^ Então alguém na multidão lhe disse: “Instrutor, diga a meu irmão que divida comigo a herança.”

[[v42-12-14]]

^<<v42-12-14,14>>^ Ele lhe respondeu: “Homem, quem me designou como juiz ou me deu o direito de repartir os bens entre vocês dois?”

[[v42-12-15]]

^<<v42-12-15,15>>^ Então lhes disse: “Mantenham os olhos abertos e resguardem-se de todo tipo de ganância,^&#42;1^ porque, mesmo quando alguém tem abundância, sua vida não vem das coisas que possui.”

[NOTE]
====
. Ou: “cobiça”.
====

[[v42-12-16]]

^<<v42-12-16,16>>^ Com isso, contou-lhes uma ilustração, dizendo: “A terra de um homem rico produziu bem.

[[v42-12-17]]

^<<v42-12-17,17>>^ Por isso, ele começou a raciocinar no íntimo: ‘O que farei agora que não tenho onde ajuntar minhas safras?’

[[v42-12-18]]

^<<v42-12-18,18>>^ E disse: ‘Farei o seguinte: derrubarei os meus celeiros e construirei maiores, e ali ajuntarei todo o meu cereal e todos os meus bens;

[[v42-12-19]]

^<<v42-12-19,19>>^ e direi a mim mesmo:^&#42;1^ “Você^&#42;2^ tem muitas coisas boas armazenadas para muitos anos. Descanse, coma, beba, divirta-se.”’

[NOTE]
====
. Ou: “à minha alma”.
. Ou: “Alma, você”.
====

[[v42-12-20]]

^<<v42-12-20,20>>^ Mas Deus lhe disse: ‘Insensato, esta noite exigirão de você a sua vida.^&#42;1^ Quem terá então as coisas que você acumulou?’

[NOTE]
====
. Ou: “alma”.
====

[[v42-12-21]]

^<<v42-12-21,21>>^ Isso é o que acontece com o homem que acumula tesouros para si, mas não é rico para com Deus.”

[[v42-12-22]]

^<<v42-12-22,22>>^ Ele disse então aos seus discípulos: “É por isso que eu lhes digo: Parem de se preocupar tanto^&#42;1^ com a sua vida,^&#42;2^ quanto ao que comer, e com o seu corpo, quanto ao que vestir.

[NOTE]
====
. Ou: “de estar ansiosos”.
. Ou: “alma”.
====

[[v42-12-23]]

^<<v42-12-23,23>>^ Pois a vida^&#42;1^ vale mais do que o alimento, e o corpo mais do que a roupa.

[NOTE]
====
. Ou: “alma”.
====

[[v42-12-24]]

^<<v42-12-24,24>>^ Vejam os corvos: eles não semeiam nem colhem, não têm nem celeiro nem depósito; contudo, Deus os alimenta. Será que vocês não valem muito mais do que as aves?

[[v42-12-25]]

^<<v42-12-25,25>>^ Quem de vocês, por estar ansioso, pode acrescentar um côvado^&#42;1^ à duração da sua vida?

[NOTE]
====
. Veja Ap. B14.
====

[[v42-12-26]]

^<<v42-12-26,26>>^ Portanto, se vocês não podem fazer uma coisa tão pequena, por que se preocupam tanto com as outras coisas?

[[v42-12-27]]

^<<v42-12-27,27>>^ Vejam como os lírios crescem: eles não trabalham nem fiam; mas eu lhes digo que nem mesmo Salomão, em toda a sua glória, se vestia como um deles.

[[v42-12-28]]

^<<v42-12-28,28>>^ Então, se Deus veste assim a vegetação do campo, que hoje existe e amanhã é lançada no forno, quanto mais ele vestirá a vocês, homens de pouca fé!

[[v42-12-29]]

^<<v42-12-29,29>>^ Assim, parem de procurar o que comer e o que beber, e parem de ficar excessivamente preocupados;

[[v42-12-30]]

^<<v42-12-30,30>>^ porque é por todas essas coisas que as nações do mundo se empenham ansiosamente, mas o seu Pai sabe que vocês necessitam dessas coisas.

[[v42-12-31]]

^<<v42-12-31,31>>^ Em vez disso, continuem a buscar o Reino dele, e essas coisas lhes serão acrescentadas.

[[v42-12-32]]

^<<v42-12-32,32>>^ “Não tema, pequeno rebanho, porque o seu Pai se agradou de dar o Reino a vocês.

[[v42-12-33]]

^<<v42-12-33,33>>^ Vendam as suas coisas e deem aos pobres.^&#42;1^ Façam para vocês bolsas de dinheiro que não se gastem, um tesouro que nunca acabe, nos céus, onde o ladrão não chega perto nem a traça consome.

[NOTE]
====
. Ou: “e façam dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v42-12-34]]

^<<v42-12-34,34>>^ Pois onde estiver o seu tesouro, ali estará também o seu coração.

[[v42-12-35]]

^<<v42-12-35,35>>^ “Estejam vestidos e preparados,^&#42;1^ estejam com as suas lâmpadas acesas,

[NOTE]
====
. Lit.: “Que seus lombos estejam cingidos”.
====

[[v42-12-36]]

^<<v42-12-36,36>>^ sejam como homens que esperam o seu senhor voltar do casamento, para que, quando ele vier e bater à porta, possam imediatamente abrir-lhe.

[[v42-12-37]]

^<<v42-12-37,37>>^ Felizes aqueles escravos cujo senhor, quando vier, os encontrar vigiando! Digo a verdade a vocês: Ele se vestirá^&#42;1^ para servir, fará que se recostem à mesa e virá servi-los.

[NOTE]
====
. Ou: “se cingirá”.
====

[[v42-12-38]]

^<<v42-12-38,38>>^ E, se ele vier na segunda vigília,^&#42;1^ ou mesmo na terceira,^&#42;2^ e os encontrar preparados, felizes são!

[NOTE]
====
. De cerca das 9 h da noite à meia-noite.
. Da meia-noite a cerca das 3 h da madrugada.
====

[[v42-12-39]]

^<<v42-12-39,39>>^ Mas saibam que, se o dono da casa soubesse a que hora viria o ladrão, não deixaria que a sua casa fosse arrombada.

[[v42-12-40]]

^<<v42-12-40,40>>^ Vocês também, mantenham-se prontos, porque o Filho do Homem virá numa hora que vocês não acham provável.”

[[v42-12-41]]

^<<v42-12-41,41>>^ Pedro perguntou então: “Senhor, essa ilustração é só para nós ou também para todos?”

[[v42-12-42]]

^<<v42-12-42,42>>^ E o Senhor disse: “Quem é realmente o administrador fiel,^&#42;1^ o prudente,^&#42;2^ a quem o seu senhor encarregará do grupo de assistentes^&#42;3^ para sempre dar a eles a sua medida de mantimentos no tempo apropriado?

[NOTE]
====
. Ou: “fiel administrador da casa”.
. Ou: “sábio”.
. Ou: “servos domésticos”.
====

[[v42-12-43]]

^<<v42-12-43,43>>^ Feliz aquele escravo se o seu senhor, quando vier, o encontrar fazendo isso!

[[v42-12-44]]

^<<v42-12-44,44>>^ Digo a verdade a vocês: Ele o encarregará de todos os seus bens.

[[v42-12-45]]

^<<v42-12-45,45>>^ Mas, se aquele escravo disser no coração: ‘Meu senhor demora a vir’, e começar a espancar os servos e as servas, e a comer, beber e se embriagar,

[[v42-12-46]]

^<<v42-12-46,46>>^ o senhor daquele escravo virá num dia em que ele não espera e numa hora que ele não sabe, e o punirá com a maior severidade e lhe designará um lugar entre os infiéis.

[[v42-12-47]]

^<<v42-12-47,47>>^ Então aquele escravo que entendeu a vontade do seu senhor, mas não se aprontou nem fez o que ele lhe pediu,^&#42;1^ será espancado com muitos golpes.

[NOTE]
====
. Ou: “nem agiu em harmonia com a sua vontade”.
====

[[v42-12-48]]

^<<v42-12-48,48>>^ Mas aquele que não entendeu e fez coisas que merecem punição será espancado com poucos golpes. Realmente, de todo aquele a quem muito foi dado, muito será exigido; e daquele que foi encarregado de muito, será exigido mais do que o normal.

[[v42-12-49]]

^<<v42-12-49,49>>^ “Eu vim para acender um fogo na terra, e o que mais posso desejar se ele já foi aceso?

[[v42-12-50]]

^<<v42-12-50,50>>^ Realmente, tenho um batismo com que devo ser batizado, e como estou aflito até que ele termine!

[[v42-12-51]]

^<<v42-12-51,51>>^ Vocês pensam que eu vim trazer paz à terra? Eu lhes digo que não! Em vez disso, vim trazer divisão.

[[v42-12-52]]

^<<v42-12-52,52>>^ Pois de agora em diante haverá numa casa cinco divididos uns contra os outros: três contra dois e dois contra três.

[[v42-12-53]]

^<<v42-12-53,53>>^ Estarão divididos, pai contra filho e filho contra pai, mãe contra filha e filha contra mãe, sogra contra nora e nora contra sogra.”

[[v42-12-54]]

^<<v42-12-54,54>>^ Então ele disse também às multidões: “Quando vocês veem uma nuvem surgindo no ocidente, dizem imediatamente: ‘Vem uma tempestade’, e assim acontece.

[[v42-12-55]]

^<<v42-12-55,55>>^ E, quando vocês veem soprar um vento sul, dizem: ‘Haverá uma onda de calor’, e assim ocorre.

[[v42-12-56]]

^<<v42-12-56,56>>^ Hipócritas! Vocês sabem examinar a aparência da terra e do céu, mas como é que não sabem examinar este tempo específico?

[[v42-12-57]]

^<<v42-12-57,57>>^ Por que não julgam também por si mesmos o que é justo?

[[v42-12-58]]

^<<v42-12-58,58>>^ Por exemplo, enquanto você e seu adversário estão indo a uma autoridade, empenhe-se, no caminho, em resolver a disputa com ele, para que ele não o leve perante o juiz, e o juiz o entregue ao oficial de justiça, e o oficial de justiça o lance na prisão.

[[v42-12-59]]

^<<v42-12-59,59>>^ Eu lhe digo: Você de modo algum sairá de lá até pagar sua última pequena moeda.”^&#42;1^

[NOTE]
====
. Lit.: “o último lépton”. Veja Ap. B14.
====

'''

xref:042-lucas/042-lucas-011.adoc#v42-11-0[&#60; Capítulo Anterior] | <<v42-12-0,Topo>> | xref:042-lucas/042-lucas-013.adoc#v42-13-0[Próximo Capítulo &#62;]