include::./index.adoc[]

[[v42-9-0]]
=== Segundo Lucas, 9
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-9-1]]

^<<v42-9-1,1>>^ Ele convocou então os Doze e lhes deu poder e autoridade sobre todos os demônios, e também para curar doenças.

[[v42-9-2]]

^<<v42-9-2,2>>^ E os enviou para pregar o Reino de Deus e para curar,

[[v42-9-3]]

^<<v42-9-3,3>>^ e lhes disse: “Não levem nada para a viagem: nem bastão, nem bolsa de provisões, nem pão, nem dinheiro;^&#42;1^ nem tenham roupa extra.^&#42;2^

[NOTE]
====
. Lit.: “prata”.
. Lit.: “duas túnicas”.
====

[[v42-9-4]]

^<<v42-9-4,4>>^ Mas, em qualquer casa em que entrarem, fiquem ali até partirem.

[[v42-9-5]]

^<<v42-9-5,5>>^ E onde quer que não os receberem, ao saírem daquela cidade, sacudam o pó dos seus pés em testemunho contra eles.”

[[v42-9-6]]

^<<v42-9-6,6>>^ Então, eles partiram e passaram pelo território, de aldeia em aldeia, declarando as boas novas e realizando curas em toda a parte.

[[v42-9-7]]

^<<v42-9-7,7>>^ E Herodes,^&#42;1^ o governador distrital,^&#42;2^ ouviu falar de tudo que estava acontecendo e ficou muito perplexo, porque alguns diziam que João havia sido levantado dentre os mortos,

[NOTE]
====
. Isto é, Herodes Antipas. Veja o Glossário.
. Lit.: “o tetrarca”.
====

[[v42-9-8]]

^<<v42-9-8,8>>^ mas outros diziam que Elias havia aparecido, e ainda outros que um dos antigos profetas tinha se levantado.

[[v42-9-9]]

^<<v42-9-9,9>>^ Herodes disse: “Eu decapitei João. Então, quem é esse de quem ouço falar essas coisas?” De modo que procurava vê-lo.

[[v42-9-10]]

^<<v42-9-10,10>>^ Quando voltaram, os apóstolos contaram a Jesus tudo que tinham feito. Então, levando-os consigo, ele se retirou, à parte, para uma cidade chamada Betsaida.

[[v42-9-11]]

^<<v42-9-11,11>>^ Mas as multidões, ao saberem disso, o seguiram. E ele as recebeu bondosamente, e começou a lhes falar do Reino de Deus, e curou os que precisavam de cura.

[[v42-9-12]]

^<<v42-9-12,12>>^ Chegando então o fim do dia, os Doze se aproximaram dele e lhe disseram: “Dispense a multidão, para que possam ir às aldeias e à zona rural ao redor, a fim de conseguirem hospedagem e algo para comer, porque aqui estamos num lugar isolado.”

[[v42-9-13]]

^<<v42-9-13,13>>^ Mas ele lhes disse: “Deem-lhes vocês algo para comer.” Eles disseram: “Não temos nada mais do que cinco pães e dois peixes, a menos que talvez nós mesmos vamos e compremos alimento para todas essas pessoas.”

[[v42-9-14]]

^<<v42-9-14,14>>^ De fato, havia ali cerca de 5.000 homens. Mas ele disse aos seus discípulos: “Façam que eles se sentem em grupos de cerca de 50 pessoas.”

[[v42-9-15]]

^<<v42-9-15,15>>^ E eles fizeram isso e mandaram que todos se sentassem.

[[v42-9-16]]

^<<v42-9-16,16>>^ Pegando então os cinco pães e os dois peixes, ele olhou para o céu e deu graças.^&#42;1^ Depois os partiu e começou a dá-los aos discípulos, para que os servissem à multidão.

[NOTE]
====
. Ou: “e os abençoou”.
====

[[v42-9-17]]

^<<v42-9-17,17>>^ Assim, todos comeram e ficaram satisfeitos; e eles recolheram os pedaços que sobraram, 12 cestos.

[[v42-9-18]]

^<<v42-9-18,18>>^ Mais tarde, enquanto estava orando sozinho, os discípulos se aproximaram dele, e ele lhes perguntou: “Quem as multidões dizem que eu sou?”

[[v42-9-19]]

^<<v42-9-19,19>>^ Em resposta, eles disseram: “João Batista; mas outros dizem que é Elias; e ainda outros dizem que um dos antigos profetas se levantou.”

[[v42-9-20]]

^<<v42-9-20,20>>^ Então ele lhes perguntou: “E vocês, quem dizem que eu sou?” Pedro respondeu: “O Cristo de Deus.”

[[v42-9-21]]

^<<v42-9-21,21>>^ Depois, numa conversa séria com eles, lhes ordenou que não contassem isso a ninguém,

[[v42-9-22]]

^<<v42-9-22,22>>^ mas disse: “O Filho do Homem tem de sofrer muitas coisas e ser rejeitado pelos anciãos, pelos principais sacerdotes e pelos escribas, e tem de ser morto e no terceiro dia ser levantado.”

[[v42-9-23]]

^<<v42-9-23,23>>^ Então ele disse também a todos: “Se alguém quer ser meu seguidor, negue a si mesmo, apanhe sua estaca de tortura^&#42;1^ dia após dia e siga-me sempre.

[NOTE]
====
. Veja o Glossário.
====

[[v42-9-24]]

^<<v42-9-24,24>>^ Pois quem quiser salvar a sua vida^&#42;1^ a perderá; mas quem perder a sua vida^&#42;2^ por minha causa é o que a salvará.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v42-9-25]]

^<<v42-9-25,25>>^ Realmente, de que adianta o homem ganhar o mundo inteiro, se ele perder a si mesmo ou causar sua própria ruína?

[[v42-9-26]]

^<<v42-9-26,26>>^ Pois quem se envergonhar de mim e das minhas palavras, dessa pessoa o Filho do Homem se envergonhará quando vier na sua glória e na glória do Pai e dos santos anjos.

[[v42-9-27]]

^<<v42-9-27,27>>^ Mas eu lhes digo a verdade: Há alguns dos que estão aqui que de modo algum provarão a morte antes de verem o Reino de Deus.”

[[v42-9-28]]

^<<v42-9-28,28>>^ Na realidade, cerca de oito dias depois de dizer essas palavras, ele levou consigo Pedro, João e Tiago, e subiu ao monte para orar.

[[v42-9-29]]

^<<v42-9-29,29>>^ E, enquanto ele orava, a aparência do seu rosto mudou e a sua roupa se tornou de um branco cintilante.

[[v42-9-30]]

^<<v42-9-30,30>>^ E apareceram dois homens conversando com ele: eram Moisés e Elias.

[[v42-9-31]]

^<<v42-9-31,31>>^ Esses apareceram com glória e começaram a falar sobre a partida dele, que ele estava para realizar em Jerusalém.

[[v42-9-32]]

^<<v42-9-32,32>>^ Pedro e os que estavam com ele haviam sido vencidos pelo sono, mas, quando despertaram completamente, viram a glória dele e os dois homens em pé com ele.

[[v42-9-33]]

^<<v42-9-33,33>>^ E, enquanto esses se afastavam dele, Pedro disse a Jesus: “Instrutor, é bom que estejamos aqui. Vamos armar, então, três tendas: uma para o senhor, uma para Moisés e uma para Elias.” Ele não se dava conta do que estava dizendo.

[[v42-9-34]]

^<<v42-9-34,34>>^ Mas, enquanto dizia isso, formou-se uma nuvem e começou a cobri-los. Quando a nuvem os envolveu, ficaram com medo.

[[v42-9-35]]

^<<v42-9-35,35>>^ Então uma voz saiu da nuvem, dizendo: “Este é meu Filho, aquele que foi escolhido. Escutem-no.”

[[v42-9-36]]

^<<v42-9-36,36>>^ No momento em que a voz falou, Jesus ficou sozinho. Mas eles ficaram calados e não contaram a ninguém, naqueles dias, nenhuma das coisas que viram.

[[v42-9-37]]

^<<v42-9-37,37>>^ No dia seguinte, quando desceram do monte, uma grande multidão foi ao encontro dele.

[[v42-9-38]]

^<<v42-9-38,38>>^ E então um homem gritou dentre a multidão: “Instrutor, imploro-lhe que veja o meu filho, porque ele é o meu filho único.

[[v42-9-39]]

^<<v42-9-39,39>>^ Vem um espírito e se apodera dele, e ele grita de repente, e o espírito o lança em convulsões e faz a sua boca espumar; só com dificuldade o espírito o deixa, depois de machucá-lo.

[[v42-9-40]]

^<<v42-9-40,40>>^ Supliquei aos seus discípulos que expulsassem o espírito, mas eles não conseguiram.”

[[v42-9-41]]

^<<v42-9-41,41>>^ Em resposta, Jesus disse: “Ó geração sem fé e pervertida, até quando terei de continuar com vocês e terei de suportá-los? Traga seu filho para cá.”

[[v42-9-42]]

^<<v42-9-42,42>>^ E, enquanto o menino se aproximava, o demônio o lançou no chão e lhe causou violentas convulsões. Mas Jesus censurou o espírito impuro e curou o menino, e o entregou ao seu pai.

[[v42-9-43]]

^<<v42-9-43,43>>^ E todos ficaram assombrados com o poder majestoso de Deus.
Enquanto todos se maravilhavam com tudo o que ele fazia, ele disse aos seus discípulos:

[[v42-9-44]]

^<<v42-9-44,44>>^ “Ouçam atentamente e lembrem-se destas palavras: O Filho do Homem será entregue^&#42;1^ às mãos dos homens.”

[NOTE]
====
. Ou: “traído”.
====

[[v42-9-45]]

^<<v42-9-45,45>>^ Mas não entenderam o que ele dizia. De fato, isso foi escondido deles para que não compreendessem, e tinham medo de lhe perguntar sobre essa declaração.

[[v42-9-46]]

^<<v42-9-46,46>>^ Então surgiu entre eles uma discussão sobre qual deles era o maior.

[[v42-9-47]]

^<<v42-9-47,47>>^ Jesus, conhecendo os raciocínios do coração deles, pegou uma criancinha, colocou-a ao seu lado

[[v42-9-48]]

^<<v42-9-48,48>>^ e lhes disse: “Quem recebe esta criancinha em meu nome recebe também a mim; e quem me recebe, recebe também Aquele que me enviou. Pois quem se comporta como menor entre todos vocês é o que é grande.”

[[v42-9-49]]

^<<v42-9-49,49>>^ Em vista disso, João disse: “Instrutor, vimos alguém expulsar demônios usando o seu nome e tentamos impedi-lo, porque ele não segue o senhor conosco.”

[[v42-9-50]]

^<<v42-9-50,50>>^ Mas Jesus lhe disse: “Não tentem impedi-lo, pois quem não é contra vocês é a favor de vocês.”

[[v42-9-51]]

^<<v42-9-51,51>>^ Aproximando-se^&#42;1^ o tempo de ser levado para cima, ele partiu resolutamente^&#42;2^ para Jerusalém.

[NOTE]
====
. Lit.: “Completando-se”.
. Lit.: “fixou a sua face”.
====

[[v42-9-52]]

^<<v42-9-52,52>>^ E enviou mensageiros na sua frente, que foram e entraram numa aldeia de samaritanos, para fazer os preparativos para ele.

[[v42-9-53]]

^<<v42-9-53,53>>^ Mas os samaritanos não o receberam, porque ele estava indo^&#42;1^ para Jerusalém.

[NOTE]
====
. Lit.: “sua face estava direcionada”.
====

[[v42-9-54]]

^<<v42-9-54,54>>^ Quando os discípulos Tiago e João viram isso, disseram: “Senhor, quer que mandemos que desça fogo do céu e os destrua?”

[[v42-9-55]]

^<<v42-9-55,55>>^ Ele, porém, se virou e os censurou.

[[v42-9-56]]

^<<v42-9-56,56>>^ Assim, foram a outra aldeia.

[[v42-9-57]]

^<<v42-9-57,57>>^ Então, enquanto caminhavam pela estrada, alguém lhe disse: “Eu seguirei o senhor para onde quer que vá.”

[[v42-9-58]]

^<<v42-9-58,58>>^ No entanto, Jesus lhe disse: “As raposas têm tocas e as aves do céu têm ninhos, mas o Filho do Homem não tem onde deitar a cabeça.”

[[v42-9-59]]

^<<v42-9-59,59>>^ Então ele disse a outro: “Seja meu seguidor.” O homem disse: “Senhor, permita-me primeiro ir enterrar meu pai.”

[[v42-9-60]]

^<<v42-9-60,60>>^ No entanto, ele lhe disse: “Deixe que os mortos enterrem seus mortos, mas você, vá e divulgue o Reino de Deus.”

[[v42-9-61]]

^<<v42-9-61,61>>^ E ainda outro disse: “Eu o seguirei, Senhor, mas permita-me primeiro me despedir da minha família.”

[[v42-9-62]]

^<<v42-9-62,62>>^ Jesus lhe disse: “Ninguém que tiver posto a mão num arado e olhar para trás está apto para o Reino de Deus.”

'''

xref:042-lucas/042-lucas-008.adoc#v42-8-0[&#60; Capítulo Anterior] | <<v42-9-0,Topo>> | xref:042-lucas/042-lucas-010.adoc#v42-10-0[Próximo Capítulo &#62;]