include::./index.adoc[]

[[v42-22-0]]
=== Segundo Lucas, 22
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-22-1]]

^<<v42-22-1,1>>^ Aproximava-se então a Festividade dos Pães sem Fermento, chamada Páscoa.

[[v42-22-2]]

^<<v42-22-2,2>>^ E os principais sacerdotes e os escribas estavam procurando o melhor modo de se livrar dele, porque tinham medo do povo.

[[v42-22-3]]

^<<v42-22-3,3>>^ Então Satanás entrou em Judas, o chamado Iscariotes, que era contado entre os Doze,

[[v42-22-4]]

^<<v42-22-4,4>>^ e este se dirigiu aos principais sacerdotes e aos capitães do templo para falar sobre como poderia entregá-lo^&#42;1^ a eles.

[NOTE]
====
. Ou: “traí-lo”.
====

[[v42-22-5]]

^<<v42-22-5,5>>^ Eles se alegraram com isso e concordaram em lhe dar dinheiro de prata.

[[v42-22-6]]

^<<v42-22-6,6>>^ De modo que ele aceitou e começou a procurar uma boa oportunidade para entregá-lo^&#42;1^ a eles sem que houvesse uma multidão em volta.

[NOTE]
====
. Ou: “traí-lo”.
====

[[v42-22-7]]

^<<v42-22-7,7>>^ Chegou o dia da Festividade dos Pães sem Fermento, em que se tem de oferecer o sacrifício pascoal;

[[v42-22-8]]

^<<v42-22-8,8>>^ então Jesus enviou Pedro e João, dizendo: “Vão e aprontem a refeição pascoal para que a comamos.”

[[v42-22-9]]

^<<v42-22-9,9>>^ Disseram-lhe: “Onde o senhor quer que a aprontemos?”

[[v42-22-10]]

^<<v42-22-10,10>>^ Ele lhes disse: “Escutem: Ao entrarem na cidade, um homem levando um jarro de barro com água encontrará vocês. Sigam-no para dentro da casa em que ele entrar.

[[v42-22-11]]

^<<v42-22-11,11>>^ E digam ao proprietário da casa: ‘O Instrutor mandou lhe dizer: “Onde está a sala dos hóspedes, em que eu possa tomar a refeição pascoal com os meus discípulos?”’

[[v42-22-12]]

^<<v42-22-12,12>>^ E esse homem lhes mostrará uma grande sala mobiliada no andar de cima. Aprontem-na ali.”

[[v42-22-13]]

^<<v42-22-13,13>>^ Eles foram então, e encontraram tudo assim como ele tinha lhes dito, e prepararam a refeição pascoal.

[[v42-22-14]]

^<<v42-22-14,14>>^ Quando chegou a hora, ele se recostou à mesa junto com os apóstolos.

[[v42-22-15]]

^<<v42-22-15,15>>^ E ele lhes disse: “Desejei muito comer esta refeição pascoal com vocês antes de sofrer,

[[v42-22-16]]

^<<v42-22-16,16>>^ pois eu lhes digo: Não a comerei de novo até que ela se cumpra no Reino de Deus.”

[[v42-22-17]]

^<<v42-22-17,17>>^ E ele recebeu um cálice, deu graças e disse: “Peguem este cálice e passem-no de um para o outro,

[[v42-22-18]]

^<<v42-22-18,18>>^ pois eu lhes digo: De agora em diante não beberei de novo do produto da videira até que venha o Reino de Deus.”

[[v42-22-19]]

^<<v42-22-19,19>>^ Ele pegou também um pão, deu graças, partiu-o e deu a eles, dizendo: “Isto representa o meu corpo, que será dado em benefício de vocês. Persistam em fazer isso em memória de mim.”

[[v42-22-20]]

^<<v42-22-20,20>>^ Ele fez o mesmo com respeito ao cálice, depois de terem tomado a refeição, dizendo: “Este cálice representa o novo pacto com base no meu sangue, que será derramado em seu benefício.

[[v42-22-21]]

^<<v42-22-21,21>>^ “Mas saibam que a mão daquele que me trai está comigo à mesa.

[[v42-22-22]]

^<<v42-22-22,22>>^ De fato, o Filho do Homem vai embora, segundo o que foi determinado; porém, ai daquele que o trai!”

[[v42-22-23]]

^<<v42-22-23,23>>^ Assim, começaram a perguntar uns aos outros qual deles realmente estaria para fazer isso.

[[v42-22-24]]

^<<v42-22-24,24>>^ No entanto, eles começaram também uma discussão acalorada sobre qual deles era o maior.

[[v42-22-25]]

^<<v42-22-25,25>>^ Mas ele lhes disse: “Os reis das nações dominam sobre elas, e os que têm autoridade sobre elas são chamados de ‘benfeitores’.

[[v42-22-26]]

^<<v42-22-26,26>>^ Vocês, porém, não devem ser assim. Mas que o maior entre vocês se torne como o mais jovem, e o que está na liderança, como aquele que serve.^&#42;1^

[NOTE]
====
. Ou: “ministra”.
====

[[v42-22-27]]

^<<v42-22-27,27>>^ Pois quem é maior: aquele que está^&#42;1^ à mesa ou aquele que serve?^&#42;2^ Não é quem está^&#42;3^ à mesa? Mas eu estou no meio de vocês como quem serve.^&#42;4^

[NOTE]
====
. Ou: “se recosta”.
. Ou: “ministra”.
. Ou: “se recosta”.
. Ou: “ministra”.
====

[[v42-22-28]]

^<<v42-22-28,28>>^ “No entanto, vocês são os que ficaram comigo nas minhas provações;

[[v42-22-29]]

^<<v42-22-29,29>>^ e eu faço com vocês um pacto para um reino, assim como o meu Pai fez um pacto comigo,

[[v42-22-30]]

^<<v42-22-30,30>>^ a fim de que vocês comam e bebam à minha mesa, no meu Reino, e se sentem em tronos para julgar as 12 tribos de Israel.

[[v42-22-31]]

^<<v42-22-31,31>>^ “Simão, Simão, escute: Satanás exigiu que todos vocês fossem peneirados como trigo.

[[v42-22-32]]

^<<v42-22-32,32>>^ Mas tenho feito súplicas por você para que a sua fé não fraqueje; e você, quando tiver voltado, fortaleça os seus irmãos.”

[[v42-22-33]]

^<<v42-22-33,33>>^ Então ele lhe disse: “Estou pronto para ir com o Senhor tanto para a prisão como para a morte.”

[[v42-22-34]]

^<<v42-22-34,34>>^ Mas ele disse: “Eu lhe digo, Pedro: O galo não cantará hoje até que você tenha negado três vezes que me conhece.”

[[v42-22-35]]

^<<v42-22-35,35>>^ Ele lhes disse também: “Quando os enviei sem bolsa de dinheiro, sem bolsa de provisões e sem sandálias, será que lhes faltou alguma coisa?” Eles disseram: “Não!”

[[v42-22-36]]

^<<v42-22-36,36>>^ Então ele lhes disse: “Mas agora, quem tiver bolsa de dinheiro, leve-a consigo, e também uma bolsa de provisões; e quem não tiver espada, venda a sua capa e compre uma.

[[v42-22-37]]

^<<v42-22-37,37>>^ Pois eu lhes digo que tem de se cumprir em mim aquilo que foi escrito: ‘Ele foi contado entre os transgressores.’ Sim, isso está se cumprindo em mim.”

[[v42-22-38]]

^<<v42-22-38,38>>^ Disseram então: “Senhor, temos aqui duas espadas.” Ele lhes disse: “É o suficiente.”

[[v42-22-39]]

^<<v42-22-39,39>>^ Ao sair, ele foi, como de costume, para o monte das Oliveiras, e os discípulos também o seguiram.

[[v42-22-40]]

^<<v42-22-40,40>>^ Quando chegaram ao lugar, ele lhes disse: “Persistam em orar, para que não caiam em tentação.”

[[v42-22-41]]

^<<v42-22-41,41>>^ E ele se afastou deles à distância de um arremesso de pedra, ajoelhou-se e começou a orar,

[[v42-22-42]]

^<<v42-22-42,42>>^ dizendo: “Pai, se tu quiseres, afasta de mim este cálice. Contudo, ocorra não a minha vontade, mas a tua.”

[[v42-22-43]]

^<<v42-22-43,43>>^ Apareceu-lhe então um anjo do céu e o fortaleceu.

[[v42-22-44]]

^<<v42-22-44,44>>^ Mas ele ficou tão angustiado que orou ainda mais intensamente; e o seu suor se tornou como gotas de sangue que caíam no chão.

[[v42-22-45]]

^<<v42-22-45,45>>^ Quando ele se levantou depois de orar e se dirigiu aos discípulos, encontrou-os adormecidos, exaustos de tristeza.

[[v42-22-46]]

^<<v42-22-46,46>>^ Ele lhes disse: “Por que vocês estão dormindo? Levantem-se e continuem orando, para que não caiam em tentação.”

[[v42-22-47]]

^<<v42-22-47,47>>^ Enquanto ele ainda falava, chegou uma multidão, e o homem chamado Judas, um dos Doze, os liderava, e ele se aproximou de Jesus para beijá-lo.

[[v42-22-48]]

^<<v42-22-48,48>>^ Mas Jesus lhe disse: “Judas, você está traindo o Filho do Homem com um beijo?”

[[v42-22-49]]

^<<v42-22-49,49>>^ Quando os que estavam em volta dele viram o que ia acontecer, disseram: “Senhor, devemos atacá-los com a espada?”

[[v42-22-50]]

^<<v42-22-50,50>>^ Um deles até mesmo atacou o escravo do sumo sacerdote, decepando-lhe a orelha direita.

[[v42-22-51]]

^<<v42-22-51,51>>^ Mas Jesus disse, em resposta: “Basta!” E tocou na orelha e o curou.

[[v42-22-52]]

^<<v42-22-52,52>>^ Jesus disse então aos principais sacerdotes, aos capitães do templo e aos anciãos que tinham ido ali em busca dele: “Vocês vieram com espadas e bastões, como se eu fosse um bandido?

[[v42-22-53]]

^<<v42-22-53,53>>^ Enquanto eu estava com vocês no templo, dia após dia, vocês não puseram as mãos em mim. Mas esta é a hora de vocês e a autoridade da escuridão.”

[[v42-22-54]]

^<<v42-22-54,54>>^ Então o prenderam e o levaram embora para a casa do sumo sacerdote. Mas Pedro seguia à distância.

[[v42-22-55]]

^<<v42-22-55,55>>^ Quando acenderam um fogo no meio do pátio e se sentaram juntos, Pedro se sentou entre eles.

[[v42-22-56]]

^<<v42-22-56,56>>^ Mas uma serva, vendo-o sentado à luz do fogo, olhou atentamente para ele e disse: “Este homem também estava com ele.”

[[v42-22-57]]

^<<v42-22-57,57>>^ Mas ele negou, dizendo: “Não o conheço, mulher.”

[[v42-22-58]]

^<<v42-22-58,58>>^ Pouco tempo depois, outra pessoa o viu e disse: “Você também é um deles.” Mas Pedro disse: “Homem, não sou.”

[[v42-22-59]]

^<<v42-22-59,59>>^ E, depois de passar cerca de uma hora, outro homem começou a insistir: “Este homem certamente também estava com ele, pois, de fato, é galileu!”

[[v42-22-60]]

^<<v42-22-60,60>>^ Mas Pedro disse: “Homem, não sei do que você está falando.” E, naquele instante, enquanto ainda falava, um galo cantou.

[[v42-22-61]]

^<<v42-22-61,61>>^ Com isso, o Senhor se virou e olhou diretamente para Pedro, e Pedro se lembrou da declaração do Senhor, que tinha lhe dito: “Hoje, antes de o galo cantar, você me negará três vezes.”

[[v42-22-62]]

^<<v42-22-62,62>>^ Então ele saiu e chorou amargamente.

[[v42-22-63]]

^<<v42-22-63,63>>^ Os homens que tinham Jesus em detenção começaram então a zombar dele, batendo nele;

[[v42-22-64]]

^<<v42-22-64,64>>^ e, depois de lhe cobrirem o rosto, diziam: “Profetize! Quem foi que bateu em você?”

[[v42-22-65]]

^<<v42-22-65,65>>^ E diziam muitas outras blasfêmias contra ele.

[[v42-22-66]]

^<<v42-22-66,66>>^ Quando o dia amanheceu, reuniu-se a assembleia dos anciãos do povo, tanto os principais sacerdotes como os escribas; eles o levaram para o Sinédrio e disseram:

[[v42-22-67]]

^<<v42-22-67,67>>^ “Se você é o Cristo, diga-nos.” Mas ele lhes disse: “Mesmo que eu lhes dissesse, vocês de modo algum acreditariam.

[[v42-22-68]]

^<<v42-22-68,68>>^ Além disso, se eu lhes fizesse perguntas, vocês não me responderiam.

[[v42-22-69]]

^<<v42-22-69,69>>^ No entanto, de agora em diante o Filho do Homem estará sentado à direita poderosa de Deus.”

[[v42-22-70]]

^<<v42-22-70,70>>^ Em vista disso, todos perguntaram: “Então, você é o Filho de Deus?” Ele lhes respondeu: “Vocês mesmos dizem que eu sou.”

[[v42-22-71]]

^<<v42-22-71,71>>^ Eles disseram: “Por que precisamos de mais testemunho? Pois nós mesmos ouvimos isso da sua própria boca.”

'''

xref:042-lucas/042-lucas-021.adoc#v42-21-0[&#60; Capítulo Anterior] | <<v42-22-0,Topo>> | xref:042-lucas/042-lucas-023.adoc#v42-23-0[Próximo Capítulo &#62;]