include::./index.adoc[]

[[v42-5-0]]
=== Segundo Lucas, 5
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-5-1]]

^<<v42-5-1,1>>^ Em certa ocasião, ele estava à beira do lago de Genesaré,^&#42;1^ e a multidão se apertava em volta dele para escutar a palavra de Deus.

[NOTE]
====
. Isto é, o mar da Galileia.
====

[[v42-5-2]]

^<<v42-5-2,2>>^ Ele viu dois barcos atracados à beira do lago, mas os pescadores tinham desembarcado e estavam lavando as suas redes.

[[v42-5-3]]

^<<v42-5-3,3>>^ Entrando num dos barcos, que era o de Simão, pediu-lhe que o afastasse um pouco da terra. Sentou-se então e, do barco, começou a ensinar as multidões.

[[v42-5-4]]

^<<v42-5-4,4>>^ Quando parou de falar, ele disse a Simão: “Vá para onde é fundo, e abaixem as suas redes para uma pesca.”

[[v42-5-5]]

^<<v42-5-5,5>>^ Simão, porém, disse em resposta: “Instrutor, trabalhamos arduamente a noite toda e não apanhamos nada, mas, como o senhor pediu, abaixarei as redes.”

[[v42-5-6]]

^<<v42-5-6,6>>^ Pois bem, quando fizeram isso, apanharam^&#42;1^ uma quantidade tão grande de peixes que suas redes começaram a se romper.

[NOTE]
====
. Lit.: “cercaram”.
====

[[v42-5-7]]

^<<v42-5-7,7>>^ Então, fizeram sinal para os seus sócios no outro barco, para que se aproximassem e os auxiliassem; e eles vieram e encheram ambos os barcos, de modo que esses começaram a afundar.

[[v42-5-8]]

^<<v42-5-8,8>>^ Vendo isso, Simão Pedro se prostrou aos joelhos de Jesus, dizendo: “Afaste-se de mim, Senhor, porque sou homem pecador.”

[[v42-5-9]]

^<<v42-5-9,9>>^ Pois tanto ele como os que estavam com ele foram tomados de espanto em vista da quantidade de peixes que tinham apanhado,

[[v42-5-10]]

^<<v42-5-10,10>>^ e o mesmo aconteceu com Tiago e João, filhos de Zebedeu, que eram sócios de Simão. Mas Jesus disse a Simão: “Pare de ter medo. De agora em diante você apanhará^&#42;1^ a homens.”^&#42;2^

[NOTE]
====
. Ou: “apanhará vivos”.
. Ou: “pessoas”.
====

[[v42-5-11]]

^<<v42-5-11,11>>^ Assim, levaram os barcos de volta a terra, abandonaram tudo e o seguiram.

[[v42-5-12]]

^<<v42-5-12,12>>^ Em outra ocasião, ele estava numa das cidades quando apareceu um homem coberto de lepra. Quando ele viu Jesus, prostrou-se com o rosto por terra e lhe implorou: “Senhor, se apenas quiser, pode me purificar.”

[[v42-5-13]]

^<<v42-5-13,13>>^ Assim, ele estendeu a mão e tocou no homem, dizendo: “Eu quero! Seja purificado.” Imediatamente a lepra desapareceu dele.

[[v42-5-14]]

^<<v42-5-14,14>>^ Então ele ordenou ao homem que não contasse nada a ninguém, e acrescentou: “Mas vá e mostre-se ao sacerdote, e faça uma oferta pela sua purificação, assim como Moisés determinou, em testemunho para eles.”

[[v42-5-15]]

^<<v42-5-15,15>>^ Mas as notícias sobre ele continuavam se espalhando, e grandes multidões se reuniam para escutar e para ser curadas de suas doenças.

[[v42-5-16]]

^<<v42-5-16,16>>^ No entanto, ele muitas vezes ia a lugares desertos para orar.

[[v42-5-17]]

^<<v42-5-17,17>>^ Num daqueles dias, quando ele estava ensinando, fariseus e instrutores da Lei, que haviam chegado de todas as aldeias da Galileia e da Judeia, e de Jerusalém, estavam sentados ali; e o poder de Jeová^&#42;1^ estava com ele para fazer curas.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-5-18]]

^<<v42-5-18,18>>^ Nisto, chegaram alguns homens carregando um homem paralítico numa maca, e eles tentavam levá-lo para dentro e colocá-lo diante de Jesus.

[[v42-5-19]]

^<<v42-5-19,19>>^ Assim, visto que não encontraram um meio de levá-lo para dentro por causa da multidão, subiram ao telhado e o baixaram em sua maca, entre as telhas, bem no meio dos que estavam diante de Jesus.

[[v42-5-20]]

^<<v42-5-20,20>>^ Quando ele viu a fé que tinham, disse: “Homem, seus pecados estão perdoados.”

[[v42-5-21]]

^<<v42-5-21,21>>^ Então, os escribas e os fariseus começaram a raciocinar, dizendo: “Quem é este que fala blasfêmias? Quem pode perdoar pecados a não ser somente Deus?”

[[v42-5-22]]

^<<v42-5-22,22>>^ Mas Jesus, discernindo o raciocínio deles, disse-lhes em resposta: “O que vocês estão raciocinando no coração?

[[v42-5-23]]

^<<v42-5-23,23>>^ O que é mais fácil dizer: ‘Seus pecados estão perdoados’, ou: ‘Levante-se e ande’?

[[v42-5-24]]

^<<v42-5-24,24>>^ Mas, a fim de que vocês saibam que o Filho do Homem tem autoridade na terra para perdoar pecados . . .”, ele disse ao paralítico: “Eu lhe digo: Levante-se, apanhe a sua maca e vá para casa.”

[[v42-5-25]]

^<<v42-5-25,25>>^ Com isso, ele se levantou diante deles, apanhou aquilo em que se deitava e foi para casa, glorificando a Deus.

[[v42-5-26]]

^<<v42-5-26,26>>^ Então, todos foram tomados de admiração, começaram a glorificar a Deus e, cheios de temor, diziam: “Vimos coisas maravilhosas hoje!”

[[v42-5-27]]

^<<v42-5-27,27>>^ Depois disso, ele saiu e viu um cobrador de impostos, chamado Levi, sentado na coletoria, e lhe disse: “Seja meu seguidor.”

[[v42-5-28]]

^<<v42-5-28,28>>^ E Levi, deixando tudo para trás, se levantou e começou a segui-lo.

[[v42-5-29]]

^<<v42-5-29,29>>^ Então Levi lhe ofereceu um grande banquete para recepcioná-lo na sua casa, e havia uma grande multidão de cobradores de impostos e de outros, que estavam comendo^&#42;1^ com eles.

[NOTE]
====
. Ou: “recostados à mesa”.
====

[[v42-5-30]]

^<<v42-5-30,30>>^ Em vista disso, os fariseus e os seus escribas começaram a resmungar, dizendo aos discípulos dele: “Por que vocês comem e bebem com cobradores de impostos e pecadores?”

[[v42-5-31]]

^<<v42-5-31,31>>^ Em resposta, Jesus lhes disse: “Os que têm saúde não precisam de médico, mas sim os doentes.

[[v42-5-32]]

^<<v42-5-32,32>>^ Eu não vim chamar os justos ao arrependimento, mas os pecadores.”

[[v42-5-33]]

^<<v42-5-33,33>>^ Eles lhe disseram: “Os discípulos de João jejuam frequentemente e oferecem súplicas, e o mesmo fazem os dos fariseus, mas os seus comem e bebem.”

[[v42-5-34]]

^<<v42-5-34,34>>^ Jesus lhes disse: “Será que vocês podem fazer os amigos do noivo jejuar enquanto o noivo está com eles?

[[v42-5-35]]

^<<v42-5-35,35>>^ Mas virão dias em que o noivo realmente será tirado deles; então, naqueles dias, eles jejuarão.”

[[v42-5-36]]

^<<v42-5-36,36>>^ Contou-lhes também uma ilustração: “Ninguém corta um pedaço de uma roupa nova para remendar uma roupa velha. Se fizer isso, o remendo novo se soltará e o remendo da roupa nova não combinará com a velha.

[[v42-5-37]]

^<<v42-5-37,37>>^ Também, ninguém põe vinho novo em odres velhos. Se fizer isso, o vinho novo arrebentará os odres e se derramará, e os odres ficarão arruinados.

[[v42-5-38]]

^<<v42-5-38,38>>^ Mas vinho novo tem de ser posto em odres novos.

[[v42-5-39]]

^<<v42-5-39,39>>^ Ninguém, depois de beber vinho velho, quer o novo, pois diz: ‘O velho é bom.’”

'''

xref:042-lucas/042-lucas-004.adoc#v42-4-0[&#60; Capítulo Anterior] | <<v42-5-0,Topo>> | xref:042-lucas/042-lucas-006.adoc#v42-6-0[Próximo Capítulo &#62;]