include::./index.adoc[]

[[v42-10-0]]
=== Segundo Lucas, 10
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-10-1]]

^<<v42-10-1,1>>^ Depois disso, o Senhor designou mais 70 e os enviou de dois em dois, na sua frente, a toda cidade e lugar aonde ele mesmo estava para ir.

[[v42-10-2]]

^<<v42-10-2,2>>^ Ele lhes disse então: “A colheita, realmente, é grande, mas os trabalhadores são poucos. Por isso, peçam ao Senhor da colheita que mande trabalhadores para a Sua colheita.

[[v42-10-3]]

^<<v42-10-3,3>>^ Vão! Eu os envio como cordeiros no meio de lobos.

[[v42-10-4]]

^<<v42-10-4,4>>^ Não levem bolsa de dinheiro, nem bolsa de provisões, nem sandálias, e não cumprimentem ninguém^&#42;1^ ao longo da estrada.

[NOTE]
====
. Ou: “não abracem a ninguém em cumprimento”.
====

[[v42-10-5]]

^<<v42-10-5,5>>^ Em qualquer casa onde entrarem, digam primeiro: ‘Haja paz nesta casa.’

[[v42-10-6]]

^<<v42-10-6,6>>^ E, se ali houver um amigo da paz, a paz de vocês descansará sobre ele. Mas, se não houver, ela voltará para vocês.

[[v42-10-7]]

^<<v42-10-7,7>>^ Assim, fiquem naquela casa, comendo e bebendo as coisas que lhes oferecerem, porque o trabalhador é digno do seu salário. Não fiquem mudando de uma casa para outra.

[[v42-10-8]]

^<<v42-10-8,8>>^ “Também, onde quer que vocês entrarem numa cidade e as pessoas os receberem, comam o que for colocado diante de vocês,

[[v42-10-9]]

^<<v42-10-9,9>>^ curem os doentes nela e digam-lhes: ‘O Reino de Deus está próximo de vocês.’

[[v42-10-10]]

^<<v42-10-10,10>>^ Mas, onde quer que entrarem numa cidade e as pessoas não os receberem, saiam para as suas ruas principais e digam:

[[v42-10-11]]

^<<v42-10-11,11>>^ ‘Nós sacudiremos até mesmo o pó da sua cidade que grudou nos nossos pés, em testemunho contra vocês. Contudo, saibam do seguinte: o Reino de Deus está próximo.’

[[v42-10-12]]

^<<v42-10-12,12>>^ Eu lhes digo que naquele dia será mais suportável para Sodoma do que para essa cidade.

[[v42-10-13]]

^<<v42-10-13,13>>^ “Ai de você, Corazim! Ai de você, Betsaida! Porque, se as obras poderosas que ocorreram em vocês tivessem ocorrido em Tiro e Sídon, há muito tempo elas teriam se arrependido, sentadas em pano de saco e em cinzas.

[[v42-10-14]]

^<<v42-10-14,14>>^ Por isso, no julgamento, será mais suportável para Tiro e Sídon do que para vocês.

[[v42-10-15]]

^<<v42-10-15,15>>^ E você, Cafarnaum, será por acaso enaltecida ao céu? Até a Sepultura^&#42;1^ você descerá!

[NOTE]
====
. Ou: “o Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v42-10-16]]

^<<v42-10-16,16>>^ “Quem escuta vocês escuta a mim. E quem desconsidera vocês desconsidera também a mim. Além disso, quem desconsidera a mim desconsidera também Aquele que me enviou.”

[[v42-10-17]]

^<<v42-10-17,17>>^ Os 70 voltaram então com alegria, dizendo: “Senhor, até mesmo os demônios nos obedecem pelo uso do seu nome.”

[[v42-10-18]]

^<<v42-10-18,18>>^ Em vista disso, ele lhes disse: “Vejo Satanás já caído como relâmpago do céu.

[[v42-10-19]]

^<<v42-10-19,19>>^ Escutem: Eu dei a vocês autoridade para pisar serpentes e escorpiões, e sobre todo o poder do inimigo, e absolutamente nada lhes fará mal.

[[v42-10-20]]

^<<v42-10-20,20>>^ Contudo, não se alegrem porque os espíritos estão sendo sujeitos a vocês, mas alegrem-se porque os nomes de vocês foram escritos nos céus.”

[[v42-10-21]]

^<<v42-10-21,21>>^ Naquela mesma hora ele ficou cheio de alegria por meio do espírito santo e disse: “Eu te louvo publicamente, Pai, Senhor do céu e da terra, porque escondeste cuidadosamente essas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos. Sim, ó Pai, porque tu te agradaste de fazer as coisas dessa maneira.

[[v42-10-22]]

^<<v42-10-22,22>>^ Tudo me foi entregue por meu Pai. E ninguém sabe quem o Filho é, exceto o Pai; e ninguém sabe quem o Pai é, exceto o Filho e aquele a quem o Filho quiser revelá-lo.”

[[v42-10-23]]

^<<v42-10-23,23>>^ Com isso, ele se virou para os discípulos e lhes disse em particular: “Felizes são os olhos que veem as coisas que vocês estão vendo.

[[v42-10-24]]

^<<v42-10-24,24>>^ Pois eu lhes digo: Muitos profetas e reis desejaram ver as coisas que vocês estão observando, mas não as viram, e ouvir as coisas que vocês estão ouvindo, mas não as ouviram.”

[[v42-10-25]]

^<<v42-10-25,25>>^ Então, um homem perito na Lei se levantou para prová-lo e perguntou: “Instrutor, o que devo fazer para herdar a vida eterna?”

[[v42-10-26]]

^<<v42-10-26,26>>^ Ele lhe disse: “O que está escrito na Lei? Como você lê?”

[[v42-10-27]]

^<<v42-10-27,27>>^ Em resposta, ele disse: “‘Ame a Jeová,^&#42;1^ seu Deus, de todo o seu coração, de toda a sua alma,^&#42;2^ de toda a sua força e de toda a sua mente’ e ‘o seu próximo como a si mesmo’.”

[NOTE]
====
. Veja Ap. A5.
. Veja o Glossário.
====

[[v42-10-28]]

^<<v42-10-28,28>>^ Ele lhe disse: “Você respondeu corretamente; persista em fazer isso e obterá a vida.”

[[v42-10-29]]

^<<v42-10-29,29>>^ Mas, querendo se mostrar justo, o homem perguntou a Jesus: “Quem é realmente o meu próximo?”

[[v42-10-30]]

^<<v42-10-30,30>>^ Em resposta, Jesus disse: “Um homem descia de Jerusalém para Jericó e caiu nas mãos de assaltantes, que lhe arrancaram tudo, o espancaram e foram embora, deixando-o quase morto.

[[v42-10-31]]

^<<v42-10-31,31>>^ Por coincidência, um sacerdote descia por aquela estrada, mas, quando o viu, passou pelo lado oposto.

[[v42-10-32]]

^<<v42-10-32,32>>^ Do mesmo modo, um levita, quando chegou ao lugar e o viu, passou pelo lado oposto.

[[v42-10-33]]

^<<v42-10-33,33>>^ Mas certo samaritano, viajando pela estrada, o encontrou e, ao vê-lo, teve pena.

[[v42-10-34]]

^<<v42-10-34,34>>^ De modo que se aproximou dele e enfaixou seus ferimentos, derramando neles azeite e vinho. Então o pôs no seu próprio animal, o levou a uma hospedaria e cuidou dele.

[[v42-10-35]]

^<<v42-10-35,35>>^ No dia seguinte tirou dois denários,^&#42;1^ deu-os ao hospedeiro e disse: ‘Cuide dele e, tudo o que você gastar além disso, eu lhe pagarei quando voltar.’

[NOTE]
====
. Veja Ap. B14.
====

[[v42-10-36]]

^<<v42-10-36,36>>^ Qual desses três você acha que mostrou ser o próximo do homem que caiu nas mãos de assaltantes?”

[[v42-10-37]]

^<<v42-10-37,37>>^ Ele respondeu: “Aquele que agiu misericordiosamente com ele.” Jesus lhe disse então: “Vá e faça você o mesmo.”

[[v42-10-38]]

^<<v42-10-38,38>>^ Ao prosseguirem, ele entrou em certa aldeia. Ali, uma mulher chamada Marta o recebeu como hóspede em sua casa.

[[v42-10-39]]

^<<v42-10-39,39>>^ Ela tinha também uma irmã, chamada Maria, que se sentou aos pés do Senhor e ficou escutando o que ele dizia.^&#42;1^

[NOTE]
====
. Lit.: “sua palavra”.
====

[[v42-10-40]]

^<<v42-10-40,40>>^ Marta, por outro lado, estava distraída, cuidando de muitos afazeres. Assim, ela se aproximou dele e disse: “Senhor, não se importa que minha irmã me deixou sozinha para cuidar das coisas? Diga a ela que venha me ajudar.”

[[v42-10-41]]

^<<v42-10-41,41>>^ Em resposta, o Senhor lhe disse: “Marta, Marta, você está ansiosa e preocupada com muitas coisas.

[[v42-10-42]]

^<<v42-10-42,42>>^ Mas poucas coisas são necessárias, ou apenas uma. Maria, por sua vez, escolheu a boa porção,^&#42;1^ e essa não será tirada dela.”

[NOTE]
====
. Ou: “melhor parte”.
====

'''

xref:042-lucas/042-lucas-009.adoc#v42-9-0[&#60; Capítulo Anterior] | <<v42-10-0,Topo>> | xref:042-lucas/042-lucas-011.adoc#v42-11-0[Próximo Capítulo &#62;]