include::./index.adoc[]

[[v42-16-0]]
=== Segundo Lucas, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-16-1]]

^<<v42-16-1,1>>^ Então ele disse também aos discípulos: “Um homem rico tinha um administrador^&#42;1^ que foi acusado de desperdiçar os bens do seu senhor.

[NOTE]
====
. Ou: “administrador da casa”.
====

[[v42-16-2]]

^<<v42-16-2,2>>^ Assim, ele o chamou e disse: ‘O que é isso que ouço a seu respeito? Preste contas da sua administração, pois você não pode mais administrar a casa.’

[[v42-16-3]]

^<<v42-16-3,3>>^ Então, o administrador disse a si mesmo: ‘O que eu vou fazer, visto que o meu senhor está me tirando a administração? Não sou bastante forte para cavar e tenho vergonha de mendigar.

[[v42-16-4]]

^<<v42-16-4,4>>^ Ah! já sei o que vou fazer para que, quando eu for afastado da administração, as pessoas me recebam em suas casas.’

[[v42-16-5]]

^<<v42-16-5,5>>^ E, chamando cada um dos devedores do seu senhor, perguntou ao primeiro: ‘Quanto você deve ao meu senhor?’

[[v42-16-6]]

^<<v42-16-6,6>>^ Ele respondeu: ‘Cem medidas^&#42;1^ de azeite.’ O administrador lhe disse: ‘Pegue de volta o seu acordo escrito, sente-se e escreva rapidamente 50.’

[NOTE]
====
. Ou: “batos”. Um bato equivalia a 22 l. Veja Ap. B14.
====

[[v42-16-7]]

^<<v42-16-7,7>>^ A seguir, perguntou a outro: ‘Agora você, quanto deve?’ Ele respondeu: ‘Cem grandes medidas^&#42;1^ de trigo.’ O administrador lhe disse: ‘Pegue de volta o seu acordo escrito e escreva 80.’

[NOTE]
====
. Ou: “Cem coros”. Um coro equivalia a 220 l. Veja Ap. B14.
====

[[v42-16-8]]

^<<v42-16-8,8>>^ E o senhor elogiou o administrador, embora este fosse injusto, porque agiu com sabedoria prática.^&#42;1^ Pois os filhos deste sistema de coisas^&#42;2^ são mais sábios em sentido prático, ao lidar com a sua própria geração, do que os filhos da luz.

[NOTE]
====
. Ou: “com astúcia; com prudência”.
. Ou: “desta época”. Veja o Glossário.
====

[[v42-16-9]]

^<<v42-16-9,9>>^ “Eu lhes digo também: Façam amigos por meio das riquezas injustas, para que, quando essas faltarem, eles os recebam nas moradas eternas.

[[v42-16-10]]

^<<v42-16-10,10>>^ Quem é fiel no mínimo é também fiel no muito, e quem é injusto no mínimo é também injusto no muito.

[[v42-16-11]]

^<<v42-16-11,11>>^ Portanto, se vocês não se mostrarem fiéis em usar as riquezas injustas, quem lhes confiará o que é verdadeiro?

[[v42-16-12]]

^<<v42-16-12,12>>^ E, se vocês não se mostrarem fiéis em usar o que é de outro, quem lhes dará o que é para vocês?

[[v42-16-13]]

^<<v42-16-13,13>>^ Nenhum servo pode ser escravo de dois senhores, pois ou odiará um e amará o outro, ou se apegará a um e desprezará o outro. Vocês não podem ser escravos de Deus e das Riquezas.”

[[v42-16-14]]

^<<v42-16-14,14>>^ Os fariseus, que amavam o dinheiro, estavam escutando tudo isso, e começaram a zombar dele.

[[v42-16-15]]

^<<v42-16-15,15>>^ Assim, ele lhes disse: “Vocês são os que se declaram justos diante dos homens, mas Deus conhece o coração de vocês. Pois aquilo que tem muito valor para os homens é repugnante à vista de Deus.

[[v42-16-16]]

^<<v42-16-16,16>>^ “A Lei e os Profetas foram declarados até João. Desde então, o Reino de Deus está sendo declarado como boas novas, e todo tipo de pessoas avança vigorosamente em direção a ele.

[[v42-16-17]]

^<<v42-16-17,17>>^ Realmente, é mais fácil passarem céu e terra do que ficar sem se cumprir um só traço de uma letra da Lei.

[[v42-16-18]]

^<<v42-16-18,18>>^ “Todo aquele que se divorcia da sua esposa e se casa com outra comete adultério, e quem se casa com uma mulher divorciada do marido comete adultério.

[[v42-16-19]]

^<<v42-16-19,19>>^ “Havia um homem rico que se vestia de púrpura e de linho, e levava uma vida de prazeres e luxo.

[[v42-16-20]]

^<<v42-16-20,20>>^ Mas um mendigo, chamado Lázaro, costumava ser colocado junto ao portão dele, e estava coberto de feridas;

[[v42-16-21]]

^<<v42-16-21,21>>^ ele desejava matar a fome com as coisas que caíam da mesa do rico. Até os cães vinham lamber as suas feridas.

[[v42-16-22]]

^<<v42-16-22,22>>^ Com o tempo, o mendigo morreu e foi carregado pelos anjos para junto de Abraão.^&#42;1^
“O rico também morreu e foi enterrado.

[NOTE]
====
. Lit.: “para o seio de Abraão”.
====

[[v42-16-23]]

^<<v42-16-23,23>>^ Na Sepultura^&#42;1^ ele ergueu os olhos, em tormentos, e viu Abraão de longe, com Lázaro ao seu lado.^&#42;2^

[NOTE]
====
. Ou: “no Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
. Lit.: “no seio dele”.
====

[[v42-16-24]]

^<<v42-16-24,24>>^ Por isso ele o chamou, dizendo: ‘Pai Abraão, tenha misericórdia de mim e envie Lázaro para mergulhar a ponta do dedo na água e refrescar a minha língua, porque estou sofrendo neste fogo intenso.’

[[v42-16-25]]

^<<v42-16-25,25>>^ Mas Abraão disse: ‘Filho, lembre-se de que você teve a sua medida de coisas boas durante a vida, mas Lázaro, por sua vez, recebeu coisas ruins. Agora, porém, ele está tendo consolo aqui, mas você está sofrendo.

[[v42-16-26]]

^<<v42-16-26,26>>^ E, além de tudo isso, estabeleceu-se um grande abismo entre nós e vocês, de modo que os que querem passar daqui para o lado de vocês não podem, nem podem pessoas passar daí para o nosso lado.’

[[v42-16-27]]

^<<v42-16-27,27>>^ O rico disse então: ‘Nesse caso, eu lhe peço, pai, que o envie à casa do meu pai,

[[v42-16-28]]

^<<v42-16-28,28>>^ pois eu tenho cinco irmãos; deixe que ele os avise, para que eles não venham também para este lugar de tormento.’

[[v42-16-29]]

^<<v42-16-29,29>>^ Mas Abraão disse: ‘Eles têm Moisés e os Profetas; que escutem a esses.’

[[v42-16-30]]

^<<v42-16-30,30>>^ Ele respondeu então: ‘Não, pai Abraão! Se alguém dentre os mortos for a eles, eles se arrependerão.’

[[v42-16-31]]

^<<v42-16-31,31>>^ Mas Abraão lhe disse: ‘Se eles não escutam Moisés nem os Profetas, não serão persuadidos nem mesmo se alguém se levantar dentre os mortos.’”

'''

xref:042-lucas/042-lucas-015.adoc#v42-15-0[&#60; Capítulo Anterior] | <<v42-16-0,Topo>> | xref:042-lucas/042-lucas-017.adoc#v42-17-0[Próximo Capítulo &#62;]