include::./index.adoc[]

[[v42-23-0]]
=== Segundo Lucas, 23
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-23-1]]

^<<v42-23-1,1>>^ Assim, toda a multidão se levantou, e o levaram a Pilatos.

[[v42-23-2]]

^<<v42-23-2,2>>^ Então começaram a acusá-lo, dizendo: “Encontramos este homem subvertendo a nossa nação, proibindo o pagamento de impostos a César e dizendo que ele mesmo é Cristo, um rei.”

[[v42-23-3]]

^<<v42-23-3,3>>^ Pilatos lhe perguntou então: “Você é o Rei dos judeus?” Em resposta ele disse: “O senhor mesmo está dizendo isso.”

[[v42-23-4]]

^<<v42-23-4,4>>^ Pilatos disse então aos principais sacerdotes e à multidão: “Não acho motivo para condenar este homem.”

[[v42-23-5]]

^<<v42-23-5,5>>^ Mas eles insistiram, dizendo: “Ele atiça o povo ensinando em toda a Judeia, começando da Galileia até aqui.”

[[v42-23-6]]

^<<v42-23-6,6>>^ Ao ouvir isso, Pilatos perguntou se o homem era galileu.

[[v42-23-7]]

^<<v42-23-7,7>>^ Ao saber que ele estava sob a jurisdição de Herodes, enviou-o a Herodes, que também estava em Jerusalém naqueles dias.

[[v42-23-8]]

^<<v42-23-8,8>>^ Quando Herodes viu Jesus, alegrou-se muito. Fazia bastante tempo que queria ver Jesus, porque tinha ouvido falar muito dele, e esperava ver algum sinal realizado por ele.

[[v42-23-9]]

^<<v42-23-9,9>>^ Começou então a lhe fazer muitas perguntas, mas ele não lhe deu nenhuma resposta.

[[v42-23-10]]

^<<v42-23-10,10>>^ No entanto, os principais sacerdotes e os escribas se levantavam e o acusavam vigorosamente.

[[v42-23-11]]

^<<v42-23-11,11>>^ Então Herodes, junto com seus soldados, o tratou com desprezo e zombou dele, vestindo-o com uma roupa esplêndida, e depois o mandou de volta a Pilatos.

[[v42-23-12]]

^<<v42-23-12,12>>^ Naquele mesmo dia, Herodes e Pilatos, que antes eram inimigos, tornaram-se amigos.

[[v42-23-13]]

^<<v42-23-13,13>>^ Pilatos convocou então os principais sacerdotes, os líderes e o povo,

[[v42-23-14]]

^<<v42-23-14,14>>^ e lhes disse: “Vocês me trouxeram este homem como se fosse alguém que incita o povo à revolta. Pois bem, eu o interroguei na frente de vocês, mas não achei neste homem base para as acusações que vocês levantam contra ele.

[[v42-23-15]]

^<<v42-23-15,15>>^ De fato, nem Herodes achou, pois o mandou de volta para nós. Como podem ver, ele não fez nada que mereça a morte.

[[v42-23-16]]

^<<v42-23-16,16>>^ Portanto, eu o castigarei e o soltarei.”

[[v42-23-17]]

^<<v42-23-17,17>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v42-23-18]]

^<<v42-23-18,18>>^ Mas toda a multidão gritou: “Mate este homem^&#42;1^ e solte Barrabás!”

[NOTE]
====
. Lit.: “Leve embora a este”.
====

[[v42-23-19]]

^<<v42-23-19,19>>^ (Esse homem tinha sido lançado na prisão por causa de uma sedição ocorrida na cidade e por assassinato.)

[[v42-23-20]]

^<<v42-23-20,20>>^ Pilatos falou com eles novamente, porque queria soltar Jesus.

[[v42-23-21]]

^<<v42-23-21,21>>^ Começaram então a gritar: “Para a estaca com ele! Para a estaca com ele!”^&#42;1^

[NOTE]
====
. Ou: “Executem-no na estaca! Executem-no na estaca!”
====

[[v42-23-22]]

^<<v42-23-22,22>>^ Ele lhes disse pela terceira vez: “Por quê? O que este homem fez de mau? Não achei nele nada que mereça a morte. Portanto, eu o castigarei e o soltarei.”

[[v42-23-23]]

^<<v42-23-23,23>>^ Em vista disso começaram a insistir, exigindo aos gritos que ele fosse executado,^&#42;1^ e a voz deles prevaleceu.

[NOTE]
====
. Ou: “executado na estaca”.
====

[[v42-23-24]]

^<<v42-23-24,24>>^ De modo que Pilatos decidiu atender ao pedido deles.

[[v42-23-25]]

^<<v42-23-25,25>>^ Ele soltou o homem a quem pediam, que tinha sido lançado na prisão por sedição e assassinato, mas entregou Jesus à vontade deles.

[[v42-23-26]]

^<<v42-23-26,26>>^ Enquanto o levavam embora, agarraram um certo Simão de Cirene, que vinha do campo, e puseram a estaca^&#42;1^ sobre ele para que a carregasse atrás de Jesus.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v42-23-27]]

^<<v42-23-27,27>>^ Um grande número de pessoas o seguiam, incluindo mulheres que batiam no peito de pesar e o lamentavam.

[[v42-23-28]]

^<<v42-23-28,28>>^ Jesus se virou para as mulheres e disse: “Filhas de Jerusalém, parem de chorar por mim. Em vez disso, chorem por vocês mesmas e pelos seus filhos;

[[v42-23-29]]

^<<v42-23-29,29>>^ pois saibam que virão dias em que as pessoas dirão: ‘Felizes as mulheres estéreis, os ventres que não deram à luz e os peitos que não amamentaram!’

[[v42-23-30]]

^<<v42-23-30,30>>^ Então começarão a dizer às montanhas: ‘Caiam sobre nós!’ e às colinas: ‘Cubram-nos!’

[[v42-23-31]]

^<<v42-23-31,31>>^ Se eles fazem isso quando a árvore está verde, o que ocorrerá quando estiver seca?”

[[v42-23-32]]

^<<v42-23-32,32>>^ Dois outros homens, criminosos, também estavam sendo levados para ser executados com ele.

[[v42-23-33]]

^<<v42-23-33,33>>^ E, quando chegaram ao lugar chamado Caveira, pregaram-no na estaca ao lado dos criminosos, um à sua direita e outro à sua esquerda.

[[v42-23-34]]

^<<v42-23-34,34>>^ Mas Jesus dizia: “Pai, perdoa-lhes, pois não sabem o que estão fazendo.” Além disso, lançaram sortes para repartir as roupas dele.

[[v42-23-35]]

^<<v42-23-35,35>>^ E o povo ficou parado, olhando. Mas os líderes zombavam e diziam: “A outros ele salvou; que ele salve a si mesmo, se é o Cristo de Deus, o Escolhido.”

[[v42-23-36]]

^<<v42-23-36,36>>^ Até mesmo os soldados zombaram dele, chegando perto e oferecendo-lhe vinho acre,

[[v42-23-37]]

^<<v42-23-37,37>>^ e dizendo: “Se você é o Rei dos judeus, salve a si mesmo.”

[[v42-23-38]]

^<<v42-23-38,38>>^ Havia também uma inscrição acima dele: “Este é o Rei dos judeus.”

[[v42-23-39]]

^<<v42-23-39,39>>^ Então um dos criminosos que estavam pendurados começou a insultá-lo, dizendo: “Você não é o Cristo? Salve a si mesmo e também a nós!”

[[v42-23-40]]

^<<v42-23-40,40>>^ Em resposta, o outro o censurou, dizendo: “Você não tem nenhum temor de Deus, agora que recebeu o mesmo julgamento?

[[v42-23-41]]

^<<v42-23-41,41>>^ E no nosso caso isso é justo, pois estamos recebendo o que merecemos pelas coisas que fizemos. Mas este homem não fez nada errado.”

[[v42-23-42]]

^<<v42-23-42,42>>^ Então ele disse: “Jesus, lembre-se de mim quando entrar no seu Reino.”

[[v42-23-43]]

^<<v42-23-43,43>>^ E ele lhe disse: “Em verdade, eu lhe digo hoje: Você estará comigo no Paraíso.”

[[v42-23-44]]

^<<v42-23-44,44>>^ Pois bem, já era por volta da sexta hora;^&#42;1^ contudo, caiu uma escuridão sobre toda aquela terra, até a nona hora,^&#42;2^

[NOTE]
====
. Isto é, por volta do meio-dia.
. Isto é, por volta das 3 h da tarde.
====

[[v42-23-45]]

^<<v42-23-45,45>>^ porque a luz do sol falhou. Então a cortina do santuário se rasgou ao meio.

[[v42-23-46]]

^<<v42-23-46,46>>^ E Jesus clamou em alta voz e disse: “Pai, às tuas mãos confio o meu espírito.” Depois de dizer isso, ele morreu.^&#42;1^

[NOTE]
====
. Ou: “expirou; deu seu último suspiro”.
====

[[v42-23-47]]

^<<v42-23-47,47>>^ Ao ver o que estava acontecendo, o oficial do exército começou a glorificar a Deus, dizendo: “Realmente, este homem era justo.”

[[v42-23-48]]

^<<v42-23-48,48>>^ E toda a multidão que tinha se reunido ali para esse espetáculo viu o que estava acontecendo; então voltaram para casa, batendo no peito.

[[v42-23-49]]

^<<v42-23-49,49>>^ Todos os conhecidos dele estavam parados à distância. Também mulheres que o tinham acompanhado desde a Galileia estavam lá e viram essas coisas.

[[v42-23-50]]

^<<v42-23-50,50>>^ Havia um homem chamado José, membro do Conselho, que era um homem bom e justo.

[[v42-23-51]]

^<<v42-23-51,51>>^ (Esse homem não tinha votado em apoio da trama e da ação deles.) Ele era de Arimateia, uma cidade da Judeia, e aguardava o Reino de Deus.

[[v42-23-52]]

^<<v42-23-52,52>>^ Esse homem compareceu perante Pilatos e pediu o corpo de Jesus.

[[v42-23-53]]

^<<v42-23-53,53>>^ Então o tirou de lá, o enrolou em linho fino e o colocou num túmulo^&#42;1^ escavado na rocha, onde ninguém ainda tinha sido sepultado.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-23-54]]

^<<v42-23-54,54>>^ Era o dia da Preparação, e o sábado estava prestes a começar.

[[v42-23-55]]

^<<v42-23-55,55>>^ Mas as mulheres que tinham vindo com ele desde a Galileia foram também até lá e viram o túmulo^&#42;1^ e como o corpo dele havia sido colocado ali;

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v42-23-56]]

^<<v42-23-56,56>>^ e voltaram para preparar aromas e óleos perfumados. Mas, naturalmente, descansaram no sábado, segundo o mandamento.

'''

xref:042-lucas/042-lucas-022.adoc#v42-22-0[&#60; Capítulo Anterior] | <<v42-23-0,Topo>> | xref:042-lucas/042-lucas-024.adoc#v42-24-0[Próximo Capítulo &#62;]