include::./index.adoc[]

[[v42-1-0]]
=== Segundo Lucas, 1
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v42-1-1]]

^<<v42-1-1,1>>^ Muitos se empenharam em compilar um relato dos fatos que recebem pleno crédito^&#42;1^ entre nós,

[NOTE]
====
. Ou: “plena credibilidade”.
====

[[v42-1-2]]

^<<v42-1-2,2>>^ assim como esses fatos nos foram transmitidos por aqueles que desde o princípio foram testemunhas oculares e proclamadores^&#42;1^ da mensagem.

[NOTE]
====
. Lit.: “assistentes”.
====

[[v42-1-3]]

^<<v42-1-3,3>>^ Assim, eu também, depois de pesquisar todas as coisas com exatidão desde o início, resolvi escrevê-las para o senhor em ordem lógica, Excelentíssimo Teófilo,

[[v42-1-4]]

^<<v42-1-4,4>>^ para que tenha plena certeza das coisas que lhe foram ensinadas oralmente.

[[v42-1-5]]

^<<v42-1-5,5>>^ Nos dias de Herodes,^&#42;1^ rei da Judeia, havia um sacerdote chamado Zacarias, da turma de Abias. Sua esposa era uma das filhas de Arão, e o nome dela era Elisabete.^&#42;2^

[NOTE]
====
. Veja o Glossário.
. Ou: “Isabel”.
====

[[v42-1-6]]

^<<v42-1-6,6>>^ Ambos eram justos diante de Deus e andavam de modo irrepreensível de acordo com todos os mandamentos e exigências legais de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-7]]

^<<v42-1-7,7>>^ Mas não tinham filhos, porque Elisabete era estéril, e ambos já eram de idade bem avançada.

[[v42-1-8]]

^<<v42-1-8,8>>^ Zacarias estava servindo perante Deus como sacerdote na designação da sua turma.

[[v42-1-9]]

^<<v42-1-9,9>>^ Segundo o costume estabelecido^&#42;1^ do sacerdócio, chegou a sua vez de oferecer incenso ao entrar no santuário de Jeová.^&#42;2^

[NOTE]
====
. Ou: “a prática estabelecida”.
. Veja Ap. A5.
====

[[v42-1-10]]

^<<v42-1-10,10>>^ E toda a multidão do povo estava orando do lado de fora, na hora de oferecer incenso.

[[v42-1-11]]

^<<v42-1-11,11>>^ Então, apareceu-lhe o anjo de Jeová,^&#42;1^ em pé à direita do altar do incenso.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-12]]

^<<v42-1-12,12>>^ Zacarias, porém, ficou aflito ao vê-lo e foi tomado de medo.

[[v42-1-13]]

^<<v42-1-13,13>>^ No entanto, o anjo lhe disse: “Não tenha medo, Zacarias, porque as suas súplicas foram ouvidas, e sua esposa, Elisabete, lhe dará um filho, e você deve pôr nele o nome de João.

[[v42-1-14]]

^<<v42-1-14,14>>^ Você terá alegria e grande felicidade, e muitos se alegrarão com o nascimento dele,

[[v42-1-15]]

^<<v42-1-15,15>>^ pois ele será grande aos olhos de Jeová.^&#42;1^ Mas ele não deve beber vinho nem outra bebida alcoólica, e ficará cheio de espírito santo mesmo antes do seu nascimento,^&#42;2^

[NOTE]
====
. Veja Ap. A5.
. Ou: “desde o ventre de sua mãe”.
====

[[v42-1-16]]

^<<v42-1-16,16>>^ e fará muitos dos filhos de Israel voltar para Jeová,^&#42;1^ o Deus deles.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-17]]

^<<v42-1-17,17>>^ Também, irá na frente Dele com o espírito e o poder de Elias, para fazer o coração dos pais se tornar como o de filhos,^&#42;1^ e fazer os desobedientes se voltar para a sabedoria prática dos justos, a fim de aprontar para Jeová^&#42;2^ um povo preparado.”

[NOTE]
====
. Ou: “se voltar para os filhos”.
. Veja Ap. A5.
====

[[v42-1-18]]

^<<v42-1-18,18>>^ Zacarias disse ao anjo: “Como posso ter certeza disso? Pois sou idoso e minha esposa já é de idade bem avançada.”

[[v42-1-19]]

^<<v42-1-19,19>>^ Em resposta, o anjo lhe disse: “Eu sou Gabriel e estou diante de Deus; fui enviado para falar com você e lhe declarar estas boas novas.

[[v42-1-20]]

^<<v42-1-20,20>>^ Mas agora você ficará mudo e não poderá falar até o dia em que essas coisas ocorrerem, porque não acreditou nas minhas palavras, que se cumprirão no seu tempo determinado.”

[[v42-1-21]]

^<<v42-1-21,21>>^ Enquanto isso, o povo continuava à espera de Zacarias, e ficaram surpresos porque ele estava demorando muito no santuário.

[[v42-1-22]]

^<<v42-1-22,22>>^ Quando saiu, ele não conseguia falar com eles, e perceberam que ele havia acabado de ver algo sobrenatural^&#42;1^ no santuário. Ele lhes fazia sinais, mas permanecia mudo.

[NOTE]
====
. Ou: “de ter uma visão”.
====

[[v42-1-23]]

^<<v42-1-23,23>>^ Quando se completaram os dias do seu serviço sagrado,^&#42;1^ ele foi para casa.

[NOTE]
====
. Ou: “serviço público”.
====

[[v42-1-24]]

^<<v42-1-24,24>>^ Alguns dias depois, Elisabete, sua esposa, ficou grávida, e se manteve isolada por cinco meses; ela dizia:

[[v42-1-25]]

^<<v42-1-25,25>>^ “É assim que Jeová^&#42;1^ agiu comigo nestes dias. Ele voltou sua atenção para mim, para tirar a minha desonra entre as pessoas.”

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-26]]

^<<v42-1-26,26>>^ No sexto mês dela, o anjo Gabriel foi enviado por Deus a uma cidade da Galileia, chamada Nazaré,

[[v42-1-27]]

^<<v42-1-27,27>>^ a uma virgem prometida em casamento a^&#42;1^ um homem chamado José, da casa de Davi; e o nome da virgem era Maria.

[NOTE]
====
. Ou: “virgem noiva de”.
====

[[v42-1-28]]

^<<v42-1-28,28>>^ Entrando onde ela estava, o anjo lhe disse: “Olá, altamente favorecida, Jeová^&#42;1^ está com você!”

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-29]]

^<<v42-1-29,29>>^ Mas ela ficou profundamente perturbada com as palavras dele e tentava entender o que poderia significar essa saudação.

[[v42-1-30]]

^<<v42-1-30,30>>^ De modo que o anjo lhe disse: “Não tenha medo, Maria, pois você achou favor diante de Deus.

[[v42-1-31]]

^<<v42-1-31,31>>^ E agora você ficará grávida^&#42;1^ e dará à luz um filho, e deve lhe dar o nome de Jesus.

[NOTE]
====
. Ou: “conceberá no seu ventre”.
====

[[v42-1-32]]

^<<v42-1-32,32>>^ Ele será grande e será chamado Filho do Altíssimo, e Jeová^&#42;1^ Deus lhe dará o trono de Davi, seu pai,

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-33]]

^<<v42-1-33,33>>^ e ele será Rei sobre a casa de Jacó para sempre, e não haverá fim do seu Reino.”

[[v42-1-34]]

^<<v42-1-34,34>>^ Maria, porém, disse ao anjo: “Como isso vai acontecer, visto que não tenho relações com nenhum homem?”

[[v42-1-35]]

^<<v42-1-35,35>>^ O anjo lhe disse em resposta: “Espírito santo virá sobre você e poder do Altíssimo a cobrirá com a sua sombra. E, por essa razão, aquele que nascer será chamado santo, Filho de Deus.

[[v42-1-36]]

^<<v42-1-36,36>>^ E saiba que Elisabete, sua parenta, também vai ter um filho, na sua velhice, e este é o sexto mês para ela, a chamada estéril;

[[v42-1-37]]

^<<v42-1-37,37>>^ pois não há nenhuma declaração de Deus que ele não possa cumprir.”^&#42;1^

[NOTE]
====
. Ou: “pois nada é impossível para Deus”.
====

[[v42-1-38]]

^<<v42-1-38,38>>^ Maria disse então: “Eu sou a escrava de Jeová!^&#42;1^ Aconteça comigo segundo a sua declaração.” Com isso, o anjo saiu da presença dela.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-39]]

^<<v42-1-39,39>>^ Naqueles dias, Maria partiu apressadamente para a região montanhosa, a uma cidade de Judá,

[[v42-1-40]]

^<<v42-1-40,40>>^ e entrou na casa de Zacarias e cumprimentou Elisabete.

[[v42-1-41]]

^<<v42-1-41,41>>^ Pois bem, quando Elisabete ouviu o cumprimento de Maria, o bebê no seu ventre pulou, e Elisabete ficou cheia de espírito santo

[[v42-1-42]]

^<<v42-1-42,42>>^ e exclamou bem alto: “Abençoada é você entre as mulheres, e abençoado é o fruto do seu ventre!

[[v42-1-43]]

^<<v42-1-43,43>>^ Então, como é que eu tenho este privilégio, de que a mãe do meu Senhor venha ao meu encontro?

[[v42-1-44]]

^<<v42-1-44,44>>^ Pois, assim que o som do seu cumprimento chegou aos meus ouvidos, o bebê no meu ventre pulou de alegria.

[[v42-1-45]]

^<<v42-1-45,45>>^ E feliz é aquela que acreditou, porque as coisas que lhe foram faladas por Jeová^&#42;1^ se cumprirão plenamente.”

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-46]]

^<<v42-1-46,46>>^ Maria disse: “Minha alma^&#42;1^ magnifica a Jeová^&#42;2^

[NOTE]
====
. Ou: “Todo o meu ser”. Veja o Glossário, “Alma”.
. Veja Ap. A5.
====

[[v42-1-47]]

^<<v42-1-47,47>>^ e meu espírito não pode deixar de estar cheio de alegria por Deus, meu Salvador,

[[v42-1-48]]

^<<v42-1-48,48>>^ porque ele olhou para a condição humilde da sua escrava. Sim, de agora em diante todas as gerações me proclamarão feliz,

[[v42-1-49]]

^<<v42-1-49,49>>^ porque o Poderoso fez grandes ações por mim, e santo é o seu nome,

[[v42-1-50]]

^<<v42-1-50,50>>^ e de geração em geração sua misericórdia está sobre os que o temem.

[[v42-1-51]]

^<<v42-1-51,51>>^ Ele agiu poderosamente com o seu braço; dispersou os que têm planos arrogantes no coração.

[[v42-1-52]]

^<<v42-1-52,52>>^ Derrubou de tronos homens poderosos e enalteceu humildes;

[[v42-1-53]]

^<<v42-1-53,53>>^ saciou plenamente de coisas boas os famintos e mandou embora, de mãos vazias, os que tinham riqueza.

[[v42-1-54]]

^<<v42-1-54,54>>^ Ele veio em socorro de Israel, seu servo, lembrando-se da sua misericórdia eterna

[[v42-1-55]]

^<<v42-1-55,55>>^ a favor de Abraão e da sua descendência,^&#42;1^ assim como tinha prometido aos nossos antepassados.”

[NOTE]
====
. Lit.: “semente”.
====

[[v42-1-56]]

^<<v42-1-56,56>>^ Maria ficou com ela cerca de três meses e depois voltou para a sua própria casa.

[[v42-1-57]]

^<<v42-1-57,57>>^ Chegou então o tempo para Elisabete dar à luz, e ela teve um filho.

[[v42-1-58]]

^<<v42-1-58,58>>^ E os vizinhos e os parentes dela ouviram que Jeová^&#42;1^ tinha lhe mostrado muita misericórdia,^&#42;2^ e eles se alegraram com ela.

[NOTE]
====
. Veja Ap. A5.
. Ou: “Jeová tinha magnificado a sua misericórdia”.
====

[[v42-1-59]]

^<<v42-1-59,59>>^ No oitavo dia, foram circuncidar o menino, e iam dar a ele o nome do pai, Zacarias.

[[v42-1-60]]

^<<v42-1-60,60>>^ Mas a mãe dele disse: “Não! Ele se chamará João.”

[[v42-1-61]]

^<<v42-1-61,61>>^ Em vista disso, disseram-lhe: “Nenhum dos seus parentes tem esse nome.”

[[v42-1-62]]

^<<v42-1-62,62>>^ Perguntaram então ao pai dele, por sinais, como queria que o menino se chamasse.

[[v42-1-63]]

^<<v42-1-63,63>>^ Ele pediu uma tabuinha e escreveu: “O nome dele é João.” Em vista disso, todos ficaram admirados.

[[v42-1-64]]

^<<v42-1-64,64>>^ No mesmo instante, sua boca foi aberta e sua língua foi solta, e ele começou a falar, louvando a Deus.

[[v42-1-65]]

^<<v42-1-65,65>>^ E todos os que moravam na vizinhança deles ficaram com medo, e começou-se a falar sobre essas coisas em toda a região montanhosa da Judeia.

[[v42-1-66]]

^<<v42-1-66,66>>^ Todos os que ouviram guardaram isso no coração, dizendo: “O que será que esse menino vai ser?” Pois, de fato, a mão de Jeová^&#42;1^ estava com ele.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-67]]

^<<v42-1-67,67>>^ Então Zacarias, seu pai, ficou cheio de espírito santo e profetizou, dizendo:

[[v42-1-68]]

^<<v42-1-68,68>>^ “Louvado seja Jeová,^&#42;1^ o Deus de Israel, porque voltou a sua atenção para o seu povo e lhe trouxe livramento.

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-69]]

^<<v42-1-69,69>>^ E ele fez surgir para nós um poderoso salvador^&#42;1^ na casa de Davi, seu servo,

[NOTE]
====
. Lit.: “um chifre de salvação”. Veja o Glossário, “Chifre”.
====

[[v42-1-70]]

^<<v42-1-70,70>>^ assim como tinha falado pela boca dos seus santos profetas da antiguidade,

[[v42-1-71]]

^<<v42-1-71,71>>^ para nos salvar dos nossos inimigos e das mãos de todos os que nos odeiam,

[[v42-1-72]]

^<<v42-1-72,72>>^ para mostrar misericórdia com relação aos nossos antepassados e para lembrar o Seu santo pacto,

[[v42-1-73]]

^<<v42-1-73,73>>^ o juramento que Ele fez a Abraão, nosso antepassado,

[[v42-1-74]]

^<<v42-1-74,74>>^ de nos conceder, depois de termos sido resgatados das mãos dos inimigos, o privilégio de lhe prestar destemidamente serviço sagrado

[[v42-1-75]]

^<<v42-1-75,75>>^ com lealdade e justiça, diante dele, todos os nossos dias.

[[v42-1-76]]

^<<v42-1-76,76>>^ Mas, quanto a você, menino, será chamado profeta do Altíssimo, pois irá na frente de Jeová^&#42;1^ para preparar os caminhos dele,

[NOTE]
====
. Veja Ap. A5.
====

[[v42-1-77]]

^<<v42-1-77,77>>^ para dar ao Seu povo conhecimento da salvação por meio do perdão dos pecados deles,

[[v42-1-78]]

^<<v42-1-78,78>>^ por causa da terna compaixão do nosso Deus. Por causa dessa compaixão, um amanhecer nos visitará do alto,

[[v42-1-79]]

^<<v42-1-79,79>>^ para dar luz aos sentados na escuridão e na sombra da morte e para guiar nossos pés no caminho da paz.”

[[v42-1-80]]

^<<v42-1-80,80>>^ E o menino cresceu e se tornou forte em espírito. E ele continuou no deserto^&#42;1^ até o dia em que se mostrou abertamente a Israel.

[NOTE]
====
. Veja o Glossário.
====

'''

xref:041-marcos/041-marcos-016.adoc#v41-16-0[&#60; Capítulo Anterior] | <<v42-1-0,Topo>> | xref:042-lucas/042-lucas-002.adoc#v42-2-0[Próximo Capítulo &#62;]