include::./index.adoc[]

[[v40-16-0]]
=== Segundo Mateus, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-16-1]]

^<<v40-16-1,1>>^ Ali os fariseus e os saduceus se aproximaram dele e, para testá-lo, pediram a ele que lhes mostrasse um sinal do céu.

[[v40-16-2]]

^<<v40-16-2,2>>^ Em resposta, ele lhes disse: “Ao cair a noite, vocês dizem: ‘Fará tempo bom, pois o céu está vermelho’,

[[v40-16-3]]

^<<v40-16-3,3>>^ e, de manhã: ‘Hoje fará tempo frio e chuvoso, pois o céu está vermelho, mas sombrio.’ Vocês sabem interpretar a aparência do céu, mas não conseguem interpretar os sinais dos tempos.

[[v40-16-4]]

^<<v40-16-4,4>>^ Uma geração má e adúltera^&#42;1^ persiste em buscar um sinal, mas nenhum sinal lhe será dado, exceto o sinal de Jonas.” Com isso se afastou, deixando-os para trás.

[NOTE]
====
. Ou: “infiel”.
====

[[v40-16-5]]

^<<v40-16-5,5>>^ Os discípulos passaram então para a outra margem, mas se esqueceram de levar pães.

[[v40-16-6]]

^<<v40-16-6,6>>^ Jesus lhes disse: “Mantenham os olhos abertos e tomem cuidado com o fermento dos fariseus e dos saduceus.”

[[v40-16-7]]

^<<v40-16-7,7>>^ Assim, começaram a raciocinar entre si, dizendo: “Não trouxemos pães.”

[[v40-16-8]]

^<<v40-16-8,8>>^ Sabendo disso, Jesus disse: “Homens de pouca fé, por que estão conversando sobre o fato de não terem pães?

[[v40-16-9]]

^<<v40-16-9,9>>^ Ainda não compreendem a questão, e não se lembram dos cinco pães, no caso dos 5.000, e de quantos cestos vocês recolheram?

[[v40-16-10]]

^<<v40-16-10,10>>^ Ou dos sete pães, no caso dos 4.000, e de quantos cestos grandes^&#42;1^ recolheram?

[NOTE]
====
. Ou: “cestos de provisões”.
====

[[v40-16-11]]

^<<v40-16-11,11>>^ Como é que vocês não compreendem que não lhes falei de pão? Eu lhes disse que tomassem cuidado com o fermento dos fariseus e dos saduceus.”

[[v40-16-12]]

^<<v40-16-12,12>>^ Compreenderam então que ele falava para tomarem cuidado, não com o fermento de pão, mas com os ensinamentos dos fariseus e dos saduceus.

[[v40-16-13]]

^<<v40-16-13,13>>^ Quando chegou à região de Cesareia de Filipe, Jesus perguntou aos seus discípulos: “Quem os homens dizem que o Filho do Homem é?”

[[v40-16-14]]

^<<v40-16-14,14>>^ Responderam: “Alguns dizem João Batista; outros, Elias; e ainda outros, Jeremias ou um dos profetas.”

[[v40-16-15]]

^<<v40-16-15,15>>^ Ele lhes perguntou: “E vocês, quem dizem que eu sou?”

[[v40-16-16]]

^<<v40-16-16,16>>^ Simão Pedro respondeu: “O senhor é o Cristo, o Filho do Deus vivente.”

[[v40-16-17]]

^<<v40-16-17,17>>^ Jesus lhe disse então: “Feliz é você, Simão, filho de Jonas, porque isso não lhe foi revelado por homens,^&#42;1^ mas pelo meu Pai, que está nos céus.

[NOTE]
====
. Lit.: “carne e sangue”.
====

[[v40-16-18]]

^<<v40-16-18,18>>^ Também, eu lhe digo: Você é Pedro, e sobre esta rocha construirei a minha congregação, e os portões da Sepultura^&#42;1^ não a vencerão.

[NOTE]
====
. Ou: “do Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v40-16-19]]

^<<v40-16-19,19>>^ Eu lhe darei as chaves do Reino dos céus, e tudo o que você amarrar na terra, já terá sido amarrado nos céus, e tudo o que você soltar na terra, já terá sido solto nos céus.”

[[v40-16-20]]

^<<v40-16-20,20>>^ Então, ele ordenou com firmeza aos discípulos que não dissessem a ninguém que ele era o Cristo.

[[v40-16-21]]

^<<v40-16-21,21>>^ Daquele tempo em diante, Jesus começou a explicar aos seus discípulos que ele tinha de ir a Jerusalém e sofrer muitas coisas da parte dos anciãos, dos principais sacerdotes e dos escribas, e que tinha de ser morto e no terceiro dia ser levantado.

[[v40-16-22]]

^<<v40-16-22,22>>^ Em vista disso, Pedro o levou à parte e começou a censurá-lo, dizendo: “Tenha compaixão de si mesmo, Senhor! Isso de modo algum lhe acontecerá.”

[[v40-16-23]]

^<<v40-16-23,23>>^ Mas ele virou as costas para Pedro e lhe disse: “Para trás de mim, Satanás! Você é uma pedra de tropeço para mim, porque não tem os pensamentos de Deus, mas os de homens.”

[[v40-16-24]]

^<<v40-16-24,24>>^ Jesus disse então aos seus discípulos: “Se alguém quer ser meu seguidor, negue a si mesmo, apanhe sua estaca de tortura^&#42;1^ e siga-me sempre.

[NOTE]
====
. Veja o Glossário.
====

[[v40-16-25]]

^<<v40-16-25,25>>^ Pois quem quiser salvar a sua vida^&#42;1^ a perderá, mas quem perder a sua vida^&#42;2^ por minha causa a achará.

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v40-16-26]]

^<<v40-16-26,26>>^ Realmente, de que adianta o homem ganhar o mundo inteiro, se ele perder a sua vida?^&#42;1^ Ou o que o homem dará em troca da sua vida?^&#42;2^

[NOTE]
====
. Ou: “alma”.
. Ou: “alma”.
====

[[v40-16-27]]

^<<v40-16-27,27>>^ Porque o Filho do Homem há de vir na glória do seu Pai, com seus anjos, e então retribuirá a cada um segundo o seu comportamento.

[[v40-16-28]]

^<<v40-16-28,28>>^ Digo-lhes a verdade: Há alguns dos que estão aqui que de modo algum provarão a morte antes de verem o Filho do Homem vir no seu Reino.”

'''

xref:040-mateus/040-mateus-015.adoc#v40-15-0[&#60; Capítulo Anterior] | <<v40-16-0,Topo>> | xref:040-mateus/040-mateus-017.adoc#v40-17-0[Próximo Capítulo &#62;]