include::./index.adoc[]

[[v40-28-0]]
=== Segundo Mateus, 28
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-28-1]]

^<<v40-28-1,1>>^ Depois do sábado, quando amanhecia o primeiro dia da semana, Maria Madalena e a outra Maria foram ver a sepultura.

[[v40-28-2]]

^<<v40-28-2,2>>^ Um grande terremoto tinha ocorrido, pois o anjo de Jeová^&#42;1^ havia descido do céu, chegado ao túmulo e rolado a pedra, e ele estava sentado sobre ela.

[NOTE]
====
. Veja Ap. A5.
====

[[v40-28-3]]

^<<v40-28-3,3>>^ Sua aparência era como um relâmpago e sua roupa era branca como a neve.

[[v40-28-4]]

^<<v40-28-4,4>>^ Com medo dele, os vigias tremeram e ficaram como que mortos.

[[v40-28-5]]

^<<v40-28-5,5>>^ Mas o anjo disse às mulheres: “Não tenham medo, pois eu sei que vocês estão procurando Jesus, que foi morto na estaca.

[[v40-28-6]]

^<<v40-28-6,6>>^ Ele não está aqui, pois foi levantado, assim como ele tinha dito. Venham, vejam o lugar onde ele estava deitado.

[[v40-28-7]]

^<<v40-28-7,7>>^ Depois vão depressa e digam aos discípulos dele: ‘Ele foi levantado dentre os mortos e agora está indo adiante de vocês para a Galileia. Ali o verão.’ Isso é o que eu vim lhes dizer.”

[[v40-28-8]]

^<<v40-28-8,8>>^ Assim, deixando rapidamente o túmulo memorial, com temor e grande alegria, correram para contar isso aos discípulos dele.

[[v40-28-9]]

^<<v40-28-9,9>>^ Nisto, Jesus foi ao encontro delas e disse: “Bom dia!” Elas se aproximaram, abraçaram os pés dele e lhe prestaram homenagem.^&#42;1^

[NOTE]
====
. Ou: “se curvaram diante dele”.
====

[[v40-28-10]]

^<<v40-28-10,10>>^ Jesus lhes disse então: “Não tenham medo! Vão, contem isso a meus irmãos, para que eles vão para a Galileia, e ali me verão.”

[[v40-28-11]]

^<<v40-28-11,11>>^ Enquanto elas estavam a caminho, alguns guardas foram à cidade e comunicaram aos principais sacerdotes tudo o que tinha acontecido.

[[v40-28-12]]

^<<v40-28-12,12>>^ Depois de estes terem se reunido com os anciãos para decidir o que fazer, deram aos soldados uma boa quantidade de moedas de prata

[[v40-28-13]]

^<<v40-28-13,13>>^ e disseram: “Digam: ‘Os discípulos dele vieram de noite e o furtaram enquanto estávamos dormindo.’

[[v40-28-14]]

^<<v40-28-14,14>>^ E, se isso chegar aos ouvidos do governador, nós lhe daremos explicações,^&#42;1^ e vocês não precisarão se preocupar.”

[NOTE]
====
. Lit.: “persuadiremos”.
====

[[v40-28-15]]

^<<v40-28-15,15>>^ Assim, eles pegaram as moedas de prata e fizeram como lhes mandaram, e essa história se tem espalhado entre os judeus até o dia de hoje.

[[v40-28-16]]

^<<v40-28-16,16>>^ No entanto, os 11 discípulos foram para a Galileia, para o monte que Jesus lhes havia indicado.

[[v40-28-17]]

^<<v40-28-17,17>>^ Quando o viram, curvaram-se diante dele,^&#42;1^ mas alguns duvidaram.

[NOTE]
====
. Ou: “prestaram-lhe homenagem”.
====

[[v40-28-18]]

^<<v40-28-18,18>>^ Jesus se aproximou e lhes disse: “Foi-me dada toda a autoridade no céu e na terra.

[[v40-28-19]]

^<<v40-28-19,19>>^ Portanto, vão e façam discípulos de pessoas de todas as nações, batizando-as em nome do Pai, e do Filho, e do espírito santo,

[[v40-28-20]]

^<<v40-28-20,20>>^ ensinando-as a obedecer a todas as coisas que lhes ordenei. E saibam que eu estou com vocês todos os dias, até o final do sistema de coisas.”^&#42;1^

[NOTE]
====
. Ou: “final da época”. Veja o Glossário, “Sistema de coisas”.
====

'''

xref:040-mateus/040-mateus-027.adoc#v40-27-0[&#60; Capítulo Anterior] | <<v40-28-0,Topo>> | xref:041-marcos/041-marcos-001.adoc#v41-1-0[Próximo Capítulo &#62;]