include::./index.adoc[]

[[v40-13-0]]
=== Segundo Mateus, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-13-1]]

^<<v40-13-1,1>>^ Naquele dia, Jesus saiu da casa e se sentou à beira do mar.

[[v40-13-2]]

^<<v40-13-2,2>>^ E as multidões que se reuniram em volta dele eram tão grandes que ele entrou num barco e se sentou, e toda a multidão ficou na praia.

[[v40-13-3]]

^<<v40-13-3,3>>^ Falou-lhes então muitas coisas por meio de ilustrações. Ele disse: “Escutem: Um semeador saiu para semear.

[[v40-13-4]]

^<<v40-13-4,4>>^ Ao passo que semeava, algumas sementes caíram à beira da estrada, e vieram as aves e as comeram.

[[v40-13-5]]

^<<v40-13-5,5>>^ Outras caíram em solo rochoso, onde não havia muita terra, e brotaram imediatamente porque o solo não era profundo.

[[v40-13-6]]

^<<v40-13-6,6>>^ Mas, quando o sol se levantou, ficaram queimadas e murcharam, porque não tinham raiz.

[[v40-13-7]]

^<<v40-13-7,7>>^ Outras caíram entre os espinhos, e os espinhos cresceram e as sufocaram.

[[v40-13-8]]

^<<v40-13-8,8>>^ Ainda outras caíram em solo bom e começaram a dar fruto, esta 100 vezes mais, aquela 60 vezes mais, outra 30 vezes mais.

[[v40-13-9]]

^<<v40-13-9,9>>^ Quem tem ouvidos, escute.”

[[v40-13-10]]

^<<v40-13-10,10>>^ Assim, os seus discípulos vieram e lhe perguntaram: “Por que o senhor lhes fala usando ilustrações?”

[[v40-13-11]]

^<<v40-13-11,11>>^ Em resposta, ele disse: “A vocês é concedido entender os segredos sagrados do Reino dos céus, mas a eles não é concedido.

[[v40-13-12]]

^<<v40-13-12,12>>^ Pois àquele que tem, mais será dado, e se fará que ele tenha em abundância; mas, daquele que não tem, até mesmo o que tem será tirado.

[[v40-13-13]]

^<<v40-13-13,13>>^ É por isso que falo a eles usando ilustrações; porque olham, mas olham em vão, e ouvem, mas ouvem em vão, e não compreendem.

[[v40-13-14]]

^<<v40-13-14,14>>^ E está se cumprindo no caso deles a profecia de Isaías, que diz: ‘Vocês realmente ouvirão, mas de modo algum compreenderão; e realmente olharão, mas de modo algum verão.

[[v40-13-15]]

^<<v40-13-15,15>>^ Pois o coração deste povo ficou insensível, eles taparam os ouvidos^&#42;1^ e fecharam os olhos, para que nunca vissem com os olhos, nem ouvissem com os ouvidos, nem compreendessem com o coração e dessem meia-volta, e eu os curasse.’

[NOTE]
====
. Ou: “seus ouvidos ouviram sem reação”.
====

[[v40-13-16]]

^<<v40-13-16,16>>^ “No entanto, felizes são os olhos de vocês porque veem e os seus ouvidos porque ouvem.

[[v40-13-17]]

^<<v40-13-17,17>>^ Pois, digo-lhes a verdade: Muitos profetas e homens justos desejaram ver as coisas que vocês estão observando, mas não as viram, e ouvir as coisas que vocês estão ouvindo, mas não as ouviram.

[[v40-13-18]]

^<<v40-13-18,18>>^ “Escutem agora a ilustração do homem que semeou.

[[v40-13-19]]

^<<v40-13-19,19>>^ Quando alguém ouve a palavra do Reino, mas não a entende, vem o Maligno e arranca o que foi semeado no seu coração; essa é a que foi semeada à beira da estrada.

[[v40-13-20]]

^<<v40-13-20,20>>^ A que foi semeada em solo rochoso representa aquele que ouve a palavra e imediatamente a aceita com alegria.

[[v40-13-21]]

^<<v40-13-21,21>>^ Contudo, ele não tem raiz em si mesmo, mas continua por algum tempo e, quando surge dificuldade ou perseguição por causa da palavra, imediatamente tropeça.

[[v40-13-22]]

^<<v40-13-22,22>>^ A que foi semeada entre os espinhos representa aquele que ouve a palavra, mas as ansiedades deste mundo^&#42;1^ e o poder enganoso das riquezas sufocam a palavra, e ela se torna infrutífera.

[NOTE]
====
. Ou: “deste sistema de coisas; desta época”. Veja o  Glossário.
====

[[v40-13-23]]

^<<v40-13-23,23>>^ A que foi semeada em solo bom representa aquele que ouve a palavra e compreende o sentido dela, que realmente dá fruto e produz, este 100 vezes mais, aquele 60 vezes mais, outro 30 vezes mais.”

[[v40-13-24]]

^<<v40-13-24,24>>^ Apresentou-lhes outra ilustração, dizendo: “O Reino dos céus pode ser comparado a um homem que semeou boa semente no seu campo.

[[v40-13-25]]

^<<v40-13-25,25>>^ Enquanto os homens dormiam, seu inimigo veio, semeou joio no meio do trigo e foi embora.

[[v40-13-26]]

^<<v40-13-26,26>>^ Quando a haste cresceu e produziu fruto, apareceu também o joio.

[[v40-13-27]]

^<<v40-13-27,27>>^ Então, os escravos do dono da casa vieram e lhe perguntaram: ‘O senhor não semeou boa semente no seu campo? De onde veio então o joio?’

[[v40-13-28]]

^<<v40-13-28,28>>^ Ele lhes respondeu: ‘Um inimigo, um homem, fez isso.’ Os escravos lhe disseram: ‘O senhor quer então que vamos ajuntar o joio?’

[[v40-13-29]]

^<<v40-13-29,29>>^ Ele disse: ‘Não, pois, ao ajuntarem o joio, poderiam arrancar também o trigo.

[[v40-13-30]]

^<<v40-13-30,30>>^ Deixem ambos crescer juntos até a colheita, e na época da colheita eu direi aos ceifeiros: Ajuntem primeiro o joio e amarrem-no em feixes para ser queimado; depois ajuntem o trigo no meu celeiro.’”

[[v40-13-31]]

^<<v40-13-31,31>>^ Apresentou-lhes outra ilustração, dizendo: “O Reino dos céus é semelhante a um grão de mostarda, que um homem pegou e plantou no seu campo.

[[v40-13-32]]

^<<v40-13-32,32>>^ De fato, essa é a menor de todas as sementes, mas, depois de crescida, é a maior das hortaliças e se torna uma árvore, de modo que as aves do céu vêm e acham abrigo entre os seus ramos.”

[[v40-13-33]]

^<<v40-13-33,33>>^ Contou-lhes outra ilustração: “O Reino dos céus é semelhante ao fermento que uma mulher pegou e misturou com três grandes medidas de farinha, até que a massa inteira ficou fermentada.”

[[v40-13-34]]

^<<v40-13-34,34>>^ Jesus falou tudo isso às multidões por meio de ilustrações. Realmente, nada lhes falava sem ilustração,

[[v40-13-35]]

^<<v40-13-35,35>>^ para que se cumprissem as palavras do profeta, que disse: “Abrirei a minha boca com ilustrações; proclamarei as coisas escondidas desde a fundação.”^&#42;1^

[NOTE]
====
. Ou, possivelmente: “fundação do mundo”.
====

[[v40-13-36]]

^<<v40-13-36,36>>^ Então, depois de dispensar as multidões, ele entrou na casa. Seus discípulos se chegaram a ele e disseram: “Explique-nos a ilustração do joio no campo.”

[[v40-13-37]]

^<<v40-13-37,37>>^ Em resposta, ele disse: “O semeador da boa semente é o Filho do Homem;

[[v40-13-38]]

^<<v40-13-38,38>>^ o campo é o mundo. Quanto à boa semente, são os filhos do Reino, mas o joio são os filhos do Maligno,

[[v40-13-39]]

^<<v40-13-39,39>>^ e o inimigo que o semeou é o Diabo. A colheita é o final de um sistema de coisas,^&#42;1^ e os ceifeiros são os anjos.

[NOTE]
====
. Ou: “uma época”. Veja o Glossário.
====

[[v40-13-40]]

^<<v40-13-40,40>>^ Portanto, assim como o joio é ajuntado e queimado no fogo, assim será no final do sistema de coisas.^&#42;1^

[NOTE]
====
. Ou: “final da época”. Veja o  Glossário, “Sistema de coisas”.
====

[[v40-13-41]]

^<<v40-13-41,41>>^ O Filho do Homem enviará seus anjos, e eles ajuntarão dentre o seu Reino todas as coisas que causam tropeço e os que praticam o que é contra a lei,

[[v40-13-42]]

^<<v40-13-42,42>>^ e os lançarão na fornalha ardente. Ali é que haverá o seu choro e o ranger dos seus dentes.

[[v40-13-43]]

^<<v40-13-43,43>>^ Naquele tempo, os justos brilharão tão claramente como o sol, no Reino do seu Pai. Quem tem ouvidos, escute.

[[v40-13-44]]

^<<v40-13-44,44>>^ “O Reino dos céus é semelhante a um tesouro escondido no campo, que um homem achou e escondeu novamente; e, na sua alegria, ele foi, vendeu todas as coisas que tinha e comprou aquele campo.

[[v40-13-45]]

^<<v40-13-45,45>>^ “Também, o Reino dos céus é semelhante a um comerciante viajante que buscava pérolas de boa qualidade.

[[v40-13-46]]

^<<v40-13-46,46>>^ Ao achar uma pérola de grande valor, foi, vendeu prontamente todas as coisas que tinha e a comprou.

[[v40-13-47]]

^<<v40-13-47,47>>^ “Também, o Reino dos céus é semelhante a uma rede de arrasto baixada ao mar e que apanhou peixes de todo tipo.

[[v40-13-48]]

^<<v40-13-48,48>>^ Quando ela ficou cheia, arrastaram-na para a praia, sentaram-se e juntaram os peixes bons em recipientes, mas jogaram fora os imprestáveis.

[[v40-13-49]]

^<<v40-13-49,49>>^ Assim será no final do sistema de coisas.^&#42;1^ Os anjos sairão e separarão os maus dos justos,

[NOTE]
====
. Ou: “final da época”. Veja o  Glossário, “Sistema de coisas”.
====

[[v40-13-50]]

^<<v40-13-50,50>>^ e os lançarão na fornalha ardente. Ali é que haverá o seu choro e o ranger dos seus dentes.

[[v40-13-51]]

^<<v40-13-51,51>>^ “Compreenderam o sentido de tudo isso?” Eles responderam: “Sim.”

[[v40-13-52]]

^<<v40-13-52,52>>^ Então ele lhes disse: “Sendo assim, todo instrutor público que é ensinado a respeito do Reino dos céus é semelhante a um homem, dono de uma casa, que tira do seu tesouro coisas novas e coisas velhas.”

[[v40-13-53]]

^<<v40-13-53,53>>^ Quando Jesus terminou de contar essas ilustrações, partiu dali.

[[v40-13-54]]

^<<v40-13-54,54>>^ Chegando à sua própria cidade,^&#42;1^ começou a ensinar ao povo na sinagoga deles, de modo que ficaram maravilhados e disseram: “Onde este homem obteve essa sabedoria e essa habilidade de realizar obras poderosas?

[NOTE]
====
. Ou: “ao seu próprio território”.
====

[[v40-13-55]]

^<<v40-13-55,55>>^ Não é este o filho do carpinteiro? Sua mãe não se chama Maria e seus irmãos Tiago, José, Simão e Judas?

[[v40-13-56]]

^<<v40-13-56,56>>^ E não estão todas as suas irmãs conosco? Então, onde ele obteve tudo isso?”

[[v40-13-57]]

^<<v40-13-57,57>>^ Assim, começaram a tropeçar por causa dele. Mas Jesus lhes disse: “Um profeta não fica sem honra a não ser na sua própria terra e na sua própria casa.”

[[v40-13-58]]

^<<v40-13-58,58>>^ E não fez ali muitas obras poderosas, por causa da falta de fé deles.

'''

xref:040-mateus/040-mateus-012.adoc#v40-12-0[&#60; Capítulo Anterior] | <<v40-13-0,Topo>> | xref:040-mateus/040-mateus-014.adoc#v40-14-0[Próximo Capítulo &#62;]