include::./index.adoc[]

[[v40-6-0]]
=== Segundo Mateus, 6
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-6-1]]

^<<v40-6-1,1>>^ “Tomem cuidado para não praticar sua justiça diante dos homens a fim de ser vistos por eles; se fizerem isso, vocês não terão recompensa de seu Pai, que está nos céus.

[[v40-6-2]]

^<<v40-6-2,2>>^ Portanto, quando você der algo a um pobre,^&#42;1^ não toque a trombeta diante de si, como fazem os hipócritas nas sinagogas e nas ruas para serem glorificados pelos homens. Digo a vocês a verdade: Eles já têm plenamente a sua recompensa.

[NOTE]
====
. Ou: “fizer dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v40-6-3]]

^<<v40-6-3,3>>^ Mas, quando você der algo a um pobre, não deixe a sua mão esquerda saber o que a direita está fazendo,

[[v40-6-4]]

^<<v40-6-4,4>>^ para que suas dádivas fiquem em segredo. Então o seu Pai, que observa em secreto, o recompensará.

[[v40-6-5]]

^<<v40-6-5,5>>^ “Também, quando orarem, não ajam como os hipócritas, pois eles gostam de orar em pé nas sinagogas e nas esquinas das ruas principais, para serem vistos pelos homens. Digo a vocês a verdade: Eles já têm plenamente a sua recompensa.

[[v40-6-6]]

^<<v40-6-6,6>>^ Mas, quando você orar, entre no seu aposento reservado e, depois de fechar a porta, ore a seu Pai, que está em secreto. Então o seu Pai, que observa em secreto, o recompensará.

[[v40-6-7]]

^<<v40-6-7,7>>^ Quando orar, não diga as mesmas coisas vez após vez, como fazem as pessoas das nações, pois imaginam que serão ouvidas por usarem muitas palavras.

[[v40-6-8]]

^<<v40-6-8,8>>^ Não sejam como elas, porque o seu Pai sabe do que vocês necessitam, antes mesmo de lhe pedirem.

[[v40-6-9]]

^<<v40-6-9,9>>^ “Portanto, orem do seguinte modo:
“‘Pai nosso, que estás nos céus, santificado^&#42;1^ seja o teu nome.

[NOTE]
====
. Ou: “tido como sagrado; tratado como santo”.
====

[[v40-6-10]]

^<<v40-6-10,10>>^ Venha o teu Reino. Seja feita a tua vontade, como no céu, assim também na terra.

[[v40-6-11]]

^<<v40-6-11,11>>^ Dá-nos hoje o nosso pão para este dia;

[[v40-6-12]]

^<<v40-6-12,12>>^ e perdoa-nos as nossas dívidas, assim como nós também perdoamos os nossos devedores.

[[v40-6-13]]

^<<v40-6-13,13>>^ E não nos leves à tentação, mas livra-nos^&#42;1^ do Maligno.’

[NOTE]
====
. Ou: “salva-nos”.
====

[[v40-6-14]]

^<<v40-6-14,14>>^ “Pois, se vocês perdoarem aos homens as falhas deles, o seu Pai celestial também perdoará vocês;

[[v40-6-15]]

^<<v40-6-15,15>>^ ao passo que, se não perdoarem aos homens as falhas deles, o seu Pai também não perdoará as falhas de vocês.

[[v40-6-16]]

^<<v40-6-16,16>>^ “Quando jejuarem, parem de ficar com o rosto triste, como os hipócritas, pois eles mudam a aparência do rosto^&#42;1^ para que os homens vejam que estão jejuando. Digo a vocês a verdade: Eles já têm plenamente a sua recompensa.

[NOTE]
====
. Ou: “negligenciam sua aparência”.
====

[[v40-6-17]]

^<<v40-6-17,17>>^ Mas você, quando jejuar, ponha óleo sobre a cabeça e lave o rosto,

[[v40-6-18]]

^<<v40-6-18,18>>^ para que os homens não vejam que você está jejuando, mas somente o seu Pai, que está em secreto. Então o seu Pai, que observa em secreto, o recompensará.

[[v40-6-19]]

^<<v40-6-19,19>>^ “Parem de acumular para vocês tesouros na terra, onde a traça e a ferrugem consomem, e onde ladrões arrombam e furtam.

[[v40-6-20]]

^<<v40-6-20,20>>^ Em vez disso, acumulem para vocês tesouros no céu, onde nem a traça nem a ferrugem consomem, e onde ladrões não arrombam nem furtam.

[[v40-6-21]]

^<<v40-6-21,21>>^ Pois onde estiver o seu tesouro, ali estará também o seu coração.

[[v40-6-22]]

^<<v40-6-22,22>>^ “A lâmpada do corpo é o olho. Então, se o seu olho for focado,^&#42;1^ todo o seu corpo será luminoso.^&#42;2^

[NOTE]
====
. Ou: “claro”. Lit.: “singelo”.
. Ou: “cheio de luz”.
====

[[v40-6-23]]

^<<v40-6-23,23>>^ Mas, se o seu olho for invejoso,^&#42;1^ todo o seu corpo será escuro. Se a luz que há em você na realidade é escuridão, como é grande essa escuridão!

[NOTE]
====
. Lit.: “mau; perverso”.
====

[[v40-6-24]]

^<<v40-6-24,24>>^ “Ninguém pode ser escravo de dois senhores; pois ou odiará um e amará o outro, ou se apegará a um e desprezará o outro. Vocês não podem ser escravos de Deus e das Riquezas.

[[v40-6-25]]

^<<v40-6-25,25>>^ “Por essa razão, eu lhes digo: Parem de se preocupar tanto^&#42;1^ com a sua vida,^&#42;2^ quanto ao que comer ou quanto ao que beber, e com o seu corpo, quanto ao que vestir. Não significa a vida^&#42;3^ mais do que o alimento e o corpo mais do que a roupa?

[NOTE]
====
. Ou: “de estar ansiosos”.
. Ou: “alma”.
. Ou: “alma”.
====

[[v40-6-26]]

^<<v40-6-26,26>>^ Observem atentamente as aves do céu; elas não semeiam nem colhem, nem ajuntam em celeiros, contudo o Pai de vocês, que está nos céus, as alimenta. Será que vocês não valem mais do que elas?

[[v40-6-27]]

^<<v40-6-27,27>>^ Quem de vocês, por estar ansioso, pode acrescentar um só côvado^&#42;1^ à duração da sua vida?

[NOTE]
====
. Veja Ap. B14.
====

[[v40-6-28]]

^<<v40-6-28,28>>^ Também, com respeito à roupa, por que estão ansiosos? Aprendam uma lição dos lírios do campo, de como eles crescem; não trabalham nem fiam.

[[v40-6-29]]

^<<v40-6-29,29>>^ Mas eu lhes digo que nem mesmo Salomão, em toda a sua glória, se vestia como um deles.

[[v40-6-30]]

^<<v40-6-30,30>>^ Então, se Deus veste assim a vegetação do campo, que hoje existe e amanhã é lançada no forno, não vestirá ele ainda mais a vocês, homens de pouca fé?

[[v40-6-31]]

^<<v40-6-31,31>>^ Portanto, nunca fiquem ansiosos, dizendo: ‘O que vamos comer?’ ou: ‘O que vamos beber?’ ou: ‘O que vamos vestir?’

[[v40-6-32]]

^<<v40-6-32,32>>^ Pois todas essas são as coisas pelas quais as nações se empenham ansiosamente. O seu Pai celestial sabe que vocês necessitam de todas essas coisas.

[[v40-6-33]]

^<<v40-6-33,33>>^ “Persistam, então, em buscar primeiro o Reino e a justiça^&#42;1^ de Deus, e todas essas outras coisas lhes serão acrescentadas.

[NOTE]
====
. Veja o Glossário.
====

[[v40-6-34]]

^<<v40-6-34,34>>^ Portanto, nunca fiquem ansiosos por causa do amanhã, pois o amanhã terá suas próprias ansiedades. Bastam a cada dia suas próprias dificuldades.

'''

xref:040-mateus/040-mateus-005.adoc#v40-5-0[&#60; Capítulo Anterior] | <<v40-6-0,Topo>> | xref:040-mateus/040-mateus-007.adoc#v40-7-0[Próximo Capítulo &#62;]