include::./index.adoc[]

[[v40-21-0]]
=== Segundo Mateus, 21
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-21-1]]

^<<v40-21-1,1>>^ Quando se aproximaram de Jerusalém e chegaram a Betfagé, no monte das Oliveiras, Jesus enviou dois discípulos,

[[v40-21-2]]

^<<v40-21-2,2>>^ dizendo-lhes: “Vão à aldeia que está ao alcance da vista e logo acharão uma jumenta amarrada, e um jumentinho com ela. Desamarrem-nos e tragam-nos para mim.

[[v40-21-3]]

^<<v40-21-3,3>>^ Se alguém lhes disser alguma coisa, digam: ‘O Senhor precisa deles.’ Com isso, imediatamente os deixará trazê-los.”

[[v40-21-4]]

^<<v40-21-4,4>>^ Isso aconteceu para que se cumprissem as palavras do profeta, que disse:

[[v40-21-5]]

^<<v40-21-5,5>>^ “Digam à filha de Sião: ‘Veja! Seu rei está vindo a você, de temperamento brando e montado num jumento, sim, num jumentinho, filho de um animal de carga.’”

[[v40-21-6]]

^<<v40-21-6,6>>^ Os discípulos foram então e fizeram conforme Jesus lhes havia ordenado.

[[v40-21-7]]

^<<v40-21-7,7>>^ Trouxeram a jumenta e seu jumentinho, colocaram sobre eles suas capas, e ele se sentou nelas.

[[v40-21-8]]

^<<v40-21-8,8>>^ A maior parte da multidão estendeu suas capas na estrada, ao passo que outros cortavam ramos das árvores e os espalhavam pela estrada.

[[v40-21-9]]

^<<v40-21-9,9>>^ Além disso, as multidões que iam na frente dele e as que o seguiam gritavam: “Salva, rogamos, o Filho de Davi! Bendito é aquele que vem em nome de Jeová!^&#42;1^ Salva-o, rogamos, nas maiores alturas!”

[NOTE]
====
. Veja Ap. A5.
====

[[v40-21-10]]

^<<v40-21-10,10>>^ Quando ele entrou em Jerusalém, a cidade inteira ficou em alvoroço, e diziam: “Quem é este?”

[[v40-21-11]]

^<<v40-21-11,11>>^ As multidões respondiam: “Este é o profeta Jesus, de Nazaré da Galileia!”

[[v40-21-12]]

^<<v40-21-12,12>>^ Jesus entrou no templo, expulsou todos os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas.

[[v40-21-13]]

^<<v40-21-13,13>>^ E lhes disse: “Está escrito: ‘Minha casa será chamada casa de oração’, mas vocês fazem dela um abrigo^&#42;1^ de ladrões.”

[NOTE]
====
. Ou: “covil”.
====

[[v40-21-14]]

^<<v40-21-14,14>>^ Também, cegos e mancos se aproximaram dele no templo, e ele os curou.

[[v40-21-15]]

^<<v40-21-15,15>>^ Quando os principais sacerdotes e os escribas viram as coisas maravilhosas que ele fazia e os meninos que gritavam no templo: “Salva, rogamos, o Filho de Davi!”, ficaram indignados

[[v40-21-16]]

^<<v40-21-16,16>>^ e lhe disseram: “Está ouvindo o que eles estão dizendo?” Jesus lhes disse: “Sim. Vocês nunca leram o seguinte: ‘Da boca de crianças e de bebês fizeste sair louvor’?”

[[v40-21-17]]

^<<v40-21-17,17>>^ E, deixando-os para trás, saiu da cidade para Betânia e passou a noite ali.

[[v40-21-18]]

^<<v40-21-18,18>>^ Ao voltar à cidade de manhã cedo, sentiu fome.

[[v40-21-19]]

^<<v40-21-19,19>>^ Ele viu uma figueira à beira da estrada e se dirigiu a ela, mas não encontrou nada, a não ser folhas, e lhe disse: “Nunca mais produza fruto algum.” E a figueira secou instantaneamente.

[[v40-21-20]]

^<<v40-21-20,20>>^ Quando os discípulos viram isso, ficaram admirados e disseram: “Como é que a figueira secou instantaneamente?”

[[v40-21-21]]

^<<v40-21-21,21>>^ Em resposta, Jesus lhes disse: “Eu lhes digo a verdade: Se tiverem fé e não duvidarem, vocês não só farão o que eu fiz à figueira, mas até mesmo se disserem a este monte: ‘Levante-se e jogue-se no mar’, isso acontecerá.

[[v40-21-22]]

^<<v40-21-22,22>>^ E tudo o que pedirem em oração, tendo fé, vocês receberão.”

[[v40-21-23]]

^<<v40-21-23,23>>^ Depois de ele entrar no templo, os principais sacerdotes e os anciãos do povo se aproximaram dele, enquanto ensinava, e perguntaram: “Com que autoridade você faz essas coisas? E quem lhe deu essa autoridade?”

[[v40-21-24]]

^<<v40-21-24,24>>^ Jesus lhes disse em resposta: “Eu também lhes perguntarei uma coisa. Se me responderem, então eu lhes direi com que autoridade faço essas coisas:

[[v40-21-25]]

^<<v40-21-25,25>>^ O batismo de João, de onde se originou? Do céu ou dos homens?”^&#42;1^ Mas eles começaram a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele nos dirá: ‘Então, por que vocês não acreditaram nele?’

[NOTE]
====
. Ou: “de origem humana”.
====

[[v40-21-26]]

^<<v40-21-26,26>>^ Mas, se dissermos: ‘Dos homens’, temos a multidão para temer, porque todos eles consideram João como profeta.”

[[v40-21-27]]

^<<v40-21-27,27>>^ Assim, responderam a Jesus: “Não sabemos.” Ele, por sua vez, lhes disse: “Então eu também não lhes digo com que autoridade faço essas coisas.

[[v40-21-28]]

^<<v40-21-28,28>>^ “O que vocês acham? Um homem tinha dois filhos. Dirigindo-se ao primeiro, disse: ‘Filho, vá trabalhar hoje no vinhedo.’

[[v40-21-29]]

^<<v40-21-29,29>>^ Em resposta, esse lhe disse: ‘Não irei’, mas depois se arrependeu e foi.

[[v40-21-30]]

^<<v40-21-30,30>>^ Aproximando-se do segundo, o pai disse a mesma coisa. Esse respondeu: ‘Sim, senhor’, mas não foi.

[[v40-21-31]]

^<<v40-21-31,31>>^ Qual dos dois fez a vontade do pai?” Eles disseram: “O primeiro.” Jesus lhes disse: “Garanto a vocês que os cobradores de impostos e as prostitutas entrarão antes de vocês no Reino de Deus.

[[v40-21-32]]

^<<v40-21-32,32>>^ Porque João veio a vocês num caminho de justiça, mas vocês não acreditaram nele. No entanto os cobradores de impostos e as prostitutas acreditaram nele; e nem mesmo depois de verem isso vocês se arrependeram a ponto de acreditar nele.

[[v40-21-33]]

^<<v40-21-33,33>>^ “Ouçam outra ilustração: havia um homem, um proprietário, que plantou um vinhedo, pôs uma cerca em volta dele, cavou um lagar de vinho e ergueu uma torre; então arrendou o vinhedo a lavradores e viajou para fora.

[[v40-21-34]]

^<<v40-21-34,34>>^ Quando chegou a estação dos frutos, enviou seus escravos aos lavradores, para receber seus frutos.

[[v40-21-35]]

^<<v40-21-35,35>>^ No entanto, os lavradores pegaram os escravos dele, e a um espancaram, a outro mataram e a outro apedrejaram.

[[v40-21-36]]

^<<v40-21-36,36>>^ Enviou novamente outros escravos, em maior número do que no primeiro grupo, mas fizeram-lhes o mesmo.

[[v40-21-37]]

^<<v40-21-37,37>>^ Por fim enviou a eles seu filho, dizendo: ‘Respeitarão o meu filho.’

[[v40-21-38]]

^<<v40-21-38,38>>^ Ao verem o filho, os lavradores disseram entre si: ‘Este é o herdeiro. Venham, vamos matá-lo e ficar com a sua herança!’

[[v40-21-39]]

^<<v40-21-39,39>>^ Assim, eles o pegaram, o lançaram para fora do vinhedo e o mataram.

[[v40-21-40]]

^<<v40-21-40,40>>^ Portanto, quando o dono do vinhedo voltar, o que fará com aqueles lavradores?”

[[v40-21-41]]

^<<v40-21-41,41>>^ Disseram-lhe: “Por serem maus, trará sobre eles uma destruição terrível e arrendará o vinhedo a outros lavradores, que lhe darão os frutos no seu tempo devido.”

[[v40-21-42]]

^<<v40-21-42,42>>^ Jesus lhes disse: “Vocês nunca leram nas Escrituras: ‘A pedra que os construtores rejeitaram, essa se tornou a principal pedra angular.^&#42;1^ Isso procede de Jeová^&#42;2^ e é maravilhoso aos nossos olhos’?

[NOTE]
====
. Lit.: “a cabeça do cunhal”.
. Veja Ap. A5.
====

[[v40-21-43]]

^<<v40-21-43,43>>^ É por isso que lhes digo: O Reino de Deus será tirado de vocês e será dado a uma nação que produza os seus frutos.

[[v40-21-44]]

^<<v40-21-44,44>>^ Também, quem cair sobre essa pedra será despedaçado. Quanto àquele sobre quem ela cair, será esmagado.”

[[v40-21-45]]

^<<v40-21-45,45>>^ Quando os principais sacerdotes e os fariseus ouviram as ilustrações dele, sabiam que falava deles.

[[v40-21-46]]

^<<v40-21-46,46>>^ Embora quisessem prendê-lo,^&#42;1^ tinham medo das multidões, porque elas o consideravam como profeta.

[NOTE]
====
. Ou: “pegá-lo”.
====

'''

xref:040-mateus/040-mateus-020.adoc#v40-20-0[&#60; Capítulo Anterior] | <<v40-21-0,Topo>> | xref:040-mateus/040-mateus-022.adoc#v40-22-0[Próximo Capítulo &#62;]