include::./index.adoc[]

[[v40-8-0]]
=== Segundo Mateus, 8
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-8-1]]

^<<v40-8-1,1>>^ Depois que ele desceu do monte, grandes multidões o seguiram.

[[v40-8-2]]

^<<v40-8-2,2>>^ Então um leproso chegou e se curvou diante dele,^&#42;1^ dizendo: “Senhor, se apenas quiser, pode me purificar.”

[NOTE]
====
. Ou: “e lhe prestou homenagem”.
====

[[v40-8-3]]

^<<v40-8-3,3>>^ Assim, ele estendeu a mão e tocou no homem, dizendo: “Eu quero! Seja purificado.” Ele foi imediatamente purificado da lepra.

[[v40-8-4]]

^<<v40-8-4,4>>^ Jesus lhe disse então: “Tenha o cuidado de não contar nada a ninguém, mas vá, mostre-se ao sacerdote e ofereça a dádiva que Moisés determinou, em testemunho para eles.”

[[v40-8-5]]

^<<v40-8-5,5>>^ Quando entrou em Cafarnaum, um oficial do exército se aproximou dele, suplicando

[[v40-8-6]]

^<<v40-8-6,6>>^ e dizendo-lhe: “Senhor, meu servo está de cama em casa, com paralisia, e está sofrendo terrivelmente.”

[[v40-8-7]]

^<<v40-8-7,7>>^ Ele lhe disse: “Quando eu chegar lá, vou curá-lo.”

[[v40-8-8]]

^<<v40-8-8,8>>^ O oficial do exército respondeu: “Senhor, não sou digno de recebê-lo debaixo do meu teto, mas apenas diga a palavra e meu servo será curado.

[[v40-8-9]]

^<<v40-8-9,9>>^ Pois eu também sou homem sujeito a autoridade e tenho soldados sob as minhas ordens, e digo a um: ‘Vá!’ e ele vai, e a outro: ‘Venha!’ e ele vem, e ao meu escravo: ‘Faça isto!’ e ele faz.”

[[v40-8-10]]

^<<v40-8-10,10>>^ Quando Jesus ouviu isso, ficou admirado e disse aos que o seguiam: “Eu lhes digo a verdade: Em ninguém em Israel encontrei tamanha fé.

[[v40-8-11]]

^<<v40-8-11,11>>^ Mas eu lhes digo que muitos virão do leste e do oeste e se recostarão à mesa com Abraão, Isaque e Jacó, no Reino dos céus,

[[v40-8-12]]

^<<v40-8-12,12>>^ ao passo que os filhos do Reino serão lançados na escuridão lá fora. Ali é que haverá o seu choro e o ranger dos seus dentes.”

[[v40-8-13]]

^<<v40-8-13,13>>^ Jesus disse então ao oficial do exército: “Vá. Que lhe aconteça segundo a fé que você mostrou.” E o servo foi curado naquela hora.

[[v40-8-14]]

^<<v40-8-14,14>>^ Ao entrar na casa de Pedro, Jesus viu a sogra deste de cama e com febre.

[[v40-8-15]]

^<<v40-8-15,15>>^ Então tocou na mão dela e a febre a deixou, e ela se levantou e começou a servi-lo.

[[v40-8-16]]

^<<v40-8-16,16>>^ Depois de anoitecer, levaram-lhe muitas pessoas possessas de demônios; e ele expulsou os espíritos com uma palavra e curou todos os que estavam doentes,

[[v40-8-17]]

^<<v40-8-17,17>>^ para que se cumprissem as palavras de Isaías, o profeta: “Ele mesmo levou nossas doenças e carregou nossas enfermidades.”

[[v40-8-18]]

^<<v40-8-18,18>>^ Quando Jesus viu uma multidão ao seu redor, deu ordem de passar para a outra margem.

[[v40-8-19]]

^<<v40-8-19,19>>^ E um escriba se aproximou e lhe disse: “Instrutor, eu o seguirei para onde quer que o senhor vá.”

[[v40-8-20]]

^<<v40-8-20,20>>^ Mas Jesus lhe disse: “As raposas têm tocas e as aves do céu têm ninhos, mas o Filho do Homem não tem onde deitar a cabeça.”

[[v40-8-21]]

^<<v40-8-21,21>>^ Então, outro discípulo lhe disse: “Senhor, permita-me primeiro ir enterrar meu pai.”

[[v40-8-22]]

^<<v40-8-22,22>>^ Jesus lhe disse: “Continue a me seguir e deixe que os mortos enterrem seus mortos.”

[[v40-8-23]]

^<<v40-8-23,23>>^ Ele entrou num barco, e seus discípulos o seguiram.

[[v40-8-24]]

^<<v40-8-24,24>>^ Levantou-se então uma grande tempestade no mar, de modo que o barco estava sendo coberto pelas ondas; mas ele estava dormindo.

[[v40-8-25]]

^<<v40-8-25,25>>^ E eles foram acordá-lo, dizendo: “Senhor, salve-nos, pois estamos prestes a morrer!”

[[v40-8-26]]

^<<v40-8-26,26>>^ No entanto, ele lhes disse: “Por que vocês estão com tanto medo,^&#42;1^ homens de pouca fé?” Então ele se levantou e censurou os ventos e o mar, e houve uma grande calmaria.

[NOTE]
====
. Ou: “são tão inseguros”.
====

[[v40-8-27]]

^<<v40-8-27,27>>^ De modo que os homens ficaram espantados e disseram: “Que homem é este? Até mesmo os ventos e o mar lhe obedecem.”

[[v40-8-28]]

^<<v40-8-28,28>>^ Quando chegou à outra margem, à região dos gadarenos, dois homens possessos de demônios, saindo dentre os túmulos,^&#42;1^ foram ao encontro dele. Eles eram extremamente ferozes, de modo que ninguém tinha coragem de passar por aquela estrada.

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v40-8-29]]

^<<v40-8-29,29>>^ E começaram a gritar: “O que você quer conosco,^&#42;1^ Filho de Deus? Veio aqui nos atormentar antes do tempo determinado?”

[NOTE]
====
. Ou: “O que nós temos a ver com você”.
====

[[v40-8-30]]

^<<v40-8-30,30>>^ Bem longe dali havia uma grande manada de porcos pastando.

[[v40-8-31]]

^<<v40-8-31,31>>^ Assim, os demônios começaram a suplicar, dizendo-lhe: “Se você nos expulsar, mande-nos para a manada de porcos.”

[[v40-8-32]]

^<<v40-8-32,32>>^ E ele lhes disse: “Vão!” Eles saíram então e entraram nos porcos, e toda a manada se jogou despenhadeiro^&#42;1^ abaixo, para dentro do mar, e morreu nas águas.

[NOTE]
====
. Ou: “encosta íngreme”.
====

[[v40-8-33]]

^<<v40-8-33,33>>^ Os que cuidavam dos porcos fugiram, entraram na cidade e contaram tudo, inclusive o que tinha acontecido com os homens possessos de demônios.

[[v40-8-34]]

^<<v40-8-34,34>>^ Então toda a cidade saiu e foi ao encontro de Jesus e, ao vê-lo, suplicaram-lhe que fosse embora daquela região.

'''

xref:040-mateus/040-mateus-007.adoc#v40-7-0[&#60; Capítulo Anterior] | <<v40-8-0,Topo>> | xref:040-mateus/040-mateus-009.adoc#v40-9-0[Próximo Capítulo &#62;]