include::./index.adoc[]

[[v40-27-0]]
=== Segundo Mateus, 27
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-27-1]]

^<<v40-27-1,1>>^ Quando amanheceu, todos os principais sacerdotes e os anciãos do povo se reuniram para decidir como entregar Jesus à morte.

[[v40-27-2]]

^<<v40-27-2,2>>^ Depois de o amarrarem, o levaram e o entregaram a Pilatos, o governador.

[[v40-27-3]]

^<<v40-27-3,3>>^ Então Judas, que havia traído Jesus, vendo que este tinha sido condenado, sentiu remorso e devolveu as 30 moedas de prata aos principais sacerdotes e aos anciãos,

[[v40-27-4]]

^<<v40-27-4,4>>^ dizendo: “Pequei quando traí sangue inocente.” Eles disseram: “O que nós temos a ver com isso? Isso é com você!”^&#42;1^

[NOTE]
====
. Ou: “Esse problema é seu!”
====

[[v40-27-5]]

^<<v40-27-5,5>>^ De modo que ele lançou as moedas de prata dentro do templo e saiu. Então foi se enforcar.

[[v40-27-6]]

^<<v40-27-6,6>>^ Mas os principais sacerdotes pegaram as moedas de prata e disseram: “Não é permitido colocá-las no tesouro sagrado, porque são o preço de sangue.”

[[v40-27-7]]

^<<v40-27-7,7>>^ Depois de consultarem uns aos outros, usaram o dinheiro para comprar o campo do oleiro, como lugar para sepultar estranhos.

[[v40-27-8]]

^<<v40-27-8,8>>^ Por isso, aquele campo é chamado de Campo de Sangue até o dia de hoje.

[[v40-27-9]]

^<<v40-27-9,9>>^ Então se cumpriram as palavras de Jeremias, o profeta: “E pegaram as 30 moedas^&#42;1^ de prata, o preço que foi definido para o homem, aquele em quem alguns dos filhos de Israel puseram um preço,

[NOTE]
====
. Ou: “peças”.
====

[[v40-27-10]]

^<<v40-27-10,10>>^ e as deram pelo campo do oleiro, segundo o que Jeová^&#42;1^ tinha me ordenado.”

[NOTE]
====
. Veja Ap. A5.
====

[[v40-27-11]]

^<<v40-27-11,11>>^ Jesus estava então perante o governador, e o governador lhe perguntou: “Você é o Rei dos judeus?” Jesus respondeu: “O senhor mesmo está dizendo isso.”

[[v40-27-12]]

^<<v40-27-12,12>>^ Mas ele não deu nenhuma resposta enquanto estava sendo acusado pelos principais sacerdotes e pelos anciãos.

[[v40-27-13]]

^<<v40-27-13,13>>^ Então Pilatos lhe perguntou: “Não está ouvindo quantas coisas testemunham contra você?”

[[v40-27-14]]

^<<v40-27-14,14>>^ Contudo, ele não lhe respondeu, não, nem com uma só palavra, de modo que o governador ficou muito surpreso.

[[v40-27-15]]

^<<v40-27-15,15>>^ Por ocasião da festividade, era costume do governador soltar um preso, aquele que a multidão quisesse.

[[v40-27-16]]

^<<v40-27-16,16>>^ Eles tinham então um preso chamado Barrabás, um criminoso muito conhecido.

[[v40-27-17]]

^<<v40-27-17,17>>^ Portanto, quando estavam reunidos, Pilatos lhes disse: “Qual deles vocês querem que eu solte: Barrabás ou Jesus, o chamado Cristo?”

[[v40-27-18]]

^<<v40-27-18,18>>^ Pois Pilatos sabia que o tinham entregado por inveja.

[[v40-27-19]]

^<<v40-27-19,19>>^ Além disso, enquanto estava sentado no tribunal, sua esposa lhe mandou este recado: “Não tenha nada a ver com esse homem justo, pois hoje eu sofri muito, num sonho, por causa dele.”

[[v40-27-20]]

^<<v40-27-20,20>>^ Mas os principais sacerdotes e os anciãos persuadiram as multidões a pedir Barrabás e a fazer com que Jesus fosse morto.

[[v40-27-21]]

^<<v40-27-21,21>>^ Então o governador lhes disse: “Qual dos dois vocês querem que eu solte?” Disseram: “Barrabás!”

[[v40-27-22]]

^<<v40-27-22,22>>^ Pilatos lhes disse: “O que, então, devo fazer com Jesus, o chamado Cristo?” Todos disseram: “Para a estaca com ele!”^&#42;1^

[NOTE]
====
. Ou: “Execute-o na estaca!”
====

[[v40-27-23]]

^<<v40-27-23,23>>^ Ele disse: “Por quê? O que ele fez de mau?” Contudo, gritaram ainda mais: “Para a estaca com ele!”

[[v40-27-24]]

^<<v40-27-24,24>>^ Vendo que não adiantava, mas, ao contrário, que se criava um alvoroço, Pilatos pegou água e lavou as mãos diante da multidão, dizendo: “Eu sou inocente do sangue deste homem. Isso é com vocês.”

[[v40-27-25]]

^<<v40-27-25,25>>^ Todo o povo disse em resposta: “Que o sangue dele caia sobre nós e sobre nossos filhos.”

[[v40-27-26]]

^<<v40-27-26,26>>^ Ele soltou então Barrabás, porém mandou que Jesus fosse chicoteado e o entregou para ser morto na estaca.

[[v40-27-27]]

^<<v40-27-27,27>>^ Os soldados do governador levaram Jesus para a residência do governador e reuniram em volta dele todo o grupo de soldados.

[[v40-27-28]]

^<<v40-27-28,28>>^ Depois de despi-lo, puseram nele um manto escarlate;^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-27-29]]

^<<v40-27-29,29>>^ trançaram uma coroa de espinhos e a puseram na cabeça dele, bem como uma cana na sua mão direita. E, ajoelhando-se diante dele, zombaram dele, dizendo: “Salve, Rei dos judeus!”

[[v40-27-30]]

^<<v40-27-30,30>>^ Então cuspiram nele, pegaram a cana e começaram a lhe bater na cabeça.

[[v40-27-31]]

^<<v40-27-31,31>>^ Por fim, depois de terem zombado dele, tiraram-lhe o manto e puseram de volta nele suas roupas, e o levaram para ser pregado na estaca.

[[v40-27-32]]

^<<v40-27-32,32>>^ Ao saírem, encontraram um homem de Cirene chamado Simão. Obrigaram esse homem a prestar serviço carregando a estaca.^&#42;1^

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-33]]

^<<v40-27-33,33>>^ Quando chegaram ao lugar chamado Gólgota, isto é, Lugar da Caveira,

[[v40-27-34]]

^<<v40-27-34,34>>^ deram-lhe vinho misturado com fel^&#42;1^ para beber; mas, depois de prová-lo, ele se recusou a beber.

[NOTE]
====
. Um líquido amargo.
====

[[v40-27-35]]

^<<v40-27-35,35>>^ Depois de pregá-lo na estaca, repartiram suas roupas, lançando sortes,

[[v40-27-36]]

^<<v40-27-36,36>>^ e ficaram sentados ali, vigiando-o.

[[v40-27-37]]

^<<v40-27-37,37>>^ Também colocaram acima da sua cabeça a acusação contra ele, por escrito: “Este é Jesus, o Rei dos judeus.”

[[v40-27-38]]

^<<v40-27-38,38>>^ Dois ladrões foram então pendurados em estacas ao lado dele, um à sua direita e outro à sua esquerda.

[[v40-27-39]]

^<<v40-27-39,39>>^ Os que passavam o insultavam, balançando a cabeça

[[v40-27-40]]

^<<v40-27-40,40>>^ e dizendo: “Você que ia derrubar o templo e construí-lo em três dias, salve a si mesmo! Se você é filho de Deus, desça da estaca!”^&#42;1^

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-41]]

^<<v40-27-41,41>>^ Do mesmo modo, também os principais sacerdotes, junto com os escribas e os anciãos, começaram a zombar dele, dizendo:

[[v40-27-42]]

^<<v40-27-42,42>>^ “A outros ele salvou; a si mesmo não pode salvar! Ele é Rei de Israel; que desça agora da estaca,^&#42;1^ e nós acreditaremos nele.

[NOTE]
====
. Ou: “estaca de tortura”. Veja o Glossário.
====

[[v40-27-43]]

^<<v40-27-43,43>>^ Depositou sua confiança em Deus; que Ele o salve agora, se Ele se agrada dele, pois disse: ‘Sou Filho de Deus.’”

[[v40-27-44]]

^<<v40-27-44,44>>^ Do mesmo modo, até os ladrões, que estavam em estacas ao lado dele, o insultavam.

[[v40-27-45]]

^<<v40-27-45,45>>^ Da sexta hora^&#42;1^ em diante, caiu uma escuridão sobre toda aquela terra, até a nona hora.^&#42;2^

[NOTE]
====
. Isto é, por volta do meio-dia.
. Isto é, por volta das 3 h da tarde.
====

[[v40-27-46]]

^<<v40-27-46,46>>^ Por volta da nona hora, Jesus clamou em alta voz: “Eli, Eli, lama sabactâni?”, isto é: “Deus meu, Deus meu, por que me abandonaste?”

[[v40-27-47]]

^<<v40-27-47,47>>^ Ouvindo isso, alguns dos que estavam ali disseram: “Este homem está chamando Elias.”

[[v40-27-48]]

^<<v40-27-48,48>>^ E um deles correu imediatamente, pegou uma esponja, ensopou-a em vinho acre, colocou-a numa cana e deu a ele para beber.

[[v40-27-49]]

^<<v40-27-49,49>>^ Mas os demais disseram: “Deixe-o! Vamos ver se Elias vem salvá-lo.”

[[v40-27-50]]

^<<v40-27-50,50>>^ Novamente Jesus clamou em alta voz e entregou seu espírito.^&#42;1^

[NOTE]
====
. Ou: “e expirou; e deu seu último suspiro”.
====

[[v40-27-51]]

^<<v40-27-51,51>>^ Naquele momento, a cortina do santuário se rasgou em duas, de alto a baixo, a terra tremeu e as rochas se partiram.

[[v40-27-52]]

^<<v40-27-52,52>>^ Os túmulos^&#42;1^ se abriram e muitos corpos dos santos que tinham adormecido foram levantados

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v40-27-53]]

^<<v40-27-53,53>>^ (e pessoas, saindo dentre os túmulos depois de ele ter sido levantado, entraram na cidade santa), e eles se tornaram visíveis a muitas pessoas.

[[v40-27-54]]

^<<v40-27-54,54>>^ Mas, quando o oficial do exército e os que estavam com ele vigiando Jesus viram o terremoto e as coisas que aconteciam, ficaram com muito medo e disseram: “Certamente este era o Filho de Deus.”

[[v40-27-55]]

^<<v40-27-55,55>>^ E havia ali muitas mulheres observando de certa distância. Elas tinham acompanhado Jesus desde a Galileia, para servi-lo.

[[v40-27-56]]

^<<v40-27-56,56>>^ Entre essas estavam Maria Madalena, também Maria, mãe de Tiago e de Josés, e a mãe dos filhos de Zebedeu.

[[v40-27-57]]

^<<v40-27-57,57>>^ Então, visto que a tarde estava avançada, chegou um homem rico de Arimateia, chamado José, que também tinha se tornado discípulo de Jesus.

[[v40-27-58]]

^<<v40-27-58,58>>^ Esse homem se aproximou de Pilatos e pediu o corpo de Jesus. Pilatos ordenou então que lhe fosse entregue.

[[v40-27-59]]

^<<v40-27-59,59>>^ José pegou o corpo, enrolou-o em puro linho fino

[[v40-27-60]]

^<<v40-27-60,60>>^ e o colocou no seu túmulo^&#42;1^ novo, que tinha aberto na rocha. E, depois de rolar uma grande pedra até a entrada do túmulo,^&#42;2^ foi embora.

[NOTE]
====
. Ou: “túmulo memorial”.
. Ou: “túmulo memorial”.
====

[[v40-27-61]]

^<<v40-27-61,61>>^ Mas Maria Madalena e a outra Maria permaneceram ali, sentadas diante da sepultura.

[[v40-27-62]]

^<<v40-27-62,62>>^ No outro dia, o dia seguinte ao da Preparação, os principais sacerdotes e os fariseus se reuniram perante Pilatos

[[v40-27-63]]

^<<v40-27-63,63>>^ e disseram: “Senhor, nós nos lembramos de que aquele impostor dizia, enquanto ainda estava vivo: ‘Depois de três dias eu serei levantado.’

[[v40-27-64]]

^<<v40-27-64,64>>^ Portanto, ordene que se mantenha a sepultura em segurança até o terceiro dia, para que não venham os discípulos dele e o furtem, e digam ao povo: ‘Ele foi levantado dentre os mortos!’ Então esta última mentira seria pior do que a primeira.”

[[v40-27-65]]

^<<v40-27-65,65>>^ Pilatos lhes disse: “Vocês podem levar soldados. Vão, mantenham a sepultura tão segura quanto puderem.”

[[v40-27-66]]

^<<v40-27-66,66>>^ De modo que foram manter a sepultura em segurança, lacrando a pedra e colocando os soldados de guarda.

'''

xref:040-mateus/040-mateus-026.adoc#v40-26-0[&#60; Capítulo Anterior] | <<v40-27-0,Topo>> | xref:040-mateus/040-mateus-028.adoc#v40-28-0[Próximo Capítulo &#62;]