include::./index.adoc[]

[[v40-11-0]]
=== Segundo Mateus, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-11-1]]

^<<v40-11-1,1>>^ Quando terminou de dar instruções aos seus 12 discípulos, Jesus partiu dali para ensinar e pregar nas cidades deles.

[[v40-11-2]]

^<<v40-11-2,2>>^ Mas, na cadeia, João ouviu falar das obras do Cristo e enviou seus discípulos

[[v40-11-3]]

^<<v40-11-3,3>>^ para lhe perguntar: “O senhor é Aquele Que Vem, ou devemos esperar outro?”

[[v40-11-4]]

^<<v40-11-4,4>>^ Jesus lhes disse em resposta: “Vão, contem a João o que vocês estão ouvindo e vendo:

[[v40-11-5]]

^<<v40-11-5,5>>^ os cegos agora veem, os mancos estão andando, os leprosos estão sendo purificados, os surdos estão ouvindo, os mortos estão sendo levantados e as boas novas estão sendo anunciadas aos pobres.

[[v40-11-6]]

^<<v40-11-6,6>>^ Feliz é aquele que não acha em mim causa para tropeço.”

[[v40-11-7]]

^<<v40-11-7,7>>^ Enquanto eles partiam, Jesus começou a falar às multidões sobre João: “O que vocês foram ver no deserto? Uma cana sacudida pelo vento?

[[v40-11-8]]

^<<v40-11-8,8>>^ O que, então, foram ver? Um homem vestido de roupas finas? Ora, os que usam roupas finas estão nos palácios dos reis.

[[v40-11-9]]

^<<v40-11-9,9>>^ Realmente, então, por que vocês foram lá? Para ver um profeta? Sim, eu lhes digo, e muito mais do que um profeta.

[[v40-11-10]]

^<<v40-11-10,10>>^ Esse é aquele a respeito de quem se escreveu: ‘Veja! Enviarei o meu mensageiro na sua frente,^&#42;1^ o qual preparará o seu caminho adiante de você!’

[NOTE]
====
. Lit.: “diante da sua face”.
====

[[v40-11-11]]

^<<v40-11-11,11>>^ Digo-lhes a verdade: Entre os nascidos de mulher não surgiu ninguém maior do que João Batista; mas aquele que é menor no Reino dos céus é maior do que ele.

[[v40-11-12]]

^<<v40-11-12,12>>^ Desde os dias de João Batista até agora, o Reino dos céus é o alvo para o qual os homens avançam vigorosamente, e os que avançam vigorosamente se apoderam dele.

[[v40-11-13]]

^<<v40-11-13,13>>^ Pois todos, os Profetas e a Lei, profetizaram até João.

[[v40-11-14]]

^<<v40-11-14,14>>^ E, se vocês quiserem aceitar, ele é ‘Elias, que há de vir’.

[[v40-11-15]]

^<<v40-11-15,15>>^ Quem tem ouvidos, escute.

[[v40-11-16]]

^<<v40-11-16,16>>^ “Com quem compararei esta geração? Ela é semelhante a crianças sentadas nas praças,^&#42;1^ que gritam para seus colegas:

[NOTE]
====
. Áreas abertas usadas como centro de compras e vendas e como local de reuniões públicas.
====

[[v40-11-17]]

^<<v40-11-17,17>>^ ‘Nós tocamos flauta para vocês, mas vocês não dançaram; nós lamentamos, mas vocês não bateram no peito de pesar.’

[[v40-11-18]]

^<<v40-11-18,18>>^ Da mesma maneira, João veio sem comer e sem beber, mas as pessoas dizem: ‘Ele tem demônio.’

[[v40-11-19]]

^<<v40-11-19,19>>^ O Filho do Homem veio comendo e bebendo, mas elas dizem: ‘Vejam! Um homem glutão e dado a beber vinho, amigo de cobradores de impostos e de pecadores.’ No entanto, a sabedoria se prova justa^&#42;1^ pelas suas obras.”^&#42;2^

[NOTE]
====
. Ou: “é vindicada”.
. Ou: “pelos seus resultados”.
====

[[v40-11-20]]

^<<v40-11-20,20>>^ Ele começou então a censurar as cidades nas quais se realizou a maioria das suas obras poderosas, pois não se arrependeram:

[[v40-11-21]]

^<<v40-11-21,21>>^ “Ai de você, Corazim! Ai de você, Betsaida! Porque, se as obras poderosas que ocorreram em vocês tivessem ocorrido em Tiro e Sídon, há muito tempo elas teriam se arrependido em pano de saco e em cinzas.

[[v40-11-22]]

^<<v40-11-22,22>>^ Mas eu lhes digo: No Dia do Julgamento será mais suportável para Tiro e Sídon do que para vocês.

[[v40-11-23]]

^<<v40-11-23,23>>^ E você, Cafarnaum, será por acaso enaltecida ao céu? Até a Sepultura^&#42;1^ você descerá. Porque, se as obras poderosas que ocorreram em você tivessem ocorrido em Sodoma, ela teria permanecido até o dia de hoje.

[NOTE]
====
. Ou: “o Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v40-11-24]]

^<<v40-11-24,24>>^ Mas eu lhes digo: No Dia do Julgamento será mais suportável para a terra de Sodoma do que para você.”

[[v40-11-25]]

^<<v40-11-25,25>>^ Em vista disso, naquela ocasião Jesus disse: “Eu te louvo publicamente, Pai, Senhor do céu e da terra, porque escondeste essas coisas dos sábios e dos intelectuais, e as revelaste aos pequeninos.

[[v40-11-26]]

^<<v40-11-26,26>>^ Sim, ó Pai, porque tu te agradaste de fazer as coisas dessa maneira.

[[v40-11-27]]

^<<v40-11-27,27>>^ Tudo me foi entregue por meu Pai. E ninguém conhece plenamente o Filho, exceto o Pai; e ninguém conhece plenamente o Pai, exceto o Filho e aquele a quem o Filho quiser revelá-lo.

[[v40-11-28]]

^<<v40-11-28,28>>^ Venham a mim, todos vocês que estão trabalhando duro e estão sobrecarregados, e eu os reanimarei.

[[v40-11-29]]

^<<v40-11-29,29>>^ Tomem sobre vocês o meu jugo e aprendam de mim, pois sou de temperamento brando e humilde de coração, e acharão revigoramento para si mesmos.^&#42;1^

[NOTE]
====
. Ou: “sua alma”.
====

[[v40-11-30]]

^<<v40-11-30,30>>^ Pois o meu jugo é suave^&#42;1^ e a minha carga é leve.”

[NOTE]
====
. Ou: “fácil de carregar”.
====

'''

xref:040-mateus/040-mateus-010.adoc#v40-10-0[&#60; Capítulo Anterior] | <<v40-11-0,Topo>> | xref:040-mateus/040-mateus-012.adoc#v40-12-0[Próximo Capítulo &#62;]