include::./index.adoc[]

[[v40-17-0]]
=== Segundo Mateus, 17
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-17-1]]

^<<v40-17-1,1>>^ Seis dias depois, Jesus chamou Pedro e os irmãos Tiago e João, e os levou a sós a um alto monte.

[[v40-17-2]]

^<<v40-17-2,2>>^ E ele foi transfigurado diante deles; seu rosto brilhava como o sol, e suas roupas se tornaram brilhantes^&#42;1^ como a luz.

[NOTE]
====
. Ou: “brancas”.
====

[[v40-17-3]]

^<<v40-17-3,3>>^ Nisto, apareceram-lhes Moisés e Elias, conversando com ele.

[[v40-17-4]]

^<<v40-17-4,4>>^ Então Pedro disse a Jesus: “Senhor, é bom que estejamos aqui. Se desejar, armarei aqui três tendas: uma para o senhor, uma para Moisés e uma para Elias.”

[[v40-17-5]]

^<<v40-17-5,5>>^ Ele ainda estava falando, quando uma nuvem luminosa os encobriu, e de repente uma voz vinda da nuvem disse: “Este é meu Filho, o amado, a quem eu aprovo. Escutem-no.”

[[v40-17-6]]

^<<v40-17-6,6>>^ Ao ouvirem isso, os discípulos se prostraram com o rosto por terra e ficaram com muito medo.

[[v40-17-7]]

^<<v40-17-7,7>>^ Jesus se aproximou, então, tocou neles e disse: “Levantem-se. Não tenham medo.”

[[v40-17-8]]

^<<v40-17-8,8>>^ Ao levantarem os olhos, não viram mais ninguém, mas apenas Jesus.

[[v40-17-9]]

^<<v40-17-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou: “Não contem essa visão a ninguém, até que o Filho do Homem seja levantado dentre os mortos.”

[[v40-17-10]]

^<<v40-17-10,10>>^ No entanto, os discípulos lhe perguntaram: “Por que então os escribas dizem que Elias tem de vir primeiro?”

[[v40-17-11]]

^<<v40-17-11,11>>^ Em resposta, ele disse: “Elias, realmente, vem e restabelecerá todas as coisas.

[[v40-17-12]]

^<<v40-17-12,12>>^ No entanto, eu lhes digo que Elias já veio e eles não o reconheceram, mas fizeram com ele o que quiseram. Do mesmo modo também o Filho do Homem sofrerá às mãos deles.”

[[v40-17-13]]

^<<v40-17-13,13>>^ Os discípulos perceberam então que lhes falava de João Batista.

[[v40-17-14]]

^<<v40-17-14,14>>^ Quando eles chegaram onde estava a multidão, um homem se aproximou dele, se ajoelhou diante dele e disse:

[[v40-17-15]]

^<<v40-17-15,15>>^ “Senhor, tenha misericórdia do meu filho, porque ele é epilético e está doente. Ele cai muitas vezes no fogo e muitas vezes na água.

[[v40-17-16]]

^<<v40-17-16,16>>^ Eu o trouxe aos seus discípulos, mas eles não conseguiram curá-lo.”

[[v40-17-17]]

^<<v40-17-17,17>>^ Jesus disse, em resposta: “Ó geração sem fé e pervertida, até quando terei de continuar com vocês? Até quando terei de suportá-los? Tragam-no aqui.”

[[v40-17-18]]

^<<v40-17-18,18>>^ Jesus censurou então o demônio, e este saiu dele; e o menino ficou curado daquele momento em diante.

[[v40-17-19]]

^<<v40-17-19,19>>^ Então os discípulos se aproximaram de Jesus em particular e perguntaram: “Por que nós não conseguimos expulsá-lo?”

[[v40-17-20]]

^<<v40-17-20,20>>^ Ele lhes respondeu: “Por terem pouca fé. Pois, eu lhes digo a verdade: Se tiverem fé do tamanho de um grão de mostarda, vocês dirão a este monte: ‘Mova-se daqui para lá’, e ele se moverá, e nada lhes será impossível.”

[[v40-17-21]]

^<<v40-17-21,21>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v40-17-22]]

^<<v40-17-22,22>>^ Foi quando estavam reunidos na Galileia que Jesus lhes disse: “O Filho do Homem será entregue^&#42;1^ às mãos dos homens,

[NOTE]
====
. Ou: “traído”.
====

[[v40-17-23]]

^<<v40-17-23,23>>^ e eles o matarão, e no terceiro dia ele será levantado.” E eles ficaram muito tristes.

[[v40-17-24]]

^<<v40-17-24,24>>^ Depois de eles chegarem a Cafarnaum, os homens que cobravam o imposto de duas dracmas^&#42;1^ se aproximaram de Pedro e perguntaram: “O seu instrutor não paga as duas dracmas de imposto?”

[NOTE]
====
. Lit.: “das dracmas duplas”. Veja Ap. B14.
====

[[v40-17-25]]

^<<v40-17-25,25>>^ Pedro disse: “Sim, ele paga.” No entanto, quando ele entrou na casa, Jesus falou primeiro que ele: “O que acha, Simão? De quem os reis da terra recebem tributos ou imposto por cabeça? Dos seus filhos ou dos estranhos?”

[[v40-17-26]]

^<<v40-17-26,26>>^ Quando ele disse: “Dos estranhos”, Jesus lhe disse: “Realmente, então, os filhos estão isentos de impostos.

[[v40-17-27]]

^<<v40-17-27,27>>^ Mas, para que não os façamos tropeçar, vá ao mar, lance o anzol e pegue o primeiro peixe que você pescar; quando abrir a boca dele, você achará uma moeda de prata.^&#42;1^ Pegue-a e entregue-a a eles por mim e por você.”

[NOTE]
====
. Lit.: “moeda de estáter”; entende-se que seja a tetradracma. Veja Ap. B14.
====

'''

xref:040-mateus/040-mateus-016.adoc#v40-16-0[&#60; Capítulo Anterior] | <<v40-17-0,Topo>> | xref:040-mateus/040-mateus-018.adoc#v40-18-0[Próximo Capítulo &#62;]