include::./index.adoc[]

[[v40-19-0]]
=== Segundo Mateus, 19
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-19-1]]

^<<v40-19-1,1>>^ Quando Jesus terminou de falar essas coisas, partiu da Galileia e foi para as fronteiras da Judeia, do outro lado do Jordão.

[[v40-19-2]]

^<<v40-19-2,2>>^ Também, grandes multidões o seguiram, e ele as curou ali.

[[v40-19-3]]

^<<v40-19-3,3>>^ Alguns fariseus se aproximaram dele, querendo pô-lo à prova, e perguntaram: “É permitido que um homem se divorcie da sua esposa por qualquer motivo?”

[[v40-19-4]]

^<<v40-19-4,4>>^ Ele respondeu: “Não leram que aquele que os criou no princípio os fez homem e mulher,

[[v40-19-5]]

^<<v40-19-5,5>>^ e disse: ‘Por essa razão o homem deixará seu pai e sua mãe e se apegará à sua esposa, e os dois serão uma só carne’?

[[v40-19-6]]

^<<v40-19-6,6>>^ De modo que não são mais dois, mas uma só carne. Portanto, o que Deus pôs sob o mesmo jugo, o homem não deve separar.”

[[v40-19-7]]

^<<v40-19-7,7>>^ Perguntaram-lhe: “Então, por que Moisés mandou que o homem desse a ela um certificado de divórcio e a mandasse embora?”

[[v40-19-8]]

^<<v40-19-8,8>>^ Ele lhes disse: “Foi por causa da dureza do coração de vocês que Moisés lhes fez a concessão de se divorciarem de suas esposas, mas não era assim no princípio.

[[v40-19-9]]

^<<v40-19-9,9>>^ Eu lhes digo que quem se divorcia da sua esposa, a não ser por causa de imoralidade sexual,^&#42;1^ e se casa com outra, comete adultério.”

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v40-19-10]]

^<<v40-19-10,10>>^ Os discípulos lhe disseram: “Se essa é a situação entre o homem e sua esposa, não é aconselhável se casar.”

[[v40-19-11]]

^<<v40-19-11,11>>^ Ele lhes disse: “Nem todos os homens dão lugar a essas palavras, mas somente os que têm o dom.

[[v40-19-12]]

^<<v40-19-12,12>>^ Pois há eunucos que nasceram assim, há eunucos que foram feitos eunucos pelos homens e há eunucos que se fizeram eunucos por causa do Reino dos céus. Dê lugar a isso aquele que pode dar lugar a isso.”

[[v40-19-13]]

^<<v40-19-13,13>>^ Então alguns trouxeram a ele criancinhas, para que pusesse as mãos sobre elas e proferisse uma oração, mas os discípulos os repreenderam.

[[v40-19-14]]

^<<v40-19-14,14>>^ Jesus, porém, disse: “Deixem as criancinhas e não tentem impedi-las de vir a mim, pois o Reino dos céus pertence aos que são como elas.”

[[v40-19-15]]

^<<v40-19-15,15>>^ Ele pôs as mãos sobre elas e partiu dali.

[[v40-19-16]]

^<<v40-19-16,16>>^ Então alguém se aproximou dele e perguntou: “Instrutor, o que devo fazer de bom para ganhar a vida eterna?”

[[v40-19-17]]

^<<v40-19-17,17>>^ Ele lhe disse: “Por que você me pergunta sobre o que é bom? Bom só existe um. Porém, se você quer entrar na vida, obedeça sempre aos mandamentos.”

[[v40-19-18]]

^<<v40-19-18,18>>^ Ele lhe perguntou: “Quais?” Jesus disse: “Não assassine; não cometa adultério; não furte; não dê falso testemunho;

[[v40-19-19]]

^<<v40-19-19,19>>^ honre seu pai e sua mãe; e ame o seu próximo como a si mesmo.”

[[v40-19-20]]

^<<v40-19-20,20>>^ O jovem lhe disse: “Tenho cumprido todos esses. O que me falta ainda?”

[[v40-19-21]]

^<<v40-19-21,21>>^ Jesus lhe disse: “Se você quer ser perfeito,^&#42;1^ vá vender seus bens e dê o dinheiro aos pobres, e você terá um tesouro no céu; e venha ser meu seguidor.”

[NOTE]
====
. Ou: “completo”.
====

[[v40-19-22]]

^<<v40-19-22,22>>^ Quando o jovem ouviu isso, foi embora triste, porque tinha muitas posses.

[[v40-19-23]]

^<<v40-19-23,23>>^ Jesus disse então aos seus discípulos: “Eu lhes digo a verdade: Será difícil para um rico entrar no Reino dos céus.

[[v40-19-24]]

^<<v40-19-24,24>>^ Eu lhes digo ainda: É mais fácil um camelo passar pelo buraco de uma agulha do que um rico entrar no Reino de Deus.”

[[v40-19-25]]

^<<v40-19-25,25>>^ Quando os discípulos ouviram isso, ficaram muito espantados e disseram: “Quem realmente pode ser salvo?”

[[v40-19-26]]

^<<v40-19-26,26>>^ Jesus olhou fixamente para eles e lhes disse: “Para os homens isso é impossível, mas para Deus todas as coisas são possíveis.”

[[v40-19-27]]

^<<v40-19-27,27>>^ Pedro respondeu: “Veja, deixamos tudo e seguimos o senhor. O que haverá então para nós?”

[[v40-19-28]]

^<<v40-19-28,28>>^ Jesus lhes disse: “Eu lhes garanto: Na recriação, quando o Filho do Homem se sentar no seu trono glorioso, vocês que me seguiram se sentarão em 12 tronos e julgarão as 12 tribos de Israel.

[[v40-19-29]]

^<<v40-19-29,29>>^ E todo aquele que tiver deixado casas, irmãos, irmãs, pai, mãe, filhos ou terras, por causa do meu nome, receberá cem vezes mais e herdará a vida eterna.

[[v40-19-30]]

^<<v40-19-30,30>>^ “Mas muitos que são primeiros serão últimos; e os últimos, primeiros.

'''

xref:040-mateus/040-mateus-018.adoc#v40-18-0[&#60; Capítulo Anterior] | <<v40-19-0,Topo>> | xref:040-mateus/040-mateus-020.adoc#v40-20-0[Próximo Capítulo &#62;]