include::./index.adoc[]

[[v40-5-0]]
=== Segundo Mateus, 5
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-5-1]]

^<<v40-5-1,1>>^ Quando ele viu as multidões, subiu ao monte e, depois de se sentar, chegaram-se a ele os seus discípulos.

[[v40-5-2]]

^<<v40-5-2,2>>^ Então ele abriu a boca e começou a ensiná-los, dizendo:

[[v40-5-3]]

^<<v40-5-3,3>>^ “Felizes os que têm consciência de sua necessidade espiritual,^&#42;1^ porque a eles pertence o Reino dos céus.

[NOTE]
====
. Ou: “os que mendigam o espírito”.
====

[[v40-5-4]]

^<<v40-5-4,4>>^ “Felizes os que choram, porque serão consolados.

[[v40-5-5]]

^<<v40-5-5,5>>^ “Felizes os de temperamento brando,^&#42;1^ porque herdarão a terra.

[NOTE]
====
. Ou: “os mansos”.
====

[[v40-5-6]]

^<<v40-5-6,6>>^ “Felizes os que têm fome e sede de justiça, porque serão saciados.^&#42;1^

[NOTE]
====
. Ou: “satisfeitos”.
====

[[v40-5-7]]

^<<v40-5-7,7>>^ “Felizes os misericordiosos, porque serão tratados com misericórdia.

[[v40-5-8]]

^<<v40-5-8,8>>^ “Felizes os puros de coração, porque verão a Deus.

[[v40-5-9]]

^<<v40-5-9,9>>^ “Felizes os pacificadores,^&#42;1^ porque serão chamados filhos de Deus.

[NOTE]
====
. Ou: “pacíficos”.
====

[[v40-5-10]]

^<<v40-5-10,10>>^ “Felizes os que são perseguidos por causa da justiça, porque a eles pertence o Reino dos céus.

[[v40-5-11]]

^<<v40-5-11,11>>^ “Felizes são vocês quando as pessoas os insultam e perseguem, e, mentindo, dizem todo tipo de coisas más contra vocês, por minha causa.

[[v40-5-12]]

^<<v40-5-12,12>>^ Alegrem-se e fiquem cheios de alegria, porque a sua recompensa é grande nos céus; pois assim perseguiram os profetas antes de vocês.

[[v40-5-13]]

^<<v40-5-13,13>>^ “Vocês são o sal da terra. Mas, se o sal perder a sua força, como sua salinidade será restaurada? Não presta mais para nada, senão para ser jogado fora, a fim de ser pisado pelos homens.

[[v40-5-14]]

^<<v40-5-14,14>>^ “Vocês são a luz do mundo. Não se pode esconder uma cidade situada sobre um monte.

[[v40-5-15]]

^<<v40-5-15,15>>^ As pessoas acendem uma lâmpada e a colocam, não debaixo de um cesto,^&#42;1^ mas em cima de um suporte, e ela brilha sobre todos na casa.

[NOTE]
====
. Ou: “cesto de medida”.
====

[[v40-5-16]]

^<<v40-5-16,16>>^ Do mesmo modo, deixem brilhar sua luz perante os homens, para que vejam suas boas obras e deem glória ao seu Pai, que está nos céus.

[[v40-5-17]]

^<<v40-5-17,17>>^ “Não pensem que vim destruir a Lei ou os Profetas. Não vim destruir, mas cumprir.

[[v40-5-18]]

^<<v40-5-18,18>>^ Eu lhes garanto que será mais fácil passarem céu e terra do que passar a menor letra ou um só traço de uma letra da Lei, sem que tudo se cumpra.

[[v40-5-19]]

^<<v40-5-19,19>>^ Portanto, quem violar o menor desses mandamentos e ensinar outros a fazer o mesmo será chamado menor com relação ao Reino dos céus. Mas quem os cumprir e ensinar será chamado grande com relação ao Reino dos céus.

[[v40-5-20]]

^<<v40-5-20,20>>^ Pois eu lhes digo que, se a sua justiça não for maior do que a dos escribas e dos fariseus, de modo algum vocês entrarão no Reino dos céus.

[[v40-5-21]]

^<<v40-5-21,21>>^ “Vocês ouviram que se disse aos dos tempos antigos: ‘Não assassine, e quem cometer um assassinato prestará contas ao tribunal de justiça.’

[[v40-5-22]]

^<<v40-5-22,22>>^ No entanto, eu lhes digo que todo aquele que continuar irado com seu irmão terá de prestar contas ao tribunal de justiça; e quem se dirigir a seu irmão com uma palavra imprópria de desprezo terá de prestar contas ao Supremo Tribunal; ao passo que quem disser: ‘Tolo imprestável!’ estará sujeito à Geena^&#42;1^ ardente.

[NOTE]
====
. Lugar onde se queimava lixo fora de Jerusalém. Veja o Glossário, “Geena”.
====

[[v40-5-23]]

^<<v40-5-23,23>>^ “Então, se você levar a sua dádiva ao altar e ali se lembrar de que o seu irmão tem algo contra você,

[[v40-5-24]]

^<<v40-5-24,24>>^ deixe a sua dádiva ali na frente do altar e vá. Faça primeiro as pazes com o seu irmão, então volte e ofereça a sua dádiva.

[[v40-5-25]]

^<<v40-5-25,25>>^ “Resolva rapidamente as questões com seu adversário, enquanto está com ele a caminho do tribunal, para não acontecer que o adversário o entregue ao juiz, e o juiz ao oficial de justiça, e você seja lançado na prisão.

[[v40-5-26]]

^<<v40-5-26,26>>^ Eu lhe digo categoricamente: Você de modo algum sairá de lá até pagar a sua última pequena moeda.^&#42;1^

[NOTE]
====
. Lit.: “o último quadrante”. Veja Ap. B14.
====

[[v40-5-27]]

^<<v40-5-27,27>>^ “Vocês ouviram que se disse: ‘Não cometa adultério.’

[[v40-5-28]]

^<<v40-5-28,28>>^ Mas eu lhes digo que todo aquele que persiste em olhar para uma mulher, a ponto de sentir paixão por ela, já cometeu no coração adultério com ela.

[[v40-5-29]]

^<<v40-5-29,29>>^ Então, se seu olho direito o faz tropeçar, arranque-o e lance-o para longe de você. Porque é melhor que você perca um dos seus membros do que todo o seu corpo ser lançado na Geena.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-30]]

^<<v40-5-30,30>>^ Também, se a sua mão direita o faz tropeçar, corte-a e lance-a para longe de você. Porque é melhor que você perca um dos seus membros do que todo o seu corpo acabar na Geena.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-31]]

^<<v40-5-31,31>>^ “Além disso, foi dito: ‘Quem se divorcia da sua esposa dê a ela um certificado de divórcio.’

[[v40-5-32]]

^<<v40-5-32,32>>^ No entanto, eu lhes digo que todo aquele que se divorcia da sua esposa, a não ser por causa de imoralidade sexual,^&#42;1^ a expõe ao adultério, e quem se casa com uma mulher divorciada comete adultério.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v40-5-33]]

^<<v40-5-33,33>>^ “Também, vocês ouviram que se disse aos dos tempos antigos: ‘Não jure sem cumprir, mas cumpra seus votos feitos a Jeová.’^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v40-5-34]]

^<<v40-5-34,34>>^ No entanto, eu lhes digo: Não jurem de modo algum, nem pelo céu, pois é o trono de Deus;

[[v40-5-35]]

^<<v40-5-35,35>>^ nem pela terra, pois é o apoio para os pés dele; nem por Jerusalém, pois é a cidade do grande Rei.

[[v40-5-36]]

^<<v40-5-36,36>>^ Não jure pela sua própria cabeça, porque você não pode tornar branco ou preto um só fio de cabelo.

[[v40-5-37]]

^<<v40-5-37,37>>^ Deixem simplesmente que a sua palavra “sim” signifique sim, e o seu “não”, não; pois tudo o que for além disso é do Maligno.

[[v40-5-38]]

^<<v40-5-38,38>>^ “Vocês ouviram que se disse: ‘Olho por olho e dente por dente.’

[[v40-5-39]]

^<<v40-5-39,39>>^ No entanto, eu lhes digo: Não resistam àquele que é mau, mas a quem lhe der uma bofetada na face direita, ofereça também a outra.

[[v40-5-40]]

^<<v40-5-40,40>>^ E, se alguém quiser levá-lo perante o tribunal para tomar a sua túnica, deixe-o ficar também com a sua capa.

[[v40-5-41]]

^<<v40-5-41,41>>^ E, se alguém em autoridade o obrigar a prestar serviço por uma milha,^&#42;1^ vá com ele duas milhas.

[NOTE]
====
. Veja o Glossário.
====

[[v40-5-42]]

^<<v40-5-42,42>>^ Dê a quem lhe pede e não se desvie de quem deseja tomar emprestado^&#42;1^ de você.

[NOTE]
====
. Isto é, tomar emprestado sem juros.
====

[[v40-5-43]]

^<<v40-5-43,43>>^ “Vocês ouviram que se disse: ‘Ame o seu próximo e odeie o seu inimigo.’

[[v40-5-44]]

^<<v40-5-44,44>>^ No entanto, eu lhes digo: Continuem a amar os seus inimigos e a orar pelos que perseguem vocês,

[[v40-5-45]]

^<<v40-5-45,45>>^ para que vocês mostrem ser filhos de seu Pai, que está nos céus, visto que ele faz o seu sol se levantar sobre os maus e sobre os bons, e faz chover sobre os justos e sobre os injustos.

[[v40-5-46]]

^<<v40-5-46,46>>^ Pois, se vocês amarem aos que os amam, que recompensa terão? Não fazem a mesma coisa os cobradores de impostos?

[[v40-5-47]]

^<<v40-5-47,47>>^ E, se cumprimentarem somente os seus irmãos, o que fazem de extraordinário? Não fazem a mesma coisa as pessoas das nações?

[[v40-5-48]]

^<<v40-5-48,48>>^ Portanto, sejam perfeitos,^&#42;1^ assim como o seu Pai celestial é perfeito.

[NOTE]
====
. Ou: “completos”.
====

'''

xref:040-mateus/040-mateus-004.adoc#v40-4-0[&#60; Capítulo Anterior] | <<v40-5-0,Topo>> | xref:040-mateus/040-mateus-006.adoc#v40-6-0[Próximo Capítulo &#62;]