include::./index.adoc[]

[[v40-18-0]]
=== Segundo Mateus, 18
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v40-18-1]]

^<<v40-18-1,1>>^ Naquela hora, os discípulos se aproximaram de Jesus e perguntaram: “Quem é realmente o maior no Reino dos céus?”

[[v40-18-2]]

^<<v40-18-2,2>>^ Então, ele chamou uma criancinha, colocou-a no meio deles

[[v40-18-3]]

^<<v40-18-3,3>>^ e disse: “Digo-lhes a verdade: A menos que vocês deem meia-volta^&#42;1^ e se tornem como criancinhas, de modo algum entrarão no Reino dos céus.

[NOTE]
====
. Ou: “mudem”.
====

[[v40-18-4]]

^<<v40-18-4,4>>^ Por isso, quem se humilha, como esta criancinha, é aquele que é o maior no Reino dos céus;

[[v40-18-5]]

^<<v40-18-5,5>>^ e quem recebe em meu nome uma criancinha como esta, recebe também a mim.

[[v40-18-6]]

^<<v40-18-6,6>>^ Mas quem fizer tropeçar um destes pequenos que têm fé em mim, seria melhor para ele que pendurassem no seu pescoço uma pedra de moinho daquelas que o jumento faz girar, e que fosse afundado no alto-mar.

[[v40-18-7]]

^<<v40-18-7,7>>^ “Ai do mundo por causa das suas pedras de tropeço! Claro, é inevitável que venham as pedras de tropeço, mas ai do homem por meio de quem vem a pedra de tropeço!

[[v40-18-8]]

^<<v40-18-8,8>>^ Então, se a sua mão ou o seu pé faz você tropeçar, corte-o e lance-o para longe. É melhor para você entrar na vida aleijado ou manco do que ser lançado com as duas mãos ou os dois pés no fogo eterno.

[[v40-18-9]]

^<<v40-18-9,9>>^ Também, se o seu olho o faz tropeçar, arranque-o e lance-o para longe de você. É melhor para você entrar na vida com um olho só do que ser lançado com os dois olhos na Geena^&#42;1^ ardente.

[NOTE]
====
. Veja o Glossário.
====

[[v40-18-10]]

^<<v40-18-10,10>>^ Tomem cuidado para não desprezar um destes pequenos, pois eu lhes digo que os anjos deles no céu estão sempre vendo a face do meu Pai, que está no céu.

[[v40-18-11]]

^<<v40-18-11,11>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v40-18-12]]

^<<v40-18-12,12>>^ “O que vocês acham? Se um homem tem 100 ovelhas e uma delas se perde, não deixará ele as 99 nos montes e irá à procura daquela que se perdeu?

[[v40-18-13]]

^<<v40-18-13,13>>^ E, se a encontrar, certamente lhes digo que se alegrará mais com ela do que com as 99 que não se perderam.

[[v40-18-14]]

^<<v40-18-14,14>>^ Do mesmo modo, não é o desejo do meu Pai,^&#42;1^ que está no céu, que se perca nem mesmo um destes pequenos.

[NOTE]
====
. Ou, possivelmente: “do Pai de vocês”.
====

[[v40-18-15]]

^<<v40-18-15,15>>^ “Além disso, se o seu irmão cometer um pecado, vá mostrar-lhe o seu erro,^&#42;1^ somente você e ele. Se ele o escutar, você ganhou o seu irmão.

[NOTE]
====
. Lit.: “repreenda-o”.
====

[[v40-18-16]]

^<<v40-18-16,16>>^ Mas, se não o escutar, leve com você mais um ou dois, para que, com base no depoimento^&#42;1^ de duas ou três testemunhas, toda questão seja estabelecida.

[NOTE]
====
. Lit.: “na boca”.
====

[[v40-18-17]]

^<<v40-18-17,17>>^ Se ele não os escutar, fale à congregação. Se não escutar nem mesmo a congregação, seja ele para você apenas como homem das nações e como cobrador de impostos.

[[v40-18-18]]

^<<v40-18-18,18>>^ “Digo-lhes a verdade: Tudo o que vocês amarrarem na terra já terá sido amarrado no céu, e tudo o que soltarem na terra já terá sido solto no céu.

[[v40-18-19]]

^<<v40-18-19,19>>^ Também lhes digo esta verdade: Se dois de vocês, na terra, concordarem em qualquer coisa importante que pedirem, ela lhes será concedida pelo meu Pai, que está no céu.

[[v40-18-20]]

^<<v40-18-20,20>>^ Pois, onde há dois ou três reunidos em meu nome, ali estou eu no meio deles.”

[[v40-18-21]]

^<<v40-18-21,21>>^ Pedro se aproximou então e lhe perguntou: “Senhor, quantas vezes devo perdoar o meu irmão se ele pecar contra mim? Até sete vezes?”

[[v40-18-22]]

^<<v40-18-22,22>>^ Jesus respondeu: “Eu não lhe digo até sete vezes, mas até 77 vezes.

[[v40-18-23]]

^<<v40-18-23,23>>^ “É por isso que o Reino dos céus pode ser comparado a um rei que queria ajustar contas com os seus escravos.

[[v40-18-24]]

^<<v40-18-24,24>>^ Quando começou a ajustá-las, trouxeram-lhe um homem que lhe devia 10.000 talentos.^&#42;1^

[NOTE]
====
. O valor de 10.000 talentos de prata equivalia a 60.000.000 de denários. Veja Ap. B14.
====

[[v40-18-25]]

^<<v40-18-25,25>>^ Mas, visto que este não tinha meios para pagar, seu senhor mandou que ele, a esposa dele, os filhos dele e tudo o que tivesse fossem vendidos e fosse feito o pagamento.

[[v40-18-26]]

^<<v40-18-26,26>>^ Então o escravo se prostrou e lhe prestou homenagem,^&#42;1^ dizendo: ‘Tenha paciência comigo, e eu lhe pagarei tudo.’

[NOTE]
====
. Ou: “e se curvou diante dele”.
====

[[v40-18-27]]

^<<v40-18-27,27>>^ Com pena dele, o senhor daquele escravo o deixou ir e cancelou a sua dívida.

[[v40-18-28]]

^<<v40-18-28,28>>^ Mas aquele escravo saiu e encontrou um dos seus coescravos, que lhe devia 100 denários.^&#42;1^ Ele o agarrou e começou a estrangulá-lo, dizendo: ‘Pague o que você deve.’

[NOTE]
====
. Veja Ap. B14.
====

[[v40-18-29]]

^<<v40-18-29,29>>^ Então seu coescravo se prostrou e lhe suplicou: ‘Tenha paciência comigo, e eu lhe pagarei.’

[[v40-18-30]]

^<<v40-18-30,30>>^ No entanto, ele não quis. Em vez disso, mandou lançá-lo na prisão, até que pagasse o que devia.

[[v40-18-31]]

^<<v40-18-31,31>>^ Quando seus coescravos viram o que tinha acontecido, ficaram muito tristes e foram contar ao seu senhor tudo o que tinha acontecido.

[[v40-18-32]]

^<<v40-18-32,32>>^ O senhor dele o convocou então e lhe disse: ‘Escravo mau, eu lhe cancelei toda aquela dívida quando você me suplicou.

[[v40-18-33]]

^<<v40-18-33,33>>^ Não devia você também ter tido misericórdia do seu coescravo, como eu tive misericórdia de você?’

[[v40-18-34]]

^<<v40-18-34,34>>^ Com isso, seu senhor, furioso, entregou-o aos carcereiros, até que pagasse tudo o que devia.

[[v40-18-35]]

^<<v40-18-35,35>>^ Meu Pai celestial tratará vocês da mesma forma, se cada um de vocês não perdoar de coração ao seu irmão.”

'''

xref:040-mateus/040-mateus-017.adoc#v40-17-0[&#60; Capítulo Anterior] | <<v40-18-0,Topo>> | xref:040-mateus/040-mateus-019.adoc#v40-19-0[Próximo Capítulo &#62;]