include::./index.adoc[]

[[v41-4-0]]
=== Segundo Marcos, 4
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-4-1]]

^<<v41-4-1,1>>^ Ele começou novamente a ensinar à beira do mar, e uma multidão muito grande se reuniu perto dele. Então ele entrou num barco e se sentou, e ficou a certa distância da margem, mas toda a multidão estava em terra, à beira do mar.

[[v41-4-2]]

^<<v41-4-2,2>>^ E ele começou a ensinar-lhes muitas coisas com ilustrações. Ensinava-lhes dizendo:

[[v41-4-3]]

^<<v41-4-3,3>>^ “Escutem: O semeador saiu para semear.

[[v41-4-4]]

^<<v41-4-4,4>>^ Ao passo que semeava, algumas sementes caíram à beira da estrada, e vieram as aves e as comeram.

[[v41-4-5]]

^<<v41-4-5,5>>^ Outras caíram em solo rochoso, onde não havia muita terra, e brotaram imediatamente porque o solo não era profundo.

[[v41-4-6]]

^<<v41-4-6,6>>^ Mas, quando o sol se levantou, ficaram queimadas e murcharam, porque não tinham raiz.

[[v41-4-7]]

^<<v41-4-7,7>>^ Outras sementes caíram entre os espinhos, e os espinhos cresceram e as sufocaram, e elas não deram fruto.

[[v41-4-8]]

^<<v41-4-8,8>>^ Mas outras caíram em solo bom e, depois de brotar e crescer, começaram a dar fruto; e produziram 30, 60 e 100 vezes mais.”

[[v41-4-9]]

^<<v41-4-9,9>>^ Ele acrescentou então: “Quem tem ouvidos para escutar, escute.”

[[v41-4-10]]

^<<v41-4-10,10>>^ Então, quando ficou sozinho, os que estavam em volta dele vieram com os Doze e começaram a lhe perguntar sobre as ilustrações.

[[v41-4-11]]

^<<v41-4-11,11>>^ Ele lhes disse: “A vocês foi dado o segredo sagrado do Reino de Deus, mas para os de fora tudo é apresentado em ilustrações,

[[v41-4-12]]

^<<v41-4-12,12>>^ para que eles olhem, mas ainda assim não vejam, e ouçam, mas ainda assim não compreendam; e eles jamais darão meia-volta e receberão perdão.”

[[v41-4-13]]

^<<v41-4-13,13>>^ Além disso, ele lhes disse: “Vocês não compreendem essa ilustração; portanto, como entenderão todas as outras ilustrações?

[[v41-4-14]]

^<<v41-4-14,14>>^ “O semeador semeia a palavra.

[[v41-4-15]]

^<<v41-4-15,15>>^ Então, aquelas sementes à beira da estrada, onde se semeia a palavra, representam os que ouvem a palavra, mas logo vem Satanás e tira a palavra que foi semeada neles.

[[v41-4-16]]

^<<v41-4-16,16>>^ Do mesmo modo, aquelas semeadas em solo rochoso representam os que ouvem a palavra e logo a aceitam com alegria.

[[v41-4-17]]

^<<v41-4-17,17>>^ Contudo, não têm raiz em si mesmos, mas continuam por algum tempo; então, assim que surge dificuldade ou perseguição por causa da palavra, tropeçam.

[[v41-4-18]]

^<<v41-4-18,18>>^ Ainda há outras que são semeadas entre os espinhos. Essas representam os que ouvem a palavra,

[[v41-4-19]]

^<<v41-4-19,19>>^ mas as ansiedades deste mundo,^&#42;1^ o poder enganoso das riquezas e os desejos de todas as outras coisas interferem e sufocam a palavra, e ela se torna infrutífera.

[NOTE]
====
. Ou: “deste sistema de coisas; desta época”. Veja o Glossário.
====

[[v41-4-20]]

^<<v41-4-20,20>>^ Finalmente, aquelas que foram semeadas em solo bom representam os que escutam a palavra, a aceitam e dão fruto: 30, 60 e 100 vezes mais.”

[[v41-4-21]]

^<<v41-4-21,21>>^ Disse-lhes também: “Será que se pega uma lâmpada para colocá-la debaixo de um cesto^&#42;1^ ou debaixo de uma cama? Não é para colocá-la em cima de um suporte?

[NOTE]
====
. Ou: “cesto de medida”.
====

[[v41-4-22]]

^<<v41-4-22,22>>^ Pois não há nada escondido que não venha a ser exposto; nada cuidadosamente oculto que não venha à tona.

[[v41-4-23]]

^<<v41-4-23,23>>^ Escute quem tem ouvidos para escutar.”

[[v41-4-24]]

^<<v41-4-24,24>>^ Disse-lhes ainda: “Prestem atenção ao que estão ouvindo. A mesma medida com que vocês medem será usada com vocês, e mais lhes será acrescentado.

[[v41-4-25]]

^<<v41-4-25,25>>^ Pois àquele que tem, mais será dado; mas daquele que não tem, até mesmo o que tem será tirado.”

[[v41-4-26]]

^<<v41-4-26,26>>^ Assim, acrescentou: “Portanto, o Reino de Deus é como quando um homem lança sementes no solo.

[[v41-4-27]]

^<<v41-4-27,27>>^ Ele dorme à noite e se levanta de dia, e as sementes brotam e crescem alto, embora ele não saiba exatamente como.

[[v41-4-28]]

^<<v41-4-28,28>>^ O solo, por si mesmo, dá fruto aos poucos: primeiro a haste, depois a espiga, e finalmente o grão maduro na espiga.

[[v41-4-29]]

^<<v41-4-29,29>>^ Mas, assim que os grãos ficam maduros, ele passa a foice, porque chegou o tempo da colheita.”

[[v41-4-30]]

^<<v41-4-30,30>>^ E acrescentou: “A que podemos comparar o Reino de Deus, ou com que ilustração podemos explicá-lo?

[[v41-4-31]]

^<<v41-4-31,31>>^ É semelhante a um grão de mostarda que, quando é semeado no solo, é a menor de todas as sementes da terra.

[[v41-4-32]]

^<<v41-4-32,32>>^ Mas, depois de semeado, cresce e se torna maior do que todas as outras hortaliças e produz grandes ramos, de modo que as aves do céu podem achar abrigo sob a sua sombra.”

[[v41-4-33]]

^<<v41-4-33,33>>^ Com muitas ilustrações desse tipo, ele lhes falava a palavra, até onde eram capazes de entender.

[[v41-4-34]]

^<<v41-4-34,34>>^ Realmente, nada lhes falava sem ilustração, mas explicava tudo em particular aos seus discípulos.

[[v41-4-35]]

^<<v41-4-35,35>>^ E naquele dia, ao cair a noite, ele lhes disse: “Passemos para a outra margem.”

[[v41-4-36]]

^<<v41-4-36,36>>^ Assim, depois de terem dispensado a multidão, eles o levaram, assim como estava, no barco; e havia outros barcos com ele.

[[v41-4-37]]

^<<v41-4-37,37>>^ Levantou-se então uma violenta tempestade, e as ondas se lançavam sobre o barco, de modo que o barco estava ficando inundado.

[[v41-4-38]]

^<<v41-4-38,38>>^ Mas ele estava na popa, dormindo sobre o travesseiro.^&#42;1^ Assim, eles o acordaram e lhe disseram: “Instrutor, o senhor não se importa que estejamos prestes a morrer?”

[NOTE]
====
. Ou: “a almofada”.
====

[[v41-4-39]]

^<<v41-4-39,39>>^ Com isso ele se levantou, censurou o vento e disse ao mar: “Silêncio! Cale-se!” E o vento parou, e houve uma grande calmaria.

[[v41-4-40]]

^<<v41-4-40,40>>^ Então ele lhes disse: “Por que vocês estão com tanto medo?^&#42;1^ Ainda não têm nenhuma fé?”

[NOTE]
====
. Ou: “são tão inseguros”.
====

[[v41-4-41]]

^<<v41-4-41,41>>^ Mas eles sentiram um medo incomum e disseram uns aos outros: “Quem é realmente este homem? Até mesmo o vento e o mar lhe obedecem.”

'''

xref:041-marcos/041-marcos-003.adoc#v41-3-0[&#60; Capítulo Anterior] | <<v41-4-0,Topo>> | xref:041-marcos/041-marcos-005.adoc#v41-5-0[Próximo Capítulo &#62;]