include::./index.adoc[]

[[v41-5-0]]
=== Segundo Marcos, 5
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-5-1]]

^<<v41-5-1,1>>^ Chegaram então à outra margem do mar, à região dos gerasenos.

[[v41-5-2]]

^<<v41-5-2,2>>^ E, assim que Jesus saiu do barco, um homem sob o poder de um espírito impuro saiu dentre os túmulos^&#42;1^ e foi ao seu encontro.

[NOTE]
====
. Ou: “túmulos memoriais”.
====

[[v41-5-3]]

^<<v41-5-3,3>>^ Ele vivia entre os túmulos, e, até aquele tempo, absolutamente ninguém havia sido capaz de mantê-lo preso, nem mesmo com uma corrente.

[[v41-5-4]]

^<<v41-5-4,4>>^ Muitas vezes ele tinha sido preso com correntes nos pés e nas mãos, mas ele quebrava as correntes das mãos e despedaçava as dos pés; e ninguém tinha força para dominá-lo.

[[v41-5-5]]

^<<v41-5-5,5>>^ E, incessantemente, noite e dia, ele gritava nos túmulos e nos montes, e se cortava com pedras.

[[v41-5-6]]

^<<v41-5-6,6>>^ Mas, ao ver Jesus a certa distância, correu e se curvou diante dele.

[[v41-5-7]]

^<<v41-5-7,7>>^ Então gritou, em voz bem alta: “O que você quer comigo,^&#42;1^ Jesus, Filho do Deus Altíssimo? Jure por Deus que não me atormentará.”

[NOTE]
====
. Ou: “O que eu tenho a ver com você”.
====

[[v41-5-8]]

^<<v41-5-8,8>>^ Pois Jesus havia lhe dito: “Saia do homem, espírito impuro!”

[[v41-5-9]]

^<<v41-5-9,9>>^ Mas Jesus lhe perguntou: “Qual é o seu nome?” E ele respondeu: “Meu nome é Legião, porque há muitos de nós.”

[[v41-5-10]]

^<<v41-5-10,10>>^ E suplicava a Jesus que não enviasse os espíritos para fora daquela região.

[[v41-5-11]]

^<<v41-5-11,11>>^ Havia então uma grande manada de porcos pastando no monte.

[[v41-5-12]]

^<<v41-5-12,12>>^ Por isso os espíritos lhe suplicaram: “Mande-nos para os porcos, para que entremos neles.”

[[v41-5-13]]

^<<v41-5-13,13>>^ E ele lhes deu permissão. Assim, os espíritos impuros saíram e entraram nos porcos; e a manada se jogou despenhadeiro^&#42;1^ abaixo, para dentro do mar, cerca de 2.000 deles, e se afogaram no mar.

[NOTE]
====
. Ou: “encosta íngreme”.
====

[[v41-5-14]]

^<<v41-5-14,14>>^ Mas os que cuidavam dos porcos fugiram e contaram isso na cidade e na zona rural, e as pessoas foram ver o que tinha acontecido.

[[v41-5-15]]

^<<v41-5-15,15>>^ Assim, aproximaram-se de Jesus e viram o possesso de demônios, que havia tido a legião, sentado, vestido e em perfeito juízo; e ficaram com medo.

[[v41-5-16]]

^<<v41-5-16,16>>^ Também, os que tinham visto tudo aquilo lhes contaram o que tinha acontecido com o homem possesso de demônios e com os porcos.

[[v41-5-17]]

^<<v41-5-17,17>>^ Assim, começaram a suplicar a Jesus que saísse daquela região.

[[v41-5-18]]

^<<v41-5-18,18>>^ Então, quando ele estava entrando no barco, o homem que tinha estado possesso de demônios suplicou que o deixasse ir com ele.

[[v41-5-19]]

^<<v41-5-19,19>>^ No entanto, ele não deixou, mas disse-lhe: “Vá para casa, para seus parentes, e conte-lhes tudo o que Jeová^&#42;1^ fez por você e a misericórdia que ele lhe demonstrou.”

[NOTE]
====
. Veja Ap. A5.
====

[[v41-5-20]]

^<<v41-5-20,20>>^ O homem foi embora e começou a proclamar em Decápolis^&#42;1^ tudo o que Jesus havia feito por ele; e todos ficavam admirados.

[NOTE]
====
. Ou: “na região das Dez Cidades”.
====

[[v41-5-21]]

^<<v41-5-21,21>>^ Depois de Jesus ter passado novamente, no barco, para a margem oposta, ajuntou-se a ele uma grande multidão, e ele estava à beira do mar.

[[v41-5-22]]

^<<v41-5-22,22>>^ Chegou então um dos presidentes da sinagoga, chamado Jairo, e, ao vê-lo, se prostrou aos seus pés.

[[v41-5-23]]

^<<v41-5-23,23>>^ Ele lhe suplicou muitas vezes: “Minha filhinha está gravemente doente.^&#42;1^ Por favor, venha e ponha as mãos sobre ela, para que possa ficar boa e viver.”

[NOTE]
====
. Ou: “está morrendo”.
====

[[v41-5-24]]

^<<v41-5-24,24>>^ Assim, Jesus foi com ele, e uma grande multidão o seguia e apertava.

[[v41-5-25]]

^<<v41-5-25,25>>^ E havia uma mulher que por 12 anos sofria de um fluxo de sangue.

[[v41-5-26]]

^<<v41-5-26,26>>^ Ela havia sofrido muito^&#42;1^ às mãos de muitos médicos, e tinha gastado todos os seus recursos, sem ter melhorado, mas, em vez disso, tinha ficado pior.

[NOTE]
====
. Ou: “tinha sido submetida a muitas dores”.
====

[[v41-5-27]]

^<<v41-5-27,27>>^ Tendo ouvido falar de Jesus, ela se aproximou por trás dele, na multidão, e tocou na sua roupa,

[[v41-5-28]]

^<<v41-5-28,28>>^ pois dizia: “Se eu apenas tocar na sua roupa, ficarei boa.”

[[v41-5-29]]

^<<v41-5-29,29>>^ E o seu fluxo de sangue secou imediatamente, e ela sentiu no corpo que tinha sido curada daquela doença aflitiva.

[[v41-5-30]]

^<<v41-5-30,30>>^ Imediatamente, Jesus percebeu que havia saído poder dele, e ele se virou na multidão e perguntou: “Quem tocou na minha roupa?”

[[v41-5-31]]

^<<v41-5-31,31>>^ Seus discípulos lhe disseram: “O senhor está vendo que a multidão o aperta, e ainda pergunta: ‘Quem me tocou?’”

[[v41-5-32]]

^<<v41-5-32,32>>^ Mas ele estava olhando em volta para ver quem tinha feito isso.

[[v41-5-33]]

^<<v41-5-33,33>>^ A mulher, tremendo de medo, sabendo o que tinha lhe acontecido, se aproximou e se prostrou diante dele, e lhe disse toda a verdade.

[[v41-5-34]]

^<<v41-5-34,34>>^ Ele disse a ela: “Filha, a sua fé fez você ficar boa. Vá em paz e fique curada da sua doença aflitiva.”

[[v41-5-35]]

^<<v41-5-35,35>>^ Enquanto ele ainda falava, chegaram alguns homens da casa do presidente da sinagoga e disseram: “Sua filha morreu! Por que incomodar mais o Instrutor?”

[[v41-5-36]]

^<<v41-5-36,36>>^ Mas Jesus ouviu as palavras deles e disse ao presidente da sinagoga: “Não tenha medo,^&#42;1^ apenas exerça fé.”

[NOTE]
====
. Ou: “Pare de ter medo”.
====

[[v41-5-37]]

^<<v41-5-37,37>>^ Então não deixou ninguém acompanhá-lo, a não ser Pedro, Tiago e João, irmão de Tiago.

[[v41-5-38]]

^<<v41-5-38,38>>^ Assim, chegaram à casa do presidente da sinagoga, e ele viu o alvoroço e os que choravam e lamentavam em alta voz.

[[v41-5-39]]

^<<v41-5-39,39>>^ Depois de entrar, disse-lhes: “Por que vocês estão chorando e fazendo esse alvoroço? A menina não morreu; ela está dormindo.”

[[v41-5-40]]

^<<v41-5-40,40>>^ Em vista disso, começaram a rir dele com desprezo. Mas, depois de mandar que todos saíssem, ele levou consigo o pai e a mãe da menina e os que estavam com ele, e entrou onde a menina estava.

[[v41-5-41]]

^<<v41-5-41,41>>^ Então, pegando a mão da menina, disse-lhe: “Talita cumi”, que traduzido significa: “Menina, digo-lhe: Levante-se!”

[[v41-5-42]]

^<<v41-5-42,42>>^ E a menina se levantou imediatamente e começou a andar. (Ela tinha 12 anos de idade.) Com isso, eles não conseguiram se conter de tanta alegria.

[[v41-5-43]]

^<<v41-5-43,43>>^ Mas ele lhes ordenou vez após vez^&#42;1^ que não deixassem ninguém saber disso, e mandou que dessem a ela algo para comer.

[NOTE]
====
. Ou: “com firmeza”.
====

'''

xref:041-marcos/041-marcos-004.adoc#v41-4-0[&#60; Capítulo Anterior] | <<v41-5-0,Topo>> | xref:041-marcos/041-marcos-006.adoc#v41-6-0[Próximo Capítulo &#62;]