include::./index.adoc[]

[[v41-11-0]]
=== Segundo Marcos, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-11-1]]

^<<v41-11-1,1>>^ Então, quando estavam chegando perto de Jerusalém, de Betfagé e de Betânia, no monte das Oliveiras, ele enviou dois dos seus discípulos

[[v41-11-2]]

^<<v41-11-2,2>>^ e lhes disse: “Vão à aldeia que está ao alcance da vista e, assim que entrarem lá, acharão um jumentinho amarrado, no qual ninguém ainda montou. Desamarrem-no e tragam-no para cá.

[[v41-11-3]]

^<<v41-11-3,3>>^ E, se alguém lhes perguntar: ‘Por que estão fazendo isso?’, digam: ‘O Senhor precisa dele, e logo o mandará de volta para cá.’”

[[v41-11-4]]

^<<v41-11-4,4>>^ Assim partiram e acharam o jumentinho amarrado junto a uma porta, do lado de fora, na rua, e o desamarraram.

[[v41-11-5]]

^<<v41-11-5,5>>^ Mas alguns dos que estavam ali perguntaram a eles: “O que vocês estão fazendo, desamarrando o jumentinho?”

[[v41-11-6]]

^<<v41-11-6,6>>^ Disseram a eles o que Jesus tinha dito, e eles os deixaram ir.

[[v41-11-7]]

^<<v41-11-7,7>>^ Trouxeram então a Jesus o jumentinho e colocaram sobre este suas capas, e ele se sentou nele.

[[v41-11-8]]

^<<v41-11-8,8>>^ Também, muitos estenderam suas capas na estrada, mas outros cortaram ramos dos campos.

[[v41-11-9]]

^<<v41-11-9,9>>^ E os que iam na frente e os que vinham atrás gritavam: “Salva, rogamos! Bendito é aquele que vem em nome de Jeová!^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v41-11-10]]

^<<v41-11-10,10>>^ Bendito é o Reino que virá, do nosso pai Davi! Salva, rogamos, nas maiores alturas!”

[[v41-11-11]]

^<<v41-11-11,11>>^ E ele entrou em Jerusalém, foi ao templo e olhou tudo em volta, mas, visto que já estava tarde, saiu com os Doze para Betânia.

[[v41-11-12]]

^<<v41-11-12,12>>^ No dia seguinte, quando estavam saindo de Betânia, ele sentiu fome.

[[v41-11-13]]

^<<v41-11-13,13>>^ De certa distância viu uma figueira que tinha folhas e foi ver se achava algo nela. Mas, ao chegar perto dela, não encontrou nada, exceto folhas, pois não era a estação dos figos.

[[v41-11-14]]

^<<v41-11-14,14>>^ Então ele lhe disse: “Nunca mais ninguém coma do seu fruto.” E os seus discípulos estavam escutando.

[[v41-11-15]]

^<<v41-11-15,15>>^ Chegaram então a Jerusalém. Ali ele entrou no templo e começou a expulsar os que vendiam e compravam no templo, e derrubou as mesas dos cambistas e as cadeiras dos que vendiam pombas;

[[v41-11-16]]

^<<v41-11-16,16>>^ e não deixava ninguém carregar nenhum utensílio através do templo.

[[v41-11-17]]

^<<v41-11-17,17>>^ Ele ensinava, dizendo-lhes: “Não está escrito: ‘Minha casa será chamada casa de oração para todas as nações’? Mas vocês fizeram dela um abrigo^&#42;1^ de ladrões.”

[NOTE]
====
. Ou: “covil”.
====

[[v41-11-18]]

^<<v41-11-18,18>>^ Os principais sacerdotes e os escribas ouviram isso, e começaram a procurar um meio de matá-lo, pois tinham medo dele, porque toda a multidão estava maravilhada com o seu ensino.

[[v41-11-19]]

^<<v41-11-19,19>>^ Quando ficou tarde no dia, saíram da cidade.

[[v41-11-20]]

^<<v41-11-20,20>>^ Mas, de manhã cedo, quando estavam passando pela figueira, viram que ela estava seca desde as raízes.

[[v41-11-21]]

^<<v41-11-21,21>>^ Pedro se lembrou e lhe disse: “Rabi, veja! A figueira que o senhor amaldiçoou secou.”

[[v41-11-22]]

^<<v41-11-22,22>>^ Jesus lhe disse em resposta: “Tenham fé em Deus.

[[v41-11-23]]

^<<v41-11-23,23>>^ Eu lhes digo a verdade: Quem disser a este monte: ‘Levante-se e jogue-se no mar’, e não duvidar no coração, mas tiver fé em que aquilo que disser vai acontecer, assim acontecerá.

[[v41-11-24]]

^<<v41-11-24,24>>^ É por isso que lhes digo: Todas as coisas que vocês pedirem em oração, tenham fé em que já as receberam, e as terão.

[[v41-11-25]]

^<<v41-11-25,25>>^ E, quando vocês estiverem em pé, orando, perdoem o que tiverem contra alguém, para que o seu Pai, que está nos céus, também perdoe as falhas de vocês.”

[[v41-11-26]]

^<<v41-11-26,26>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v41-11-27]]

^<<v41-11-27,27>>^ Chegaram novamente a Jerusalém. E enquanto ele andava pelo templo, os principais sacerdotes, os escribas e os anciãos vieram

[[v41-11-28]]

^<<v41-11-28,28>>^ e lhe perguntaram: “Com que autoridade você faz essas coisas? E quem lhe deu autoridade para fazer essas coisas?”

[[v41-11-29]]

^<<v41-11-29,29>>^ Jesus lhes disse: “Eu lhes farei uma pergunta. Respondam-me, e eu lhes direi com que autoridade faço essas coisas.

[[v41-11-30]]

^<<v41-11-30,30>>^ O batismo de João era do céu ou dos homens?^&#42;1^ Respondam-me.”

[NOTE]
====
. Ou: “de origem humana”.
====

[[v41-11-31]]

^<<v41-11-31,31>>^ Então eles começaram a raciocinar entre si, dizendo: “Se dissermos: ‘Do céu’, ele dirá: ‘Então, por que vocês não acreditaram nele?’

[[v41-11-32]]

^<<v41-11-32,32>>^ Mas nos atrevemos a dizer: ‘Dos homens’?” Eles tinham medo da multidão, pois todos achavam que João realmente tinha sido um profeta.

[[v41-11-33]]

^<<v41-11-33,33>>^ Assim, responderam a Jesus: “Não sabemos.” Jesus lhes disse: “Então eu também não lhes digo com que autoridade faço essas coisas.”

'''

xref:041-marcos/041-marcos-010.adoc#v41-10-0[&#60; Capítulo Anterior] | <<v41-11-0,Topo>> | xref:041-marcos/041-marcos-012.adoc#v41-12-0[Próximo Capítulo &#62;]