include::./index.adoc[]

[[v41-2-0]]
=== Segundo Marcos, 2
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-2-1]]

^<<v41-2-1,1>>^ No entanto, depois de alguns dias, ele entrou novamente em Cafarnaum, e a notícia de que ele estava em casa se espalhou.

[[v41-2-2]]

^<<v41-2-2,2>>^ Então tantas pessoas se ajuntaram que não havia mais lugar, nem mesmo perto da porta, e ele começou a lhes falar a palavra.

[[v41-2-3]]

^<<v41-2-3,3>>^ E lhe trouxeram um paralítico, carregado por quatro homens.

[[v41-2-4]]

^<<v41-2-4,4>>^ Mas eles não podiam levá-lo diretamente a Jesus por causa da multidão; assim, removeram o telhado acima de onde Jesus estava e, depois de fazer uma abertura, baixaram a maca em que o paralítico estava deitado.

[[v41-2-5]]

^<<v41-2-5,5>>^ Quando Jesus viu a fé que tinham, disse ao paralítico: “Filho, seus pecados estão perdoados.”

[[v41-2-6]]

^<<v41-2-6,6>>^ Porém, alguns escribas estavam ali sentados e raciocinavam no coração:

[[v41-2-7]]

^<<v41-2-7,7>>^ “Por que este homem fala dessa maneira? Ele está blasfemando. Quem pode perdoar pecados a não ser um só, Deus?”

[[v41-2-8]]

^<<v41-2-8,8>>^ Mas Jesus imediatamente discerniu em seu espírito que estavam raciocinando desse modo entre eles e lhes disse: “Por que vocês estão raciocinando essas coisas no coração?

[[v41-2-9]]

^<<v41-2-9,9>>^ O que é mais fácil dizer ao paralítico: ‘Seus pecados estão perdoados’, ou: ‘Levante-se, apanhe a sua maca e ande’?

[[v41-2-10]]

^<<v41-2-10,10>>^ Mas, a fim de que vocês saibam que o Filho do Homem tem autoridade para perdoar pecados na terra . . .”, ele disse ao paralítico:

[[v41-2-11]]

^<<v41-2-11,11>>^ “Eu lhe digo: Levante-se, apanhe a sua maca e vá para casa.”

[[v41-2-12]]

^<<v41-2-12,12>>^ Com isso, ele se levantou, apanhou imediatamente a sua maca e saiu andando na frente de todos. Assim, todos ficaram maravilhados e glorificaram a Deus, dizendo: “Nunca vimos nada igual.”

[[v41-2-13]]

^<<v41-2-13,13>>^ Novamente, ele foi para a beira do mar; toda a multidão ia ao seu encontro, e ele começou a ensiná-los.

[[v41-2-14]]

^<<v41-2-14,14>>^ Enquanto caminhava, ele viu Levi, filho de Alfeu, sentado na coletoria, e lhe disse: “Seja meu seguidor.” Então ele se levantou e o seguiu.

[[v41-2-15]]

^<<v41-2-15,15>>^ Mais tarde, Jesus estava comendo^&#42;1^ na casa de Levi, e muitos cobradores de impostos e pecadores estavam comendo^&#42;2^ com Jesus e seus discípulos, pois muitos deles o seguiam.

[NOTE]
====
. Ou: “recostado à mesa”.
. Ou: “recostados à mesa”.
====

[[v41-2-16]]

^<<v41-2-16,16>>^ Mas, quando os escribas dos fariseus viram que ele comia com os pecadores e os cobradores de impostos, perguntaram aos discípulos: “Ele come com cobradores de impostos e pecadores?”

[[v41-2-17]]

^<<v41-2-17,17>>^ Ao ouvir isso, Jesus lhes disse: “Os que têm saúde não precisam de médico, mas sim os doentes. Eu não vim chamar os justos, mas os pecadores.”

[[v41-2-18]]

^<<v41-2-18,18>>^ Os discípulos de João e os fariseus praticavam o jejum. Assim, aproximaram-se de Jesus e lhe perguntaram: “Por que os discípulos de João e os discípulos dos fariseus praticam o jejum, mas os seus discípulos não praticam o jejum?”

[[v41-2-19]]

^<<v41-2-19,19>>^ Então Jesus lhes disse: “Será que os amigos do noivo têm motivo para jejuar enquanto o noivo está com eles? Enquanto eles têm o noivo consigo, não podem jejuar.

[[v41-2-20]]

^<<v41-2-20,20>>^ Mas virão dias em que o noivo será tirado deles, e então, naquele dia, jejuarão.

[[v41-2-21]]

^<<v41-2-21,21>>^ Ninguém costura um remendo de pano novo^&#42;1^ numa roupa velha. Se fizer isso, o remendo de pano novo repuxará a roupa velha, e o rasgão ficará pior.

[NOTE]
====
. Ou: “pano não pré-encolhido”.
====

[[v41-2-22]]

^<<v41-2-22,22>>^ Também, ninguém põe vinho novo em odres velhos. Se fizer isso, o vinho arrebentará os odres, e tanto o vinho como os odres serão perdidos. Mas põe-se vinho novo em odres novos.”

[[v41-2-23]]

^<<v41-2-23,23>>^ Ele estava passando pelos campos de cereais no sábado, e seus discípulos começaram a arrancar espigas enquanto caminhavam.

[[v41-2-24]]

^<<v41-2-24,24>>^ De modo que os fariseus lhe disseram: “Veja! Por que eles estão fazendo o que não é permitido no sábado?”

[[v41-2-25]]

^<<v41-2-25,25>>^ Mas ele lhes disse: “Vocês nunca leram o que Davi fez numa situação de necessidade, quando ele e seus homens ficaram com fome?

[[v41-2-26]]

^<<v41-2-26,26>>^ Como, no relato sobre Abiatar, o principal sacerdote, ele entrou na casa de Deus e comeu os pães da apresentação,^&#42;1^ os quais a ninguém é permitido comer, a não ser aos sacerdotes, e deu também deles aos homens que estavam com ele?”

[NOTE]
====
. Ou: “proposição”.
====

[[v41-2-27]]

^<<v41-2-27,27>>^ E acrescentou: “O sábado veio à existência por causa do homem, e não o homem por causa do sábado.

[[v41-2-28]]

^<<v41-2-28,28>>^ Portanto, o Filho do Homem é Senhor até mesmo do sábado.”

'''

xref:041-marcos/041-marcos-001.adoc#v41-1-0[&#60; Capítulo Anterior] | <<v41-2-0,Topo>> | xref:041-marcos/041-marcos-003.adoc#v41-3-0[Próximo Capítulo &#62;]