include::./index.adoc[]

[[v41-6-0]]
=== Segundo Marcos, 6
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-6-1]]

^<<v41-6-1,1>>^ Ele partiu dali e entrou na sua própria cidade,^&#42;1^ e seus discípulos o seguiram.

[NOTE]
====
. Ou: “no seu próprio território”.
====

[[v41-6-2]]

^<<v41-6-2,2>>^ Quando chegou o sábado, ele começou a ensinar na sinagoga, e a maioria dos que o ouviram ficaram maravilhados e disseram: “Onde este homem obteve essas coisas? Por que foi dada essa sabedoria a ele, e por que essas obras poderosas são realizadas pelas suas mãos?

[[v41-6-3]]

^<<v41-6-3,3>>^ Não é este o carpinteiro, filho de Maria e irmão de Tiago, José, Judas e Simão? E não estão as suas irmãs aqui conosco?” Assim, começaram a tropeçar por causa dele.

[[v41-6-4]]

^<<v41-6-4,4>>^ Mas Jesus lhes disse: “Um profeta não fica sem honra a não ser na sua própria terra, entre os seus parentes e na sua própria casa.”

[[v41-6-5]]

^<<v41-6-5,5>>^ E não pôde fazer nenhuma obra poderosa ali, a não ser pôr as mãos sobre alguns doentes e curá-los.

[[v41-6-6]]

^<<v41-6-6,6>>^ Realmente, admirou-se com a sua falta de fé. E percorreu todas as aldeias nas redondezas,^&#42;1^ ensinando.

[NOTE]
====
. Ou: “percorreu as aldeias num circuito”.
====

[[v41-6-7]]

^<<v41-6-7,7>>^ Ele convocou então os Doze e começou a enviá-los de dois em dois, e lhes deu autoridade sobre os espíritos impuros.

[[v41-6-8]]

^<<v41-6-8,8>>^ Também lhes deu ordens para não levarem nada para a viagem, a não ser um bastão — nem pão, nem bolsa de provisões, nem dinheiro^&#42;1^ no cinto —,

[NOTE]
====
. Lit.: “cobre”.
====

[[v41-6-9]]

^<<v41-6-9,9>>^ mas ordenou que eles calçassem sandálias e que não levassem roupa extra.^&#42;1^

[NOTE]
====
. Lit.: “vestissem duas túnicas”.
====

[[v41-6-10]]

^<<v41-6-10,10>>^ Além disso, ele lhes disse: “Em qualquer casa em que entrarem, fiquem ali até saírem daquele lugar.

[[v41-6-11]]

^<<v41-6-11,11>>^ E qualquer lugar que não os receber nem os ouvir, ao saírem dali sacudam a poeira que está nos seus pés, em testemunho para eles.”

[[v41-6-12]]

^<<v41-6-12,12>>^ Assim, partiram e pregaram que as pessoas deveriam se arrepender;

[[v41-6-13]]

^<<v41-6-13,13>>^ eles expulsavam muitos demônios, passavam azeite em muitos doentes e os curavam.

[[v41-6-14]]

^<<v41-6-14,14>>^ E o rei Herodes ouviu falar disso, pois o nome de Jesus havia se tornado bem conhecido, e as pessoas diziam: “João, o Batizador, foi levantado dentre os mortos, e é por isso que ele realiza obras poderosas.”^&#42;1^

[NOTE]
====
. Ou: “que operam nele obras poderosas”.
====

[[v41-6-15]]

^<<v41-6-15,15>>^ Mas outros diziam: “É Elias.” Ainda outros diziam: “É um profeta semelhante a um dos profetas antigos.”

[[v41-6-16]]

^<<v41-6-16,16>>^ Mas, ao ouvir isso, Herodes disse: “João, aquele que eu decapitei, foi levantado.”

[[v41-6-17]]

^<<v41-6-17,17>>^ De fato, o próprio Herodes anteriormente havia mandado prender João e o havia amarrado na prisão por causa de Herodias, esposa de Filipe, seu irmão, porque tinha se casado com ela.

[[v41-6-18]]

^<<v41-6-18,18>>^ Pois João dizia a Herodes: “Não é permitido que o senhor tenha a esposa do seu irmão.”

[[v41-6-19]]

^<<v41-6-19,19>>^ Por isso, Herodias nutria ressentimento contra ele e queria matá-lo, mas não podia.

[[v41-6-20]]

^<<v41-6-20,20>>^ Pois Herodes tinha temor de João, sabendo que era homem justo e santo, e o protegia. Sempre que o ouvia, ficava perplexo, sem saber o que fazer; contudo, ouvia-o com prazer.

[[v41-6-21]]

^<<v41-6-21,21>>^ Mas chegou um dia conveniente, quando Herodes, no seu aniversário, ofereceu um banquete aos altos funcionários, aos comandantes militares e aos homens mais importantes da Galileia.

[[v41-6-22]]

^<<v41-6-22,22>>^ E a filha de Herodias entrou e dançou, e ela agradou a Herodes e aos que comiam^&#42;1^ com ele. O rei disse à moça: “Peça-me o que quiser, e eu darei a você.”

[NOTE]
====
. Ou: “se recostavam à mesa”.
====

[[v41-6-23]]

^<<v41-6-23,23>>^ Sim, ele lhe jurou: “O que for que você me pedir, até a metade do meu reino, eu darei a você.”

[[v41-6-24]]

^<<v41-6-24,24>>^ Então ela saiu e perguntou à sua mãe: “O que devo pedir?” Ela respondeu: “A cabeça de João, o Batizador.”

[[v41-6-25]]

^<<v41-6-25,25>>^ Imediatamente, ela correu até o rei e fez o seu pedido, dizendo: “Quero que o senhor me dê sem demora, numa bandeja, a cabeça de João Batista.”

[[v41-6-26]]

^<<v41-6-26,26>>^ Embora isso o entristecesse profundamente, o rei não quis desconsiderar o pedido dela, por causa dos juramentos que tinha feito e por causa dos seus convidados.^&#42;1^

[NOTE]
====
. Ou: “dos que se recostavam à mesa”.
====

[[v41-6-27]]

^<<v41-6-27,27>>^ Assim, o rei enviou imediatamente um soldado da sua guarda com ordens para que trouxesse a cabeça de João. Então ele foi, decapitou-o na prisão

[[v41-6-28]]

^<<v41-6-28,28>>^ e trouxe a cabeça numa bandeja. Ele a deu à moça, e a moça a deu à sua mãe.

[[v41-6-29]]

^<<v41-6-29,29>>^ Quando os discípulos dele ouviram isso, foram pegar o seu corpo e o colocaram num túmulo.^&#42;1^

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v41-6-30]]

^<<v41-6-30,30>>^ Os apóstolos se reuniram em volta de Jesus e lhe contaram tudo o que tinham feito e ensinado.

[[v41-6-31]]

^<<v41-6-31,31>>^ E ele lhes disse: “Venham comigo, vamos sozinhos a um lugar isolado para descansar um pouco.” Pois havia muitos que iam e vinham, e eles não tinham folga nem para tomar uma refeição.

[[v41-6-32]]

^<<v41-6-32,32>>^ Por isso partiram no barco para um lugar isolado, para ficarem sozinhos.

[[v41-6-33]]

^<<v41-6-33,33>>^ Mas as pessoas os viram partir, e muitos ficaram sabendo disso. E afluíram para lá a pé, de todas as cidades, e chegaram primeiro que eles.

[[v41-6-34]]

^<<v41-6-34,34>>^ Pois bem, ao desembarcar, ele viu uma grande multidão e teve pena deles, porque eram como ovelhas sem pastor. E começou a lhes ensinar muitas coisas.

[[v41-6-35]]

^<<v41-6-35,35>>^ Já era tarde, e seus discípulos se aproximaram dele e disseram: “Este lugar é isolado e já é tarde.

[[v41-6-36]]

^<<v41-6-36,36>>^ Dispense-os, para que possam ir à zona rural e às aldeias ao redor comprar algo para comer.”

[[v41-6-37]]

^<<v41-6-37,37>>^ Ele lhes respondeu: “Deem-lhes vocês algo para comer.” Perguntaram-lhe então: “Devemos ir comprar pães no valor de 200 denários,^&#42;1^ e dá-los às pessoas para comer?”

[NOTE]
====
. Veja Ap. B14.
====

[[v41-6-38]]

^<<v41-6-38,38>>^ Ele lhes disse: “Quantos pães vocês têm? Vão ver!” Depois de verificarem, disseram: “Cinco, além de dois peixes.”

[[v41-6-39]]

^<<v41-6-39,39>>^ E ele mandou que todos se sentassem em grupos na grama verde.

[[v41-6-40]]

^<<v41-6-40,40>>^ Assim eles se sentaram em grupos de cem e de cinquenta.

[[v41-6-41]]

^<<v41-6-41,41>>^ Pegando então os cinco pães e os dois peixes, ele olhou para o céu e proferiu uma bênção. Depois partiu os pães e começou a dá-los aos discípulos, para que os servissem às pessoas, e repartiu os dois peixes entre todos.

[[v41-6-42]]

^<<v41-6-42,42>>^ Assim, todos comeram e ficaram satisfeitos;

[[v41-6-43]]

^<<v41-6-43,43>>^ e recolheram 12 cestos cheios de pedaços de pão, além das sobras de peixes.

[[v41-6-44]]

^<<v41-6-44,44>>^ Os que comeram os pães foram 5.000 homens.

[[v41-6-45]]

^<<v41-6-45,45>>^ Então, sem demora, ele mandou os discípulos entrar no barco e partir na frente, para a margem oposta, em direção a Betsaida, enquanto ele mesmo dispensava a multidão.

[[v41-6-46]]

^<<v41-6-46,46>>^ Mas, depois de se despedir deles, foi a um monte para orar.

[[v41-6-47]]

^<<v41-6-47,47>>^ Quando anoiteceu, o barco estava no meio do mar, mas ele estava sozinho em terra.

[[v41-6-48]]

^<<v41-6-48,48>>^ Então, ao ver que tinham grandes dificuldades para remar por causa do vento contrário, ele se dirigiu a eles por volta da quarta vigília da noite,^&#42;1^ andando sobre o mar, mas parecia que ele ia^&#42;2^ passar direto por eles.

[NOTE]
====
. Isto é, de cerca das 3 h da madrugada até o nascer do sol, por volta das 6 h da manhã.
. Ou: “mas ele estava prestes a”.
====

[[v41-6-49]]

^<<v41-6-49,49>>^ Quando o viram andando sobre o mar, pensaram: “É uma aparição!” e gritaram,

[[v41-6-50]]

^<<v41-6-50,50>>^ pois todos eles o viram e ficaram assustados. Mas ele lhes disse imediatamente: “Coragem! Sou eu; não tenham medo.”

[[v41-6-51]]

^<<v41-6-51,51>>^ Então subiu no barco com eles, e o vento parou. Em vista disso, ficaram muito espantados,

[[v41-6-52]]

^<<v41-6-52,52>>^ porque não tinham compreendido o significado dos pães; o coração deles continuava fechado ao entendimento.

[[v41-6-53]]

^<<v41-6-53,53>>^ Quando terminaram a travessia, chegaram a Genesaré e ancoraram o barco ali.

[[v41-6-54]]

^<<v41-6-54,54>>^ Mas, assim que saíram do barco, as pessoas o reconheceram.

[[v41-6-55]]

^<<v41-6-55,55>>^ Elas percorreram toda aquela região e começaram a levar os doentes em macas, para onde ouviam falar que ele estava.

[[v41-6-56]]

^<<v41-6-56,56>>^ E onde quer que ele entrasse — em aldeias, em cidades ou na zona rural —, colocavam os doentes nas praças^&#42;1^ e lhe imploravam que pudessem tocar pelo menos na borda da sua roupa. E todos os que tocavam nela ficavam bons.

[NOTE]
====
. Áreas abertas usadas como centro de compras e vendas e como local de reuniões públicas.
====

'''

xref:041-marcos/041-marcos-005.adoc#v41-5-0[&#60; Capítulo Anterior] | <<v41-6-0,Topo>> | xref:041-marcos/041-marcos-007.adoc#v41-7-0[Próximo Capítulo &#62;]