include::./index.adoc[]

[[v41-12-0]]
=== Segundo Marcos, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-12-1]]

^<<v41-12-1,1>>^ Então ele começou a lhes falar com ilustrações: “Um homem plantou um vinhedo, pôs uma cerca em volta dele, cavou um tanque como lagar de vinho e ergueu uma torre; então arrendou o vinhedo a lavradores e viajou para fora.

[[v41-12-2]]

^<<v41-12-2,2>>^ Na época devida, enviou um escravo aos lavradores para receber deles alguns dos frutos do vinhedo.

[[v41-12-3]]

^<<v41-12-3,3>>^ Mas eles o pegaram e espancaram, e o mandaram embora de mãos vazias.

[[v41-12-4]]

^<<v41-12-4,4>>^ Enviou-lhes outro escravo, e eles lhe bateram na cabeça e o humilharam.

[[v41-12-5]]

^<<v41-12-5,5>>^ Então enviou outro, e eles o mataram; e enviou muitos outros: a uns eles espancaram, a outros mataram.

[[v41-12-6]]

^<<v41-12-6,6>>^ Ele tinha mais um, um filho amado. Por fim o enviou a eles, dizendo: ‘Respeitarão o meu filho.’

[[v41-12-7]]

^<<v41-12-7,7>>^ Mas aqueles lavradores disseram entre si: ‘Este é o herdeiro. Venham, vamos matá-lo, e a herança será nossa.’

[[v41-12-8]]

^<<v41-12-8,8>>^ Assim, eles o pegaram, o mataram e o lançaram para fora do vinhedo.

[[v41-12-9]]

^<<v41-12-9,9>>^ O que fará o dono do vinhedo? Voltará e matará os lavradores, e dará o vinhedo a outros.

[[v41-12-10]]

^<<v41-12-10,10>>^ Vocês nunca leram esta passagem das Escrituras: ‘A pedra que os construtores rejeitaram, essa se tornou a principal pedra angular.^&#42;1^

[NOTE]
====
. Lit.: “a cabeça do cunhal”.
====

[[v41-12-11]]

^<<v41-12-11,11>>^ Isso procede de Jeová^&#42;1^ e é maravilhoso aos nossos olhos’?”

[NOTE]
====
. Veja Ap. A5.
====

[[v41-12-12]]

^<<v41-12-12,12>>^ Em vista disso, quiseram prendê-lo,^&#42;1^ porque sabiam que ele havia contado a ilustração pensando neles. Mas tinham medo da multidão, de modo que o deixaram e foram embora.

[NOTE]
====
. Ou: “pegá-lo”.
====

[[v41-12-13]]

^<<v41-12-13,13>>^ A seguir, enviaram-lhe alguns dos fariseus e dos partidários de Herodes, para apanhá-lo nas suas palavras.

[[v41-12-14]]

^<<v41-12-14,14>>^ Ao chegarem, eles lhe disseram: “Instrutor, sabemos que o senhor é verdadeiro e que não busca agradar a homens, pois não olha para a aparência das pessoas, mas ensina o caminho de Deus em harmonia com a verdade. É permitido^&#42;1^ ou não pagar a César o imposto por cabeça?

[NOTE]
====
. Ou: “lícito; certo”.
====

[[v41-12-15]]

^<<v41-12-15,15>>^ Devemos pagar ou não devemos pagar?” Percebendo a hipocrisia deles, ele lhes disse: “Por que vocês me põem à prova? Tragam-me um denário^&#42;1^ para eu ver.”

[NOTE]
====
. Veja Ap. B14.
====

[[v41-12-16]]

^<<v41-12-16,16>>^ Trouxeram-lhe um, e ele lhes perguntou: “De quem é esta imagem e inscrição?” Responderam-lhe: “De César.”

[[v41-12-17]]

^<<v41-12-17,17>>^ Jesus disse então: “Paguem a César o que é de César, mas a Deus o que é de Deus.” E ficaram maravilhados com ele.

[[v41-12-18]]

^<<v41-12-18,18>>^ Então os saduceus, que dizem não haver ressurreição, se aproximaram e lhe perguntaram:

[[v41-12-19]]

^<<v41-12-19,19>>^ “Instrutor, Moisés nos escreveu que, se alguém morre e deixa esposa, mas não deixa filhos, o irmão dele deve tomar a viúva em casamento para dar descendência ao seu irmão.

[[v41-12-20]]

^<<v41-12-20,20>>^ Havia sete irmãos. O primeiro tomou uma esposa, mas morreu sem deixar descendente.

[[v41-12-21]]

^<<v41-12-21,21>>^ E o segundo se casou com ela, mas morreu sem deixar descendente, e o mesmo aconteceu com o terceiro.

[[v41-12-22]]

^<<v41-12-22,22>>^ E nenhum dos sete deixou descendente. Por último, morreu também a mulher.

[[v41-12-23]]

^<<v41-12-23,23>>^ Na ressurreição, de qual deles ela será esposa? Pois os sete a tiveram como esposa.”

[[v41-12-24]]

^<<v41-12-24,24>>^ Jesus lhes disse: “Não é por isso que vocês estão enganados, porque não conhecem nem as Escrituras, nem o poder de Deus?

[[v41-12-25]]

^<<v41-12-25,25>>^ Pois, quando se levantam dentre os mortos, os homens não se casam, nem as mulheres são dadas em casamento, mas são como os anjos nos céus.

[[v41-12-26]]

^<<v41-12-26,26>>^ Quanto aos mortos serem levantados, vocês não leram no livro de Moisés, no relato sobre o espinheiro, que Deus lhe disse: ‘Eu sou o Deus de Abraão, o Deus de Isaque e o Deus de Jacó’?

[[v41-12-27]]

^<<v41-12-27,27>>^ Ele é Deus, não de mortos, mas de vivos. Vocês estão muito enganados.”

[[v41-12-28]]

^<<v41-12-28,28>>^ Um dos escribas, que havia se aproximado e ouvido a discussão, vendo que ele tinha lhes respondido bem, perguntou-lhe: “Qual mandamento é o primeiro^&#42;1^ de todos?”

[NOTE]
====
. Ou: “mais importante”.
====

[[v41-12-29]]

^<<v41-12-29,29>>^ Jesus respondeu: “O primeiro é: ‘Ouve, ó Israel: Jeová,^&#42;1^ nosso Deus, é um só Jeová.^&#42;2^

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v41-12-30]]

^<<v41-12-30,30>>^ Ame a Jeová,^&#42;1^ seu Deus, de todo o seu coração, de toda a sua alma,^&#42;2^ de toda a sua mente e de toda a sua força.’

[NOTE]
====
. Veja Ap. A5.
. Veja o Glossário.
====

[[v41-12-31]]

^<<v41-12-31,31>>^ O segundo é: ‘Ame o seu próximo como a si mesmo.’ Não há outro mandamento maior do que esses.”

[[v41-12-32]]

^<<v41-12-32,32>>^ O escriba lhe disse: “Instrutor, o senhor disse bem, em harmonia com a verdade: ‘Ele é um só, e não há outro além dele’;

[[v41-12-33]]

^<<v41-12-33,33>>^ e amá-lo de todo o coração, de todo o entendimento e de toda a força, e amar o próximo como a si mesmo vale muito mais do que todas as ofertas queimadas e sacrifícios.”

[[v41-12-34]]

^<<v41-12-34,34>>^ Com isso, Jesus, percebendo que ele tinha respondido de modo inteligente, disse-lhe: “Você não está longe do Reino de Deus.” Mas ninguém teve coragem de lhe fazer mais perguntas.

[[v41-12-35]]

^<<v41-12-35,35>>^ No entanto, ao continuar ensinando no templo, Jesus disse: “Como é que os escribas dizem que o Cristo é filho de Davi?

[[v41-12-36]]

^<<v41-12-36,36>>^ O próprio Davi disse, pelo espírito santo: ‘Jeová^&#42;1^ disse ao meu Senhor: “Sente-se à minha direita, até que eu ponha os seus inimigos debaixo dos seus pés.”’

[NOTE]
====
. Veja Ap. A5.
====

[[v41-12-37]]

^<<v41-12-37,37>>^ O próprio Davi o chama de Senhor, então como ele pode ser seu filho?”
E a grande multidão o escutava com prazer.

[[v41-12-38]]

^<<v41-12-38,38>>^ E ele ensinava, dizendo: “Cuidado com os escribas, que querem andar de vestes compridas e querem cumprimentos nas praças públicas,

[[v41-12-39]]

^<<v41-12-39,39>>^ os primeiros^&#42;1^ assentos nas sinagogas e os lugares mais destacados nos banquetes.

[NOTE]
====
. Ou: “melhores”.
====

[[v41-12-40]]

^<<v41-12-40,40>>^ Eles devoram as casas^&#42;1^ das viúvas e, para impressionar,^&#42;2^ fazem longas orações. Eles receberão um julgamento mais severo.”^&#42;3^

[NOTE]
====
. Ou: “os bens”.
. Ou: “e, como pretexto”.
. Ou: “pesado”.
====

[[v41-12-41]]

^<<v41-12-41,41>>^ E ele se sentou, com os cofres^&#42;1^ do tesouro à vista, e começou a observar como a multidão punha dinheiro nos cofres do tesouro, e muitos ricos punham neles muitas moedas.

[NOTE]
====
. Ou: “as caixas”.
====

[[v41-12-42]]

^<<v41-12-42,42>>^ Chegou então uma viúva pobre e pôs neles duas pequenas moedas de pouquíssimo valor.^&#42;1^

[NOTE]
====
. Lit.: “dois léptons, que é um quadrante”. Veja Ap. B14.
====

[[v41-12-43]]

^<<v41-12-43,43>>^ Ele chamou então os discípulos e lhes disse: “Digo-lhes a verdade: Esta viúva pobre pôs nos cofres do tesouro mais do que todos os outros.

[[v41-12-44]]

^<<v41-12-44,44>>^ Pois todos eles puseram do que lhes sobrava, mas ela, da sua carência,^&#42;1^ pôs tudo que possuía, tudo que tinha para viver.”

[NOTE]
====
. Ou: “pobreza”.
====

'''

xref:041-marcos/041-marcos-011.adoc#v41-11-0[&#60; Capítulo Anterior] | <<v41-12-0,Topo>> | xref:041-marcos/041-marcos-013.adoc#v41-13-0[Próximo Capítulo &#62;]