include::./index.adoc[]

[[v41-14-0]]
=== Segundo Marcos, 14
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-14-1]]

^<<v41-14-1,1>>^ Dali a dois dias era a Páscoa e a Festividade dos Pães sem Fermento. E os principais sacerdotes e os escribas estavam procurando um modo astucioso de^&#42;1^ prendê-lo^&#42;2^ e matá-lo.

[NOTE]
====
. Ou: “por meio de uma trama”.
. Ou: “pegá-lo”.
====

[[v41-14-2]]

^<<v41-14-2,2>>^ Pois diziam: “Não durante a festividade; talvez haja um alvoroço entre o povo.”

[[v41-14-3]]

^<<v41-14-3,3>>^ E, quando ele estava em Betânia, comendo^&#42;1^ na casa de Simão, o leproso, chegou uma mulher com um frasco de alabastro que continha óleo perfumado, nardo genuíno, muito caro. Ela rompeu o frasco de alabastro e começou a derramá-lo sobre a cabeça dele.

[NOTE]
====
. Ou: “recostado à mesa”.
====

[[v41-14-4]]

^<<v41-14-4,4>>^ Em vista disso, alguns disseram uns aos outros, indignados: “Por que se desperdiçou esse óleo perfumado?

[[v41-14-5]]

^<<v41-14-5,5>>^ Pois esse óleo perfumado poderia ter sido vendido por mais de 300 denários,^&#42;1^ e o dinheiro dado aos pobres!” E ficaram muito aborrecidos com ela.^&#42;2^

[NOTE]
====
. Veja Ap. B14.
. Ou: “E falaram com ela de modo irritado; E a repreenderam.”
====

[[v41-14-6]]

^<<v41-14-6,6>>^ Mas Jesus disse: “Deixem-na em paz. Por que vocês estão perturbando a mulher? Ela me fez uma coisa muito boa.

[[v41-14-7]]

^<<v41-14-7,7>>^ Porque vocês sempre têm consigo os pobres e podem lhes fazer o bem sempre que quiserem, mas nem sempre terão a mim.

[[v41-14-8]]

^<<v41-14-8,8>>^ Ela fez o que pôde; ela se antecipou em derramar óleo perfumado sobre o meu corpo, em vista do meu sepultamento.

[[v41-14-9]]

^<<v41-14-9,9>>^ Eu lhes digo a verdade: Onde quer que se preguem as boas novas em todo o mundo, o que essa mulher fez também será relatado, em memória dela.”

[[v41-14-10]]

^<<v41-14-10,10>>^ E Judas Iscariotes, um dos Doze, se dirigiu aos principais sacerdotes a fim de entregá-lo^&#42;1^ a eles.

[NOTE]
====
. Ou: “traí-lo”.
====

[[v41-14-11]]

^<<v41-14-11,11>>^ Quando ouviram isso, se alegraram e prometeram lhe dar dinheiro de prata. De modo que ele começou a procurar uma oportunidade para traí-lo.

[[v41-14-12]]

^<<v41-14-12,12>>^ Então, no primeiro dia da Festividade dos Pães sem Fermento, quando costumavam oferecer o sacrifício pascoal, seus discípulos lhe perguntaram: “Onde o senhor quer que façamos os preparativos para tomar a refeição pascoal?”

[[v41-14-13]]

^<<v41-14-13,13>>^ Em vista disso, ele enviou dois dos seus discípulos e lhes disse: “Vão à cidade, e um homem levando um jarro de barro com água encontrará vocês. Sigam-no,

[[v41-14-14]]

^<<v41-14-14,14>>^ e onde quer que ele entrar, digam ao dono da casa: ‘O Instrutor diz: “Onde está a sala dos hóspedes, em que eu possa tomar a refeição pascoal com os meus discípulos?”’

[[v41-14-15]]

^<<v41-14-15,15>>^ E ele lhes mostrará uma grande sala no andar de cima, mobiliada e pronta. Façam ali os preparativos para nós.”

[[v41-14-16]]

^<<v41-14-16,16>>^ Então os discípulos foram, entraram na cidade e encontraram tudo assim como ele tinha lhes dito, e prepararam a refeição pascoal.

[[v41-14-17]]

^<<v41-14-17,17>>^ Depois de anoitecer, ele chegou com os Doze.

[[v41-14-18]]

^<<v41-14-18,18>>^ E, enquanto estavam recostados à mesa e comiam, Jesus disse: “Digo-lhes a verdade: Um de vocês, que está comendo comigo, me trairá.”

[[v41-14-19]]

^<<v41-14-19,19>>^ Eles começaram a ficar tristes, e lhe perguntavam um por um: “Por acaso sou eu?”

[[v41-14-20]]

^<<v41-14-20,20>>^ Ele lhes disse: “É um dos Doze, aquele que põe comigo a mão na tigela.

[[v41-14-21]]

^<<v41-14-21,21>>^ Pois o Filho do Homem vai embora, assim como está escrito a respeito dele, mas ai daquele que trai o Filho do Homem! Seria melhor para esse homem que não tivesse nascido.”

[[v41-14-22]]

^<<v41-14-22,22>>^ E, ao continuarem a comer, pegou um pão, proferiu uma bênção, partiu-o e deu a eles, dizendo: “Peguem; isto representa o meu corpo.”

[[v41-14-23]]

^<<v41-14-23,23>>^ E, pegando um cálice, ele deu graças, deu-o a eles, e todos beberam dele.

[[v41-14-24]]

^<<v41-14-24,24>>^ E lhes disse: “Isto representa o meu ‘sangue do pacto’, que será derramado em benefício de muitos.

[[v41-14-25]]

^<<v41-14-25,25>>^ Eu lhes digo a verdade: Eu de modo algum beberei mais do produto da videira até aquele dia em que beberei vinho novo, no Reino de Deus.”

[[v41-14-26]]

^<<v41-14-26,26>>^ Por fim, depois de cantarem louvores,^&#42;1^ saíram para o monte das Oliveiras.

[NOTE]
====
. Ou: “hinos; salmos”.
====

[[v41-14-27]]

^<<v41-14-27,27>>^ E Jesus lhes disse: “Todos vocês tropeçarão, pois está escrito: ‘Ferirei o pastor, e as ovelhas serão espalhadas.’

[[v41-14-28]]

^<<v41-14-28,28>>^ Mas, depois que eu for levantado, irei adiante de vocês para a Galileia.”

[[v41-14-29]]

^<<v41-14-29,29>>^ No entanto, Pedro lhe disse: “Mesmo que todos os outros tropecem, eu não tropeçarei.”

[[v41-14-30]]

^<<v41-14-30,30>>^ Em vista disso, Jesus lhe disse: “Digo-lhe a verdade: Hoje, sim, ainda esta noite, antes de o galo cantar duas vezes, você me negará três vezes.”

[[v41-14-31]]

^<<v41-14-31,31>>^ Mas ele insistiu: “Mesmo que eu tenha de morrer com o senhor, de modo algum o negarei.” E todos os outros começaram a dizer a mesma coisa.

[[v41-14-32]]

^<<v41-14-32,32>>^ Assim, chegaram a um lugar chamado Getsêmani, e ele disse aos seus discípulos: “Sentem-se aqui enquanto eu oro.”

[[v41-14-33]]

^<<v41-14-33,33>>^ E ele levou consigo Pedro, Tiago e João, e começou a ficar profundamente angustiado^&#42;1^ e muito aflito.

[NOTE]
====
. Ou: “ficar atônito”.
====

[[v41-14-34]]

^<<v41-14-34,34>>^ Disse-lhes: “Estou^&#42;1^ profundamente triste, a ponto de morrer. Fiquem aqui e mantenham-se vigilantes.”

[NOTE]
====
. Ou: “Minha alma está”.
====

[[v41-14-35]]

^<<v41-14-35,35>>^ E, indo um pouco mais adiante, ele se prostrou no chão e começou a orar para que, se fosse possível, aquela hora se afastasse dele.

[[v41-14-36]]

^<<v41-14-36,36>>^ E disse: “Aba,^&#42;1^ Pai, todas as coisas são possíveis para ti; afasta de mim este cálice. Contudo, não o que eu quero, mas o que tu queres.”

[NOTE]
====
. Palavra hebraica ou aramaica que significa “ó Pai!”
====

[[v41-14-37]]

^<<v41-14-37,37>>^ Ele voltou e os encontrou dormindo, e disse a Pedro: “Simão, você está dormindo? Não teve força para se manter vigilante por uma hora?

[[v41-14-38]]

^<<v41-14-38,38>>^ Mantenham-se vigilantes e orem continuamente, para que não caiam em tentação. Naturalmente, o espírito está disposto,^&#42;1^ mas a carne é fraca.”

[NOTE]
====
. Ou: “pronto”.
====

[[v41-14-39]]

^<<v41-14-39,39>>^ Ele se afastou de novo e orou, dizendo a mesma coisa.

[[v41-14-40]]

^<<v41-14-40,40>>^ E voltou novamente e os encontrou dormindo, pois estavam com os olhos pesados, e por isso não sabiam o que lhe responder.

[[v41-14-41]]

^<<v41-14-41,41>>^ Voltou então pela terceira vez e lhes disse: “Numa ocasião como esta, vocês estão dormindo e descansando! Basta! Chegou a hora! O Filho do Homem está sendo entregue^&#42;1^ às mãos de pecadores.

[NOTE]
====
. Ou: “traído”.
====

[[v41-14-42]]

^<<v41-14-42,42>>^ Levantem-se, vamos embora. Vejam! Aquele que me trai está chegando.”

[[v41-14-43]]

^<<v41-14-43,43>>^ E imediatamente, enquanto ele ainda falava, chegou Judas, um dos Doze, e com ele uma multidão com espadas e bastões. Eles tinham sido enviados pelos principais sacerdotes, pelos escribas e pelos anciãos.

[[v41-14-44]]

^<<v41-14-44,44>>^ O traidor havia combinado com eles um sinal, dizendo: “Aquele que eu beijar é ele; prendam-no e levem-no embora sob vigilância.”

[[v41-14-45]]

^<<v41-14-45,45>>^ Então se dirigiu diretamente a ele, se aproximou e disse: “Rabi!” e o beijou ternamente.

[[v41-14-46]]

^<<v41-14-46,46>>^ Assim, eles o agarraram e prenderam.

[[v41-14-47]]

^<<v41-14-47,47>>^ No entanto, um dos que estavam presentes puxou a espada e atacou o escravo do sumo sacerdote, decepando-lhe a orelha.

[[v41-14-48]]

^<<v41-14-48,48>>^ Então Jesus lhes disse: “Vocês vieram me prender com espadas e bastões, como se eu fosse um bandido?

[[v41-14-49]]

^<<v41-14-49,49>>^ Dia após dia eu estava com vocês no templo, ensinando; contudo, vocês não me prenderam. Porém, isso é para cumprir as Escrituras.”

[[v41-14-50]]

^<<v41-14-50,50>>^ E todos o abandonaram e fugiram.

[[v41-14-51]]

^<<v41-14-51,51>>^ No entanto um jovem, usando apenas uma roupa de linho fino por cima do corpo nu, começou a segui-lo de perto, e tentaram prendê-lo,

[[v41-14-52]]

^<<v41-14-52,52>>^ mas ele largou a roupa de linho e escapou nu.^&#42;1^

[NOTE]
====
. Ou: “pouco vestido; apenas com uma túnica”.
====

[[v41-14-53]]

^<<v41-14-53,53>>^ Levaram então Jesus ao sumo sacerdote; e todos os principais sacerdotes, os anciãos e os escribas se reuniram.

[[v41-14-54]]

^<<v41-14-54,54>>^ Mas Pedro, de uma boa distância, o seguiu até o pátio do sumo sacerdote; e ficou sentado junto com os criados se aquecendo diante de um fogo.

[[v41-14-55]]

^<<v41-14-55,55>>^ Os principais sacerdotes e todo o Sinédrio estavam procurando testemunhos contra Jesus, para entregá-lo à morte, mas não achavam nenhum.

[[v41-14-56]]

^<<v41-14-56,56>>^ Na verdade, muitos davam testemunho falso contra ele, mas os seus testemunhos não estavam de acordo.

[[v41-14-57]]

^<<v41-14-57,57>>^ Também alguns se levantavam e davam testemunho falso contra ele, dizendo:

[[v41-14-58]]

^<<v41-14-58,58>>^ “Nós o ouvimos dizer: ‘Derrubarei este templo feito por mãos humanas e em três dias construirei outro, não feito por mãos humanas.’”

[[v41-14-59]]

^<<v41-14-59,59>>^ Mas mesmo nesse ponto seu testemunho não estava de acordo.

[[v41-14-60]]

^<<v41-14-60,60>>^ Então o sumo sacerdote se levantou no meio deles e perguntou a Jesus: “Você não diz nada em resposta? O que diz do testemunho destes homens contra você?”

[[v41-14-61]]

^<<v41-14-61,61>>^ Mas ele continuou calado e não deu nenhuma resposta. O sumo sacerdote voltou a interrogá-lo, dizendo: “Você é o Cristo, o Filho do Bendito?”

[[v41-14-62]]

^<<v41-14-62,62>>^ Jesus respondeu então: “Sou; e vocês verão o Filho do Homem sentado à direita de poder e vindo com as nuvens do céu.”

[[v41-14-63]]

^<<v41-14-63,63>>^ Em vista disso, o sumo sacerdote rasgou suas vestes e disse: “Que necessidade temos ainda de testemunhas?

[[v41-14-64]]

^<<v41-14-64,64>>^ Vocês ouviram a blasfêmia. Qual é a sua decisão?”^&#42;1^ Todos decidiram que ele merecia a morte.

[NOTE]
====
. Ou: “O que vocês acham?”
====

[[v41-14-65]]

^<<v41-14-65,65>>^ E alguns começaram a cuspir nele, a cobrir-lhe o rosto, a esmurrá-lo e a dizer-lhe: “Profetize!” E, depois de esbofeteá-lo, os oficiais de justiça o levaram.

[[v41-14-66]]

^<<v41-14-66,66>>^ Então, enquanto Pedro estava embaixo, no pátio, chegou uma das servas do sumo sacerdote.

[[v41-14-67]]

^<<v41-14-67,67>>^ Vendo Pedro se aquecer, olhou bem para ele e disse: “Você também estava com o Nazareno, esse Jesus.”

[[v41-14-68]]

^<<v41-14-68,68>>^ Mas ele negou, dizendo: “Não o conheço nem sei do que você está falando”, e saiu para a entrada do pátio.^&#42;1^

[NOTE]
====
. Ou: “vestíbulo”.
====

[[v41-14-69]]

^<<v41-14-69,69>>^ A serva o viu ali e novamente começou a dizer aos presentes: “Este é um deles.”

[[v41-14-70]]

^<<v41-14-70,70>>^ Mais uma vez ele negou isso. E, pouco depois, os que estavam presentes começaram a dizer a Pedro de novo: “Certamente você é um deles, pois, de fato, você é galileu.”

[[v41-14-71]]

^<<v41-14-71,71>>^ Mas ele começou a amaldiçoar a si mesmo e a jurar: “Eu não conheço esse homem de quem vocês estão falando!”

[[v41-14-72]]

^<<v41-14-72,72>>^ Imediatamente um galo cantou pela segunda vez, e Pedro se lembrou do que Jesus tinha lhe dito: “Antes de o galo cantar duas vezes, você me negará três vezes.” E, muito abalado, ele começou a chorar.

'''

xref:041-marcos/041-marcos-013.adoc#v41-13-0[&#60; Capítulo Anterior] | <<v41-14-0,Topo>> | xref:041-marcos/041-marcos-015.adoc#v41-15-0[Próximo Capítulo &#62;]