include::./index.adoc[]

[[v41-13-0]]
=== Segundo Marcos, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-13-1]]

^<<v41-13-1,1>>^ Quando ele estava saindo do templo, um dos seus discípulos lhe disse: “Instrutor, veja que pedras e que edifícios maravilhosos!”

[[v41-13-2]]

^<<v41-13-2,2>>^ No entanto, Jesus lhe disse: “Está vendo estes grandes edifícios? De modo algum ficará aqui pedra sobre pedra sem ser derrubada.”

[[v41-13-3]]

^<<v41-13-3,3>>^ Quando ele estava sentado no monte das Oliveiras, com o templo à vista, Pedro, Tiago, João e André lhe perguntaram em particular:

[[v41-13-4]]

^<<v41-13-4,4>>^ “Diga-nos: Quando acontecerão essas coisas e qual será o sinal de que todas essas coisas estão prestes a chegar a um final?”

[[v41-13-5]]

^<<v41-13-5,5>>^ Assim, Jesus começou a lhes dizer: “Cuidado para que ninguém os engane.

[[v41-13-6]]

^<<v41-13-6,6>>^ Muitos virão em meu nome, dizendo: ‘Sou eu’, e enganarão a muitos.

[[v41-13-7]]

^<<v41-13-7,7>>^ Além disso, quando ouvirem falar de guerras e notícias de guerras, não fiquem apavorados. Essas coisas têm de acontecer, mas ainda não é o fim.

[[v41-13-8]]

^<<v41-13-8,8>>^ “Porque nação se levantará contra nação e reino contra reino; haverá terremotos num lugar após outro; também haverá falta de alimentos. Essas coisas são um começo das dores de aflição.

[[v41-13-9]]

^<<v41-13-9,9>>^ “Quanto a vocês, tomem cuidado. As pessoas os entregarão aos tribunais locais, e vocês serão espancados nas sinagogas, e serão postos diante de governadores e reis, por minha causa, para darem testemunho a eles.

[[v41-13-10]]

^<<v41-13-10,10>>^ Também, em todas as nações, as boas novas têm de ser pregadas primeiro.

[[v41-13-11]]

^<<v41-13-11,11>>^ E, quando levarem vocês para entregá-los, não fiquem preocupados^&#42;1^ com o que dizer, mas digam o que lhes for dado naquela hora. Pois quem fala não são vocês, mas é o espírito santo.

[NOTE]
====
. Ou: “ansiosos antecipadamente”.
====

[[v41-13-12]]

^<<v41-13-12,12>>^ Além disso, irmão entregará irmão à morte, e o pai ao filho, e os filhos se levantarão contra os pais e farão com que sejam mortos.

[[v41-13-13]]

^<<v41-13-13,13>>^ E vocês serão odiados por todos, por causa do meu nome. Mas quem perseverar^&#42;1^ até o fim será salvo.

[NOTE]
====
. Ou: “persevera”.
====

[[v41-13-14]]

^<<v41-13-14,14>>^ “No entanto, quando vocês virem a coisa repugnante que causa desolação estar^&#42;1^ num lugar onde não devia (que o leitor use de discernimento), então, os que estiverem na Judeia fujam para os montes.

[NOTE]
====
. Ou: “estar de pé”.
====

[[v41-13-15]]

^<<v41-13-15,15>>^ O homem que estiver no terraço não desça, nem entre para tirar algo da sua casa,

[[v41-13-16]]

^<<v41-13-16,16>>^ e o homem que estiver no campo não volte ao que deixou atrás, para apanhar sua capa.

[[v41-13-17]]

^<<v41-13-17,17>>^ Ai das mulheres grávidas e das que amamentarem naqueles dias!

[[v41-13-18]]

^<<v41-13-18,18>>^ Persistam em orar para que isso não ocorra no inverno;

[[v41-13-19]]

^<<v41-13-19,19>>^ pois aqueles dias serão dias de tribulação, como nunca ocorreu desde o princípio da criação, que Deus criou, até agora,^&#42;1^ nem ocorrerá de novo.

[NOTE]
====
. Ou: “até aquele tempo”.
====

[[v41-13-20]]

^<<v41-13-20,20>>^ De fato, se Jeová^&#42;1^ não tivesse abreviado os dias, ninguém seria salvo. Mas, por causa dos escolhidos, que ele escolheu, ele abreviou os dias.

[NOTE]
====
. Veja Ap. A5.
====

[[v41-13-21]]

^<<v41-13-21,21>>^ “Então, também, se alguém lhes disser: ‘Vejam! Aqui está o Cristo!’ ou ‘Vejam! Ali está ele!’, não acreditem.

[[v41-13-22]]

^<<v41-13-22,22>>^ Porque surgirão falsos cristos e falsos profetas, e farão sinais e milagres a fim de desencaminhar, se possível, os escolhidos.

[[v41-13-23]]

^<<v41-13-23,23>>^ Vocês, portanto, sejam vigilantes. Eu lhes disse tudo antecipadamente.

[[v41-13-24]]

^<<v41-13-24,24>>^ “Mas naqueles dias, depois daquela tribulação, o sol escurecerá, a lua não dará a sua luz,

[[v41-13-25]]

^<<v41-13-25,25>>^ as estrelas cairão do céu, e os poderes que estão nos céus serão abalados.

[[v41-13-26]]

^<<v41-13-26,26>>^ E então verão o Filho do Homem vir nas nuvens, com grande poder e glória.

[[v41-13-27]]

^<<v41-13-27,27>>^ E então ele enviará os anjos e reunirá os seus escolhidos desde os quatro ventos, desde a extremidade da terra até a extremidade do céu.

[[v41-13-28]]

^<<v41-13-28,28>>^ “Aprendam desta ilustração sobre a figueira: assim que os ramos novos ficam tenros e brotam folhas, vocês sabem que o verão está próximo.

[[v41-13-29]]

^<<v41-13-29,29>>^ Do mesmo modo, quando virem essas coisas acontecer, saibam que ele^&#42;1^ está próximo, às portas.

[NOTE]
====
. Isto é, o Filho do Homem.
====

[[v41-13-30]]

^<<v41-13-30,30>>^ Eu lhes garanto que esta geração de modo algum passará até que todas essas coisas aconteçam.

[[v41-13-31]]

^<<v41-13-31,31>>^ Céu e terra passarão, mas as minhas palavras de modo algum passarão.

[[v41-13-32]]

^<<v41-13-32,32>>^ “A respeito daquele dia ou daquela hora ninguém sabe, nem os anjos no céu, nem o Filho, mas somente o Pai.

[[v41-13-33]]

^<<v41-13-33,33>>^ Sejam vigilantes, mantenham-se despertos, pois vocês não sabem quando é o tempo determinado.

[[v41-13-34]]

^<<v41-13-34,34>>^ É semelhante a um homem que, ao viajar para fora, deixou sua casa e deu autoridade aos seus escravos, a cada um o seu trabalho, e ordenou ao porteiro que se mantivesse vigilante.

[[v41-13-35]]

^<<v41-13-35,35>>^ Portanto, mantenham-se vigilantes, pois vocês não sabem quando virá o senhor da casa, quer tarde no dia, quer à meia-noite, quer antes do amanhecer,^&#42;1^ quer de manhã cedo,

[NOTE]
====
. Lit.: “quando o galo canta”.
====

[[v41-13-36]]

^<<v41-13-36,36>>^ a fim de que, quando ele vier de repente, não os encontre dormindo.

[[v41-13-37]]

^<<v41-13-37,37>>^ Mas o que eu digo a vocês, digo a todos: Mantenham-se vigilantes.”

'''

xref:041-marcos/041-marcos-012.adoc#v41-12-0[&#60; Capítulo Anterior] | <<v41-13-0,Topo>> | xref:041-marcos/041-marcos-014.adoc#v41-14-0[Próximo Capítulo &#62;]