include::./index.adoc[]

[[v41-9-0]]
=== Segundo Marcos, 9
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-9-1]]

^<<v41-9-1,1>>^ Ele lhes disse também: “Digo a verdade a vocês: Há alguns dos que estão aqui que de modo algum provarão a morte antes de verem o Reino de Deus já vindo em poder.”

[[v41-9-2]]

^<<v41-9-2,2>>^ Seis dias depois, Jesus chamou Pedro, Tiago e João, e os levou a sós a um alto monte. E ele foi transfigurado diante deles;

[[v41-9-3]]

^<<v41-9-3,3>>^ suas roupas se tornaram cintilantes e ficaram muito mais brancas do que qualquer lavadeiro na terra poderia alvejar.

[[v41-9-4]]

^<<v41-9-4,4>>^ Também lhes apareceu Elias com Moisés, e eles estavam conversando com Jesus.

[[v41-9-5]]

^<<v41-9-5,5>>^ Então Pedro disse a Jesus: “Rabi, é bom que estejamos aqui. Vamos armar, então, três tendas: uma para o senhor, uma para Moisés e uma para Elias.”

[[v41-9-6]]

^<<v41-9-6,6>>^ Na verdade, não sabia como reagir, pois eles estavam com muito medo.

[[v41-9-7]]

^<<v41-9-7,7>>^ E formou-se uma nuvem, encobrindo-os, e uma voz saiu da nuvem: “Este é meu Filho, o amado. Escutem-no.”

[[v41-9-8]]

^<<v41-9-8,8>>^ De repente, então, olharam em volta e não viram mais ninguém com eles, a não ser Jesus.

[[v41-9-9]]

^<<v41-9-9,9>>^ Enquanto desciam do monte, Jesus lhes ordenou com firmeza que não contassem a ninguém o que tinham visto, até que o Filho do Homem fosse levantado dentre os mortos.

[[v41-9-10]]

^<<v41-9-10,10>>^ Eles obedeceram às suas palavras,^&#42;1^ mas discutiram entre si o que significava ele ser levantado dentre os mortos.

[NOTE]
====
. Ou, possivelmente: “guardaram o assunto para si”.
====

[[v41-9-11]]

^<<v41-9-11,11>>^ E lhe perguntaram: “Por que os escribas dizem que Elias tem de vir primeiro?”

[[v41-9-12]]

^<<v41-9-12,12>>^ Ele lhes respondeu: “Elias realmente vem primeiro e restabelece todas as coisas. Mas como é que está escrito a respeito do Filho do Homem que ele tem de sofrer muitas coisas e ser tratado com desprezo?

[[v41-9-13]]

^<<v41-9-13,13>>^ Porém, eu lhes digo que Elias, de fato, já veio, e fizeram com ele tudo o que quiseram, assim como está escrito a respeito dele.”

[[v41-9-14]]

^<<v41-9-14,14>>^ Ao chegarem onde estavam os outros discípulos, notaram uma grande multidão em volta deles, e havia escribas discutindo com eles.

[[v41-9-15]]

^<<v41-9-15,15>>^ Mas, assim que as pessoas da multidão o viram, ficaram admiradas e correram para cumprimentá-lo.

[[v41-9-16]]

^<<v41-9-16,16>>^ Então ele lhes perguntou: “Sobre o que vocês estão discutindo com eles?”

[[v41-9-17]]

^<<v41-9-17,17>>^ E alguém da multidão lhe respondeu: “Instrutor, eu trouxe meu filho para o senhor, porque ele tem um espírito mudo.

[[v41-9-18]]

^<<v41-9-18,18>>^ Onde quer que esse espírito o apanhe, lança-o no chão, e ele espuma pela boca, range os dentes e perde a força. Eu pedi aos seus discípulos que expulsassem o espírito, mas eles não foram capazes de fazer isso.”

[[v41-9-19]]

^<<v41-9-19,19>>^ Em resposta, ele lhes disse: “Ó geração sem fé, até quando terei de continuar com vocês? Até quando terei de suportá-los? Tragam-no a mim.”

[[v41-9-20]]

^<<v41-9-20,20>>^ De modo que o levaram a ele, mas, ao ver Jesus, o espírito lançou o menino imediatamente em convulsões. Depois de cair no chão, ele ficou rolando e espumando pela boca.

[[v41-9-21]]

^<<v41-9-21,21>>^ Então Jesus perguntou ao pai: “Há quanto tempo isso acontece com ele?” Ele respondeu: “Desde a infância,

[[v41-9-22]]

^<<v41-9-22,22>>^ e o espírito o lança muitas vezes no fogo e também na água, para matá-lo. Mas, se o senhor puder fazer algo, tenha pena de nós e ajude-nos.”

[[v41-9-23]]

^<<v41-9-23,23>>^ Jesus lhe disse: “Esta expressão: ‘Se puder’! Ora, tudo é possível para quem tem fé.”

[[v41-9-24]]

^<<v41-9-24,24>>^ Imediatamente, o pai do menino clamou: “Eu tenho fé! Ajude-me onde preciso de fé!”

[[v41-9-25]]

^<<v41-9-25,25>>^ Observando então que uma multidão estava rapidamente se aproximando deles, Jesus censurou o espírito impuro, dizendo-lhe: “Espírito mudo e surdo, eu lhe ordeno que saia dele e não entre nele novamente!”

[[v41-9-26]]

^<<v41-9-26,26>>^ Depois de clamar e de causar muitas convulsões no menino, o espírito saiu; e o menino parecia morto, de modo que a maioria das pessoas dizia: “Ele está morto!”

[[v41-9-27]]

^<<v41-9-27,27>>^ Mas Jesus o pegou pela mão e o levantou, e ele ficou de pé.

[[v41-9-28]]

^<<v41-9-28,28>>^ Assim, depois de entrar numa casa, seus discípulos lhe perguntaram em particular: “Por que nós não conseguimos expulsá-lo?”

[[v41-9-29]]

^<<v41-9-29,29>>^ Ele lhes respondeu: “Essa espécie só sai por oração.”

[[v41-9-30]]

^<<v41-9-30,30>>^ Partiram dali e atravessaram a Galileia, mas ele não quis que ninguém soubesse disso,

[[v41-9-31]]

^<<v41-9-31,31>>^ pois estava ensinando os seus discípulos. E lhes dizia: “O Filho do Homem será entregue^&#42;1^ às mãos dos homens, e eles o matarão, mas, embora seja morto, será levantado três dias depois.”

[NOTE]
====
. Ou: “traído”.
====

[[v41-9-32]]

^<<v41-9-32,32>>^ No entanto, não entendiam o que ele lhes dizia e tinham medo de perguntar.

[[v41-9-33]]

^<<v41-9-33,33>>^ E entraram em Cafarnaum. Então, quando estava dentro da casa, ele lhes perguntou: “Sobre o que vocês estavam discutindo na estrada?”

[[v41-9-34]]

^<<v41-9-34,34>>^ Eles ficaram calados, pois na estrada tinham discutido entre si sobre quem era o maior.

[[v41-9-35]]

^<<v41-9-35,35>>^ Então ele se sentou, chamou os Doze e lhes disse: “Se alguém quer ser o primeiro, tem de ser o último de todos e servo^&#42;1^ de todos.”

[NOTE]
====
. Ou: “ministro”.
====

[[v41-9-36]]

^<<v41-9-36,36>>^ Então ele pegou uma criancinha e a colocou no meio deles; pôs os braços em volta dela e lhes disse:

[[v41-9-37]]

^<<v41-9-37,37>>^ “Quem recebe uma destas criancinhas em meu nome recebe também a mim; e quem me recebe, recebe não só a mim, mas também Aquele que me enviou.”

[[v41-9-38]]

^<<v41-9-38,38>>^ João lhe disse: “Instrutor, vimos alguém expulsar demônios usando o seu nome e tentamos impedi-lo, porque ele não estava nos acompanhando.”

[[v41-9-39]]

^<<v41-9-39,39>>^ Mas Jesus disse: “Não tentem impedi-lo, porque ninguém que faça uma obra poderosa em meu nome pode logo depois falar mal de mim.

[[v41-9-40]]

^<<v41-9-40,40>>^ Pois quem não é contra nós é a favor de nós.

[[v41-9-41]]

^<<v41-9-41,41>>^ E eu garanto a vocês que quem lhes der um copo de água para beber, por vocês pertencerem a Cristo, de modo algum perderá sua recompensa.

[[v41-9-42]]

^<<v41-9-42,42>>^ Mas quem fizer tropeçar um destes pequenos que têm fé, seria melhor para ele que pusessem no seu pescoço uma pedra de moinho daquelas que o jumento faz girar, e que fosse lançado no mar.

[[v41-9-43]]

^<<v41-9-43,43>>^ “Se a sua mão faz você tropeçar, corte-a. É melhor para você entrar na vida aleijado do que ir com as duas mãos para a Geena,^&#42;1^ para o fogo que não pode ser apagado.

[NOTE]
====
. Veja o Glossário.
====

[[v41-9-44]]

^<<v41-9-44,44>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v41-9-45]]

^<<v41-9-45,45>>^ E, se o seu pé o faz tropeçar, corte-o. É melhor para você entrar na vida manco do que ser lançado com os dois pés na Geena.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v41-9-46]]

^<<v41-9-46,46>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v41-9-47]]

^<<v41-9-47,47>>^ E, se o seu olho o faz tropeçar, lance-o para longe. É melhor para você entrar no Reino de Deus com um olho só do que ser lançado com os dois olhos na Geena,^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v41-9-48]]

^<<v41-9-48,48>>^ onde os vermes não morrem e o fogo não é apagado.

[[v41-9-49]]

^<<v41-9-49,49>>^ “Pois todos têm de ser salgados com fogo.

[[v41-9-50]]

^<<v41-9-50,50>>^ O sal é bom, mas, se o sal perder a sua salinidade, o que farão para recuperar o seu sabor? Tenham sal em vocês mesmos e mantenham a paz uns com os outros.”

'''

xref:041-marcos/041-marcos-008.adoc#v41-8-0[&#60; Capítulo Anterior] | <<v41-9-0,Topo>> | xref:041-marcos/041-marcos-010.adoc#v41-10-0[Próximo Capítulo &#62;]