include::./index.adoc[]

[[v41-1-0]]
=== Segundo Marcos, 1
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-1-1]]

^<<v41-1-1,1>>^ Princípio das boas novas^&#42;1^ a respeito de Jesus Cristo, o Filho de Deus.

[NOTE]
====
. Ou: “do evangelho”.
====

[[v41-1-2]]

^<<v41-1-2,2>>^ Conforme está escrito em Isaías, o profeta: “(Veja! Enviarei o meu mensageiro na sua frente,^&#42;1^ o qual preparará o seu caminho.)

[NOTE]
====
. Lit.: “diante da sua face”.
====

[[v41-1-3]]

^<<v41-1-3,3>>^ A voz de alguém está clamando no deserto:^&#42;1^ ‘Preparem o caminho para Jeová!^&#42;2^ Endireitem as suas estradas.’”

[NOTE]
====
. Veja o Glossário.
. Veja Ap. A5.
====

[[v41-1-4]]

^<<v41-1-4,4>>^ João, o Batizador, estava no deserto, pregando o batismo em símbolo de arrependimento para o perdão de pecados.

[[v41-1-5]]

^<<v41-1-5,5>>^ E todo o território da Judeia e todos os habitantes de Jerusalém iam ao encontro dele e eram batizados^&#42;1^ por ele no rio Jordão, confessando abertamente os seus pecados.

[NOTE]
====
. Ou: “mergulhados; imersos”.
====

[[v41-1-6]]

^<<v41-1-6,6>>^ João usava roupa de pelo de camelo e um cinto de couro na cintura, e comia gafanhotos e mel silvestre.

[[v41-1-7]]

^<<v41-1-7,7>>^ Ele pregava: “Alguém mais forte do que eu vem depois de mim, e não sou digno de me abaixar e desamarrar o cordão das suas sandálias.

[[v41-1-8]]

^<<v41-1-8,8>>^ Eu batizei vocês com água, mas ele os batizará com espírito santo.”

[[v41-1-9]]

^<<v41-1-9,9>>^ No decorrer daqueles dias, Jesus chegou de Nazaré, da Galileia, e foi batizado por João no Jordão.

[[v41-1-10]]

^<<v41-1-10,10>>^ Imediatamente, ao sair da água, viu os céus se abrindo e o espírito descer como pomba sobre ele.

[[v41-1-11]]

^<<v41-1-11,11>>^ E uma voz saiu dos céus: “Você é meu Filho, o amado; eu o aprovo.”

[[v41-1-12]]

^<<v41-1-12,12>>^ E o espírito o impeliu imediatamente a ir ao deserto.

[[v41-1-13]]

^<<v41-1-13,13>>^ Assim, ele ficou no deserto por 40 dias, e foi tentado por Satanás. Ele estava com os animais selvagens, mas os anjos o serviam.

[[v41-1-14]]

^<<v41-1-14,14>>^ Então, depois de João ter sido preso, Jesus entrou na Galileia, pregando as boas novas de Deus

[[v41-1-15]]

^<<v41-1-15,15>>^ e dizendo: “Chegou o tempo determinado, e o Reino de Deus está próximo. Arrependam-se e tenham fé nas boas novas.”

[[v41-1-16]]

^<<v41-1-16,16>>^ Enquanto andava à beira do mar da Galileia, ele viu Simão e André, irmão de Simão, lançando suas redes no mar, pois eram pescadores.

[[v41-1-17]]

^<<v41-1-17,17>>^ De modo que Jesus lhes disse: “Sigam-me, e eu farei de vocês pescadores de homens.”^&#42;1^

[NOTE]
====
. Ou: “pessoas”.
====

[[v41-1-18]]

^<<v41-1-18,18>>^ E eles abandonaram imediatamente as suas redes e o seguiram.

[[v41-1-19]]

^<<v41-1-19,19>>^ Depois de ir um pouco mais à frente, ele viu Tiago, filho de Zebedeu, e seu irmão João, enquanto estavam no seu barco consertando as suas redes,

[[v41-1-20]]

^<<v41-1-20,20>>^ e sem demora ele os chamou. Então eles deixaram seu pai, Zebedeu, no barco com os empregados e o seguiram.

[[v41-1-21]]

^<<v41-1-21,21>>^ E entraram em Cafarnaum.
Assim que chegou o sábado, ele entrou na sinagoga e começou a ensinar.

[[v41-1-22]]

^<<v41-1-22,22>>^ E as pessoas ficaram maravilhadas com o seu modo de ensinar, pois ele as ensinava como quem tinha autoridade, e não como os escribas.

[[v41-1-23]]

^<<v41-1-23,23>>^ Naquele momento havia na sinagoga deles um homem sob o poder de um espírito impuro, e ele gritou:

[[v41-1-24]]

^<<v41-1-24,24>>^ “O que você quer conosco,^&#42;1^ Jesus Nazareno? Veio nos destruir? Eu sei exatamente quem você é: o Santo de Deus!”

[NOTE]
====
. Ou: “O que nós temos a ver com você”.
====

[[v41-1-25]]

^<<v41-1-25,25>>^ Mas Jesus o censurou, dizendo: “Cale-se e saia dele!”

[[v41-1-26]]

^<<v41-1-26,26>>^ E o espírito impuro, depois de lançar o homem em convulsão e gritar ao máximo da sua voz, saiu dele.

[[v41-1-27]]

^<<v41-1-27,27>>^ Pois bem, todos ficaram tão pasmados que começaram a discutir o que tinha acontecido, dizendo: “O que é isso? Um novo ensinamento! Ele dá ordens com autoridade até mesmo a espíritos impuros, e eles lhe obedecem.”

[[v41-1-28]]

^<<v41-1-28,28>>^ De modo que o relato sobre ele se espalhou rapidamente em todas as direções, por toda a região da Galileia.

[[v41-1-29]]

^<<v41-1-29,29>>^ Depois saíram da sinagoga e foram à casa de Simão e André, com Tiago e João.

[[v41-1-30]]

^<<v41-1-30,30>>^ A sogra de Simão estava de cama, com febre, e falaram dela a Jesus imediatamente.

[[v41-1-31]]

^<<v41-1-31,31>>^ Ele se dirigiu a ela, pegou-a pela mão e a levantou. A febre a deixou, e ela começou a servi-los.

[[v41-1-32]]

^<<v41-1-32,32>>^ Ao anoitecer, após o pôr do sol, as pessoas levaram a ele todos os doentes e os possessos de demônios;

[[v41-1-33]]

^<<v41-1-33,33>>^ e a cidade toda estava reunida na frente da porta.

[[v41-1-34]]

^<<v41-1-34,34>>^ Assim, ele curou a muitos que sofriam de várias doenças e expulsou muitos demônios, mas não deixava os demônios falar, pois sabiam que ele era Cristo.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “sabiam quem ele era”.
====

[[v41-1-35]]

^<<v41-1-35,35>>^ De manhã cedo, quando ainda estava escuro, ele se levantou, saiu e foi para um lugar isolado, e ali começou a orar.

[[v41-1-36]]

^<<v41-1-36,36>>^ No entanto, Simão e os que estavam com ele foram à sua procura.

[[v41-1-37]]

^<<v41-1-37,37>>^ Ao encontrá-lo, disseram-lhe: “Todos estão procurando o senhor.”

[[v41-1-38]]

^<<v41-1-38,38>>^ Mas ele lhes disse: “Vamos a outro lugar, às cidades vizinhas, para que eu também pregue ali, pois foi por isso que vim.”

[[v41-1-39]]

^<<v41-1-39,39>>^ E ele foi, pregando nas sinagogas deles, em toda a Galileia, e expulsando os demônios.

[[v41-1-40]]

^<<v41-1-40,40>>^ Aproximou-se dele também um leproso, suplicando-lhe até de joelhos: “Se o senhor apenas quiser, pode me purificar.”

[[v41-1-41]]

^<<v41-1-41,41>>^ Em vista disso, ele teve pena; e estendeu a mão, tocou no homem e lhe disse: “Eu quero! Seja purificado.”

[[v41-1-42]]

^<<v41-1-42,42>>^ Imediatamente a lepra desapareceu dele, e ele ficou purificado.

[[v41-1-43]]

^<<v41-1-43,43>>^ Então Jesus o mandou logo embora, depois de lhe ordenar com firmeza:

[[v41-1-44]]

^<<v41-1-44,44>>^ “Tenha o cuidado de não contar nada a ninguém, mas vá, mostre-se ao sacerdote e ofereça pela sua purificação o que Moisés determinou, em testemunho para eles.”

[[v41-1-45]]

^<<v41-1-45,45>>^ Mas, depois de se afastar, o homem começou a proclamar e a divulgar amplamente o acontecido, de modo que Jesus não podia mais entrar abertamente numa cidade, mas ficava fora, em lugares isolados. Contudo, as pessoas continuavam a vir a ele de todas as partes.

'''

xref:040-mateus/040-mateus-028.adoc#v40-28-0[&#60; Capítulo Anterior] | <<v41-1-0,Topo>> | xref:041-marcos/041-marcos-002.adoc#v41-2-0[Próximo Capítulo &#62;]