include::./index.adoc[]

[[v41-16-0]]
=== Segundo Marcos, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-16-1]]

^<<v41-16-1,1>>^ Então, passado o sábado, Maria Madalena, Maria, mãe de Tiago, e Salomé compraram aromas para passar no corpo dele.

[[v41-16-2]]

^<<v41-16-2,2>>^ E, no primeiro dia da semana, chegaram bem cedo ao túmulo,^&#42;1^ depois de o sol se levantar.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v41-16-3]]

^<<v41-16-3,3>>^ Diziam umas às outras: “Quem rolará a pedra da entrada do túmulo para nós?”

[[v41-16-4]]

^<<v41-16-4,4>>^ Mas, ao levantarem os olhos, viram que a pedra, embora muito grande, tinha sido rolada.

[[v41-16-5]]

^<<v41-16-5,5>>^ Quando elas entraram no túmulo, viram um jovem sentado à direita, usando uma veste comprida, branca, e ficaram espantadas.

[[v41-16-6]]

^<<v41-16-6,6>>^ Ele lhes disse: “Não se assustem. Vocês estão procurando Jesus, o Nazareno, que foi morto na estaca. Ele foi levantado; não está aqui. Vejam, este é o lugar onde o colocaram.

[[v41-16-7]]

^<<v41-16-7,7>>^ Agora vão, digam aos discípulos dele e a Pedro: ‘Ele está indo adiante de vocês para a Galileia. Ali o verão, assim como ele lhes disse.’”

[[v41-16-8]]

^<<v41-16-8,8>>^ Então elas saíram e fugiram do túmulo, tremendo e tomadas de emoção. E não disseram nada a ninguém, pois estavam com medo.^&#42;1^

[NOTE]
====
. Segundo antigos manuscritos confiáveis, o Evangelho de Marcos termina com as palavras do v. 8. Veja Ap. A3.
====

'''

xref:041-marcos/041-marcos-015.adoc#v41-15-0[&#60; Capítulo Anterior] | <<v41-16-0,Topo>> | xref:042-lucas/042-lucas-001.adoc#v42-1-0[Próximo Capítulo &#62;]