include::./index.adoc[]

[[v41-3-0]]
=== Segundo Marcos, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v41-3-1]]

^<<v41-3-1,1>>^ Novamente ele entrou numa sinagoga, e ali estava um homem com a mão atrofiada.^&#42;1^

[NOTE]
====
. Ou: “paralisada”.
====

[[v41-3-2]]

^<<v41-3-2,2>>^ Assim, observavam-no atentamente para ver se curaria o homem no sábado, a fim de acusá-lo.

[[v41-3-3]]

^<<v41-3-3,3>>^ Ele disse ao homem com a mão atrofiada:^&#42;1^ “Levante-se e venha para o centro.”

[NOTE]
====
. Ou: “paralisada”.
====

[[v41-3-4]]

^<<v41-3-4,4>>^ A seguir, ele lhes perguntou: “É permitido, no sábado, fazer o bem ou fazer o mal, salvar uma vida^&#42;1^ ou matar?” Mas eles continuaram calados.

[NOTE]
====
. Ou: “alma”.
====

[[v41-3-5]]

^<<v41-3-5,5>>^ Depois de olhar para os que estavam à sua volta, com indignação e profundamente triste com a insensibilidade do coração deles, ele disse ao homem: “Estenda a mão.” Ele a estendeu, e a mão foi restabelecida.

[[v41-3-6]]

^<<v41-3-6,6>>^ Os fariseus saíram então e imediatamente começaram a conspirar^&#42;1^ com os partidários de Herodes contra Jesus, para matá-lo.

[NOTE]
====
. Ou: “se reunir em conselho”.
====

[[v41-3-7]]

^<<v41-3-7,7>>^ Mas Jesus foi para o mar com os seus discípulos, e uma grande multidão da Galileia e da Judeia o seguia.

[[v41-3-8]]

^<<v41-3-8,8>>^ Ao ouvir falar de quantas coisas ele fazia, uma grande multidão foi ao encontro dele, até mesmo de Jerusalém, da Idumeia, do outro lado do Jordão e dos arredores de Tiro e de Sídon.

[[v41-3-9]]

^<<v41-3-9,9>>^ E ele disse aos seus discípulos que mantivessem um pequeno barco à disposição dele, para que a multidão não o apertasse.

[[v41-3-10]]

^<<v41-3-10,10>>^ Visto que ele curava a muitos, todos os que tinham doenças graves se aglomeravam em volta dele para tocá-lo.

[[v41-3-11]]

^<<v41-3-11,11>>^ Até mesmo os espíritos impuros, sempre que o viam, se prostravam diante dele, gritavam e diziam: “Você é o Filho de Deus.”

[[v41-3-12]]

^<<v41-3-12,12>>^ Muitas vezes, porém, ele lhes ordenou com firmeza que não dissessem a outros quem ele era.

[[v41-3-13]]

^<<v41-3-13,13>>^ Ele subiu a um monte e convocou os que ele quis, e eles se dirigiram a ele.

[[v41-3-14]]

^<<v41-3-14,14>>^ Formou^&#42;1^ então um grupo de 12, a quem deu o nome de apóstolos, aqueles que o acompanhariam e que ele enviaria para pregar,

[NOTE]
====
. Ou: “Designou”.
====

[[v41-3-15]]

^<<v41-3-15,15>>^ com autoridade para expulsar demônios.

[[v41-3-16]]

^<<v41-3-16,16>>^ E no grupo dos Doze que ele formou^&#42;1^ estavam Simão (a quem também deu o nome de Pedro),

[NOTE]
====
. Ou: “designou”.
====

[[v41-3-17]]

^<<v41-3-17,17>>^ Tiago, filho de Zebedeu, João, irmão de Tiago (ele também deu a estes o nome de Boanerges, que significa “filhos do trovão”),

[[v41-3-18]]

^<<v41-3-18,18>>^ André, Filipe, Bartolomeu, Mateus, Tomé, Tiago, filho de Alfeu, Tadeu, Simão, o Cananita,^&#42;1^

[NOTE]
====
. Ou: “o zeloso”.
====

[[v41-3-19]]

^<<v41-3-19,19>>^ e Judas Iscariotes, que mais tarde o traiu.
Então ele entrou numa casa,

[[v41-3-20]]

^<<v41-3-20,20>>^ e novamente a multidão se ajuntou, de modo que não podiam sequer tomar uma refeição.

[[v41-3-21]]

^<<v41-3-21,21>>^ Mas, quando os seus parentes souberam do que estava acontecendo, saíram para pegá-lo, pois diziam: “Ele perdeu o juízo.”

[[v41-3-22]]

^<<v41-3-22,22>>^ Também os escribas que desceram de Jerusalém diziam: “Ele está com Belzebu^&#42;1^ e expulsa os demônios por meio do governante dos demônios.”

[NOTE]
====
. Um nome usado para Satanás.
====

[[v41-3-23]]

^<<v41-3-23,23>>^ Portanto, depois de chamá-los, falou-lhes com ilustrações: “Como Satanás pode expulsar a Satanás?

[[v41-3-24]]

^<<v41-3-24,24>>^ Se um reino fica dividido contra si mesmo, esse reino não pode ficar de pé,

[[v41-3-25]]

^<<v41-3-25,25>>^ e, se uma casa fica dividida contra si mesma, essa casa não poderá ficar de pé.

[[v41-3-26]]

^<<v41-3-26,26>>^ Também, se Satanás se levantou contra si mesmo e ficou dividido, não pode ficar de pé, mas está chegando ao fim.

[[v41-3-27]]

^<<v41-3-27,27>>^ De fato, ninguém que entre na casa de um homem forte é capaz de roubar os seus bens, a menos que primeiro amarre o homem forte. Só então poderá saquear a casa dele.

[[v41-3-28]]

^<<v41-3-28,28>>^ Eu lhes digo a verdade: Todas as coisas serão perdoadas aos filhos dos homens, não importa que pecados cometam e que blasfêmias digam.

[[v41-3-29]]

^<<v41-3-29,29>>^ No entanto, quem blasfema contra o espírito santo nunca terá perdão, mas é culpado de pecado eterno.”

[[v41-3-30]]

^<<v41-3-30,30>>^ Jesus disse isso porque diziam: “Ele está com um espírito impuro.”

[[v41-3-31]]

^<<v41-3-31,31>>^ Chegaram então sua mãe e seus irmãos e, ficando do lado de fora, mandaram alguém chamá-lo.

[[v41-3-32]]

^<<v41-3-32,32>>^ Como havia uma multidão sentada em volta dele, disseram-lhe: “Veja! Sua mãe e seus irmãos estão lá fora procurando o senhor.”

[[v41-3-33]]

^<<v41-3-33,33>>^ Mas ele lhes respondeu: “Quem são minha mãe e meus irmãos?”

[[v41-3-34]]

^<<v41-3-34,34>>^ Então ele olhou para os que estavam sentados ao redor dele e disse: “Aqui estão a minha mãe e os meus irmãos!

[[v41-3-35]]

^<<v41-3-35,35>>^ Quem faz a vontade de Deus, esse é meu irmão, minha irmã e minha mãe.”

'''

xref:041-marcos/041-marcos-002.adoc#v41-2-0[&#60; Capítulo Anterior] | <<v41-3-0,Topo>> | xref:041-marcos/041-marcos-004.adoc#v41-4-0[Próximo Capítulo &#62;]