include::./index.adoc[]

[[v43-8-0]]
=== Segundo João, 8
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-8-12]]

^<<v43-8-12,12>>^ Então Jesus se dirigiu novamente a eles e disse: “Eu sou a luz do mundo. Quem me segue de modo algum andará na escuridão, mas terá a luz da vida.”

[[v43-8-13]]

^<<v43-8-13,13>>^ Os fariseus lhe disseram então: “Você dá testemunho de si mesmo; seu testemunho não é verdadeiro.”

[[v43-8-14]]

^<<v43-8-14,14>>^ Jesus lhes respondeu: “Mesmo que eu dê testemunho de mim mesmo, meu testemunho é verdadeiro, porque eu sei de onde vim e para onde vou. Mas vocês não sabem de onde eu vim nem para onde vou.

[[v43-8-15]]

^<<v43-8-15,15>>^ Vocês julgam segundo a carne;^&#42;1^ eu não julgo a ninguém.

[NOTE]
====
. Ou: “segundo padrões humanos”.
====

[[v43-8-16]]

^<<v43-8-16,16>>^ Contudo, mesmo que eu julgue, meu julgamento é verdadeiro, porque não estou sozinho, mas o Pai, que me enviou, está comigo.

[[v43-8-17]]

^<<v43-8-17,17>>^ Também, na própria Lei de vocês está escrito: ‘O testemunho de dois homens é verdadeiro.’

[[v43-8-18]]

^<<v43-8-18,18>>^ Eu sou um que dá testemunho de mim mesmo, e o Pai, que me enviou, dá testemunho de mim.”

[[v43-8-19]]

^<<v43-8-19,19>>^ Então eles lhe perguntaram: “Onde está o seu Pai?” Jesus respondeu: “Vocês não conhecem nem a mim nem ao meu Pai. Se me conhecessem, conheceriam também o meu Pai.”

[[v43-8-20]]

^<<v43-8-20,20>>^ Ele disse essas palavras no local onde ficavam os cofres do tesouro, enquanto ensinava no templo. Mas ninguém o prendeu, pois a sua hora ainda não havia chegado.

[[v43-8-21]]

^<<v43-8-21,21>>^ Novamente, ele lhes disse: “Eu vou embora, e vocês me procurarão, contudo morrerão nos seus pecados. Para onde eu vou, vocês não podem ir.”

[[v43-8-22]]

^<<v43-8-22,22>>^ Então os judeus começaram a dizer: “Será que ele vai se matar? Porque ele diz: ‘Para onde eu vou, vocês não podem ir.’”

[[v43-8-23]]

^<<v43-8-23,23>>^ E ele acrescentou: “Vocês são dos domínios de baixo; eu sou dos domínios de cima. Vocês são deste mundo; eu não sou deste mundo.

[[v43-8-24]]

^<<v43-8-24,24>>^ É por isso que eu lhes disse: Vocês morrerão nos seus pecados. Pois, se vocês não acreditarem em quem eu sou, morrerão nos seus pecados.”

[[v43-8-25]]

^<<v43-8-25,25>>^ Perguntaram-lhe então: “Quem é você?” Jesus lhes disse em resposta: “Por que é que estou falando com vocês?

[[v43-8-26]]

^<<v43-8-26,26>>^ Tenho muitas coisas para falar a respeito de vocês e para julgar. De fato, Aquele que me enviou é verdadeiro, e aquilo que ouvi dele eu digo ao mundo.”

[[v43-8-27]]

^<<v43-8-27,27>>^ Eles não compreenderam que lhes falava do Pai.

[[v43-8-28]]

^<<v43-8-28,28>>^ Então Jesus disse: “Depois que vocês tiverem erguido o Filho do Homem, então saberão que eu sou ele e que não faço nada de minha própria iniciativa, mas falo aquilo que o Pai me ensinou.

[[v43-8-29]]

^<<v43-8-29,29>>^ E Aquele que me enviou está comigo; ele não me deixou só, porque faço sempre o que lhe agrada.”

[[v43-8-30]]

^<<v43-8-30,30>>^ Quando ele disse essas coisas, muitos depositaram fé nele.

[[v43-8-31]]

^<<v43-8-31,31>>^ Então Jesus disse aos judeus que acreditaram nele: “Se vocês permanecerem nas minhas palavras, são realmente meus discípulos;

[[v43-8-32]]

^<<v43-8-32,32>>^ vocês conhecerão a verdade, e a verdade os libertará.”

[[v43-8-33]]

^<<v43-8-33,33>>^ Responderam-lhe: “Somos descendentes de Abraão e nunca fomos escravos de ninguém. Como é que você diz: ‘Vocês ficarão livres’?”

[[v43-8-34]]

^<<v43-8-34,34>>^ Jesus lhes respondeu: “Digo-lhes com toda a certeza: Todo aquele que peca é escravo do pecado.

[[v43-8-35]]

^<<v43-8-35,35>>^ Além disso, o escravo não permanece na casa para sempre; o filho permanece para sempre.

[[v43-8-36]]

^<<v43-8-36,36>>^ Portanto, se o Filho os libertar, vocês serão realmente livres.

[[v43-8-37]]

^<<v43-8-37,37>>^ Sei que vocês são descendentes de Abraão. Mas vocês procuram me matar, porque não aceitam as minhas palavras.^&#42;1^

[NOTE]
====
. Ou: “porque a minha palavra não faz progresso entre vocês”.
====

[[v43-8-38]]

^<<v43-8-38,38>>^ Eu falo do que vi enquanto estava com o meu Pai, mas vocês fazem o que ouviram do seu pai.”

[[v43-8-39]]

^<<v43-8-39,39>>^ Em resposta, eles lhe disseram: “Nosso pai é Abraão.” Jesus lhes disse: “Se vocês fossem filhos de Abraão, fariam as obras de Abraão.

[[v43-8-40]]

^<<v43-8-40,40>>^ Mas o fato é que vocês procuram matar a mim, um homem que lhes disse a verdade que ouviu de Deus. Abraão não agiu assim.

[[v43-8-41]]

^<<v43-8-41,41>>^ Vocês fazem as obras do seu pai.” Eles lhe disseram: “Não nascemos de imoralidade.^&#42;1^ Temos um só Pai, Deus.”

[NOTE]
====
. Ou: “imoralidade sexual”. Em grego, porneía. Veja o Glossário.
====

[[v43-8-42]]

^<<v43-8-42,42>>^ Jesus lhes disse: “Se Deus fosse o seu Pai, vocês me amariam, pois vim de Deus e estou aqui. Eu não vim de minha própria iniciativa, mas foi ele que me enviou.

[[v43-8-43]]

^<<v43-8-43,43>>^ Por que vocês não entendem o que estou dizendo? Porque são incapazes de ouvir as minhas palavras.

[[v43-8-44]]

^<<v43-8-44,44>>^ Vocês são filhos do seu pai, o Diabo, e querem satisfazer os desejos do seu pai. Ele foi um assassino quando começou,^&#42;1^ e não permaneceu na verdade, porque nele não há verdade. Quando ele fala a mentira, está fazendo o que lhe é próprio, porque é um mentiroso e o pai da mentira.

[NOTE]
====
. Ou: “desde o princípio”.
====

[[v43-8-45]]

^<<v43-8-45,45>>^ Por outro lado, visto que eu lhes digo a verdade, vocês não acreditam em mim.

[[v43-8-46]]

^<<v43-8-46,46>>^ Quem de vocês me declara culpado de pecado? Se eu falo a verdade, por que é que não acreditam em mim?

[[v43-8-47]]

^<<v43-8-47,47>>^ Quem é de Deus escuta as declarações de Deus. É por isso que vocês não escutam, porque não são de Deus.”

[[v43-8-48]]

^<<v43-8-48,48>>^ Em resposta, os judeus lhe disseram: “Não estamos certos em dizer que você é samaritano e tem demônio?”

[[v43-8-49]]

^<<v43-8-49,49>>^ Jesus respondeu: “Eu não tenho demônio, mas honro o meu Pai, e vocês me desonram.

[[v43-8-50]]

^<<v43-8-50,50>>^ Mas não procuro glória para mim mesmo; há Alguém que procura, e ele julga.

[[v43-8-51]]

^<<v43-8-51,51>>^ Digo-lhes com toda a certeza: Se alguém obedecer às minhas palavras, nunca jamais verá a morte.”

[[v43-8-52]]

^<<v43-8-52,52>>^ Os judeus lhe disseram: “Agora sabemos que você tem demônio. Abraão morreu, os profetas também, mas você diz: ‘Se alguém obedecer às minhas palavras, nunca jamais provará a morte.’

[[v43-8-53]]

^<<v43-8-53,53>>^ Será que você é maior do que nosso pai Abraão, que morreu? Os profetas também morreram. Quem você pensa que é?”

[[v43-8-54]]

^<<v43-8-54,54>>^ Jesus respondeu: “Se eu glorificar a mim mesmo, a minha glória não é nada. É o meu Pai quem me glorifica, aquele que vocês dizem ser o seu Deus.

[[v43-8-55]]

^<<v43-8-55,55>>^ No entanto, vocês não o conhecem, mas eu o conheço. E, se eu dissesse que não o conheço, seria um mentiroso, como vocês. Mas eu o conheço e obedeço à sua palavra.

[[v43-8-56]]

^<<v43-8-56,56>>^ Abraão, o pai de vocês, alegrou-se muito com a perspectiva de ver o meu dia, e ele o viu e se alegrou.”

[[v43-8-57]]

^<<v43-8-57,57>>^ Então os judeus lhe disseram: “Você não tem nem 50 anos, e ainda assim viu Abraão?”

[[v43-8-58]]

^<<v43-8-58,58>>^ Jesus lhes disse: “Digo-lhes com toda a certeza: Antes de Abraão vir à existência, eu já existia.”

[[v43-8-59]]

^<<v43-8-59,59>>^ Assim, apanharam pedras para atirar nele, mas Jesus se escondeu e saiu do templo.

'''

xref:043-joao/043-joao-007.adoc#v43-7-0[&#60; Capítulo Anterior] | <<v43-8-0,Topo>> | xref:043-joao/043-joao-009.adoc#v43-9-0[Próximo Capítulo &#62;]