include::./index.adoc[]

[[v43-13-0]]
=== Segundo João, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-13-1]]

^<<v43-13-1,1>>^ Jesus sabia, antes da Festividade da Páscoa, que havia chegado a hora de deixar este mundo e ir para o Pai. Assim, tendo amado os seus que estavam no mundo, ele os amou até o fim.

[[v43-13-2]]

^<<v43-13-2,2>>^ Eles estavam tomando a refeição,^&#42;1^ e o Diabo já tinha posto no coração de Judas Iscariotes, filho de Simão, que o traísse.

[NOTE]
====
. Ou: “ceia”, referindo-se à Páscoa.
====

[[v43-13-3]]

^<<v43-13-3,3>>^ Jesus sabia que o Pai tinha entregado todas as coisas nas suas mãos e que tinha vindo de Deus e estava indo para Deus;

[[v43-13-4]]

^<<v43-13-4,4>>^ assim, ele se levantou da mesa e tirou a sua capa.^&#42;1^ Pegou então uma toalha e a amarrou na cintura.^&#42;2^

[NOTE]
====
. Ou: “as suas roupas exteriores”.
. Ou: “e cingiu-se”.
====

[[v43-13-5]]

^<<v43-13-5,5>>^ Depois, colocou água numa bacia e começou a lavar os pés dos discípulos e a enxugá-los com a toalha que tinha na cintura.^&#42;1^

[NOTE]
====
. Ou: “toalha da qual estava cingido”.
====

[[v43-13-6]]

^<<v43-13-6,6>>^ Então chegou a Simão Pedro. Este lhe disse: “Senhor, vai lavar os meus pés?”

[[v43-13-7]]

^<<v43-13-7,7>>^ Jesus lhe respondeu: “O que estou fazendo, você não entende agora, mas entenderá depois dessas coisas.”

[[v43-13-8]]

^<<v43-13-8,8>>^ Pedro lhe disse: “O senhor nunca lavará os meus pés.” Jesus disse então: “Se eu não lavar você, você não tem parte comigo.”

[[v43-13-9]]

^<<v43-13-9,9>>^ Simão Pedro lhe respondeu: “Senhor, então lave não só os meus pés, mas também as minhas mãos e a minha cabeça.”

[[v43-13-10]]

^<<v43-13-10,10>>^ Jesus lhe disse: “Quem se banhou está completamente limpo e não precisa lavar nada, só os pés. E vocês estão limpos, mas nem todos.”

[[v43-13-11]]

^<<v43-13-11,11>>^ Pois ele sabia quem o estava traindo. É por isso que disse: “Nem todos vocês estão limpos.”

[[v43-13-12]]

^<<v43-13-12,12>>^ Então, depois de lavar os pés deles e pôr a sua capa,^&#42;1^ ele se recostou novamente à mesa e lhes disse: “Vocês entendem o que eu lhes fiz?

[NOTE]
====
. Ou: “as suas roupas exteriores”.
====

[[v43-13-13]]

^<<v43-13-13,13>>^ Vocês me chamam de ‘Instrutor’ e ‘Senhor’, e estão certos, pois eu sou mesmo.

[[v43-13-14]]

^<<v43-13-14,14>>^ Portanto, se eu, o Senhor e Instrutor, lavei os seus pés, vocês também devem^&#42;1^ lavar os pés uns dos outros.

[NOTE]
====
. Ou: “também têm a obrigação de”.
====

[[v43-13-15]]

^<<v43-13-15,15>>^ Pois estabeleci o modelo para vocês, a fim de que, assim como eu lhes fiz, vocês também façam.

[[v43-13-16]]

^<<v43-13-16,16>>^ Digo-lhes com toda a certeza: O escravo não é maior do que o seu senhor, nem o enviado é maior do que aquele que o enviou.

[[v43-13-17]]

^<<v43-13-17,17>>^ Se vocês sabem essas coisas, felizes serão se as praticarem.

[[v43-13-18]]

^<<v43-13-18,18>>^ Não estou falando a respeito de todos vocês; conheço os que eu escolhi. Mas é para que se cumpra esta passagem das Escrituras: ‘Aquele que comia do meu pão se voltou contra mim.’^&#42;1^

[NOTE]
====
. Lit.: “levantou seu calcanhar contra mim”.
====

[[v43-13-19]]

^<<v43-13-19,19>>^ Digo-lhes isso agora, antes que ocorra, para que, quando ocorrer, acreditem em quem eu sou.

[[v43-13-20]]

^<<v43-13-20,20>>^ Digo-lhes com toda a certeza: Quem recebe a qualquer um que eu envio recebe também a mim, e quem me recebe, recebe também Aquele que me enviou.”

[[v43-13-21]]

^<<v43-13-21,21>>^ Depois de dizer isso, Jesus ficou profundamente angustiado, e declarou:^&#42;1^ “Digo-lhes com toda a certeza: Um de vocês me trairá.”

[NOTE]
====
. Ou: “e deu testemunho, dizendo”.
====

[[v43-13-22]]

^<<v43-13-22,22>>^ Os discípulos começaram a olhar uns para os outros, sem saber sobre qual deles ele estava falando.

[[v43-13-23]]

^<<v43-13-23,23>>^ Um dos seus discípulos, aquele a quem Jesus amava, estava recostado junto^&#42;1^ de Jesus.

[NOTE]
====
. Lit.: “ao seio”.
====

[[v43-13-24]]

^<<v43-13-24,24>>^ Portanto, Simão Pedro acenou com a cabeça para esse discípulo e lhe disse: “Diga-nos a respeito de quem ele está falando.”

[[v43-13-25]]

^<<v43-13-25,25>>^ De modo que ele se encostou no peito de Jesus e lhe perguntou: “Senhor, quem é?”

[[v43-13-26]]

^<<v43-13-26,26>>^ Jesus respondeu: “É aquele a quem eu der o pedaço de pão que vou molhar na tigela.” Então, depois de molhar o pão, ele o deu a Judas, filho de Simão Iscariotes.

[[v43-13-27]]

^<<v43-13-27,27>>^ Depois que Judas pegou o pedaço de pão, Satanás entrou nele. Então Jesus lhe disse: “Faça mais depressa o que você está fazendo.”

[[v43-13-28]]

^<<v43-13-28,28>>^ Mas nenhum dos que se recostavam à mesa entendeu por que ele lhe disse isso.

[[v43-13-29]]

^<<v43-13-29,29>>^ De fato, visto que Judas cuidava da caixa de dinheiro, alguns pensavam que Jesus estava lhe dizendo: “Compre o que precisamos para a festividade”, ou que devia dar algo aos pobres.

[[v43-13-30]]

^<<v43-13-30,30>>^ Assim, depois de receber o pedaço de pão, ele saiu imediatamente. Era noite.

[[v43-13-31]]

^<<v43-13-31,31>>^ Portanto, depois que ele saiu, Jesus disse: “Agora o Filho do Homem é glorificado, e Deus é glorificado por meio dele.

[[v43-13-32]]

^<<v43-13-32,32>>^ O próprio Deus o glorificará, e o glorificará imediatamente.

[[v43-13-33]]

^<<v43-13-33,33>>^ Filhinhos, estou com vocês mais um pouco. Vocês me procurarão e, assim como eu disse aos judeus, agora digo também a vocês: ‘Para onde eu vou, vocês não podem ir.’

[[v43-13-34]]

^<<v43-13-34,34>>^ Eu lhes dou um novo mandamento: Amem uns aos outros; assim como eu amei vocês, amem também uns aos outros.

[[v43-13-35]]

^<<v43-13-35,35>>^ Por meio disto todos saberão que vocês são meus discípulos: se tiverem amor entre si.”

[[v43-13-36]]

^<<v43-13-36,36>>^ Simão Pedro lhe disse: “Senhor, para onde vai?” Jesus respondeu: “Para onde eu vou, você não pode me seguir agora, mas me seguirá depois.”

[[v43-13-37]]

^<<v43-13-37,37>>^ Pedro lhe disse: “Senhor, por que não posso segui-lo agora? Eu darei a minha vida^&#42;1^ pelo senhor.”

[NOTE]
====
. Ou: “alma”.
====

[[v43-13-38]]

^<<v43-13-38,38>>^ Jesus respondeu: “Você dará a sua vida^&#42;1^ por mim? Digo-lhe com toda a certeza: O galo de modo algum cantará até que você tenha me negado três vezes.”

[NOTE]
====
. Ou: “alma”.
====

'''

xref:043-joao/043-joao-012.adoc#v43-12-0[&#60; Capítulo Anterior] | <<v43-13-0,Topo>> | xref:043-joao/043-joao-014.adoc#v43-14-0[Próximo Capítulo &#62;]