include::./index.adoc[]

[[v43-10-0]]
=== Segundo João, 10
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-10-1]]

^<<v43-10-1,1>>^ “Digo-lhes com toda a certeza: Quem não entra no aprisco das ovelhas pela porta, mas sobe por outro lugar, é ladrão e saqueador.

[[v43-10-2]]

^<<v43-10-2,2>>^ Mas quem entra pela porta é o pastor das ovelhas.

[[v43-10-3]]

^<<v43-10-3,3>>^ O porteiro abre para ele, e as ovelhas escutam a sua voz. Ele chama por nome as suas ovelhas e as leva para fora.

[[v43-10-4]]

^<<v43-10-4,4>>^ Depois de retirar todas as suas ovelhas, ele vai à frente delas, e elas o seguem, porque conhecem a sua voz.

[[v43-10-5]]

^<<v43-10-5,5>>^ De modo algum seguirão um estranho, mas fugirão dele, porque não conhecem a voz de estranhos.”

[[v43-10-6]]

^<<v43-10-6,6>>^ Jesus fez essa comparação, mas eles não entenderam o que ele lhes disse.

[[v43-10-7]]

^<<v43-10-7,7>>^ Por isso, Jesus disse de novo: “Digo-lhes com toda a certeza: Eu sou a porta das ovelhas.

[[v43-10-8]]

^<<v43-10-8,8>>^ Todos os que vieram em meu lugar são ladrões e saqueadores; mas as ovelhas não os escutaram.

[[v43-10-9]]

^<<v43-10-9,9>>^ Eu sou a porta. Quem entrar por mim será salvo; entrará e sairá, e achará pastagem.

[[v43-10-10]]

^<<v43-10-10,10>>^ O ladrão só vem para furtar, matar e destruir. Eu vim para que tivessem vida, e a tivessem na mais plena medida.

[[v43-10-11]]

^<<v43-10-11,11>>^ Eu sou o bom pastor; o bom pastor dá a sua vida^&#42;1^ pelas ovelhas.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-12]]

^<<v43-10-12,12>>^ O empregado, que não é pastor e a quem não pertencem as ovelhas, quando vê o lobo chegando, abandona as ovelhas e foge, e o lobo as ataca e espalha;

[[v43-10-13]]

^<<v43-10-13,13>>^ ele foge porque é um empregado e não se importa com as ovelhas.

[[v43-10-14]]

^<<v43-10-14,14>>^ Eu sou o bom pastor. Conheço as minhas ovelhas, e as minhas ovelhas me conhecem,

[[v43-10-15]]

^<<v43-10-15,15>>^ assim como o Pai me conhece e eu conheço o Pai; e eu dou a minha vida^&#42;1^ pelas ovelhas.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-16]]

^<<v43-10-16,16>>^ “E tenho outras ovelhas, que não são desse aprisco; a essas também tenho de trazer, e elas escutarão a minha voz e se tornarão um só rebanho, com um só pastor.

[[v43-10-17]]

^<<v43-10-17,17>>^ É por isso que o Pai me ama, porque entrego a minha vida,^&#42;1^ para que eu possa recebê-la de novo.

[NOTE]
====
. Ou: “alma”.
====

[[v43-10-18]]

^<<v43-10-18,18>>^ Ninguém a tira de mim, mas eu a entrego de minha própria iniciativa. Tenho o direito^&#42;1^ de entregá-la e tenho o direito^&#42;2^ de recebê-la de novo. Recebi esse mandamento do meu Pai.”

[NOTE]
====
. Lit.: “autoridade”.
. Lit.: “autoridade”.
====

[[v43-10-19]]

^<<v43-10-19,19>>^ Surgiu novamente uma divisão entre os judeus por causa dessas palavras.

[[v43-10-20]]

^<<v43-10-20,20>>^ Muitos deles diziam: “Ele tem demônio e está louco. Por que vocês o escutam?”

[[v43-10-21]]

^<<v43-10-21,21>>^ Outros diziam: “Essas não são declarações de um homem endemoninhado. Será que um demônio pode abrir os olhos de cegos?”

[[v43-10-22]]

^<<v43-10-22,22>>^ Ocorreu então a Festividade da Dedicação em Jerusalém. Era inverno,

[[v43-10-23]]

^<<v43-10-23,23>>^ e Jesus estava andando no templo, no Pórtico^&#42;1^ de Salomão.

[NOTE]
====
. Ou: “na Colunata”.
====

[[v43-10-24]]

^<<v43-10-24,24>>^ Então os judeus o rodearam e lhe disseram: “Por quanto tempo você nos deixará^&#42;1^ na dúvida? Se você é o Cristo, diga-nos claramente.”

[NOTE]
====
. Ou: “você deixará as nossas almas”.
====

[[v43-10-25]]

^<<v43-10-25,25>>^ Jesus lhes respondeu: “Eu lhes disse, e mesmo assim vocês não acreditam. As obras que eu faço em nome do meu Pai dão testemunho de mim.

[[v43-10-26]]

^<<v43-10-26,26>>^ Mas vocês não acreditam porque não são minhas ovelhas.

[[v43-10-27]]

^<<v43-10-27,27>>^ Minhas ovelhas escutam a minha voz; eu as conheço, e elas me seguem.

[[v43-10-28]]

^<<v43-10-28,28>>^ Eu lhes dou vida eterna, e elas jamais serão destruídas, e ninguém as arrancará da minha mão.

[[v43-10-29]]

^<<v43-10-29,29>>^ O que o meu Pai me deu é maior do que todas as outras coisas, e ninguém pode arrancá-las da mão do Pai.

[[v43-10-30]]

^<<v43-10-30,30>>^ Eu e o Pai somos um.”^&#42;1^

[NOTE]
====
. Ou: “estamos em união”.
====

[[v43-10-31]]

^<<v43-10-31,31>>^ Mais uma vez, os judeus apanharam pedras para apedrejá-lo.

[[v43-10-32]]

^<<v43-10-32,32>>^ Então Jesus lhes disse: “Eu lhes mostrei muitas boas obras da parte do Pai. Por qual dessas obras vocês vão me apedrejar?”

[[v43-10-33]]

^<<v43-10-33,33>>^ Os judeus lhe responderam: “Nós não vamos apedrejá-lo por uma boa obra, mas por blasfêmia; pois você, embora seja um homem, se faz um deus.”

[[v43-10-34]]

^<<v43-10-34,34>>^ Jesus lhes respondeu: “Não está escrito na sua Lei: ‘Eu disse: “Vocês são deuses”’?^&#42;1^

[NOTE]
====
. Ou: “seres divinos”.
====

[[v43-10-35]]

^<<v43-10-35,35>>^ Se aqueles contra quem se dirigiu a palavra de Deus foram chamados de ‘deuses’ — e as Escrituras não podem ser anuladas —,

[[v43-10-36]]

^<<v43-10-36,36>>^ vocês dizem a mim, a quem o Pai santificou e enviou ao mundo: ‘Você blasfema’, porque eu disse: ‘Sou Filho de Deus’?

[[v43-10-37]]

^<<v43-10-37,37>>^ Se não faço as obras do meu Pai, não acreditem em mim.

[[v43-10-38]]

^<<v43-10-38,38>>^ Mas, se eu as faço, mesmo que não acreditem em mim, acreditem nas obras, para que saibam e acreditem que o Pai está em união comigo e eu em união com o Pai.”

[[v43-10-39]]

^<<v43-10-39,39>>^ Então mais uma vez tentaram prendê-lo, mas ele escapou.

[[v43-10-40]]

^<<v43-10-40,40>>^ E ele se retirou novamente para o outro lado do Jordão, para o lugar onde João batizava no princípio, e ficou ali.

[[v43-10-41]]

^<<v43-10-41,41>>^ Muitos foram ao encontro dele, e diziam: “João não realizou nenhum sinal, mas todas as coisas que João disse a respeito deste homem eram verdadeiras.”

[[v43-10-42]]

^<<v43-10-42,42>>^ E muitos ali depositaram fé nele.

'''

xref:043-joao/043-joao-009.adoc#v43-9-0[&#60; Capítulo Anterior] | <<v43-10-0,Topo>> | xref:043-joao/043-joao-011.adoc#v43-11-0[Próximo Capítulo &#62;]