include::./index.adoc[]

[[v43-21-0]]
=== Segundo João, 21
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-21-1]]

^<<v43-21-1,1>>^ Depois disso, Jesus apareceu novamente aos discípulos junto ao mar de Tiberíades. Ele apareceu do seguinte modo:

[[v43-21-2]]

^<<v43-21-2,2>>^ estavam juntos Simão Pedro, Tomé (que era chamado Gêmeo), Natanael, de Caná da Galileia, os filhos de Zebedeu e mais dois dos seus discípulos.

[[v43-21-3]]

^<<v43-21-3,3>>^ Simão Pedro lhes disse: “Vou pescar.” Eles lhe disseram: “Nós vamos com você.” Assim, foram e entraram no barco, mas durante aquela noite não apanharam nada.

[[v43-21-4]]

^<<v43-21-4,4>>^ Ao amanhecer, Jesus estava na praia, mas os discípulos não perceberam que era Jesus.

[[v43-21-5]]

^<<v43-21-5,5>>^ Então Jesus lhes perguntou: “Filhos, vocês têm alguma coisa^&#42;1^ para comer?” Eles responderam: “Não.”

[NOTE]
====
. Ou: “algum peixe”.
====

[[v43-21-6]]

^<<v43-21-6,6>>^ Ele lhes disse: “Lancem a rede do lado direito do barco e acharão.” Então eles a lançaram, mas não conseguiram recolhê-la, por causa da grande quantidade de peixes.

[[v43-21-7]]

^<<v43-21-7,7>>^ Então, o discípulo a quem Jesus amava disse a Pedro: “É o Senhor!” Ao ouvir que era o Senhor, Simão Pedro vestiu^&#42;1^ sua roupa, pois estava nu,^&#42;2^ e se lançou no mar.

[NOTE]
====
. Ou: “cingiu-se de”.
. Ou: “pouco vestido”.
====

[[v43-21-8]]

^<<v43-21-8,8>>^ Mas os outros discípulos vieram no pequeno barco, arrastando a rede cheia de peixes, pois não estavam longe da terra, a apenas cerca de 90 metros.^&#42;1^

[NOTE]
====
. Lit.: “cerca de 200 côvados”. Veja Ap. B14.
====

[[v43-21-9]]

^<<v43-21-9,9>>^ Quando desembarcaram em terra, viram ali um fogo, com peixe sobre as brasas, e pão.

[[v43-21-10]]

^<<v43-21-10,10>>^ Jesus lhes disse: “Tragam alguns dos peixes que vocês acabaram de apanhar.”

[[v43-21-11]]

^<<v43-21-11,11>>^ Então Simão Pedro subiu a bordo e puxou a rede para a terra; ela estava cheia de peixes, 153 peixes grandes. Embora houvesse tantos, a rede não se rompeu.

[[v43-21-12]]

^<<v43-21-12,12>>^ Jesus lhes disse: “Venham comer.” Nenhum dos discípulos tinha coragem de lhe perguntar quem ele era, porque sabiam que era o Senhor.

[[v43-21-13]]

^<<v43-21-13,13>>^ Jesus foi, pegou o pão e deu a eles, e fez o mesmo com o peixe.

[[v43-21-14]]

^<<v43-21-14,14>>^ Essa foi a terceira vez que Jesus apareceu aos discípulos depois de ter sido levantado dentre os mortos.

[[v43-21-15]]

^<<v43-21-15,15>>^ Quando terminaram de comer, Jesus perguntou a Simão Pedro: “Simão, filho de João, você me ama mais do que a estes?” Ele lhe respondeu: “Sim, Senhor; o senhor sabe que eu o amo.”^&#42;1^ Ele lhe disse: “Alimente os meus cordeiros.”

[NOTE]
====
. Ou: “que eu tenho afeição pelo senhor”.
====

[[v43-21-16]]

^<<v43-21-16,16>>^ Novamente ele lhe perguntou, pela segunda vez: “Simão, filho de João, você me ama?” Ele lhe respondeu: “Sim, Senhor; o senhor sabe que eu o amo.”^&#42;1^ Ele lhe disse: “Pastoreie as minhas ovelhinhas.”

[NOTE]
====
. Ou: “que eu tenho afeição pelo senhor”.
====

[[v43-21-17]]

^<<v43-21-17,17>>^ Ele lhe perguntou pela terceira vez: “Simão, filho de João, você me ama?”^&#42;1^ Pedro ficou triste por ele lhe perguntar pela terceira vez: “Você me ama?”^&#42;2^ Por isso, ele lhe disse: “Senhor, o senhor sabe todas as coisas. O senhor sabe que eu o amo.”^&#42;3^ Jesus lhe disse: “Alimente as minhas ovelhinhas.

[NOTE]
====
. Ou: “você tem afeição por mim”.
. Ou: “Você tem afeição por mim?”
. Ou: “que eu tenho afeição pelo senhor”.
====

[[v43-21-18]]

^<<v43-21-18,18>>^ Digo-lhe com toda a certeza: Quando você era mais jovem, você se vestia e andava por onde queria. Mas, quando envelhecer, estenderá as mãos, e outro homem o vestirá e o levará para onde você não quer.”

[[v43-21-19]]

^<<v43-21-19,19>>^ Disse isso para indicar com que tipo de morte ele glorificaria a Deus. Depois de dizer isso, disse-lhe: “Continue a me seguir.”

[[v43-21-20]]

^<<v43-21-20,20>>^ Pedro se virou e viu que o discípulo que Jesus amava os seguia, aquele que na refeição havia se encostado no peito dele e dito: “Senhor, quem é que o trai?”

[[v43-21-21]]

^<<v43-21-21,21>>^ Portanto, quando o viu, Pedro disse a Jesus: “Senhor, e o que acontecerá a este homem?”

[[v43-21-22]]

^<<v43-21-22,22>>^ Jesus lhe disse: “Se eu quiser que ele permaneça até eu vir, o que importa isso a você? Continue você a me seguir.”

[[v43-21-23]]

^<<v43-21-23,23>>^ Assim, espalhou-se entre os irmãos que esse discípulo não ia morrer. No entanto, Jesus não lhe disse que ele não ia morrer, mas disse: “Se eu quiser que ele permaneça até eu vir, o que importa isso a você?”

[[v43-21-24]]

^<<v43-21-24,24>>^ Esse é o discípulo que dá testemunho dessas coisas e que escreveu essas coisas, e nós sabemos que o testemunho dele é verdadeiro.

[[v43-21-25]]

^<<v43-21-25,25>>^ De fato, há também muitas outras coisas que Jesus fez. Se fossem escritas em todos os detalhes, suponho que o próprio mundo não poderia conter os rolos escritos.

'''

xref:043-joao/043-joao-020.adoc#v43-20-0[&#60; Capítulo Anterior] | <<v43-21-0,Topo>> | xref:044-atos/044-atos-001.adoc#v44-1-0[Próximo Capítulo &#62;]