include::./index.adoc[]

[[v43-15-0]]
=== Segundo João, 15
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-15-1]]

^<<v43-15-1,1>>^ “Eu sou a verdadeira videira, e o meu Pai é o lavrador.

[[v43-15-2]]

^<<v43-15-2,2>>^ Ele tira todo ramo em mim que não dá fruto, e limpa todo ramo que dá fruto, para que dê mais fruto.

[[v43-15-3]]

^<<v43-15-3,3>>^ Vocês já estão limpos, por causa da palavra que lhes falei.

[[v43-15-4]]

^<<v43-15-4,4>>^ Permaneçam em união comigo, e eu permanecerei em união com vocês. Assim como um ramo não pode dar fruto por si mesmo a menos que permaneça na videira, vocês também não podem dar fruto a menos que permaneçam em união comigo.

[[v43-15-5]]

^<<v43-15-5,5>>^ Eu sou a videira; vocês são os ramos. Quem permanece em união comigo, e eu em união com ele, esse dá muito fruto, pois separados de mim vocês não podem fazer nada.

[[v43-15-6]]

^<<v43-15-6,6>>^ Se alguém não permanece em união comigo, ele é lançado fora como um ramo, e seca. Esses ramos são ajuntados, jogados no fogo e queimados.

[[v43-15-7]]

^<<v43-15-7,7>>^ Se vocês permanecerem em união comigo e as minhas declarações permanecerem em vocês, peçam o que quiserem e assim lhes acontecerá.

[[v43-15-8]]

^<<v43-15-8,8>>^ Isto glorifica o meu Pai: que vocês persistam em dar muito fruto e mostrem que são meus discípulos.

[[v43-15-9]]

^<<v43-15-9,9>>^ Assim como o Pai me ama, eu amo vocês; permaneçam no meu amor.

[[v43-15-10]]

^<<v43-15-10,10>>^ Se vocês obedecerem aos meus mandamentos, permanecerão no meu amor, assim como eu obedeço aos mandamentos do Pai e permaneço no amor dele.

[[v43-15-11]]

^<<v43-15-11,11>>^ “Eu lhes disse essas coisas para que vocês sintam a mesma alegria que eu,^&#42;1^ e a sua alegria se torne plena.

[NOTE]
====
. Ou: “para que a minha alegria esteja em vocês”.
====

[[v43-15-12]]

^<<v43-15-12,12>>^ Este é o meu mandamento: Amem uns aos outros, assim como eu amei vocês.

[[v43-15-13]]

^<<v43-15-13,13>>^ Ninguém tem maior amor do que aquele que dá a sua vida^&#42;1^ pelos seus amigos.

[NOTE]
====
. Ou: “alma”.
====

[[v43-15-14]]

^<<v43-15-14,14>>^ Vocês são meus amigos, se fizerem o que lhes mando.

[[v43-15-15]]

^<<v43-15-15,15>>^ Não os chamo mais de escravos, porque o escravo não sabe o que o seu senhor faz. Mas eu os chamo de amigos, porque lhes revelei tudo que ouvi do meu Pai.

[[v43-15-16]]

^<<v43-15-16,16>>^ Vocês não me escolheram, mas eu escolhi vocês, e eu os designei para irem e continuarem dando fruto, fruto que permaneça, para que, não importa o que pedirem ao Pai em meu nome, ele dê a vocês.

[[v43-15-17]]

^<<v43-15-17,17>>^ “Eu lhes ordeno essas coisas para que amem uns aos outros.

[[v43-15-18]]

^<<v43-15-18,18>>^ Se o mundo os odeia, vocês sabem^&#42;1^ que odiou a mim antes de odiar vocês.

[NOTE]
====
. Ou: “odeia, saibam”.
====

[[v43-15-19]]

^<<v43-15-19,19>>^ Se vocês fizessem parte do mundo, o mundo os amaria por pertencerem a ele. Agora, visto que vocês não fazem parte do mundo, mas eu os escolhi do mundo, por isso o mundo os odeia.

[[v43-15-20]]

^<<v43-15-20,20>>^ Lembrem-se do que eu lhes disse: O escravo não é maior do que o seu senhor. Se perseguiram a mim, perseguirão também a vocês; se obedeceram às minhas palavras, obedecerão também às suas.

[[v43-15-21]]

^<<v43-15-21,21>>^ Mas farão todas essas coisas contra vocês por causa do meu nome, porque não conhecem Aquele que me enviou.

[[v43-15-22]]

^<<v43-15-22,22>>^ Se eu não tivesse vindo e falado com eles, não seriam culpados de pecado. Mas agora eles não têm desculpa para o seu pecado.

[[v43-15-23]]

^<<v43-15-23,23>>^ Quem me odeia, também odeia o meu Pai.

[[v43-15-24]]

^<<v43-15-24,24>>^ Se eu não tivesse feito entre eles as obras que ninguém mais fez, não seriam culpados de pecado; mas agora eles me viram e odiaram a mim e ao meu Pai.

[[v43-15-25]]

^<<v43-15-25,25>>^ Mas isso aconteceu para que se cumprissem as palavras escritas na Lei deles: ‘Odiaram-me sem motivo.’

[[v43-15-26]]

^<<v43-15-26,26>>^ Quando vier o ajudador que eu lhes enviarei da parte do Pai, o espírito da verdade, que vem do Pai, esse dará testemunho de mim;

[[v43-15-27]]

^<<v43-15-27,27>>^ e vocês, por sua vez, darão testemunho, porque estiveram comigo desde o começo.

'''

xref:043-joao/043-joao-014.adoc#v43-14-0[&#60; Capítulo Anterior] | <<v43-15-0,Topo>> | xref:043-joao/043-joao-016.adoc#v43-16-0[Próximo Capítulo &#62;]