include::./index.adoc[]

[[v43-16-0]]
=== Segundo João, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-16-1]]

^<<v43-16-1,1>>^ “Eu lhes disse essas coisas para que vocês não tropecem.

[[v43-16-2]]

^<<v43-16-2,2>>^ Os homens os expulsarão da sinagoga. De fato, vem a hora em que quem matar vocês pensará que está prestando um serviço sagrado a Deus.

[[v43-16-3]]

^<<v43-16-3,3>>^ Mas eles farão isso porque não conhecem nem ao Pai nem a mim.

[[v43-16-4]]

^<<v43-16-4,4>>^ Contudo, eu lhes disse essas coisas para que, quando chegar a hora de acontecerem, vocês se lembrem de que lhes falei delas.
“Eu não lhes disse essas coisas no princípio porque eu estava com vocês.

[[v43-16-5]]

^<<v43-16-5,5>>^ Mas agora vou para Aquele que me enviou; mesmo assim, nenhum de vocês me pergunta: ‘Para onde o senhor vai?’

[[v43-16-6]]

^<<v43-16-6,6>>^ Pelo contrário, o coração de vocês está cheio de tristeza porque eu lhes disse essas coisas.

[[v43-16-7]]

^<<v43-16-7,7>>^ Contudo, eu lhes digo a verdade: É em seu benefício que vou embora. Pois, se eu não for embora, o ajudador não virá a vocês; mas, se eu for, o enviarei a vocês.

[[v43-16-8]]

^<<v43-16-8,8>>^ E, quando ele vier, dará ao mundo provas convincentes do pecado, da justiça e do julgamento:

[[v43-16-9]]

^<<v43-16-9,9>>^ primeiro, do pecado, porque eles não exercem fé em mim;

[[v43-16-10]]

^<<v43-16-10,10>>^ depois, da justiça, porque vou para o Pai e vocês não me verão mais;

[[v43-16-11]]

^<<v43-16-11,11>>^ então, do julgamento, porque o governante deste mundo foi julgado.

[[v43-16-12]]

^<<v43-16-12,12>>^ “Ainda tenho muitas coisas para lhes dizer, mas agora vocês não são capazes de suportá-las.

[[v43-16-13]]

^<<v43-16-13,13>>^ No entanto, quando ele^&#42;1^ vier, o espírito da verdade, ele os guiará a toda a verdade, pois não falará de sua própria iniciativa, mas falará o que ouvir e declarará a vocês as coisas que virão.

[NOTE]
====
. “Ele”, tanto no v. 13 como no v. 14, se refere ao “ajudador” mencionado no v. 7. Jesus usou “o ajudador” (que é do gênero masculino em grego) como personificação do espírito santo, uma força impessoal, que é do gênero neutro em grego.
====

[[v43-16-14]]

^<<v43-16-14,14>>^ Ele me glorificará, porque receberá do que é meu e o declarará a vocês.

[[v43-16-15]]

^<<v43-16-15,15>>^ Tudo que o Pai tem é meu. É por isso que eu disse que ele receberá do que é meu e o declarará a vocês.

[[v43-16-16]]

^<<v43-16-16,16>>^ Em breve vocês não me verão mais; e também em breve vocês me verão.”

[[v43-16-17]]

^<<v43-16-17,17>>^ Em vista disso, alguns dos seus discípulos disseram uns aos outros: “O que ele quer dizer com: ‘Em breve vocês não me verão; e também em breve vocês me verão’ e ‘porque vou para o Pai’?”

[[v43-16-18]]

^<<v43-16-18,18>>^ Eles diziam: “O que ele quer dizer com: ‘Em breve’? Não sabemos do que ele está falando.”

[[v43-16-19]]

^<<v43-16-19,19>>^ Jesus sabia que eles queriam lhe fazer perguntas, de modo que lhes disse: “Vocês estão perguntando uns aos outros o que eu quis dizer quando falei: ‘Em breve vocês não me verão; e também em breve vocês me verão’?

[[v43-16-20]]

^<<v43-16-20,20>>^ Digo-lhes com toda a certeza: Vocês chorarão e lamentarão, mas o mundo se alegrará; vocês ficarão tristes, mas a sua tristeza será transformada em alegria.

[[v43-16-21]]

^<<v43-16-21,21>>^ Quando uma mulher está dando à luz, ela sofre porque chegou a sua hora; mas, quando nasce o seu bebê, ela não se lembra mais da aflição, por causa da alegria de um ser humano ter vindo ao mundo.

[[v43-16-22]]

^<<v43-16-22,22>>^ Do mesmo modo, agora vocês estão tristes; mas eu os verei novamente, e o seu coração se alegrará, e ninguém tirará a sua alegria.

[[v43-16-23]]

^<<v43-16-23,23>>^ Naquele dia vocês não me farão absolutamente nenhuma pergunta. Digo-lhes com toda a certeza: Se pedirem ao Pai qualquer coisa em meu nome, ele a dará a vocês.

[[v43-16-24]]

^<<v43-16-24,24>>^ Até agora vocês não pediram nem uma única coisa em meu nome. Peçam e receberão, para que a sua alegria seja completa.

[[v43-16-25]]

^<<v43-16-25,25>>^ “Eu lhes disse essas coisas usando comparações. Vem a hora em que não lhes falarei mais usando comparações, mas eu lhes falarei claramente a respeito do Pai.

[[v43-16-26]]

^<<v43-16-26,26>>^ Naquele dia vocês pedirão ao Pai em meu nome. Não quero dizer com isso que pedirei por vocês.

[[v43-16-27]]

^<<v43-16-27,27>>^ Pois o próprio Pai ama^&#42;1^ vocês, porque vocês me amam e acreditam que vim como representante de Deus.

[NOTE]
====
. Ou: “tem afeição por”.
====

[[v43-16-28]]

^<<v43-16-28,28>>^ Vim como representante do Pai e entrei no mundo. Agora, deixo o mundo e vou para o Pai.”

[[v43-16-29]]

^<<v43-16-29,29>>^ Seus discípulos disseram: “Agora, sim, o senhor está falando claramente e não está fazendo comparações.

[[v43-16-30]]

^<<v43-16-30,30>>^ Agora sabemos que o senhor sabe todas as coisas e não precisa que lhe façam perguntas. Por isso acreditamos que o senhor veio de Deus.”

[[v43-16-31]]

^<<v43-16-31,31>>^ Jesus lhes respondeu: “Agora vocês acreditam?

[[v43-16-32]]

^<<v43-16-32,32>>^ Escutem: Vem a hora — realmente já veio — em que vocês serão espalhados, cada um para a sua própria casa, e me deixarão sozinho. Mas eu não estou sozinho, porque o Pai está comigo.

[[v43-16-33]]

^<<v43-16-33,33>>^ Eu lhes disse essas coisas para que, por meio de mim, vocês tenham paz. No mundo vocês terão tribulação, mas coragem! Eu venci o mundo.”

'''

xref:043-joao/043-joao-015.adoc#v43-15-0[&#60; Capítulo Anterior] | <<v43-16-0,Topo>> | xref:043-joao/043-joao-017.adoc#v43-17-0[Próximo Capítulo &#62;]