include::./index.adoc[]

[[v43-18-0]]
=== Segundo João, 18
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-18-1]]

^<<v43-18-1,1>>^ Depois de dizer essas coisas, Jesus saiu com seus discípulos para o outro lado do vale^&#42;1^ do Cédron; ali havia um jardim, onde ele e seus discípulos entraram.

[NOTE]
====
. Ou: “da torrente de inverno”.
====

[[v43-18-2]]

^<<v43-18-2,2>>^ Judas, aquele que o estava traindo, também conhecia o lugar, porque Jesus muitas vezes tinha se reunido ali com seus discípulos.

[[v43-18-3]]

^<<v43-18-3,3>>^ Assim, Judas, trazendo o destacamento de soldados e também os guardas^&#42;1^ enviados pelos principais sacerdotes e pelos fariseus, chegou ali com tochas, lâmpadas e armas.

[NOTE]
====
. Ou: “guardas do templo”.
====

[[v43-18-4]]

^<<v43-18-4,4>>^ Então Jesus, sabendo de tudo o que ia lhe acontecer, deu um passo à frente e lhes disse: “Quem vocês estão procurando?”

[[v43-18-5]]

^<<v43-18-5,5>>^ Responderam-lhe: “Jesus, o Nazareno.” Ele lhes disse: “Sou eu.” Judas, o traidor, também estava com eles.

[[v43-18-6]]

^<<v43-18-6,6>>^ No entanto, quando Jesus lhes disse: “Sou eu”, eles recuaram e caíram no chão.

[[v43-18-7]]

^<<v43-18-7,7>>^ Então lhes perguntou novamente: “Quem vocês estão procurando?” Disseram: “Jesus, o Nazareno.”

[[v43-18-8]]

^<<v43-18-8,8>>^ Jesus respondeu: “Eu lhes disse que sou eu. Então, se é a mim que vocês estão procurando, deixem estes homens ir.”

[[v43-18-9]]

^<<v43-18-9,9>>^ Isso aconteceu para que se cumprisse o que ele tinha dito: “Não perdi nem mesmo um daqueles que me deste.”

[[v43-18-10]]

^<<v43-18-10,10>>^ Então Simão Pedro, que tinha uma espada, a puxou e atacou o escravo do sumo sacerdote, cortando-lhe a orelha direita. O nome do escravo era Malco.

[[v43-18-11]]

^<<v43-18-11,11>>^ Mas Jesus disse a Pedro: “Ponha a espada na bainha. Por acaso não devo beber o cálice que o Pai me deu?”

[[v43-18-12]]

^<<v43-18-12,12>>^ Então, os soldados, o comandante militar e os guardas dos judeus prenderam Jesus e o amarraram.

[[v43-18-13]]

^<<v43-18-13,13>>^ Eles o levaram primeiro a Anás, por ser sogro de Caifás, o sumo sacerdote naquele ano.

[[v43-18-14]]

^<<v43-18-14,14>>^ De fato, foi Caifás quem tinha dito aos judeus que era para o bem deles que um só homem morresse a favor do povo.

[[v43-18-15]]

^<<v43-18-15,15>>^ Simão Pedro, bem como um outro discípulo, seguia Jesus. Este discípulo era conhecido do sumo sacerdote e entrou com Jesus no pátio do sumo sacerdote,

[[v43-18-16]]

^<<v43-18-16,16>>^ mas Pedro ficou do lado de fora, junto à porta.^&#42;1^ Portanto, o outro discípulo, que era conhecido do sumo sacerdote, saiu, falou com a serva que tomava conta da porta e levou Pedro para dentro.

[NOTE]
====
. Ou: “entrada”.
====

[[v43-18-17]]

^<<v43-18-17,17>>^ A serva perguntou então a Pedro: “Você também não é um dos discípulos desse homem?” Ele respondeu: “Não sou.”

[[v43-18-18]]

^<<v43-18-18,18>>^ Os escravos e os guardas estavam em volta de um braseiro que tinham acendido, porque fazia frio, e se aqueciam. Pedro também estava com eles e se aquecia.

[[v43-18-19]]

^<<v43-18-19,19>>^ Então o principal sacerdote interrogou Jesus sobre os seus discípulos e sobre os seus ensinamentos.

[[v43-18-20]]

^<<v43-18-20,20>>^ Jesus lhe respondeu: “Falei ao mundo publicamente. Sempre ensinei nas sinagogas e no templo, onde todos os judeus se reúnem, e não disse nada em segredo.

[[v43-18-21]]

^<<v43-18-21,21>>^ Por que o senhor me faz perguntas? Pergunte aos que ouviram o que eu lhes disse. Eles certamente sabem o que eu disse.”

[[v43-18-22]]

^<<v43-18-22,22>>^ Depois de Jesus dizer isso, um dos guardas que estava ali lhe deu uma bofetada e disse: “É assim que você responde ao principal sacerdote?”

[[v43-18-23]]

^<<v43-18-23,23>>^ Jesus lhe respondeu: “Se eu disse algo errado, diga^&#42;1^ o que foi que eu disse de errado; mas, se o que eu disse está certo, por que você me bate?”

[NOTE]
====
. Ou: “testifique”.
====

[[v43-18-24]]

^<<v43-18-24,24>>^ Então Anás o mandou amarrado a Caifás, o sumo sacerdote.

[[v43-18-25]]

^<<v43-18-25,25>>^ Simão Pedro estava ali e se aquecia. Então lhe perguntaram: “Você também não é um dos discípulos dele?” Ele negou, dizendo: “Não sou.”

[[v43-18-26]]

^<<v43-18-26,26>>^ Um dos escravos do sumo sacerdote, parente do homem cuja orelha Pedro havia cortado, perguntou: “Não vi você no jardim com ele?”

[[v43-18-27]]

^<<v43-18-27,27>>^ No entanto, Pedro negou de novo, e imediatamente um galo cantou.

[[v43-18-28]]

^<<v43-18-28,28>>^ Então, levaram Jesus da presença de Caifás para a residência do governador. Já era de manhã cedo. Mas eles mesmos não entraram na residência do governador, para não ficarem impuros e assim poderem comer a refeição pascoal.

[[v43-18-29]]

^<<v43-18-29,29>>^ Portanto, Pilatos saiu ao encontro deles e perguntou: “Que acusação vocês levantam contra esse homem?”

[[v43-18-30]]

^<<v43-18-30,30>>^ Responderam-lhe: “Se esse homem não fosse um criminoso,^&#42;1^ não o teríamos entregado ao senhor.”

[NOTE]
====
. Ou: “malfeitor”.
====

[[v43-18-31]]

^<<v43-18-31,31>>^ Assim, Pilatos lhes disse: “Levem-no vocês mesmos e julguem-no segundo a sua lei.” Os judeus lhe disseram: “Não nos é permitido matar ninguém.”

[[v43-18-32]]

^<<v43-18-32,32>>^ Isso aconteceu para que se cumprissem as palavras que Jesus tinha dito indicando o tipo de morte que estava para sofrer.

[[v43-18-33]]

^<<v43-18-33,33>>^ Então Pilatos entrou novamente na residência do governador, chamou Jesus e lhe perguntou: “Você é o Rei dos judeus?”

[[v43-18-34]]

^<<v43-18-34,34>>^ Jesus disse: “O senhor está perguntando porque acha isso, ou outros lhe contaram a meu respeito?”

[[v43-18-35]]

^<<v43-18-35,35>>^ Pilatos respondeu: “Por acaso eu sou judeu? A sua própria nação e os principais sacerdotes o entregaram a mim. O que você fez?”

[[v43-18-36]]

^<<v43-18-36,36>>^ Jesus respondeu: “Meu Reino não faz parte deste mundo. Se meu Reino fizesse parte deste mundo, meus assistentes teriam lutado para que eu não fosse entregue aos judeus. Mas o fato é que o meu Reino não é daqui.”

[[v43-18-37]]

^<<v43-18-37,37>>^ Então Pilatos lhe perguntou: “Pois bem, você é rei?” Jesus respondeu: “O senhor mesmo está dizendo que eu sou rei. Para isto nasci e para isto vim ao mundo: para dar testemunho da verdade. Todo aquele que está do lado da verdade escuta a minha voz.”

[[v43-18-38]]

^<<v43-18-38,38>>^ Pilatos lhe disse: “O que é verdade?”
Depois de dizer isso, ele saiu novamente ao encontro dos judeus e lhes disse: “Não vejo motivo para acusá-lo.

[[v43-18-39]]

^<<v43-18-39,39>>^ Além disso, vocês têm o costume de que eu liberte um homem por ocasião da Páscoa. Portanto, querem que eu solte o Rei dos judeus?”

[[v43-18-40]]

^<<v43-18-40,40>>^ Eles gritaram de novo: “Este homem não; queremos Barrabás!” Ora, Barrabás era um bandido.

'''

xref:043-joao/043-joao-017.adoc#v43-17-0[&#60; Capítulo Anterior] | <<v43-18-0,Topo>> | xref:043-joao/043-joao-019.adoc#v43-19-0[Próximo Capítulo &#62;]