include::./index.adoc[]

[[v43-7-0]]
=== Segundo João, 7
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-7-1]]

^<<v43-7-1,1>>^ Depois disso, Jesus continuou a viajar^&#42;1^ pela Galileia, porque não queria andar pela Judeia, visto que os judeus procuravam matá-lo.

[NOTE]
====
. Ou: “andar”.
====

[[v43-7-2]]

^<<v43-7-2,2>>^ No entanto, estava próxima a festividade judaica das Tendas,^&#42;1^

[NOTE]
====
. Ou: “Barracas”.
====

[[v43-7-3]]

^<<v43-7-3,3>>^ e seus irmãos lhe disseram: “Saia daqui e vá à Judeia para que os seus discípulos também possam ver as obras que você está fazendo.

[[v43-7-4]]

^<<v43-7-4,4>>^ Pois ninguém faz as coisas em segredo quando procura ser conhecido publicamente. Se você está fazendo essas coisas, mostre-se ao mundo.”

[[v43-7-5]]

^<<v43-7-5,5>>^ Na verdade, seus irmãos não exerciam fé nele.

[[v43-7-6]]

^<<v43-7-6,6>>^ Portanto, Jesus lhes disse: “A minha hora ainda não chegou, mas para vocês qualquer hora é boa.

[[v43-7-7]]

^<<v43-7-7,7>>^ O mundo não tem razão para odiar vocês, mas odeia a mim, porque dou testemunho dele, de que as suas obras são más.

[[v43-7-8]]

^<<v43-7-8,8>>^ Subam para a festividade; eu ainda não vou a essa festividade, porque o meu tempo ainda não se cumpriu.”

[[v43-7-9]]

^<<v43-7-9,9>>^ Assim, depois de lhes dizer essas coisas, ele permaneceu na Galileia.

[[v43-7-10]]

^<<v43-7-10,10>>^ Mas, depois que os seus irmãos subiram para a festividade, ele também subiu, não abertamente, mas em segredo.

[[v43-7-11]]

^<<v43-7-11,11>>^ Por isso, os judeus começaram a procurá-lo na festividade e a dizer: “Onde está aquele homem?”

[[v43-7-12]]

^<<v43-7-12,12>>^ E entre as multidões muitos cochichavam por causa dele. Alguns diziam: “Ele é um homem bom.” Outros diziam: “Não é. Ele está enganando a multidão.”

[[v43-7-13]]

^<<v43-7-13,13>>^ Naturalmente, ninguém falava dele em público, por medo dos judeus.

[[v43-7-14]]

^<<v43-7-14,14>>^ Quando a festividade já estava na metade, Jesus subiu ao templo e começou a ensinar.

[[v43-7-15]]

^<<v43-7-15,15>>^ Os judeus ficaram admirados, e diziam: “Como é que este homem tem tanto conhecimento das Escrituras,^&#42;1^ se não estudou nas escolas?”^&#42;2^

[NOTE]
====
. Lit.: “conhece escritos”.
. Isto é, nas escolas rabínicas.
====

[[v43-7-16]]

^<<v43-7-16,16>>^ Então Jesus lhes respondeu: “O que eu ensino não é meu, mas pertence àquele que me enviou.

[[v43-7-17]]

^<<v43-7-17,17>>^ Se alguém desejar fazer a Sua vontade, saberá se os ensinamentos são de Deus ou se o que falo se origina de mim.

[[v43-7-18]]

^<<v43-7-18,18>>^ Quem fala as suas próprias ideias procura a sua própria glória; mas quem procura a glória daquele que o enviou é verdadeiro, e não há injustiça nele.

[[v43-7-19]]

^<<v43-7-19,19>>^ Moisés lhes deu a Lei, não deu? Mas nenhum de vocês obedece à Lei. Por que procuram me matar?”

[[v43-7-20]]

^<<v43-7-20,20>>^ A multidão respondeu: “Você tem demônio. Quem está procurando matá-lo?”

[[v43-7-21]]

^<<v43-7-21,21>>^ Em resposta, Jesus lhes disse: “Realizei uma só obra, e todos vocês estão surpresos.

[[v43-7-22]]

^<<v43-7-22,22>>^ Então, considerem o seguinte:^&#42;1^ Moisés deu a vocês a circuncisão (não que ela tenha vindo de Moisés, mas sim dos antepassados), e vocês circuncidam um homem num sábado.

[NOTE]
====
. Ou: “Por isso”.
====

[[v43-7-23]]

^<<v43-7-23,23>>^ Se um homem recebe a circuncisão num sábado para que a Lei de Moisés não seja violada, por que vocês estão tão irados comigo por eu ter curado completamente um homem num sábado?

[[v43-7-24]]

^<<v43-7-24,24>>^ Parem de julgar pelas aparências, mas façam um julgamento justo.”

[[v43-7-25]]

^<<v43-7-25,25>>^ Então alguns dos habitantes de Jerusalém começaram a dizer: “Não é este o homem que procuram matar?

[[v43-7-26]]

^<<v43-7-26,26>>^ No entanto, ele está aqui falando em público, e não lhe dizem nada. Será que os nossos líderes realmente acham que ele é o Cristo?

[[v43-7-27]]

^<<v43-7-27,27>>^ Mas nós sabemos de onde é esse homem; ao passo que, quando o Cristo vier, ninguém saberá de onde ele é.”

[[v43-7-28]]

^<<v43-7-28,28>>^ Então, enquanto ensinava no templo, Jesus disse bem alto: “Vocês me conhecem e sabem de onde eu sou. E eu não vim de minha própria iniciativa, mas Aquele que me enviou é real, e vocês não o conhecem.

[[v43-7-29]]

^<<v43-7-29,29>>^ Eu o conheço, porque sou representante dele, e ele me enviou.”

[[v43-7-30]]

^<<v43-7-30,30>>^ Por isso procuraram prendê-lo, mas ninguém conseguiu segurá-lo, pois a sua hora ainda não havia chegado.

[[v43-7-31]]

^<<v43-7-31,31>>^ Contudo, muitos da multidão depositaram fé nele, e diziam: “Quando o Cristo vier, será que realizará mais sinais do que esse homem realizou?”

[[v43-7-32]]

^<<v43-7-32,32>>^ Os fariseus ouviram a multidão cochichando essas coisas a respeito dele, e os principais sacerdotes e os fariseus enviaram guardas^&#42;1^ para prendê-lo.^&#42;2^

[NOTE]
====
. Ou: “guardas do templo”.
. Ou: “pegá-lo”.
====

[[v43-7-33]]

^<<v43-7-33,33>>^ Então Jesus disse: “Ficarei com vocês mais um pouco, antes de ir para Aquele que me enviou.

[[v43-7-34]]

^<<v43-7-34,34>>^ Vocês me procurarão, mas não me acharão, e, para onde eu vou,^&#42;1^ vocês não podem ir.”

[NOTE]
====
. Ou: “e onde eu estou”.
====

[[v43-7-35]]

^<<v43-7-35,35>>^ Portanto, os judeus disseram entre si: “Para onde esse homem pretende ir, de modo que não poderemos achá-lo? Será que ele pretende ir aos judeus dispersos entre os gregos e ensinar os gregos?

[[v43-7-36]]

^<<v43-7-36,36>>^ O que ele quer dizer com as palavras: ‘Vocês me procurarão, mas não me acharão, e, para onde eu vou, vocês não podem ir’?”

[[v43-7-37]]

^<<v43-7-37,37>>^ No último dia, o grande dia da festividade, Jesus se levantou e disse bem alto: “Se alguém tiver sede, venha a mim e beba.

[[v43-7-38]]

^<<v43-7-38,38>>^ Quem depositar fé em mim, assim como disse uma passagem das Escrituras, ‘do seu íntimo fluirão correntes de água viva’.”

[[v43-7-39]]

^<<v43-7-39,39>>^ No entanto, ao dizer isso, ele falava sobre o espírito, que os que depositaram fé nele iam receber; pois até então não havia espírito, porque Jesus ainda não havia sido glorificado.

[[v43-7-40]]

^<<v43-7-40,40>>^ Alguns da multidão que ouviram essas palavras começaram a dizer: “Este é realmente o Profeta.”

[[v43-7-41]]

^<<v43-7-41,41>>^ Outros diziam: “Este é o Cristo.” Mas alguns diziam: “Será que o Cristo vem da Galileia?

[[v43-7-42]]

^<<v43-7-42,42>>^ Não dizem as Escrituras que o Cristo virá da descendência de Davi e de Belém, a aldeia de onde Davi era?”

[[v43-7-43]]

^<<v43-7-43,43>>^ Assim, surgiu uma divisão entre a multidão por causa dele.

[[v43-7-44]]

^<<v43-7-44,44>>^ Alguns deles, porém, queriam prendê-lo,^&#42;1^ mas ninguém conseguiu segurá-lo.

[NOTE]
====
. Ou: “pegá-lo”.
====

[[v43-7-45]]

^<<v43-7-45,45>>^ Os guardas voltaram então aos principais sacerdotes e aos fariseus, e estes lhes perguntaram: “Por que vocês não o trouxeram para cá?”

[[v43-7-46]]

^<<v43-7-46,46>>^ Os guardas responderam: “Nunca homem algum falou assim!”

[[v43-7-47]]

^<<v43-7-47,47>>^ Então os fariseus disseram: “Será que vocês também foram enganados?

[[v43-7-48]]

^<<v43-7-48,48>>^ Por acaso algum dos nossos líderes ou dos fariseus depositou fé nele?

[[v43-7-49]]

^<<v43-7-49,49>>^ Mas essa multidão, que não conhece a Lei, são pessoas amaldiçoadas.”

[[v43-7-50]]

^<<v43-7-50,50>>^ Nicodemos, que tinha ido a ele antes e era um deles, lhes disse:

[[v43-7-51]]

^<<v43-7-51,51>>^ “Será que a nossa Lei julga um homem sem que primeiro o ouça e saiba o que ele está fazendo?”

[[v43-7-52]]

^<<v43-7-52,52>>^ Em resposta, disseram-lhe: “Será que você também é da Galileia? Pesquise e veja que nenhum profeta surgirá na Galileia.”^&#42;1^

[NOTE]
====
. Vários manuscritos antigos e confiáveis omitem desde o v. 53 até o capítulo 8, v. 11.
====

'''

xref:043-joao/043-joao-006.adoc#v43-6-0[&#60; Capítulo Anterior] | <<v43-7-0,Topo>> | xref:043-joao/043-joao-008.adoc#v43-8-0[Próximo Capítulo &#62;]