include::./index.adoc[]

[[v43-12-0]]
=== Segundo João, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-12-1]]

^<<v43-12-1,1>>^ Seis dias antes da Páscoa, Jesus chegou a Betânia, onde estava Lázaro, a quem Jesus havia levantado dentre os mortos.

[[v43-12-2]]

^<<v43-12-2,2>>^ Ofereceram-lhe ali um jantar; Marta servia, e Lázaro era um dos que comiam^&#42;1^ com ele.

[NOTE]
====
. Ou: “se recostavam à mesa”.
====

[[v43-12-3]]

^<<v43-12-3,3>>^ Então, Maria pegou quase meio quilo^&#42;1^ de óleo perfumado, nardo genuíno, muito caro, derramou-o nos pés de Jesus e os enxugou com seu cabelo. A casa se encheu com a fragrância do óleo perfumado.

[NOTE]
====
. Ou: “pegou uma libra”, isto é, uma libra romana, cerca de 327 g. Veja Ap. B14.
====

[[v43-12-4]]

^<<v43-12-4,4>>^ Mas Judas Iscariotes, um dos seus discípulos, que estava para traí-lo, disse:

[[v43-12-5]]

^<<v43-12-5,5>>^ “Por que esse óleo perfumado não foi vendido por 300 denários,^&#42;1^ e o dinheiro dado aos pobres?”

[NOTE]
====
. Veja Ap. B14.
====

[[v43-12-6]]

^<<v43-12-6,6>>^ Na verdade, ele disse isso não porque estivesse preocupado com os pobres, mas porque era ladrão; ele cuidava da caixa de dinheiro e roubava o dinheiro que era colocado nela.

[[v43-12-7]]

^<<v43-12-7,7>>^ Então Jesus disse: “Deixem-na em paz, para que ela faça isso em vista do dia do meu sepultamento.

[[v43-12-8]]

^<<v43-12-8,8>>^ Porque vocês sempre têm consigo os pobres, mas nem sempre terão a mim.”

[[v43-12-9]]

^<<v43-12-9,9>>^ Nesse meio-tempo, uma grande multidão de judeus ficou sabendo que ele estava em Betânia, e eles foram para lá, não somente por causa de Jesus, mas também para ver Lázaro, a quem ele havia levantado dentre os mortos.

[[v43-12-10]]

^<<v43-12-10,10>>^ Os principais sacerdotes fizeram planos para matar Lázaro também,

[[v43-12-11]]

^<<v43-12-11,11>>^ visto que era por causa dele que muitos judeus iam para lá e depositavam fé em Jesus.

[[v43-12-12]]

^<<v43-12-12,12>>^ No dia seguinte, a grande multidão que tinha ido à festividade soube que Jesus estava chegando a Jerusalém.

[[v43-12-13]]

^<<v43-12-13,13>>^ Então, pegaram folhas de palmeiras e saíram ao encontro dele, e começaram a gritar: “Salva, rogamos-te! Bendito é aquele que vem em nome de Jeová!^&#42;1^ Bendito é o Rei de Israel!”

[NOTE]
====
. Veja Ap. A5.
====

[[v43-12-14]]

^<<v43-12-14,14>>^ Jesus achou um jumentinho e montou nele, assim como está escrito:

[[v43-12-15]]

^<<v43-12-15,15>>^ “Não tema, filha de Sião. Veja! Seu rei está vindo, montado num jumentinho.”

[[v43-12-16]]

^<<v43-12-16,16>>^ De início, os discípulos não entenderam aquilo, mas, quando Jesus foi glorificado, eles se lembraram de que essas coisas estavam escritas a respeito dele e que tinham feito isso a ele.

[[v43-12-17]]

^<<v43-12-17,17>>^ As pessoas que estavam com ele quando chamou Lázaro para fora do túmulo^&#42;1^ e o levantou dentre os mortos davam testemunho.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v43-12-18]]

^<<v43-12-18,18>>^ Foi também por isso que a multidão foi ao encontro dele, porque ouviu que ele havia realizado esse sinal.

[[v43-12-19]]

^<<v43-12-19,19>>^ Portanto, os fariseus disseram entre si: “Vejam, não estamos conseguindo nada. Olhem como o mundo inteiro foi atrás dele!”

[[v43-12-20]]

^<<v43-12-20,20>>^ Havia alguns gregos entre os que tinham ido adorar na festividade.

[[v43-12-21]]

^<<v43-12-21,21>>^ Eles se aproximaram de Filipe, que era de Betsaida da Galileia, e lhe pediram: “Senhor, queremos ver Jesus.”

[[v43-12-22]]

^<<v43-12-22,22>>^ Filipe foi dizer isso a André. Então André e Filipe falaram com Jesus.

[[v43-12-23]]

^<<v43-12-23,23>>^ Mas Jesus lhes respondeu: “Chegou a hora para o Filho do Homem ser glorificado.

[[v43-12-24]]

^<<v43-12-24,24>>^ Digo-lhes com toda a certeza: Se o grão de trigo não cai no solo e não morre, continua sendo apenas um grão; mas, se morre, ele dá muito fruto.

[[v43-12-25]]

^<<v43-12-25,25>>^ Quem ama a sua vida^&#42;1^ a perderá,^&#42;2^ mas quem odeia a sua vida^&#42;3^ neste mundo a preservará para a vida eterna.

[NOTE]
====
. Ou: “alma”.
. Lit.: “destrói”.
. Ou: “alma”.
====

[[v43-12-26]]

^<<v43-12-26,26>>^ Se alguém quiser me servir, siga-me; e, onde eu estiver, ali estará também o meu servo. Se alguém quiser me servir, o Pai o honrará.

[[v43-12-27]]

^<<v43-12-27,27>>^ Agora eu estou aflito,^&#42;1^ e o que direi? Pai, salva-me desta hora. Contudo, foi para isto que eu vim, para esta hora.

[NOTE]
====
. Ou: “minha alma está aflita”.
====

[[v43-12-28]]

^<<v43-12-28,28>>^ Pai, glorifica o teu nome.” Então veio uma voz do céu: “Eu já o glorifiquei e o glorificarei de novo.”

[[v43-12-29]]

^<<v43-12-29,29>>^ A multidão que estava ali ouviu isso e começou a dizer que tinha trovejado. Outros disseram: “Um anjo falou com ele.”

[[v43-12-30]]

^<<v43-12-30,30>>^ Jesus respondeu: “Essa voz não veio por minha causa, mas por causa de vocês.

[[v43-12-31]]

^<<v43-12-31,31>>^ Agora este mundo está sendo julgado; agora será expulso o governante deste mundo.

[[v43-12-32]]

^<<v43-12-32,32>>^ Mas, quando eu for erguido da terra, atrairei a mim todo tipo de pessoas.”

[[v43-12-33]]

^<<v43-12-33,33>>^ Na verdade, ele dizia isso para indicar o tipo de morte que estava para sofrer.

[[v43-12-34]]

^<<v43-12-34,34>>^ Então a multidão lhe respondeu: “Ouvimos da Lei que o Cristo permanece para sempre. Como é que você diz que o Filho do Homem tem de ser erguido? Quem é esse Filho do Homem?”

[[v43-12-35]]

^<<v43-12-35,35>>^ Jesus lhes disse, então: “A luz estará entre vocês por mais um pouco de tempo. Andem enquanto vocês ainda têm a luz, para que a escuridão não os vença; quem anda na escuridão não sabe para onde vai.

[[v43-12-36]]

^<<v43-12-36,36>>^ Enquanto vocês têm a luz, exerçam fé na luz, para que possam se tornar filhos da luz.”
Depois de dizer essas coisas, Jesus foi embora e se escondeu deles.

[[v43-12-37]]

^<<v43-12-37,37>>^ Embora ele tivesse realizado tantos sinais na frente deles, não depositavam fé nele,

[[v43-12-38]]

^<<v43-12-38,38>>^ para que se cumprissem as palavras de Isaías, o profeta, que disse: “Jeová,^&#42;1^ quem depositou fé no que falamos?^&#42;2^ E a quem foi revelado o braço de Jeová?”^&#42;3^

[NOTE]
====
. Veja Ap. A5.
. Ou: “no nosso relato”. Lit.: “na coisa ouvida de nós”.
. Veja Ap. A5.
====

[[v43-12-39]]

^<<v43-12-39,39>>^ Isaías também disse a razão pela qual eles não podiam acreditar:

[[v43-12-40]]

^<<v43-12-40,40>>^ “Ele lhes cegou os olhos e lhes endureceu o coração, para que não vissem com os olhos, nem entendessem com o coração, e dessem meia-volta, e eu os curasse.”

[[v43-12-41]]

^<<v43-12-41,41>>^ Isaías disse isso porque viu a glória dele e falou sobre ele.

[[v43-12-42]]

^<<v43-12-42,42>>^ De qualquer modo, até mesmo muitos líderes dos judeus realmente depositavam fé nele, mas, por causa dos fariseus, não declaravam isso publicamente, para não serem expulsos da sinagoga,

[[v43-12-43]]

^<<v43-12-43,43>>^ pois amavam mais a glória dos homens do que a glória de Deus.

[[v43-12-44]]

^<<v43-12-44,44>>^ No entanto, Jesus disse bem alto: “Quem deposita fé em mim deposita fé não somente em mim, mas também naquele que me enviou;

[[v43-12-45]]

^<<v43-12-45,45>>^ e quem me vê, vê também Aquele que me enviou.

[[v43-12-46]]

^<<v43-12-46,46>>^ Eu vim como luz ao mundo, para que todo aquele que deposita fé em mim não permaneça na escuridão.

[[v43-12-47]]

^<<v43-12-47,47>>^ Mas, se alguém ouve as minhas declarações e não as cumpre, eu não o julgo; pois não vim julgar o mundo, mas salvar o mundo.

[[v43-12-48]]

^<<v43-12-48,48>>^ Quem me desconsidera e não aceita as minhas declarações tem quem o julgue. As palavras que eu falei é que o julgarão no último dia.

[[v43-12-49]]

^<<v43-12-49,49>>^ Pois não falei de minha própria iniciativa, mas o Pai, que me enviou, ele mesmo me deu um mandamento sobre o que dizer e o que falar.

[[v43-12-50]]

^<<v43-12-50,50>>^ E eu sei que o seu mandamento significa vida eterna. Portanto, tudo o que eu falo, falo assim como o Pai me disse.”

'''

xref:043-joao/043-joao-011.adoc#v43-11-0[&#60; Capítulo Anterior] | <<v43-12-0,Topo>> | xref:043-joao/043-joao-013.adoc#v43-13-0[Próximo Capítulo &#62;]