include::./index.adoc[]

[[v43-11-0]]
=== Segundo João, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v43-11-1]]

^<<v43-11-1,1>>^ Um homem chamado Lázaro estava doente; ele era de Betânia, a aldeia de Maria e de sua irmã Marta.

[[v43-11-2]]

^<<v43-11-2,2>>^ Foi essa Maria que derramou óleo perfumado sobre o Senhor e enxugou os pés dele com o cabelo; Lázaro, que estava doente, era irmão dela.

[[v43-11-3]]

^<<v43-11-3,3>>^ Então, as irmãs dele mandaram dizer a Jesus: “Senhor, aquele que o senhor ama^&#42;1^ está doente.”

[NOTE]
====
. Ou: “aquele por quem o senhor tem afeição”.
====

[[v43-11-4]]

^<<v43-11-4,4>>^ Mas Jesus, quando ouviu isso, disse: “O resultado dessa doença não será a morte, mas a glória de Deus, para que o Filho de Deus seja glorificado por meio dela.”

[[v43-11-5]]

^<<v43-11-5,5>>^ Jesus amava Marta, a irmã dela e Lázaro.

[[v43-11-6]]

^<<v43-11-6,6>>^ No entanto, quando ouviu que Lázaro estava doente, permaneceu por mais dois dias no lugar onde estava.

[[v43-11-7]]

^<<v43-11-7,7>>^ Depois, ele disse aos discípulos: “Vamos novamente à Judeia.”

[[v43-11-8]]

^<<v43-11-8,8>>^ Os discípulos lhe disseram: “Rabi, há pouco tempo os da Judeia queriam apedrejá-lo, e o senhor vai novamente para lá?”

[[v43-11-9]]

^<<v43-11-9,9>>^ Jesus respondeu: “Não há 12 horas de luz no dia? Se alguém anda na luz do dia, não tropeça, porque vê a luz deste mundo.

[[v43-11-10]]

^<<v43-11-10,10>>^ Mas, se alguém anda de noite, tropeça, porque nele não há luz.”

[[v43-11-11]]

^<<v43-11-11,11>>^ Depois de dizer isso, ele acrescentou: “Lázaro, nosso amigo, adormeceu, mas eu vou lá para acordá-lo.”

[[v43-11-12]]

^<<v43-11-12,12>>^ Então os discípulos lhe disseram: “Senhor, se ele está dormindo, ficará bom.”

[[v43-11-13]]

^<<v43-11-13,13>>^ Jesus, no entanto, havia falado da morte dele; mas eles imaginavam que estivesse falando do sono natural.

[[v43-11-14]]

^<<v43-11-14,14>>^ Então, Jesus lhes disse claramente: “Lázaro morreu;

[[v43-11-15]]

^<<v43-11-15,15>>^ e, por causa de vocês, eu me alegro de que eu não estava lá, para que vocês acreditem. Mas vamos até onde ele está.”

[[v43-11-16]]

^<<v43-11-16,16>>^ Portanto, Tomé, que era chamado Gêmeo, disse aos outros discípulos: “Vamos também, para morrermos com ele.”

[[v43-11-17]]

^<<v43-11-17,17>>^ Quando Jesus chegou, ficou sabendo que Lázaro já estava no túmulo^&#42;1^ por quatro dias.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v43-11-18]]

^<<v43-11-18,18>>^ Betânia era perto de Jerusalém, a cerca de três quilômetros^&#42;1^ de distância,

[NOTE]
====
. Lit.: “cerca de 15 estádios”. Veja Ap. B14.
====

[[v43-11-19]]

^<<v43-11-19,19>>^ e muitos judeus tinham ido consolar Marta e Maria por causa do seu irmão.

[[v43-11-20]]

^<<v43-11-20,20>>^ Quando Marta ouviu que Jesus estava chegando, foi ao encontro dele; Maria, porém, ficou sentada em casa.

[[v43-11-21]]

^<<v43-11-21,21>>^ Marta disse então a Jesus: “Senhor, se estivesse aqui, meu irmão não teria morrido.

[[v43-11-22]]

^<<v43-11-22,22>>^ Contudo, mesmo agora, eu sei que tudo o que o senhor pedir a Deus, Deus lhe dará.”

[[v43-11-23]]

^<<v43-11-23,23>>^ Jesus lhe disse: “Seu irmão se levantará.”

[[v43-11-24]]

^<<v43-11-24,24>>^ Marta respondeu: “Sei que ele se levantará na ressurreição, no último dia.”

[[v43-11-25]]

^<<v43-11-25,25>>^ Jesus lhe disse: “Eu sou a ressurreição e a vida. Quem exercer fé em mim, ainda que morra, voltará a viver;

[[v43-11-26]]

^<<v43-11-26,26>>^ e todo aquele que vive e exerce fé em mim não morrerá jamais. Você acredita nisso?”

[[v43-11-27]]

^<<v43-11-27,27>>^ Ela lhe respondeu: “Sim, Senhor, eu acredito que o senhor é o Cristo, o Filho de Deus, aquele que tinha de vir ao mundo.”

[[v43-11-28]]

^<<v43-11-28,28>>^ Depois de dizer isso, ela foi chamar Maria, sua irmã, e lhe disse em particular: “O Instrutor está aqui e está chamando você.”

[[v43-11-29]]

^<<v43-11-29,29>>^ Quando ouviu isso, ela se levantou depressa e foi ao encontro dele.

[[v43-11-30]]

^<<v43-11-30,30>>^ Jesus ainda não tinha entrado na aldeia, mas estava no lugar onde Marta o havia encontrado.

[[v43-11-31]]

^<<v43-11-31,31>>^ Quando os judeus que estavam na casa, consolando Maria, viram que ela se levantou depressa e saiu, eles a seguiram, achando que ela estivesse indo ao túmulo^&#42;1^ para chorar.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v43-11-32]]

^<<v43-11-32,32>>^ Quando Maria chegou ao lugar onde Jesus estava e o viu, ela se prostrou aos seus pés e lhe disse: “Senhor, se estivesse aqui, meu irmão não teria morrido.”

[[v43-11-33]]

^<<v43-11-33,33>>^ Vendo que ela e os judeus que a acompanhavam estavam chorando, Jesus se comoveu profundamente^&#42;1^ e ficou aflito.

[NOTE]
====
. Lit.: “gemeu no espírito”.
====

[[v43-11-34]]

^<<v43-11-34,34>>^ Ele perguntou: “Onde o colocaram?” Disseram-lhe: “Senhor, venha ver.”

[[v43-11-35]]

^<<v43-11-35,35>>^ E Jesus começou a chorar.

[[v43-11-36]]

^<<v43-11-36,36>>^ Em vista disso, os judeus disseram: “Vejam como ele o amava!”^&#42;1^

[NOTE]
====
. Ou: “ele tinha afeição por ele”.
====

[[v43-11-37]]

^<<v43-11-37,37>>^ Mas alguns deles diziam: “Não podia este homem, que abriu os olhos do cego, impedir que Lázaro morresse?”

[[v43-11-38]]

^<<v43-11-38,38>>^ Assim, de novo profundamente comovido, Jesus foi ao túmulo.^&#42;1^ Na realidade, era uma caverna, e havia uma pedra encostada nela.

[NOTE]
====
. Ou: “túmulo memorial”.
====

[[v43-11-39]]

^<<v43-11-39,39>>^ Jesus disse: “Retirem a pedra.” Marta, irmã do falecido, disse-lhe: “Senhor, ele já deve estar cheirando, porque já faz quatro dias.”

[[v43-11-40]]

^<<v43-11-40,40>>^ Jesus respondeu: “Eu não lhe disse que, se você acreditasse, veria a glória de Deus?”

[[v43-11-41]]

^<<v43-11-41,41>>^ Portanto, retiraram a pedra. Jesus levantou então os olhos para o céu e disse: “Pai, eu te agradeço porque me ouviste.

[[v43-11-42]]

^<<v43-11-42,42>>^ Na verdade, eu sei que sempre me ouves, mas falei por causa da multidão que está ao meu redor, para que acreditem que tu me enviaste.”

[[v43-11-43]]

^<<v43-11-43,43>>^ Depois de dizer isso, ele gritou bem alto: “Lázaro, venha para fora!”

[[v43-11-44]]

^<<v43-11-44,44>>^ O homem que estava morto saiu com os pés e as mãos amarrados com faixas, e com um pano enrolado no rosto. Jesus lhes disse: “Tirem as faixas dele e deixem-no ir.”

[[v43-11-45]]

^<<v43-11-45,45>>^ Portanto, muitos dos judeus que tinham ido visitar Maria e viram o que ele fez depositaram fé nele,

[[v43-11-46]]

^<<v43-11-46,46>>^ mas alguns deles foram contar aos fariseus o que Jesus tinha feito.

[[v43-11-47]]

^<<v43-11-47,47>>^ Então os principais sacerdotes e os fariseus reuniram o Sinédrio e disseram: “O que faremos, visto que esse homem realiza muitos sinais?

[[v43-11-48]]

^<<v43-11-48,48>>^ Se o deixarmos continuar assim, todos depositarão fé nele, e os romanos virão e tirarão tanto o nosso lugar^&#42;1^ como a nossa nação.”

[NOTE]
====
. Isto é, o templo.
====

[[v43-11-49]]

^<<v43-11-49,49>>^ Então um deles, Caifás, que era sumo sacerdote naquele ano, lhes disse: “Vocês não sabem nada,

[[v43-11-50]]

^<<v43-11-50,50>>^ nem refletiram que é para o seu bem que um só homem morra a favor do povo, em vez de toda a nação ser destruída.”

[[v43-11-51]]

^<<v43-11-51,51>>^ No entanto, ele não disse isso por si mesmo, mas, como era sumo sacerdote naquele ano, profetizou que Jesus iria morrer pela nação,

[[v43-11-52]]

^<<v43-11-52,52>>^ e não só pela nação, mas também para reunir em um só grupo os filhos de Deus que estavam espalhados.

[[v43-11-53]]

^<<v43-11-53,53>>^ Assim, daquele dia em diante fizeram planos para matá-lo.

[[v43-11-54]]

^<<v43-11-54,54>>^ Por isso, Jesus não andava mais publicamente entre os judeus, mas partiu dali para a região perto do deserto, para uma cidade chamada Efraim, e ficou ali com os discípulos.

[[v43-11-55]]

^<<v43-11-55,55>>^ Estava próxima a Páscoa dos judeus, e muitos da zona rural subiram a Jerusalém antes da Páscoa, a fim de se purificar cerimonialmente.

[[v43-11-56]]

^<<v43-11-56,56>>^ Procuravam Jesus e, no templo, diziam uns aos outros: “Que acham? Será que ele não virá à festividade?”

[[v43-11-57]]

^<<v43-11-57,57>>^ Mas os principais sacerdotes e os fariseus tinham dado ordens de que, se alguém soubesse onde Jesus estava, os informasse, para que pudessem prendê-lo.^&#42;1^

[NOTE]
====
. Ou: “pegá-lo”.
====

'''

xref:043-joao/043-joao-010.adoc#v43-10-0[&#60; Capítulo Anterior] | <<v43-11-0,Topo>> | xref:043-joao/043-joao-012.adoc#v43-12-0[Próximo Capítulo &#62;]