include::./index.adoc[]

[[v47-3-0]]
=== A Segunda aos Coríntios, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-3-1]]

^<<v47-3-1,1>>^ Estamos começando a recomendar a nós mesmos novamente? Ou será que precisamos, como alguns, de cartas de recomendação para vocês ou da parte de vocês?

[[v47-3-2]]

^<<v47-3-2,2>>^ Vocês mesmos são a nossa carta, escrita no nosso coração, conhecida e lida por toda a humanidade.

[[v47-3-3]]

^<<v47-3-3,3>>^ Porque é evidente que vocês são carta de Cristo, escrita por nós como ministros, não com tinta, mas com o espírito de um Deus vivente; não em tábuas de pedra, mas em tábuas carnais, em corações.

[[v47-3-4]]

^<<v47-3-4,4>>^ Temos tal confiança em Deus por meio do Cristo.

[[v47-3-5]]

^<<v47-3-5,5>>^ Não que estejamos qualificados^&#42;1^ por nós mesmos para considerar que qualquer coisa venha de nós, mas a nossa qualificação vem de Deus,

[NOTE]
====
. Ou: “adequadamente qualificados”.
====

[[v47-3-6]]

^<<v47-3-6,6>>^ que de fato nos habilitou para sermos servos^&#42;1^ de um novo pacto, não de um código escrito, mas do espírito; pois o código escrito condena à morte, mas o espírito dá vida.

[NOTE]
====
. Ou: “ministros”.
====

[[v47-3-7]]

^<<v47-3-7,7>>^ Ora, se o código que ministra a morte e que foi gravado com letras em pedras veio com tal glória que os filhos de Israel não podiam olhar para o rosto de Moisés por causa da glória do seu rosto, glória que seria eliminada,

[[v47-3-8]]

^<<v47-3-8,8>>^ não deveria a ministração do espírito ter uma glória ainda maior?

[[v47-3-9]]

^<<v47-3-9,9>>^ Pois, se o código que ministrava a condenação era glorioso, quanto mais gloriosa seria a ministração da justiça!^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v47-3-10]]

^<<v47-3-10,10>>^ De fato, mesmo aquilo que no passado havia sido feito glorioso perdeu a glória por causa da glória que lhe é superior.

[[v47-3-11]]

^<<v47-3-11,11>>^ Pois, se aquilo que seria eliminado foi introduzido com glória, quanto maior seria a glória daquilo que permanece!

[[v47-3-12]]

^<<v47-3-12,12>>^ Visto que temos tal esperança, falamos com muita confiança,

[[v47-3-13]]

^<<v47-3-13,13>>^ e não fazemos como Moisés, que colocava um véu sobre o rosto para que os filhos de Israel não fixassem os olhos no fim daquilo que seria eliminado.

[[v47-3-14]]

^<<v47-3-14,14>>^ Mas a mente deles ficou insensível. Pois até hoje, quando o antigo pacto é lido, o mesmo véu permanece sem ser levantado, visto que ele só é removido por meio de Cristo.

[[v47-3-15]]

^<<v47-3-15,15>>^ De fato, até hoje, sempre que Moisés é lido, um véu cobre o coração deles.

[[v47-3-16]]

^<<v47-3-16,16>>^ Mas, quando alguém se volta para Jeová,^&#42;1^ o véu é retirado.

[NOTE]
====
. Veja Ap. A5.
====

[[v47-3-17]]

^<<v47-3-17,17>>^ Ora, Jeová^&#42;1^ é o Espírito, e onde está o espírito de Jeová,^&#42;2^ ali há liberdade.

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v47-3-18]]

^<<v47-3-18,18>>^ E todos nós, ao passo que com o rosto descoberto refletimos como um espelho a glória de Jeová,^&#42;1^ somos transformados nessa mesma imagem, com mais e mais glória,^&#42;2^ exatamente como Jeová,^&#42;3^ o Espírito,^&#42;4^ o faz.

[NOTE]
====
. Veja Ap. A5.
. Lit.: “de glória em glória”.
. Veja Ap. A5.
. Ou, possivelmente: “como o espírito de Jeová”.
====

'''

xref:047-2-corintios/047-2-corintios-002.adoc#v47-2-0[&#60; Capítulo Anterior] | <<v47-3-0,Topo>> | xref:047-2-corintios/047-2-corintios-004.adoc#v47-4-0[Próximo Capítulo &#62;]