include::./index.adoc[]

[[v47-12-0]]
=== A Segunda aos Coríntios, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-12-1]]

^<<v47-12-1,1>>^ Tenho de me gabar. Não há nada a ganhar com isso, mas passarei às visões sobrenaturais e revelações da parte do Senhor.

[[v47-12-2]]

^<<v47-12-2,2>>^ Conheço um homem em união com Cristo que, há 14 anos — quer no corpo, quer fora do corpo, não sei; Deus sabe —, foi arrebatado ao terceiro céu.

[[v47-12-3]]

^<<v47-12-3,3>>^ Sim, conheço esse homem que — quer no corpo, quer separado do corpo, não sei; Deus sabe —

[[v47-12-4]]

^<<v47-12-4,4>>^ foi arrebatado para o paraíso e ouviu palavras que não podem ser ditas e que não se permite ao homem falar.

[[v47-12-5]]

^<<v47-12-5,5>>^ Eu me gabarei desse homem, mas não me gabarei de mim mesmo, a não ser das minhas fraquezas.

[[v47-12-6]]

^<<v47-12-6,6>>^ Pois, mesmo que eu quisesse me gabar, eu não seria insensato, porque diria a verdade. Mas evito fazer isso para que ninguém me dê crédito por algo além do que vê em mim ou do que ouve de mim,

[[v47-12-7]]

^<<v47-12-7,7>>^ só porque recebo essas revelações extraordinárias.
Para impedir que eu ficasse enaltecido demais, foi-me dado um espinho na carne, um anjo de Satanás, para me esbofetear^&#42;1^ continuamente, a fim de que eu não me enaltecesse demais.

[NOTE]
====
. Ou: “espancar”.
====

[[v47-12-8]]

^<<v47-12-8,8>>^ Três vezes supliquei ao Senhor, pedindo que isso se afastasse de mim.

[[v47-12-9]]

^<<v47-12-9,9>>^ Mas ele me disse: “A minha bondade imerecida é suficiente para você, pois o meu poder está sendo aperfeiçoado na fraqueza.” Com muita alegria, então, eu me gabarei das minhas fraquezas, para que o poder do Cristo permaneça sobre mim como uma tenda.

[[v47-12-10]]

^<<v47-12-10,10>>^ Assim, tenho prazer em fraquezas, em insultos, em privações, em perseguições e dificuldades, por Cristo. Pois, quando estou fraco, então é que sou poderoso.

[[v47-12-11]]

^<<v47-12-11,11>>^ Tornei-me insensato. Vocês me obrigaram a isso, porque deveriam ter me recomendado. Pois não me mostrei em coisa alguma inferior aos seus superapóstolos, embora eu não seja nada.

[[v47-12-12]]

^<<v47-12-12,12>>^ De fato, os sinais que identificam um apóstolo foram produzidos entre vocês com grande perseverança, e por sinais, milagres^&#42;1^ e obras poderosas.

[NOTE]
====
. Ou: “portentos”.
====

[[v47-12-13]]

^<<v47-12-13,13>>^ Pois em que é que vocês foram menos favorecidos do que as outras congregações, a não ser no fato de que eu mesmo não me tornei um fardo para vocês? Perdoem-me bondosamente essa injustiça.

[[v47-12-14]]

^<<v47-12-14,14>>^ Vejam, esta é a terceira vez que estou pronto para ir visitá-los, e não me tornarei um fardo. Pois estou buscando não os seus bens, mas a vocês; porque não se espera que os filhos acumulem para os pais, mas sim os pais para os filhos.

[[v47-12-15]]

^<<v47-12-15,15>>^ Quanto a mim, de muito boa vontade gastarei e serei completamente gasto a favor de vocês.^&#42;1^ Se os amo tanto, deveria eu ser amado menos?

[NOTE]
====
. Ou: “das suas almas”.
====

[[v47-12-16]]

^<<v47-12-16,16>>^ Mas, seja como for, não os sobrecarreguei. No entanto, vocês dizem que fui “ardiloso” e que os apanhei “com astúcia”.

[[v47-12-17]]

^<<v47-12-17,17>>^ Será que me aproveitei de vocês por meio de algum daqueles que lhes enviei?

[[v47-12-18]]

^<<v47-12-18,18>>^ Insisti com Tito para que visitasse vocês e enviei o irmão com ele. Será que Tito se aproveitou de vocês? Por acaso não andamos no mesmo espírito, nas mesmas pisadas?

[[v47-12-19]]

^<<v47-12-19,19>>^ Vocês pensaram durante todo esse tempo que estávamos fazendo a nossa defesa perante vocês? É perante Deus que estamos falando, em união com Cristo. Mas, amados, tudo o que fazemos é para edificar vocês.

[[v47-12-20]]

^<<v47-12-20,20>>^ Pois receio que, quando eu chegar aí, talvez não os encontre como eu queria, e eu não seja como vocês queriam, mas, em vez disso, que eu encontre brigas, ciúme, acessos de ira, discórdias, calúnias, cochichos,^&#42;1^ demonstrações de orgulho e desordens.

[NOTE]
====
. Ou: “fofocas”.
====

[[v47-12-21]]

^<<v47-12-21,21>>^ Talvez, quando eu for novamente, meu Deus me humilhe diante de vocês, e eu tenha de chorar por muitos que anteriormente pecaram e não se arrependeram da impureza, da imoralidade sexual^&#42;1^ e da conduta insolente^&#42;2^ que praticaram.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
. Ou: “conduta desavergonhada”. Em grego, asélgeia. Veja o Glossário.
====

'''

xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[&#60; Capítulo Anterior] | <<v47-12-0,Topo>> | xref:047-2-corintios/047-2-corintios-013.adoc#v47-13-0[Próximo Capítulo &#62;]