include::./index.adoc[]

[[v47-10-0]]
=== A Segunda aos Coríntios, 10
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-10-1]]

^<<v47-10-1,1>>^ Eu mesmo, Paulo, suplico-lhes pela brandura e bondade do Cristo, eu que sou humilde quando estou pessoalmente entre vocês, mas ousado com vocês quando ausente.

[[v47-10-2]]

^<<v47-10-2,2>>^ Rogo que, quando eu estiver presente, não tenha de ser ousado e tomar medidas fortes, como penso que tomarei, contra alguns que nos encaram como se andássemos de acordo com a carne.

[[v47-10-3]]

^<<v47-10-3,3>>^ Pois, embora vivamos na carne, não travamos combate de acordo com o que somos na carne.

[[v47-10-4]]

^<<v47-10-4,4>>^ Porque as armas do nosso combate não são carnais, mas poderosas em Deus para demolir fortalezas.^&#42;1^

[NOTE]
====
. Ou: “coisas fortemente entrincheiradas”.
====

[[v47-10-5]]

^<<v47-10-5,5>>^ Pois demolimos raciocínios e toda barreira^&#42;1^ que se ergue contra o conhecimento de Deus, e levamos todo pensamento ao cativeiro, para fazê-lo obediente ao Cristo;

[NOTE]
====
. Ou: “altivez”.
====

[[v47-10-6]]

^<<v47-10-6,6>>^ e estamos preparados para punir toda desobediência, uma vez que a obediência de vocês esteja completa.

[[v47-10-7]]

^<<v47-10-7,7>>^ Vocês julgam as coisas pela aparência. Se alguém estiver convencido de que pertence a Cristo, que ele reflita novamente no seguinte fato: assim como ele pertence a Cristo, nós também pertencemos.

[[v47-10-8]]

^<<v47-10-8,8>>^ Pois, mesmo que eu me orgulhasse um pouco demais da autoridade que o Senhor nos deu para edificar vocês, e não para os derrubar, eu não me envergonharia.

[[v47-10-9]]

^<<v47-10-9,9>>^ Mas não quero dar a impressão de que estou tentando amedrontá-los com as minhas cartas.

[[v47-10-10]]

^<<v47-10-10,10>>^ Pois eles dizem: “As cartas dele têm peso e força, mas a presença dele é fraca, e a palavra dele desprezível.”

[[v47-10-11]]

^<<v47-10-11,11>>^ Que tal homem saiba que aquilo que dizemos^&#42;1^ por cartas quando estamos ausentes, nós faremos^&#42;2^ quando estivermos presentes.

[NOTE]
====
. Lit.: “o que somos em palavra”.
. Lit.: “também seremos em ação”.
====

[[v47-10-12]]

^<<v47-10-12,12>>^ Pois não nos atrevemos a nos igualar ou a nos comparar com alguns que recomendam a si mesmos. Mas, quando eles se avaliam pelos seus próprios critérios e se comparam consigo mesmos, mostram que não têm entendimento.

[[v47-10-13]]

^<<v47-10-13,13>>^ No entanto, nós não nos orgulharemos de algo feito fora dos nossos limites designados, mas somente do que fazemos dentro dos limites do território que Deus demarcou^&#42;1^ para nós, o qual inclui vocês.

[NOTE]
====
. Ou: “repartiu por medida”.
====

[[v47-10-14]]

^<<v47-10-14,14>>^ Realmente, não estamos indo além dos nossos limites, como se o nosso território não os incluísse, pois fomos os primeiros a chegar até vocês com as boas novas a respeito do Cristo.

[[v47-10-15]]

^<<v47-10-15,15>>^ Não, não nos orgulhamos fora dos nossos limites designados, isto é, do trabalho árduo de outros, mas esperamos que, ao passo que a sua fé continuar crescendo, o trabalho que realizamos continue a crescer, dentro do nosso território. Então aumentaremos ainda mais,

[[v47-10-16]]

^<<v47-10-16,16>>^ para que declaremos as boas novas às regiões que ficam além de vocês, a fim de não nos orgulharmos de algo já feito em território de outro.

[[v47-10-17]]

^<<v47-10-17,17>>^ “Mas quem se orgulhar, orgulhe-se em Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v47-10-18]]

^<<v47-10-18,18>>^ Pois o aprovado não é aquele que recomenda a si mesmo, mas sim aquele a quem Jeová^&#42;1^ recomenda.

[NOTE]
====
. Veja Ap. A5.
====

'''

xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[&#60; Capítulo Anterior] | <<v47-10-0,Topo>> | xref:047-2-corintios/047-2-corintios-011.adoc#v47-11-0[Próximo Capítulo &#62;]