include::./index.adoc[]

[[v47-13-0]]
=== A Segunda aos Coríntios, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-13-1]]

^<<v47-13-1,1>>^ Esta é a terceira vez que estou para ir visitá-los. “Toda questão deve ficar estabelecida com base no depoimento^&#42;1^ de duas ou três testemunhas.”

[NOTE]
====
. Lit.: “na boca”.
====

[[v47-13-2]]

^<<v47-13-2,2>>^ Embora eu esteja ausente agora, é como se eu estivesse presente pela segunda vez, e eu previno os que pecaram no passado, e a todos os outros, que não os pouparei se eu for aí outra vez,

[[v47-13-3]]

^<<v47-13-3,3>>^ visto que vocês estão querendo provas de que Cristo, que não é fraco ao lidar com vocês, mas é poderoso entre vocês, fala realmente por meio de mim.

[[v47-13-4]]

^<<v47-13-4,4>>^ Pois, de fato, ele foi morto na estaca em razão de sua fraqueza, mas está vivo por causa do poder de Deus. É verdade que nós também somos fracos com ele, mas viveremos junto com ele por causa do poder de Deus em vocês.

[[v47-13-5]]

^<<v47-13-5,5>>^ Persistam em examinar se estão na fé; persistam em pôr à prova o que vocês mesmos são. Ou não reconhecem que Jesus Cristo está em união com vocês? A menos que estejam reprovados.

[[v47-13-6]]

^<<v47-13-6,6>>^ Eu realmente espero que vocês reconheçam que nós não estamos reprovados.

[[v47-13-7]]

^<<v47-13-7,7>>^ Oramos a Deus que vocês não façam nada de errado, não para que nós pareçamos aprovados, mas para que vocês façam o que é bom, mesmo que nós pareçamos reprovados.

[[v47-13-8]]

^<<v47-13-8,8>>^ Pois não podemos fazer nada contra a verdade, mas somente a favor da verdade.

[[v47-13-9]]

^<<v47-13-9,9>>^ Nós certamente nos alegramos sempre que estamos fracos e vocês poderosos. E o que pedimos em oração é que vocês sejam reajustados.

[[v47-13-10]]

^<<v47-13-10,10>>^ É por isso que escrevo estas coisas enquanto estou ausente, para que, quando estiver presente, não tenha de ser severo ao usar a autoridade que o Senhor me deu, que é para edificar, e não para derrubar.

[[v47-13-11]]

^<<v47-13-11,11>>^ Finalmente, irmãos, continuem a se alegrar, a ser reajustados, a ser consolados, a pensar do mesmo modo, a viver pacificamente; e o Deus de amor e de paz estará com vocês.

[[v47-13-12]]

^<<v47-13-12,12>>^ Cumprimentem uns aos outros com beijo santo.

[[v47-13-13]]

^<<v47-13-13,13>>^ Todos os santos lhes mandam saudações.

[[v47-13-14]]

^<<v47-13-14,14>>^ A bondade imerecida do Senhor Jesus Cristo, o amor de Deus e a participação no espírito santo estejam com todos vocês.

'''

xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[&#60; Capítulo Anterior] | <<v47-13-0,Topo>> | xref:048-galatas/048-galatas-001.adoc#v48-1-0[Próximo Capítulo &#62;]