include::./index.adoc[]

[[v47-9-0]]
=== A Segunda aos Coríntios, 9
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-9-1]]

^<<v47-9-1,1>>^ A respeito do serviço^&#42;1^ em favor dos santos, não é de todo necessário que eu lhes escreva,

[NOTE]
====
. Ou: “ministério”.
====

[[v47-9-2]]

^<<v47-9-2,2>>^ pois conheço a sua prontidão e dela falo com orgulho aos macedônios, dizendo que a Acaia já está pronta há um ano, e o zelo de vocês estimulou a maioria deles.

[[v47-9-3]]

^<<v47-9-3,3>>^ Mas estou enviando os irmãos, para que o orgulho que temos de vocês nesse respeito não se mostre infundado, e para que vocês estejam realmente prontos, assim como eu disse que estariam.

[[v47-9-4]]

^<<v47-9-4,4>>^ Senão, se os macedônios fossem comigo e não os achassem prontos, nós — para não mencionar vocês — ficaríamos envergonhados por ter tido confiança em vocês.

[[v47-9-5]]

^<<v47-9-5,5>>^ Por isso achei necessário incentivar os irmãos a ir visitá-los antes e a aprontar com antecedência a sua prometida dádiva generosa, para que estivesse pronta como algo dado com generosidade, e não à força.

[[v47-9-6]]

^<<v47-9-6,6>>^ Mas, quanto a isso, quem semear parcimoniosamente colherá também parcimoniosamente, e quem semear generosamente colherá também generosamente.

[[v47-9-7]]

^<<v47-9-7,7>>^ Faça cada um conforme resolveu no coração, não a contragosto^&#42;1^ nem por obrigação, pois Deus ama quem dá com alegria.

[NOTE]
====
. Ou: “não com relutância”.
====

[[v47-9-8]]

^<<v47-9-8,8>>^ Além do mais, Deus é capaz de tornar abundante para vocês toda a Sua bondade imerecida, para que sempre sejam plenamente autossuficientes em tudo, e também tenham bastante para toda boa obra.

[[v47-9-9]]

^<<v47-9-9,9>>^ (Assim como está escrito: “Ele distribui amplamente;^&#42;1^ dá aos pobres. Sua justiça permanece para sempre.”

[NOTE]
====
. Ou: “generosamente”.
====

[[v47-9-10]]

^<<v47-9-10,10>>^ Aquele que fornece abundantemente semente ao semeador e pão como alimento também fornecerá e multiplicará a semente para vocês semearem e aumentará a colheita da justiça de vocês.)

[[v47-9-11]]

^<<v47-9-11,11>>^ Em tudo vocês estão sendo enriquecidos para praticar todo tipo de generosidade, a qual, por nosso intermédio, produz agradecimentos a Deus;

[[v47-9-12]]

^<<v47-9-12,12>>^ porque esse serviço que estão prestando^&#42;1^ não somente suprirá adequadamente as necessidades dos santos, mas também se tornará uma abundante fonte de agradecimentos a Deus.

[NOTE]
====
. Ou: “porque o ministério desse serviço público”.
====

[[v47-9-13]]

^<<v47-9-13,13>>^ Eles glorificam a Deus, pois esse serviço de ajuda^&#42;1^ prova que vocês são submissos às boas novas a respeito do Cristo, conforme declararam publicamente, e que são generosos na sua contribuição para eles e para todos.

[NOTE]
====
. Ou: “esse ministério”.
====

[[v47-9-14]]

^<<v47-9-14,14>>^ E, com súplicas a favor de vocês, eles expressam que os amam, por causa da extraordinária bondade imerecida de Deus para com vocês.

[[v47-9-15]]

^<<v47-9-15,15>>^ Graças sejam dadas a Deus por Sua indescritível dádiva.^&#42;1^

[NOTE]
====
. Ou: “dádiva gratuita”.
====

'''

xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[&#60; Capítulo Anterior] | <<v47-9-0,Topo>> | xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[Próximo Capítulo &#62;]