include::./index.adoc[]

[[v47-2-0]]
=== A Segunda aos Coríntios, 2
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-2-1]]

^<<v47-2-1,1>>^ Pois eu decidi que a minha próxima visita a vocês não será triste.

[[v47-2-2]]

^<<v47-2-2,2>>^ Porque, se eu os entristecer, quem haverá para me alegrar, a não ser aqueles que eu tiver entristecido?

[[v47-2-3]]

^<<v47-2-3,3>>^ Escrevi o que escrevi para que, quando eu for aí, não fique triste por causa daqueles que deveriam me alegrar; porque tenho confiança de que o que me traz alegria traz a mesma alegria a todos vocês.

[[v47-2-4]]

^<<v47-2-4,4>>^ Pois eu lhes escrevi com muita aflição e angústia de coração, com muitas lágrimas, não para entristecê-los, mas para que soubessem do profundo amor que tenho por vocês.

[[v47-2-5]]

^<<v47-2-5,5>>^ Ora, se alguém causou tristeza, ele entristeceu não a mim, mas a todos vocês, até certo ponto — para não ser severo demais no que digo.

[[v47-2-6]]

^<<v47-2-6,6>>^ Essa censura da parte da maioria é suficiente para esse homem;

[[v47-2-7]]

^<<v47-2-7,7>>^ agora, ao contrário, vocês devem perdoá-lo bondosamente e consolá-lo, para que ele não seja vencido^&#42;1^ pela excessiva tristeza.

[NOTE]
====
. Ou: “consumido”.
====

[[v47-2-8]]

^<<v47-2-8,8>>^ Eu os exorto, portanto, a reafirmar o seu amor por ele.

[[v47-2-9]]

^<<v47-2-9,9>>^ Pois é também por isso que lhes escrevi: para ver se vocês dariam provas de que são obedientes em todas as coisas.

[[v47-2-10]]

^<<v47-2-10,10>>^ Se vocês perdoarem alguém por alguma coisa, eu também perdoo. De fato, o que perdoei (se eu tiver perdoado alguma coisa), foi para o bem de vocês, à vista de Cristo,

[[v47-2-11]]

^<<v47-2-11,11>>^ para que não sejamos vencidos^&#42;1^ por Satanás, pois não desconhecemos as suas tramas.^&#42;2^

[NOTE]
====
. Ou: “enganados”.
. Ou: “intenções; maquinações”.
====

[[v47-2-12]]

^<<v47-2-12,12>>^ Quando cheguei a Trôade para declarar as boas novas a respeito do Cristo, e foi aberta para mim uma porta na obra do Senhor,^&#42;1^

[NOTE]
====
. Lit.: “uma porta no Senhor”.
====

[[v47-2-13]]

^<<v47-2-13,13>>^ meu espírito não teve alívio porque não achei Tito, meu irmão. Então me despedi dos irmãos dali e parti para a Macedônia.

[[v47-2-14]]

^<<v47-2-14,14>>^ Mas graças sejam dadas a Deus, que sempre nos conduz num desfile triunfal em companhia do Cristo e, por nosso intermédio, espalha^&#42;1^ o aroma do conhecimento dele por toda a parte!

[NOTE]
====
. Ou: “faz sentir”.
====

[[v47-2-15]]

^<<v47-2-15,15>>^ Pois para Deus somos aroma agradável de Cristo, entre os que estão a caminho da salvação^&#42;1^ e entre os que estão a caminho da destruição^&#42;2^

[NOTE]
====
. Ou: “estão sendo salvos”.
. Ou: “estão perecendo”.
====

[[v47-2-16]]

^<<v47-2-16,16>>^ — para estes últimos, cheiro^&#42;1^ de morte que leva à morte; para os primeiros, aroma de vida que leva à vida. E quem está qualificado para isso?

[NOTE]
====
. Ou: “aroma”.
====

[[v47-2-17]]

^<<v47-2-17,17>>^ Nós estamos, pois não somos vendedores ambulantes da^&#42;1^ palavra de Deus, como muitos são, mas falamos com toda a sinceridade como enviados por Deus, sim, à vista de Deus e na companhia de Cristo.

[NOTE]
====
. Ou: “não comercializamos a; não lucramos com a”.
====

'''

xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[&#60; Capítulo Anterior] | <<v47-2-0,Topo>> | xref:047-2-corintios/047-2-corintios-003.adoc#v47-3-0[Próximo Capítulo &#62;]