include::./index.adoc[]

[[v47-7-0]]
=== A Segunda aos Coríntios, 7
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-7-1]]

^<<v47-7-1,1>>^ Portanto, amados, visto que temos essas promessas, purifiquemo-nos de toda imundície da carne e do espírito, aperfeiçoando a santidade no temor de Deus.

[[v47-7-2]]

^<<v47-7-2,2>>^ Deem lugar a nós no seu coração. Não fizemos injustiça a ninguém, não corrompemos a ninguém, não nos aproveitamos de ninguém.

[[v47-7-3]]

^<<v47-7-3,3>>^ Não digo isso para condenar vocês. Pois eu já disse que vocês estão no nosso coração, para morrer conosco e para viver conosco.

[[v47-7-4]]

^<<v47-7-4,4>>^ Uso de muita franqueza ao falar com vocês. Tenho muito orgulho de vocês. Estou plenamente consolado; estou transbordando de alegria em toda a nossa aflição.

[[v47-7-5]]

^<<v47-7-5,5>>^ De fato, quando chegamos à Macedônia, não tivemos^&#42;1^ alívio, mas continuamos a ser afligidos de todos os modos — havia lutas por fora, temores por dentro.

[NOTE]
====
. Lit.: “nossa carne não teve”.
====

[[v47-7-6]]

^<<v47-7-6,6>>^ Mas Deus, que consola os desanimados, nos consolou com a presença de Tito;

[[v47-7-7]]

^<<v47-7-7,7>>^ e não somente com a presença dele, mas também com o consolo que ele recebeu por causa de vocês, pois ele nos contou do seu desejo de me ver, da sua profunda tristeza, da sua sincera preocupação^&#42;1^ por mim; de modo que me alegrei ainda mais.

[NOTE]
====
. Lit.: “do seu zelo”.
====

[[v47-7-8]]

^<<v47-7-8,8>>^ Pois, mesmo que eu os tenha entristecido com a minha carta, não lamento isso. Embora a princípio eu tenha lamentado (porque vejo que a carta os entristeceu, ainda que por pouco tempo),

[[v47-7-9]]

^<<v47-7-9,9>>^ agora me alegro, não porque vocês foram entristecidos, mas porque a sua tristeza os levou ao arrependimento. Pois vocês foram entristecidos segundo a vontade de Deus,^&#42;1^ e assim não foram prejudicados em nada por nossa causa.

[NOTE]
====
. Ou: “entristecidos de modo piedoso”.
====

[[v47-7-10]]

^<<v47-7-10,10>>^ Porque a tristeza segundo a vontade de Deus^&#42;1^ produz o arrependimento que leva à salvação, e disso ninguém se lamentará; mas a tristeza do mundo produz a morte.

[NOTE]
====
. Ou: “tristeza piedosa”.
====

[[v47-7-11]]

^<<v47-7-11,11>>^ Pois vejam que diligência a sua tristeza segundo a vontade de Deus^&#42;1^ produziu em vocês: fez com que se reabilitassem, que ficassem indignados, que tivessem temor, desejo sincero e zelo, que corrigissem o erro! Vocês demonstraram em todos os sentidos que são puros^&#42;2^ nesse assunto.

[NOTE]
====
. Ou: “tristeza piedosa”.
. Ou: “castos; inocentes”.
====

[[v47-7-12]]

^<<v47-7-12,12>>^ Embora eu tenha escrito a vocês, não fiz isso por causa daquele que cometeu o erro, nem daquele contra quem se cometeu o erro, mas para que ficasse clara entre vocês, à vista de Deus, a sua diligência em nos obedecer.

[[v47-7-13]]

^<<v47-7-13,13>>^ É por isso que fomos consolados.
Mas, além do consolo que recebemos, nós nos alegramos ainda mais por causa da alegria de Tito, porque todos vocês reanimaram o espírito dele.

[[v47-7-14]]

^<<v47-7-14,14>>^ Pois, se eu falei de vocês para ele com orgulho, não fui envergonhado; mas, assim como tudo o que dissemos a vocês era verdade, também se mostrou verdadeiro aquilo que falamos a Tito com orgulho.

[[v47-7-15]]

^<<v47-7-15,15>>^ Além disso, os ternos sentimentos dele por vocês aumentam quando ele se lembra da obediência de todos vocês, de como o receberam com temor e tremor.

[[v47-7-16]]

^<<v47-7-16,16>>^ Eu me alegro porque em tudo posso ter confiança em^&#42;1^ vocês.

[NOTE]
====
. Ou, possivelmente: “posso ter bom ânimo por causa de”.
====

'''

xref:047-2-corintios/047-2-corintios-006.adoc#v47-6-0[&#60; Capítulo Anterior] | <<v47-7-0,Topo>> | xref:047-2-corintios/047-2-corintios-008.adoc#v47-8-0[Próximo Capítulo &#62;]