include::./index.adoc[]

[[v47-11-0]]
=== A Segunda aos Coríntios, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-11-1]]

^<<v47-11-1,1>>^ Eu gostaria que vocês me suportassem numa pequena insensatez. Mas, de fato, vocês estão me suportando!

[[v47-11-2]]

^<<v47-11-2,2>>^ Pois tenho ciúme de vocês, um ciúme semelhante ao de Deus,^&#42;1^ porque eu pessoalmente os prometi em casamento a um só marido, ao Cristo, a fim de apresentá-los como virgem casta^&#42;2^ a ele.

[NOTE]
====
. Lit.: “um zelo de Deus”.
. Ou: “pura”.
====

[[v47-11-3]]

^<<v47-11-3,3>>^ Mas tenho medo de que, assim como a serpente seduziu Eva pela sua astúcia, a mente de vocês seja de algum modo corrompida, afastando-se da sinceridade e da castidade^&#42;1^ que devemos ao Cristo.

[NOTE]
====
. Ou: “pureza”.
====

[[v47-11-4]]

^<<v47-11-4,4>>^ Pois, de fato, se alguém chega e prega um Jesus diferente do que nós pregamos, ou se vocês recebem um espírito diferente do que receberam, ou boas novas diferentes das que aceitaram, vocês facilmente o suportam.

[[v47-11-5]]

^<<v47-11-5,5>>^ Pois eu não me considero inferior aos seus superapóstolos em coisa alguma.

[[v47-11-6]]

^<<v47-11-6,6>>^ Mas, mesmo que eu seja imperito no falar, certamente não o sou no conhecimento; de fato, deixamos isso claro a vocês de todos os modos e em todas as coisas.

[[v47-11-7]]

^<<v47-11-7,7>>^ Ou será que cometi um pecado por me humilhar para que vocês fossem enaltecidos, ao declarar-lhes de boa vontade as boas novas de Deus sem custo?

[[v47-11-8]]

^<<v47-11-8,8>>^ A outras congregações despojei,^&#42;1^ aceitando provisões^&#42;2^ delas a fim de servir a vocês.

[NOTE]
====
. Lit.: “roubei”.
. Ou: “apoio”.
====

[[v47-11-9]]

^<<v47-11-9,9>>^ Contudo, quando estive presente entre vocês e passei necessidade, não me tornei um fardo para ninguém, pois os irmãos vindos da Macedônia supriram abundantemente as minhas necessidades. Sim, tomei cuidado para não me tornar um fardo para vocês em nenhum sentido, e continuarei fazendo isso.

[[v47-11-10]]

^<<v47-11-10,10>>^ Tão certo como a verdade de Cristo está em mim, não deixarei de falar com orgulho sobre isso nas regiões da Acaia.

[[v47-11-11]]

^<<v47-11-11,11>>^ Por quê? Porque não amo vocês? Deus sabe que os amo.

[[v47-11-12]]

^<<v47-11-12,12>>^ Mas o que estou fazendo continuarei fazendo, a fim de eliminar o pretexto daqueles que estão procurando um motivo^&#42;1^ para ser considerados iguais a nós nas coisas das quais^&#42;2^ se gabam.

[NOTE]
====
. Ou: “pretexto”.
. Ou: “no cargo do qual”.
====

[[v47-11-13]]

^<<v47-11-13,13>>^ Pois esses homens são falsos apóstolos, trabalhadores enganosos, disfarçados de apóstolos de Cristo.

[[v47-11-14]]

^<<v47-11-14,14>>^ E isso não é de admirar, pois o próprio Satanás se disfarça de anjo de luz.

[[v47-11-15]]

^<<v47-11-15,15>>^ Portanto, não surpreende que os servos^&#42;1^ dele também se disfarcem de servos^&#42;2^ da justiça. Mas o fim deles será segundo as suas obras.

[NOTE]
====
. Ou: “ministros”.
. Ou: “ministros”.
====

[[v47-11-16]]

^<<v47-11-16,16>>^ Digo novamente: Que ninguém pense que sou insensato. Mas, se vocês pensam isso, então aceitem-me como um insensato, para que eu também me gabe um pouco.

[[v47-11-17]]

^<<v47-11-17,17>>^ Estou falando agora, não seguindo o exemplo do Senhor, mas como alguém insensato, com a autoconfiança de quem se gaba.

[[v47-11-18]]

^<<v47-11-18,18>>^ Já que muitos se gabam segundo a carne,^&#42;1^ eu também me gabarei.

[NOTE]
====
. Isto é, por motivos humanos.
====

[[v47-11-19]]

^<<v47-11-19,19>>^ Vocês, que são tão “sensatos”, suportam de boa vontade os insensatos.

[[v47-11-20]]

^<<v47-11-20,20>>^ De fato, suportam a quem quer que os escravize, a quem quer que devore os seus bens, a quem quer que tome o que vocês têm, a quem quer que se enalteça sobre vocês, a quem quer que lhes bata no rosto.

[[v47-11-21]]

^<<v47-11-21,21>>^ É uma desonra para nós dizer isso, pois pode parecer que fomos fracos.
Mas, se outros agem com ousadia — estou falando como insensato —, eu também ajo com ousadia.

[[v47-11-22]]

^<<v47-11-22,22>>^ Eles são hebreus? Eu também sou. São israelitas? Eu também sou. São descendência^&#42;1^ de Abraão? Eu também sou.

[NOTE]
====
. Lit.: “semente”.
====

[[v47-11-23]]

^<<v47-11-23,23>>^ São ministros de Cristo? Respondo como louco: eu o sou ainda mais destacadamente — eu trabalhei mais, fui preso mais vezes, sofri incontáveis golpes e muitas vezes corri perigo de morte;

[[v47-11-24]]

^<<v47-11-24,24>>^ cinco vezes recebi dos judeus 40 golpes menos um,

[[v47-11-25]]

^<<v47-11-25,25>>^ três vezes fui espancado com varas, uma vez fui apedrejado, três vezes sofri naufrágio, uma noite e um dia passei em alto-mar;

[[v47-11-26]]

^<<v47-11-26,26>>^ em muitas viagens, em perigos de rios, em perigos de ladrões, em perigos por parte do meu próprio povo, em perigos por parte das nações, em perigos na cidade, em perigos no deserto,^&#42;1^ em perigos no mar, em perigos entre falsos irmãos,

[NOTE]
====
. Veja o Glossário.
====

[[v47-11-27]]

^<<v47-11-27,27>>^ em grande esforço e trabalho árduo, em muitas noites sem dormir, em fome e sede, frequentemente sem ter o que comer, em frio e sem ter o que vestir.^&#42;1^

[NOTE]
====
. Lit.: “e em nudez”.
====

[[v47-11-28]]

^<<v47-11-28,28>>^ Além dessas coisas exteriores, há o que diariamente pesa sobre mim:^&#42;1^ a ansiedade por todas as congregações.

[NOTE]
====
. Ou: “há a pressão diária que enfrento”.
====

[[v47-11-29]]

^<<v47-11-29,29>>^ Quem está fraco, sem que eu também me sinta fraco? Quem tropeça, sem que eu fique enfurecido?

[[v47-11-30]]

^<<v47-11-30,30>>^ Se é preciso que me gabe, eu me gabarei das coisas que mostram a minha fraqueza.

[[v47-11-31]]

^<<v47-11-31,31>>^ O Deus e Pai do Senhor Jesus, Aquele que deve ser louvado para sempre, sabe que não estou mentindo.

[[v47-11-32]]

^<<v47-11-32,32>>^ Em Damasco, o governador sob o rei Aretas pôs guardas na cidade dos damascenos para me prender,

[[v47-11-33]]

^<<v47-11-33,33>>^ mas me fizeram descer num cesto^&#42;1^ por uma janela na muralha da cidade, e eu escapei das mãos dele.

[NOTE]
====
. Ou: “cesto de vime”.
====

'''

xref:047-2-corintios/047-2-corintios-010.adoc#v47-10-0[&#60; Capítulo Anterior] | <<v47-11-0,Topo>> | xref:047-2-corintios/047-2-corintios-012.adoc#v47-12-0[Próximo Capítulo &#62;]