include::./index.adoc[]

[[v47-8-0]]
=== A Segunda aos Coríntios, 8
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v47-8-1]]

^<<v47-8-1,1>>^ Agora, irmãos, queremos que vocês saibam da bondade imerecida de Deus que foi concedida às congregações da Macedônia.

[[v47-8-2]]

^<<v47-8-2,2>>^ Mesmo sob aflição durante uma grande prova, a imensa alegria e a extrema pobreza deles fizeram transbordar^&#42;1^ as riquezas de sua generosidade.

[NOTE]
====
. Ou: “tornaram abundantes”.
====

[[v47-8-3]]

^<<v47-8-3,3>>^ Pois o que eles fizeram foi segundo seus recursos, sim, sou testemunha de que foi até mesmo além de seus recursos;

[[v47-8-4]]

^<<v47-8-4,4>>^ eles nos suplicavam insistentemente, de sua própria iniciativa, pelo privilégio de dar bondosamente, para participar no serviço^&#42;1^ de ajuda aos santos.

[NOTE]
====
. Ou: “ministério”.
====

[[v47-8-5]]

^<<v47-8-5,5>>^ E fizeram mais do que esperávamos, visto que se entregaram primeiramente ao Senhor e a nós, pela vontade de Deus.

[[v47-8-6]]

^<<v47-8-6,6>>^ Assim, incentivamos Tito a terminar a coleta da bondosa dádiva de vocês, visto que ele havia iniciado esse trabalho no seu meio.

[[v47-8-7]]

^<<v47-8-7,7>>^ Portanto, assim como vocês são ricos em tudo — em fé, em palavra, em conhecimento, em toda a diligência e em nosso amor por vocês —, sejam ricos também no que se refere a essa bondosa dádiva.

[[v47-8-8]]

^<<v47-8-8,8>>^ Não digo isso como uma ordem, mas para informá-los da diligência de outros e para pôr à prova a sinceridade do amor de vocês.

[[v47-8-9]]

^<<v47-8-9,9>>^ Pois vocês conhecem a bondade imerecida do nosso Senhor Jesus Cristo: embora fosse rico, tornou-se pobre por causa de vocês, para que vocês se tornassem ricos por meio da pobreza dele.

[[v47-8-10]]

^<<v47-8-10,10>>^ E a esse respeito dou a minha opinião: cuidar disso é para o seu próprio bem, visto que já faz um ano que vocês não somente iniciaram essa obra, mas também mostraram o desejo de fazê-la.

[[v47-8-11]]

^<<v47-8-11,11>>^ Agora, então, terminem o que começaram, de modo que a sua prontidão para agir seja completada segundo os recursos que têm à disposição.

[[v47-8-12]]

^<<v47-8-12,12>>^ Pois, se já existe a prontidão, a dádiva é especialmente aceitável segundo o que a pessoa tem, não segundo o que a pessoa não tem.

[[v47-8-13]]

^<<v47-8-13,13>>^ Porque não quero aliviar outros e sobrecarregar vocês;

[[v47-8-14]]

^<<v47-8-14,14>>^ mas, por meio de uma compensação,^&#42;1^ que o excedente que agora vocês têm supra a necessidade deles, a fim de que o excedente deles também supra a carência de vocês, e desse modo haja uma compensação.^&#42;2^

[NOTE]
====
. Ou: “reciprocidade”.
. Ou: “reciprocidade”.
====

[[v47-8-15]]

^<<v47-8-15,15>>^ Assim como está escrito: “Quem tinha muito não teve demais, e quem tinha pouco não teve de menos.”

[[v47-8-16]]

^<<v47-8-16,16>>^ Graças sejam dadas a Deus por ter colocado no coração de Tito a mesma preocupação sincera que temos por vocês,

[[v47-8-17]]

^<<v47-8-17,17>>^ porque ele não só correspondeu ao nosso incentivo, mas, como tem muito boa vontade, está indo visitá-los por iniciativa própria.

[[v47-8-18]]

^<<v47-8-18,18>>^ Nós, porém, estamos enviando junto com ele o irmão que tem sido elogiado em todas as congregações por causa do que está fazendo pelas boas novas.

[[v47-8-19]]

^<<v47-8-19,19>>^ Não só isso, mas ele também foi designado pelas congregações para ser nosso companheiro de viagem ao cuidarmos dessa^&#42;1^ bondosa dádiva para a glória do Senhor e como prova da nossa prontidão em ajudar.

[NOTE]
====
. Ou: “administrarmos essa”.
====

[[v47-8-20]]

^<<v47-8-20,20>>^ Estamos assim evitando que alguém nos critique com relação a essa contribuição generosa da qual estamos cuidando.^&#42;1^

[NOTE]
====
. Ou: “que estamos administrando”.
====

[[v47-8-21]]

^<<v47-8-21,21>>^ Pois ‘cuidamos de tudo honestamente, não somente à vista de Jeová,^&#42;1^ mas também à vista dos homens’.

[NOTE]
====
. Veja Ap. A5.
====

[[v47-8-22]]

^<<v47-8-22,22>>^ Além disso, estamos enviando com eles o nosso irmão, cuja diligência comprovamos muitas vezes e em muitos assuntos; mas ele agora se mostra ainda mais diligente por causa da grande confiança que tem em vocês.

[[v47-8-23]]

^<<v47-8-23,23>>^ No entanto, se houver qualquer dúvida quanto a Tito, ele é meu companheiro^&#42;1^ e colaborador a favor dos interesses de vocês; ou, se houver dúvidas quanto aos nossos irmãos, eles são enviados^&#42;2^ das congregações e uma glória para Cristo.

[NOTE]
====
. Lit.: “parceiro”.
. Ou: “apóstolos”.
====

[[v47-8-24]]

^<<v47-8-24,24>>^ Portanto, deem a eles provas do seu amor e mostrem às congregações o motivo de falarmos com orgulho a respeito de vocês.

'''

xref:047-2-corintios/047-2-corintios-007.adoc#v47-7-0[&#60; Capítulo Anterior] | <<v47-8-0,Topo>> | xref:047-2-corintios/047-2-corintios-009.adoc#v47-9-0[Próximo Capítulo &#62;]