include::./index.adoc[]

[[v46-6-0]]
=== A Primeira aos Coríntios, 6
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-6-1]]

^<<v46-6-1,1>>^ Quando algum de vocês tem uma questão contra outro, como se atreve a ir a juízo perante os injustos, e não perante os santos?

[[v46-6-2]]

^<<v46-6-2,2>>^ Ou vocês não sabem que os santos julgarão o mundo? E, se o mundo será julgado por vocês, será que vocês não são capazes de julgar questões de tão pouca importância?

[[v46-6-3]]

^<<v46-6-3,3>>^ Não sabem que nós julgaremos anjos? Então por que não questões desta vida?

[[v46-6-4]]

^<<v46-6-4,4>>^ Se vocês, então, têm questões desta vida para serem julgadas, por que vocês escolhem como juízes a homens que são vistos com desaprovação pela congregação?

[[v46-6-5]]

^<<v46-6-5,5>>^ Digo isso para induzi-los à vergonha. Será que não há nenhum homem sábio entre vocês que possa julgar entre seus irmãos?

[[v46-6-6]]

^<<v46-6-6,6>>^ Em vez disso, irmão vai a juízo contra irmão, e isso perante descrentes!

[[v46-6-7]]

^<<v46-6-7,7>>^ Realmente, já é uma derrota para vocês quando movem ações judiciais uns contra os outros. Não seria melhor sofrer a injustiça? Não seria melhor ficar com o prejuízo?^&#42;1^

[NOTE]
====
. Ou: “ser defraudado”.
====

[[v46-6-8]]

^<<v46-6-8,8>>^ Pelo contrário, vocês fazem injustiça e causam prejuízo,^&#42;1^ e isso a seus irmãos!

[NOTE]
====
. Ou: “e defraudam”.
====

[[v46-6-9]]

^<<v46-6-9,9>>^ Ou será que vocês não sabem que os injustos não herdarão o Reino de Deus? Não se enganem.^&#42;1^ Os que praticam imoralidade sexual,^&#42;2^ os idólatras, os adúlteros, os homens que se submetem a atos homossexuais, os homens que praticam o homossexualismo,^&#42;3^

[NOTE]
====
. Ou: “Não se deixem enganar.”
. Veja o Glossário.
. Ou: “homens que têm relações sexuais com homens”. Lit.: “homens que se deitam com homens”.
====

[[v46-6-10]]

^<<v46-6-10,10>>^ os ladrões, os gananciosos, os beberrões, os injuriadores^&#42;1^ e os extorsores não herdarão o Reino de Deus.

[NOTE]
====
. Ou: “os que agridem com palavras”.
====

[[v46-6-11]]

^<<v46-6-11,11>>^ E, no entanto, isso é o que alguns de vocês foram. Mas vocês foram lavados; vocês foram santificados; vocês foram declarados justos no nome do Senhor Jesus Cristo e com o espírito do nosso Deus.

[[v46-6-12]]

^<<v46-6-12,12>>^ Tudo me é permitido,^&#42;1^ mas nem tudo é vantajoso. Tudo me é permitido, mas não me deixarei ser controlado^&#42;2^ por nada.

[NOTE]
====
. Ou: “lícito”.
. Ou: “colocado debaixo de autoridade”.
====

[[v46-6-13]]

^<<v46-6-13,13>>^ O alimento é para o estômago, e o estômago para o alimento; mas Deus reduzirá ambos a nada. O corpo não é para imoralidade sexual,^&#42;1^ mas para o Senhor; e o Senhor é para o corpo.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v46-6-14]]

^<<v46-6-14,14>>^ Mas Deus levantou o Senhor e também levantará a nós da morte, por meio do seu poder.

[[v46-6-15]]

^<<v46-6-15,15>>^ Vocês não sabem que os seus corpos são membros de Cristo? Deveria eu, então, tirar os membros do Cristo e uni-los a uma prostituta? De modo algum!

[[v46-6-16]]

^<<v46-6-16,16>>^ Vocês não sabem que aquele que se une a uma prostituta é um só corpo com ela? Pois “os dois”, diz ele, “serão uma só carne”.

[[v46-6-17]]

^<<v46-6-17,17>>^ Mas quem está unido ao Senhor é um só em espírito com ele.

[[v46-6-18]]

^<<v46-6-18,18>>^ Fujam da imoralidade sexual!^&#42;1^ Qualquer outro pecado que o homem possa cometer é fora de seu corpo, mas quem pratica a imoralidade sexual peca contra o seu próprio corpo.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
====

[[v46-6-19]]

^<<v46-6-19,19>>^ Vocês não sabem que o seu corpo é o templo do espírito santo, que está em vocês e que lhes foi dado por Deus? Além disso, vocês não pertencem a si mesmos,

[[v46-6-20]]

^<<v46-6-20,20>>^ pois foram comprados por um preço. Portanto, glorifiquem a Deus no corpo de vocês.

'''

xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[&#60; Capítulo Anterior] | <<v46-6-0,Topo>> | xref:046-1-corintios/046-1-corintios-007.adoc#v46-7-0[Próximo Capítulo &#62;]