include::./index.adoc[]

[[v46-9-0]]
=== A Primeira aos Coríntios, 9
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-9-1]]

^<<v46-9-1,1>>^ Não sou livre? Não sou apóstolo? Não vi Jesus, nosso Senhor? Não são vocês a minha obra no Senhor?

[[v46-9-2]]

^<<v46-9-2,2>>^ Mesmo que eu não seja apóstolo para os outros, com toda a certeza sou para vocês! Pois vocês são o selo que confirma o meu apostolado no Senhor.

[[v46-9-3]]

^<<v46-9-3,3>>^ Minha defesa perante os que me questionam é a seguinte:

[[v46-9-4]]

^<<v46-9-4,4>>^ Será que não temos o direito de^&#42;1^ comer e beber?

[NOTE]
====
. Lit.: “não temos autoridade para”.
====

[[v46-9-5]]

^<<v46-9-5,5>>^ Será que não temos o direito de ser acompanhados por uma esposa crente,^&#42;1^ assim como os outros apóstolos, os irmãos do Senhor e Cefas?^&#42;2^

[NOTE]
====
. Ou: “uma irmã como esposa”.
. Também chamado de Pedro.
====

[[v46-9-6]]

^<<v46-9-6,6>>^ Ou será que só eu e Barnabé não temos o direito de deixar de trabalhar para o nosso sustento?

[[v46-9-7]]

^<<v46-9-7,7>>^ Que soldado serve com os seus próprios recursos? Quem planta um vinhedo e não come do seu fruto? Ou quem pastoreia um rebanho e não toma do leite do rebanho?

[[v46-9-8]]

^<<v46-9-8,8>>^ Será que estou dizendo essas coisas de um ponto de vista humano? Ou a Lei não diz também essas coisas?

[[v46-9-9]]

^<<v46-9-9,9>>^ Pois está escrito na Lei de Moisés: “Não amordace o touro quando ele debulha o grão.” Será que é com touros que Deus está preocupado?

[[v46-9-10]]

^<<v46-9-10,10>>^ Ou não é de fato por nossa causa que ele diz isso? Realmente, isso foi escrito por nossa causa, porque o homem que ara e o homem que debulha devem fazer essas coisas na esperança de receber uma parte.

[[v46-9-11]]

^<<v46-9-11,11>>^ Se nós semeamos entre vocês coisas espirituais, seria demais colhermos de vocês apoio material?

[[v46-9-12]]

^<<v46-9-12,12>>^ Se outros homens têm esse direito sobre vocês, será que nós não temos esse direito ainda muito mais? Contudo, não fizemos uso desse direito,^&#42;1^ mas estamos suportando tudo para não criar nenhum obstáculo às boas novas a respeito do Cristo.

[NOTE]
====
. Lit.: “dessa autoridade”.
====

[[v46-9-13]]

^<<v46-9-13,13>>^ Vocês não sabem que os homens que cumprem deveres sagrados comem das coisas do templo, e que aqueles que servem regularmente diante do altar recebem uma parte do que é oferecido no altar?

[[v46-9-14]]

^<<v46-9-14,14>>^ Do mesmo modo, o Senhor ordenou que aqueles que proclamam as boas novas vivam das boas novas.

[[v46-9-15]]

^<<v46-9-15,15>>^ Mas eu não tenho feito uso de nem uma única dessas coisas. De fato, não escrevi para que se fizesse isso no meu caso, pois seria melhor morrer do que . . . Ninguém vai tirar o meu motivo de orgulho!

[[v46-9-16]]

^<<v46-9-16,16>>^ Ora, se eu estou declarando as boas novas, isso não é motivo para me orgulhar, pois me é imposta a necessidade. Realmente, ai de mim se eu não declarar as boas novas!

[[v46-9-17]]

^<<v46-9-17,17>>^ Se eu faço isso espontaneamente, tenho uma recompensa; mas, mesmo se o fizer contra a minha vontade, ainda assim estou incumbido de uma responsabilidade.^&#42;1^

[NOTE]
====
. Ou: “administração”.
====

[[v46-9-18]]

^<<v46-9-18,18>>^ Então, qual é a minha recompensa? É que, quando eu declarar as boas novas, eu ofereça as boas novas sem custo, para não abusar da minha autoridade^&#42;1^ no que se refere às boas novas.

[NOTE]
====
. Ou: “dos meus direitos”.
====

[[v46-9-19]]

^<<v46-9-19,19>>^ Pois, embora eu seja livre com relação a todos, eu me fiz escravo de todos, para ganhar o maior número possível de pessoas.

[[v46-9-20]]

^<<v46-9-20,20>>^ Para os judeus me tornei como judeu, para ganhar os judeus; para os debaixo de lei me tornei como debaixo de lei — embora eu mesmo não esteja debaixo de lei —, para ganhar os debaixo de lei.

[[v46-9-21]]

^<<v46-9-21,21>>^ Para os sem lei me tornei como sem lei — embora eu não esteja sem lei para com Deus, mas esteja debaixo de lei para com Cristo —, para ganhar os sem lei.

[[v46-9-22]]

^<<v46-9-22,22>>^ Para os fracos me tornei fraco, para ganhar os fracos. Eu me tornei todas as coisas para pessoas de todo tipo, para de todos os modos possíveis salvar alguns.

[[v46-9-23]]

^<<v46-9-23,23>>^ Mas faço tudo pela causa das boas novas, para compartilhá-las com outros.

[[v46-9-24]]

^<<v46-9-24,24>>^ Vocês não sabem que numa corrida todos os corredores correm, mas apenas um recebe o prêmio? Corram de tal modo que consigam ganhá-lo.

[[v46-9-25]]

^<<v46-9-25,25>>^ Todos os que participam numa competição exercem^&#42;1^ autodomínio em todas as coisas. Claro, eles fazem isso para receber uma coroa perecível, mas nós, uma que não perece.

[NOTE]
====
. Ou: “Todo atleta exerce”.
====

[[v46-9-26]]

^<<v46-9-26,26>>^ Portanto, não corro sem rumo; direciono os meus golpes de modo a não golpear o ar;

[[v46-9-27]]

^<<v46-9-27,27>>^ surro^&#42;1^ o meu corpo e o conduzo como escravo, para que, depois de ter pregado a outros, eu mesmo não venha a ser de algum modo reprovado.^&#42;2^

[NOTE]
====
. Ou: “puno; disciplino severamente”.
. Ou: “desqualificado”.
====

'''

xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[&#60; Capítulo Anterior] | <<v46-9-0,Topo>> | xref:046-1-corintios/046-1-corintios-010.adoc#v46-10-0[Próximo Capítulo &#62;]