include::./index.adoc[]

[[v46-16-0]]
=== A Primeira aos Coríntios, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-16-1]]

^<<v46-16-1,1>>^ Agora, quanto à coleta para os santos, vocês podem seguir as orientações que dei às congregações da Galácia.

[[v46-16-2]]

^<<v46-16-2,2>>^ Todo primeiro dia da semana, cada um de vocês deve pôr algo à parte, conforme os seus recursos, para que as coletas não sejam feitas quando eu chegar.

[[v46-16-3]]

^<<v46-16-3,3>>^ Mas, quando eu chegar aí, enviarei a Jerusalém os homens que vocês aprovarem por cartas, para que levem a bondosa dádiva de vocês.

[[v46-16-4]]

^<<v46-16-4,4>>^ No entanto, se parecer apropriado que eu também vá para lá, eles irão comigo.

[[v46-16-5]]

^<<v46-16-5,5>>^ Mas vou visitar vocês depois de ter passado pela Macedônia, pois vou passar pela Macedônia;

[[v46-16-6]]

^<<v46-16-6,6>>^ e talvez fique algum tempo com vocês, ou até passe o inverno aí, para que depois vocês me acompanhem parte do caminho para onde eu for.

[[v46-16-7]]

^<<v46-16-7,7>>^ Pois não quero agora vê-los só de passagem; espero passar algum tempo com vocês, se Jeová^&#42;1^ permitir.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-16-8]]

^<<v46-16-8,8>>^ No entanto, vou permanecer em Éfeso até a Festividade de Pentecostes,

[[v46-16-9]]

^<<v46-16-9,9>>^ porque me foi aberta uma porta ampla para atividade, mas há muitos opositores.

[[v46-16-10]]

^<<v46-16-10,10>>^ Se Timóteo chegar aí, tomem providências para que ele não tenha nada a temer enquanto estiver entre vocês, pois ele está realizando a obra de Jeová,^&#42;1^ assim como eu.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-16-11]]

^<<v46-16-11,11>>^ Portanto, que ninguém o menospreze. Encaminhem-no em paz em sua viagem, para que ele venha me encontrar, pois estou esperando por ele junto com os irmãos.

[[v46-16-12]]

^<<v46-16-12,12>>^ Quanto a Apolo, nosso irmão, insisti muito que ele fosse visitar vocês com os irmãos. Ele não tem intenção de ir agora, mas irá quando tiver oportunidade.

[[v46-16-13]]

^<<v46-16-13,13>>^ Fiquem despertos, mantenham-se firmes na fé, sejam corajosos,^&#42;1^ tornem-se poderosos.

[NOTE]
====
. Ou: “ajam como homens”.
====

[[v46-16-14]]

^<<v46-16-14,14>>^ Que tudo que vocês fizerem seja com amor.

[[v46-16-15]]

^<<v46-16-15,15>>^ Tenho uma exortação a dar a vocês, irmãos: vocês sabem que os da casa de Estéfanas são os primeiros frutos da Acaia e que eles se dedicaram a servir os santos.

[[v46-16-16]]

^<<v46-16-16,16>>^ Que vocês também se sujeitem a pessoas como eles e a todos os que cooperam e trabalham arduamente.

[[v46-16-17]]

^<<v46-16-17,17>>^ Mas eu me alegro com a presença de Estéfanas, de Fortunato e de Acaico, porque compensaram a ausência de vocês aqui.

[[v46-16-18]]

^<<v46-16-18,18>>^ Pois eles reanimaram o meu espírito e o de vocês. Portanto, reconheçam o valor de homens como esses.

[[v46-16-19]]

^<<v46-16-19,19>>^ As congregações da Ásia lhes mandam saudações. Áquila e Prisca, junto com a congregação que se reúne na casa deles, enviam a vocês calorosas saudações no Senhor.

[[v46-16-20]]

^<<v46-16-20,20>>^ Todos os irmãos lhes enviam saudações. Cumprimentem uns aos outros com beijo santo.

[[v46-16-21]]

^<<v46-16-21,21>>^ Aqui estão as minhas saudações, as de Paulo, pela minha própria mão.

[[v46-16-22]]

^<<v46-16-22,22>>^ Se alguém não amar o Senhor, seja amaldiçoado. Venha, nosso Senhor!

[[v46-16-23]]

^<<v46-16-23,23>>^ Que a bondade imerecida do Senhor Jesus esteja com vocês.

[[v46-16-24]]

^<<v46-16-24,24>>^ Que o meu amor esteja com todos vocês em união com Cristo Jesus.

'''

xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[&#60; Capítulo Anterior] | <<v46-16-0,Topo>> | xref:047-2-corintios/047-2-corintios-001.adoc#v47-1-0[Próximo Capítulo &#62;]