include::./index.adoc[]

[[v46-5-0]]
=== A Primeira aos Coríntios, 5
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-5-1]]

^<<v46-5-1,1>>^ O fato é que se relata entre vocês imoralidade sexual,^&#42;1^ imoralidade^&#42;2^ que não se encontra nem entre as nações: um homem está vivendo com^&#42;3^ a esposa de seu pai.

[NOTE]
====
. Em grego, porneía. Veja o Glossário.
. Em grego, porneía. Veja o Glossário.
. Lit.: “possuindo”.
====

[[v46-5-2]]

^<<v46-5-2,2>>^ E vocês se orgulham disso? Não deviam, na verdade, estar de luto, para que o homem que cometeu esse ato fosse tirado do seu meio?

[[v46-5-3]]

^<<v46-5-3,3>>^ Embora eu esteja ausente em corpo, estou presente em espírito, e já julguei o homem que fez isso, como se eu estivesse aí com vocês.

[[v46-5-4]]

^<<v46-5-4,4>>^ Quando estiverem reunidos em nome do nosso Senhor Jesus, sabendo que estou com vocês em espírito com o poder do nosso Senhor Jesus,

[[v46-5-5]]

^<<v46-5-5,5>>^ entreguem esse homem a Satanás, para a destruição da carne, a fim de que o espírito seja salvo no dia do Senhor.

[[v46-5-6]]

^<<v46-5-6,6>>^ O seu motivo de orgulho não é bom. Não sabem que um pouco de fermento leveda a massa toda?

[[v46-5-7]]

^<<v46-5-7,7>>^ Eliminem o velho fermento, para que sejam massa nova, sem fermento, como de fato são. Pois, realmente, Cristo, o nosso cordeiro pascoal, já foi sacrificado.

[[v46-5-8]]

^<<v46-5-8,8>>^ Portanto, celebremos a festividade, não com o velho fermento, nem com o fermento da maldade e da impiedade, mas com pães sem fermento, de sinceridade e de verdade.

[[v46-5-9]]

^<<v46-5-9,9>>^ Eu lhes escrevi na minha carta que parassem de ter convivência^&#42;1^ com os que praticam imoralidade sexual,^&#42;2^

[NOTE]
====
. Ou: “de se associar”.
. Veja o Glossário.
====

[[v46-5-10]]

^<<v46-5-10,10>>^ não querendo dizer toda a convivência com as pessoas deste mundo que praticam imoralidade sexual,^&#42;1^ ou com os gananciosos, com os extorsores ou com os idólatras. Nesse caso, vocês teriam realmente de sair do mundo.

[NOTE]
====
. Veja o Glossário.
====

[[v46-5-11]]

^<<v46-5-11,11>>^ Mas eu lhes escrevo agora que parem de ter convivência^&#42;1^ com qualquer um que se chame irmão, mas que pratique imoralidade sexual,^&#42;2^ ou que seja ganancioso, idólatra, injuriador,^&#42;3^ beberrão ou extorsor; nem sequer comam com tal homem.

[NOTE]
====
. Ou: “de se associar”.
. Veja o Glossário.
. Ou: “uma pessoa que agride com palavras”.
====

[[v46-5-12]]

^<<v46-5-12,12>>^ Pois o que eu tenho a ver com o julgamento dos de fora? Não são vocês que julgam os de dentro,

[[v46-5-13]]

^<<v46-5-13,13>>^ ao passo que Deus julga os de fora? “Removam do meio de vocês a pessoa má.”

'''

xref:046-1-corintios/046-1-corintios-004.adoc#v46-4-0[&#60; Capítulo Anterior] | <<v46-5-0,Topo>> | xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[Próximo Capítulo &#62;]