include::./index.adoc[]

[[v46-7-0]]
=== A Primeira aos Coríntios, 7
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-7-1]]

^<<v46-7-1,1>>^ Agora, quanto às coisas sobre as quais vocês escreveram, é melhor que o homem não toque em^&#42;1^ mulher;

[NOTE]
====
. Isto é, não tenha relações sexuais com.
====

[[v46-7-2]]

^<<v46-7-2,2>>^ mas, visto que há tanta imoralidade sexual,^&#42;1^ que cada homem tenha a sua própria esposa, e que cada mulher tenha o seu próprio marido.

[NOTE]
====
. Aqui a palavra grega porneía ocorre no plural. Veja o Glossário.
====

[[v46-7-3]]

^<<v46-7-3,3>>^ O marido dê à esposa o que lhe é devido, e faça a esposa o mesmo para com o marido.

[[v46-7-4]]

^<<v46-7-4,4>>^ A esposa não tem autoridade sobre o seu próprio corpo, mas sim o marido; do mesmo modo, o marido não tem autoridade sobre o seu próprio corpo, mas sim a esposa.

[[v46-7-5]]

^<<v46-7-5,5>>^ Não privem um ao outro do que é devido, a não ser por consentimento mútuo, por um tempo determinado, para que dediquem tempo à oração e depois se unam novamente, a fim de que Satanás não os tente pela sua falta de autodomínio.

[[v46-7-6]]

^<<v46-7-6,6>>^ No entanto, digo isso como concessão, não como ordem.

[[v46-7-7]]

^<<v46-7-7,7>>^ Mas eu queria que todos os homens fossem como eu. Entretanto, cada um tem o seu próprio dom da parte de Deus, um desse modo, outro daquele modo.

[[v46-7-8]]

^<<v46-7-8,8>>^ Agora, digo aos que não são casados e às viúvas que é melhor para eles que permaneçam assim como eu.

[[v46-7-9]]

^<<v46-7-9,9>>^ Mas, se não tiverem autodomínio, que se casem, pois é melhor se casar do que ficar ardendo de paixão.

[[v46-7-10]]

^<<v46-7-10,10>>^ Aos casados ordeno, não eu, mas o Senhor, que a esposa não se separe do marido.

[[v46-7-11]]

^<<v46-7-11,11>>^ Mas, se ela se separar, que permaneça sem se casar, ou então que se reconcilie com o marido; e o marido não deve deixar a esposa.

[[v46-7-12]]

^<<v46-7-12,12>>^ Mas aos outros digo eu, sim, eu, não o Senhor: Se algum irmão tem esposa descrente, e ela está disposta a ficar com ele, que ele não a deixe;

[[v46-7-13]]

^<<v46-7-13,13>>^ e se uma mulher tem marido descrente, e ele está disposto a ficar com ela, que ela não deixe o marido.

[[v46-7-14]]

^<<v46-7-14,14>>^ Pois o marido descrente está santificado em relação à esposa, e a esposa descrente está santificada em relação ao irmão; do contrário, os seus filhos seriam impuros, mas agora são santos.

[[v46-7-15]]

^<<v46-7-15,15>>^ No entanto, se o descrente decidir deixá-la,^&#42;1^ que a deixe; o irmão ou a irmã não estão sob obrigação nessas circunstâncias, mas Deus chamou vocês à paz.

[NOTE]
====
. Ou: “separar-se”.
====

[[v46-7-16]]

^<<v46-7-16,16>>^ Pois, esposa, como sabe se não salvará o seu marido? Ou, marido, como sabe se não salvará a sua esposa?

[[v46-7-17]]

^<<v46-7-17,17>>^ Contudo, que cada um ande conforme a porção que Jeová^&#42;1^ lhe deu, conforme Deus o chamou. E assim dou esta ordem em todas as congregações.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-7-18]]

^<<v46-7-18,18>>^ Alguém já era circuncidado quando foi chamado? Que não desfaça a circuncisão. Alguém era incircunciso quando foi chamado? Não seja circuncidado.

[[v46-7-19]]

^<<v46-7-19,19>>^ A circuncisão não significa nada, e a incircuncisão não significa nada; o que importa é a obediência aos mandamentos de Deus.

[[v46-7-20]]

^<<v46-7-20,20>>^ Que cada um permaneça no estado em que foi chamado.

[[v46-7-21]]

^<<v46-7-21,21>>^ Você foi chamado quando escravo? Não se preocupe com isso; mas, se puder ficar livre, aproveite a oportunidade.

[[v46-7-22]]

^<<v46-7-22,22>>^ Pois todo aquele que era escravo quando foi chamado no Senhor é agora o liberto que pertence ao Senhor; igualmente, aquele que era livre quando foi chamado é agora escravo de Cristo.

[[v46-7-23]]

^<<v46-7-23,23>>^ Vocês foram comprados por um preço; parem de se tornar escravos de homens.

[[v46-7-24]]

^<<v46-7-24,24>>^ Irmãos, que cada um permaneça diante de Deus no estado em que foi chamado.

[[v46-7-25]]

^<<v46-7-25,25>>^ Agora, no que se refere aos que são virgens,^&#42;1^ não tenho ordem da parte do Senhor, mas dou a minha opinião como alguém que é fiel pela misericórdia do Senhor.

[NOTE]
====
. Ou: “aos que nunca se casaram”.
====

[[v46-7-26]]

^<<v46-7-26,26>>^ Portanto, penso que é melhor o homem continuar como está, em vista das dificuldades atuais.

[[v46-7-27]]

^<<v46-7-27,27>>^ Você está amarrado a uma esposa? Pare de tentar ficar livre. Você não está amarrado a uma esposa? Pare de procurar uma esposa.

[[v46-7-28]]

^<<v46-7-28,28>>^ Mas, mesmo que você se case, não comete pecado. E, se uma pessoa virgem se casa, não comete pecado. No entanto, os que fizerem isso terão dificuldades na vida.^&#42;1^ Mas eu estou tentando poupá-los disso.

[NOTE]
====
. Lit.: “tribulação na carne”.
====

[[v46-7-29]]

^<<v46-7-29,29>>^ Além disso, digo o seguinte, irmãos: O tempo que resta é reduzido. De agora em diante, aqueles que têm esposa vivam como se não tivessem;

[[v46-7-30]]

^<<v46-7-30,30>>^ os que choram, como quem não chora; os que se alegram, como quem não se alegra; os que compram, como quem não possui;

[[v46-7-31]]

^<<v46-7-31,31>>^ e os que fazem uso do mundo, como quem não o usa plenamente. Porque a cena deste mundo está mudando.

[[v46-7-32]]

^<<v46-7-32,32>>^ Realmente, quero que vocês estejam livres de preocupação. O homem que não é casado se preocupa com as coisas do Senhor, em como pode agradar ao Senhor.

[[v46-7-33]]

^<<v46-7-33,33>>^ Mas o homem casado se preocupa com as coisas do mundo, em como pode agradar à esposa,

[[v46-7-34]]

^<<v46-7-34,34>>^ e está dividido. Além disso, a mulher não casada e a virgem se preocupam com as coisas do Senhor, para serem santas tanto no corpo como no espírito. No entanto, a mulher casada se preocupa com as coisas do mundo, em como pode agradar ao marido.

[[v46-7-35]]

^<<v46-7-35,35>>^ Digo isso para o seu próprio bem, não para lhes impor restrições,^&#42;1^ mas para induzi-los a fazer o que é apropriado e a servir constantemente ao Senhor, sem distração.

[NOTE]
====
. Lit.: “para lhes armar um laço”.
====

[[v46-7-36]]

^<<v46-7-36,36>>^ Mas, se alguém, por ficar sem se casar,^&#42;1^ acha que está se comportando de modo impróprio, e se ele estiver além da flor da juventude, então isto é o que deve ocorrer: que ele faça o que quer; ele não peca. Que se casem.

[NOTE]
====
. Ou: “com relação à sua virgindade”.
====

[[v46-7-37]]

^<<v46-7-37,37>>^ No entanto, se alguém estiver resolvido no coração e não sentir necessidade, mas tiver controle^&#42;1^ sobre a sua própria vontade e tiver tomado no seu próprio coração a decisão de não se casar,^&#42;2^ ele fará bem.

[NOTE]
====
. Lit.: “autoridade”.
. Ou: “de manter a sua própria virgindade”.
====

[[v46-7-38]]

^<<v46-7-38,38>>^ Assim também, aquele que se casa^&#42;1^ faz bem, mas aquele que não se casar fará melhor.

[NOTE]
====
. Ou: “que dá a sua virgindade em casamento”.
====

[[v46-7-39]]

^<<v46-7-39,39>>^ A esposa está amarrada ao marido durante todo o tempo em que ele estiver vivo. Mas, se o seu marido adormecer na morte, ela estará livre para se casar com quem quiser, somente no Senhor.

[[v46-7-40]]

^<<v46-7-40,40>>^ Na minha opinião, porém, ela será mais feliz se permanecer como está; e estou certo de que tenho também o espírito de Deus.

'''

xref:046-1-corintios/046-1-corintios-006.adoc#v46-6-0[&#60; Capítulo Anterior] | <<v46-7-0,Topo>> | xref:046-1-corintios/046-1-corintios-008.adoc#v46-8-0[Próximo Capítulo &#62;]