include::./index.adoc[]

[[v46-14-0]]
=== A Primeira aos Coríntios, 14
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-14-1]]

^<<v46-14-1,1>>^ Empenhem-se pelo amor, mas continuem se esforçando pelos^&#42;1^ dons espirituais, de preferência o de profetizar.

[NOTE]
====
. Ou: “continuem buscando zelosamente os”.
====

[[v46-14-2]]

^<<v46-14-2,2>>^ Pois quem fala em outra língua não fala a homens, mas a Deus, porque ninguém entende, embora ele fale segredos sagrados pelo espírito.

[[v46-14-3]]

^<<v46-14-3,3>>^ No entanto, quem profetiza edifica, encoraja e consola a homens com suas palavras.

[[v46-14-4]]

^<<v46-14-4,4>>^ Quem fala em outra língua edifica a si mesmo, mas quem profetiza edifica a congregação.

[[v46-14-5]]

^<<v46-14-5,5>>^ Eu gostaria que todos vocês falassem em línguas, mas prefiro que profetizem. Na verdade, quem profetiza é maior do que aquele que fala em línguas, a menos que este interprete,^&#42;1^ para que a congregação seja edificada.

[NOTE]
====
. Ou: “traduza”.
====

[[v46-14-6]]

^<<v46-14-6,6>>^ Mas, irmãos, se eu fosse agora visitá-los falando em línguas, que bem eu faria a vocês, a não ser que lhes falasse com uma revelação, com conhecimento, com uma profecia ou com um ensinamento?

[[v46-14-7]]

^<<v46-14-7,7>>^ O mesmo acontece com as coisas inanimadas que produzem som, quer seja flauta quer harpa. Se não houver distinção entre as notas, como alguém reconhecerá o que se toca na flauta ou na harpa?

[[v46-14-8]]

^<<v46-14-8,8>>^ Pois, se a trombeta não der um toque claro, quem se aprontará para a batalha?

[[v46-14-9]]

^<<v46-14-9,9>>^ Do mesmo modo, se com a língua vocês não proferirem palavras que sejam fáceis de entender, como alguém saberá o que se fala? Vocês estarão, na verdade, falando ao vento.

[[v46-14-10]]

^<<v46-14-10,10>>^ Pode ser que se falem muitos idiomas diferentes no mundo, mas nenhum deles é sem significado.

[[v46-14-11]]

^<<v46-14-11,11>>^ Pois, se eu não entender o sentido do que se fala, serei um estrangeiro para aquele que fala, e aquele que fala será um estrangeiro para mim.

[[v46-14-12]]

^<<v46-14-12,12>>^ Assim também vocês: visto que desejam tanto ter os dons do espírito, procurem ter em abundância dons que edificarão a congregação.

[[v46-14-13]]

^<<v46-14-13,13>>^ Portanto, quem fala em outra língua, ore para que a possa interpretar.^&#42;1^

[NOTE]
====
. Ou: “traduzir”.
====

[[v46-14-14]]

^<<v46-14-14,14>>^ Pois, se eu oro em outra língua, é o meu dom do espírito que ora, mas a minha mente fica improdutiva.

[[v46-14-15]]

^<<v46-14-15,15>>^ O que se deve fazer, então? Orarei com o dom do espírito, mas orarei também com a minha mente. Cantarei louvores com o dom do espírito, mas cantarei louvores também com a minha mente.

[[v46-14-16]]

^<<v46-14-16,16>>^ De outro modo, se você der louvor com um dom do espírito, como é que a pessoa comum que está no meio de vocês dirá “amém” aos seus agradecimentos, visto que não sabe o que você está dizendo?

[[v46-14-17]]

^<<v46-14-17,17>>^ É verdade que você dá graças de um modo excelente, mas o outro não está sendo edificado.

[[v46-14-18]]

^<<v46-14-18,18>>^ Agradeço a Deus por falar em mais línguas do que todos vocês.

[[v46-14-19]]

^<<v46-14-19,19>>^ Contudo, numa congregação, prefiro falar cinco palavras com a minha mente,^&#42;1^ para também instruir^&#42;2^ outros, a falar dez mil palavras em outra língua.

[NOTE]
====
. Ou: “com o meu entendimento”.
. Ou: “instruir oralmente”.
====

[[v46-14-20]]

^<<v46-14-20,20>>^ Irmãos, não se tornem crianças no seu entendimento. Sejam crianças quanto à maldade, e tornem-se adultos no seu entendimento.

[[v46-14-21]]

^<<v46-14-21,21>>^ Está escrito na Lei: “‘Pelas línguas de estrangeiros e pelos lábios de estranhos falarei a este povo, e mesmo assim se recusarão a me ouvir’, diz Jeová.”^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v46-14-22]]

^<<v46-14-22,22>>^ Portanto, as línguas não servem de sinal para os crentes, mas para os descrentes, ao passo que a profecia não é para os descrentes, mas para os crentes.

[[v46-14-23]]

^<<v46-14-23,23>>^ Assim, se a congregação inteira se reunir e todos falarem em línguas, e entrarem pessoas comuns ou descrentes, não dirão que vocês estão loucos?

[[v46-14-24]]

^<<v46-14-24,24>>^ Mas, se todos vocês estiverem profetizando, e entrar um descrente ou uma pessoa comum, ele será repreendido e examinado cuidadosamente por todos.

[[v46-14-25]]

^<<v46-14-25,25>>^ Os segredos do seu coração serão então revelados, de modo que ele se prostrará com o rosto por terra e adorará a Deus, declarando: “Deus está realmente entre vocês.”

[[v46-14-26]]

^<<v46-14-26,26>>^ O que deve ser feito então, irmãos? Quando vocês se reúnem, um tem salmo, outro tem ensinamento, outro tem revelação, outro fala em outra língua, e outro tem interpretação. Que todas as coisas ocorram para a edificação.

[[v46-14-27]]

^<<v46-14-27,27>>^ E, se alguém falar em outra língua, que isso seja limitado a dois ou no máximo três, um de cada vez, e alguém deve interpretar.^&#42;1^

[NOTE]
====
. Ou: “traduzir”.
====

[[v46-14-28]]

^<<v46-14-28,28>>^ Mas, se não houver intérprete,^&#42;1^ ele deve ficar calado na congregação e falar consigo mesmo e com Deus.

[NOTE]
====
. Ou: “tradutor”.
====

[[v46-14-29]]

^<<v46-14-29,29>>^ Que dois ou três profetas falem, e os outros discirnam o significado.

[[v46-14-30]]

^<<v46-14-30,30>>^ Mas, se outro recebe uma revelação enquanto está sentado ali, que aquele que estava falando se cale.

[[v46-14-31]]

^<<v46-14-31,31>>^ Pois todos vocês podem profetizar, um de cada vez, para que todos aprendam e sejam encorajados.

[[v46-14-32]]

^<<v46-14-32,32>>^ E o dom espiritual dos profetas deve ser controlado pelos profetas.

[[v46-14-33]]

^<<v46-14-33,33>>^ Pois Deus não é Deus de desordem, mas de paz.
Como em todas as congregações dos santos,

[[v46-14-34]]

^<<v46-14-34,34>>^ que as mulheres fiquem caladas nas congregações, pois não lhes é permitido falar. Em vez disso, que estejam em sujeição, como também diz a Lei.

[[v46-14-35]]

^<<v46-14-35,35>>^ Se elas quiserem aprender algo, perguntem ao marido, em casa, pois é vergonhoso para uma mulher falar na congregação.

[[v46-14-36]]

^<<v46-14-36,36>>^ Foi de vocês que a palavra de Deus se originou? Será que vocês foram os únicos que ela alcançou?

[[v46-14-37]]

^<<v46-14-37,37>>^ Se alguém acha que é profeta ou que tem um dom do espírito, ele deve reconhecer que as coisas que estou escrevendo a vocês são o mandamento do Senhor.

[[v46-14-38]]

^<<v46-14-38,38>>^ Mas, se alguém desconsiderar isso, ele será desconsiderado.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “se alguém ignora isso, continuará na ignorância”.
====

[[v46-14-39]]

^<<v46-14-39,39>>^ Portanto, meus irmãos, continuem se esforçando pelo profetizar; contudo, não proíbam o falar em línguas.

[[v46-14-40]]

^<<v46-14-40,40>>^ Mas que todas as coisas ocorram com decência e ordem.

'''

xref:046-1-corintios/046-1-corintios-013.adoc#v46-13-0[&#60; Capítulo Anterior] | <<v46-14-0,Topo>> | xref:046-1-corintios/046-1-corintios-015.adoc#v46-15-0[Próximo Capítulo &#62;]