include::./index.adoc[]

[[v46-4-0]]
=== A Primeira aos Coríntios, 4
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-4-1]]

^<<v46-4-1,1>>^ Os homens devem nos considerar como assistentes do^&#42;1^ Cristo e administradores dos segredos sagrados de Deus.

[NOTE]
====
. Ou: “subordinados ao”.
====

[[v46-4-2]]

^<<v46-4-2,2>>^ Ora, o que se espera dos administradores é que se mostrem fiéis.

[[v46-4-3]]

^<<v46-4-3,3>>^ Para mim, pouco importa ser examinado por vocês ou por um tribunal humano. Na verdade, nem eu examino a mim mesmo.

[[v46-4-4]]

^<<v46-4-4,4>>^ Pois não estou ciente de nada contra mim mesmo. Mas isso não prova que eu seja justo; quem me examina é Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v46-4-5]]

^<<v46-4-5,5>>^ Portanto, não julguem nada antes do tempo devido, até que venha o Senhor. Ele trará da escuridão para a luz as coisas secretas e revelará as intenções dos corações, e então cada um receberá o seu louvor da parte de Deus.

[[v46-4-6]]

^<<v46-4-6,6>>^ Irmãos, eu apliquei^&#42;1^ essas coisas a mim mesmo e a Apolo para o bem de vocês, a fim de que, por meio do nosso exemplo, aprendam a regra: “Não vão além das coisas que estão escritas”, a fim de que não fiquem cheios de orgulho, tomando o partido de um contra o outro.

[NOTE]
====
. Ou: “transferi”.
====

[[v46-4-7]]

^<<v46-4-7,7>>^ Pois quem torna você diferente dos outros? Realmente, o que você tem que não tenha recebido? Se você, de fato, recebeu tudo que tem, por que se gaba como se não o tivesse recebido?

[[v46-4-8]]

^<<v46-4-8,8>>^ Vocês já estão satisfeitos? Já estão ricos? Já começaram a reinar sem nós? Eu realmente queria que vocês já tivessem começado a reinar, para que nós também reinássemos com vocês.

[[v46-4-9]]

^<<v46-4-9,9>>^ Pois me parece que Deus pôs a nós, os apóstolos, em exibição por último, como homens condenados à morte, porque nos tornamos um espetáculo^&#42;1^ para o mundo, para anjos e para homens.

[NOTE]
====
. Lit.: “um teatro”.
====

[[v46-4-10]]

^<<v46-4-10,10>>^ Nós somos tolos por causa de Cristo, mas vocês são prudentes em união com Cristo; nós somos fracos, mas vocês são fortes; vocês são honrados, mas nós somos desonrados.

[[v46-4-11]]

^<<v46-4-11,11>>^ Até agora, passamos fome e sede, não temos roupa suficiente,^&#42;1^ somos espancados,^&#42;2^ estamos desabrigados

[NOTE]
====
. Lit.: “e sede, e estando nus”.
. Ou: “maltratados”.
====

[[v46-4-12]]

^<<v46-4-12,12>>^ e trabalhamos arduamente com as nossas próprias mãos. Quando insultados, abençoamos; quando perseguidos, suportamos com paciência;

[[v46-4-13]]

^<<v46-4-13,13>>^ quando caluniados, respondemos com brandura;^&#42;1^ nós nos tornamos como o lixo^&#42;2^ do mundo, a escória de todas as coisas, até agora.

[NOTE]
====
. Lit.: “suplicamos”.
. Ou: “refugo”.
====

[[v46-4-14]]

^<<v46-4-14,14>>^ Estou escrevendo essas coisas, não para envergonhá-los, mas para instruí-los como meus filhos amados.

[[v46-4-15]]

^<<v46-4-15,15>>^ Pois, embora vocês tenham 10.000 tutores^&#42;1^ em Cristo, certamente não têm muitos pais; porque fui eu que me tornei seu pai em Cristo Jesus por meio das boas novas.

[NOTE]
====
. Ou: “guardiões”.
====

[[v46-4-16]]

^<<v46-4-16,16>>^ Assim, eu os exorto: tornem-se meus imitadores.

[[v46-4-17]]

^<<v46-4-17,17>>^ É por isso que lhes envio Timóteo, porque ele é meu filho amado e fiel no Senhor. Ele lembrará vocês do meu modo de fazer as coisas^&#42;1^ em união com Cristo Jesus, assim como estou ensinando em toda a parte, em todas as congregações.

[NOTE]
====
. Lit.: “dos meus caminhos”.
====

[[v46-4-18]]

^<<v46-4-18,18>>^ Alguns estão cheios de orgulho, como se eu não fosse visitar vocês.

[[v46-4-19]]

^<<v46-4-19,19>>^ Mas vou visitá-los em breve, se Jeová^&#42;1^ quiser, e tomarei conhecimento não das palavras desses orgulhosos, mas do poder deles.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-4-20]]

^<<v46-4-20,20>>^ Pois o Reino de Deus não é questão de palavras, mas de poder.

[[v46-4-21]]

^<<v46-4-21,21>>^ O que vocês preferem? Que eu os visite com uma vara, ou com amor e brandura de espírito?

'''

xref:046-1-corintios/046-1-corintios-003.adoc#v46-3-0[&#60; Capítulo Anterior] | <<v46-4-0,Topo>> | xref:046-1-corintios/046-1-corintios-005.adoc#v46-5-0[Próximo Capítulo &#62;]