include::./index.adoc[]

[[v46-10-0]]
=== A Primeira aos Coríntios, 10
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v46-10-1]]

^<<v46-10-1,1>>^ Irmãos, quero que vocês saibam que os nossos antepassados estiveram todos debaixo da nuvem e todos passaram pelo mar,

[[v46-10-2]]

^<<v46-10-2,2>>^ todos foram batizados em Moisés, por meio da nuvem e do mar,

[[v46-10-3]]

^<<v46-10-3,3>>^ todos comeram o mesmo alimento espiritual

[[v46-10-4]]

^<<v46-10-4,4>>^ e todos beberam a mesma bebida espiritual. Pois bebiam da rocha espiritual que os seguia, e essa rocha representava^&#42;1^ o Cristo.

[NOTE]
====
. Ou: “era”.
====

[[v46-10-5]]

^<<v46-10-5,5>>^ Contudo, Deus não se agradou da maioria deles, pois foram mortos no deserto.^&#42;1^

[NOTE]
====
. Veja o Glossário.
====

[[v46-10-6]]

^<<v46-10-6,6>>^ Essas coisas se tornaram exemplos para nós, para que não desejemos coisas prejudiciais, como eles desejaram.

[[v46-10-7]]

^<<v46-10-7,7>>^ Não se tornem idólatras, como alguns deles se tornaram; assim como está escrito: “O povo se sentou para comer e beber. Então se levantaram para se divertir.”

[[v46-10-8]]

^<<v46-10-8,8>>^ E não cometamos imoralidade sexual,^&#42;1^ como alguns deles cometeram imoralidade sexual, só para caírem, 23.000 deles num só dia.

[NOTE]
====
. Veja o Glossário.
====

[[v46-10-9]]

^<<v46-10-9,9>>^ Nem ponhamos Jeová^&#42;1^ à prova, como alguns deles o puseram à prova, só para serem mortos pelas serpentes.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-10-10]]

^<<v46-10-10,10>>^ E não sejam queixosos, como alguns deles se queixaram, só para serem mortos pelo destruidor.

[[v46-10-11]]

^<<v46-10-11,11>>^ Essas coisas lhes aconteceram como exemplos e foram escritas como aviso para nós, para quem já chegou o fim dos sistemas de coisas.

[[v46-10-12]]

^<<v46-10-12,12>>^ Portanto, quem pensa estar de pé, tome cuidado para não cair.

[[v46-10-13]]

^<<v46-10-13,13>>^ Não sobreveio a vocês nenhuma tentação a não ser as que são comuns aos homens. Mas Deus é fiel, e ele não deixará que vocês sejam tentados além do que podem suportar; mas, quando vier a tentação, ele também providenciará a saída, para que a possam suportar.

[[v46-10-14]]

^<<v46-10-14,14>>^ Portanto, meus amados, fujam da idolatria.

[[v46-10-15]]

^<<v46-10-15,15>>^ Falo como a homens de discernimento; julguem vocês mesmos o que eu digo.

[[v46-10-16]]

^<<v46-10-16,16>>^ Será que o cálice de bênção que abençoamos não é uma participação no sangue do Cristo? O pão que partimos não é uma participação no corpo do Cristo?

[[v46-10-17]]

^<<v46-10-17,17>>^ Visto que há um só pão, nós, embora muitos, somos um só corpo, pois todos participamos daquele único pão.

[[v46-10-18]]

^<<v46-10-18,18>>^ Olhem para o Israel natural:^&#42;1^ Não são participantes com o altar os que comem dos sacrifícios?

[NOTE]
====
. Lit.: “Israel segundo a carne”.
====

[[v46-10-19]]

^<<v46-10-19,19>>^ O que então estou querendo dizer? Que aquilo que se sacrifica a um ídolo é alguma coisa, ou que o ídolo é alguma coisa?

[[v46-10-20]]

^<<v46-10-20,20>>^ Não; mas digo que o que as nações sacrificam, elas sacrificam a demônios, e não a Deus. E eu não quero que vocês se tornem participantes de nada com os demônios.

[[v46-10-21]]

^<<v46-10-21,21>>^ Vocês não podem beber o cálice de Jeová^&#42;1^ e o cálice de demônios; não podem participar da “mesa de Jeová”^&#42;2^ e da mesa de demônios.

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v46-10-22]]

^<<v46-10-22,22>>^ Ou ‘estamos provocando Jeová^&#42;1^ ao ciúme’? Será que somos mais fortes do que ele?

[NOTE]
====
. Veja Ap. A5.
====

[[v46-10-23]]

^<<v46-10-23,23>>^ Tudo é permitido,^&#42;1^ mas nem tudo é vantajoso. Tudo é permitido, mas nem tudo edifica.

[NOTE]
====
. Ou: “lícito”.
====

[[v46-10-24]]

^<<v46-10-24,24>>^ Que cada um persista em buscar não a sua própria vantagem, mas a da outra pessoa.

[[v46-10-25]]

^<<v46-10-25,25>>^ Comam de tudo o que se vende no açougue, sem fazer perguntas por causa da sua consciência,

[[v46-10-26]]

^<<v46-10-26,26>>^ pois “a Jeová^&#42;1^ pertence a terra e tudo o que nela há”.

[NOTE]
====
. Veja Ap. A5.
====

[[v46-10-27]]

^<<v46-10-27,27>>^ Se algum descrente os convidar para uma refeição, e vocês quiserem ir, comam de tudo o que se puser diante de vocês, sem fazer perguntas por causa da sua consciência.

[[v46-10-28]]

^<<v46-10-28,28>>^ Mas, se alguém lhes disser: “Isso é algo oferecido em sacrifício”, não comam, por causa daquele que lhes disse isso e por causa da consciência.

[[v46-10-29]]

^<<v46-10-29,29>>^ Não me refiro à sua própria consciência, mas à da outra pessoa. Pois, por que a minha liberdade deveria ser julgada pela consciência de outro?

[[v46-10-30]]

^<<v46-10-30,30>>^ Se eu dou graças quando participo de uma refeição, por que serei criticado por causa daquilo pelo qual dou graças?

[[v46-10-31]]

^<<v46-10-31,31>>^ Portanto, quer vocês comam, quer bebam, quer façam qualquer outra coisa, façam todas as coisas para a glória de Deus.

[[v46-10-32]]

^<<v46-10-32,32>>^ Não se tornem motivo de tropeço para judeus, nem para gregos, nem para a congregação de Deus,

[[v46-10-33]]

^<<v46-10-33,33>>^ assim como eu estou tentando agradar a todos em todas as coisas, não buscando a minha própria vantagem, mas a do maior número de pessoas, para que sejam salvas.

'''

xref:046-1-corintios/046-1-corintios-009.adoc#v46-9-0[&#60; Capítulo Anterior] | <<v46-10-0,Topo>> | xref:046-1-corintios/046-1-corintios-011.adoc#v46-11-0[Próximo Capítulo &#62;]