include::./index.adoc[]

[[v45-16-0]]
=== Aos Romanos, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-16-1]]

^<<v45-16-1,1>>^ Apresento-lhes^&#42;1^ a nossa irmã Febe, que é ministra da congregação em Cencreia,

[NOTE]
====
. Ou: “Recomendo-lhes”.
====

[[v45-16-2]]

^<<v45-16-2,2>>^ para que vocês a acolham no Senhor de um modo digno dos santos e lhe deem toda a ajuda necessária, pois ela mesma também se mostrou defensora de muitos, de mim inclusive.

[[v45-16-3]]

^<<v45-16-3,3>>^ Transmitam minhas saudações a Prisca e Áquila, meus colaboradores em Cristo Jesus,

[[v45-16-4]]

^<<v45-16-4,4>>^ que arriscaram o próprio pescoço por mim^&#42;1^ e a quem não somente eu, mas também todas as congregações das nações, somos gratos.

[NOTE]
====
. Ou: “minha alma”.
====

[[v45-16-5]]

^<<v45-16-5,5>>^ Saudações também à congregação que se reúne na casa deles. Saudações ao meu amado Epêneto, que é um dos primeiros frutos da Ásia para Cristo.

[[v45-16-6]]

^<<v45-16-6,6>>^ Saudações a Maria, que trabalhou arduamente a favor de vocês.

[[v45-16-7]]

^<<v45-16-7,7>>^ Saudações a Andrônico e a Júnias, meus parentes e companheiros de prisão, que são homens bem conhecidos pelos apóstolos e estão em união com Cristo há mais tempo do que eu.

[[v45-16-8]]

^<<v45-16-8,8>>^ Transmitam minhas saudações a Amplíato, meu amado no Senhor.

[[v45-16-9]]

^<<v45-16-9,9>>^ Saudações a Urbano, nosso colaborador em Cristo, e também ao meu amado Estáquis.

[[v45-16-10]]

^<<v45-16-10,10>>^ Saudações a Apeles, o aprovado em Cristo. Saudações aos da casa de Aristóbulo.

[[v45-16-11]]

^<<v45-16-11,11>>^ Saudações a Herodião, meu parente. Saudações aos da casa de Narciso que estão no Senhor.

[[v45-16-12]]

^<<v45-16-12,12>>^ Saudações a Trifena e Trifosa, mulheres que trabalham arduamente no Senhor. Saudações à nossa amada Pérside, pois ela tem trabalhado arduamente no Senhor.

[[v45-16-13]]

^<<v45-16-13,13>>^ Saudações a Rufo, o escolhido no Senhor, e à mãe dele, que é também minha.

[[v45-16-14]]

^<<v45-16-14,14>>^ Saudações a Asíncrito, Flegonte, Hermes, Pátrobas, Hermas e aos irmãos que estão com eles.

[[v45-16-15]]

^<<v45-16-15,15>>^ Saudações a Filólogo e Júlia, Nereu e sua irmã, e Olimpas, e a todos os santos que estão com eles.

[[v45-16-16]]

^<<v45-16-16,16>>^ Cumprimentem uns aos outros com beijo santo. Todas as congregações do Cristo mandam saudações a vocês.

[[v45-16-17]]

^<<v45-16-17,17>>^ Eu os exorto agora, irmãos, a ficar atentos àqueles que causam divisões e dão motivos para tropeço contrariando os ensinamentos que vocês aprenderam; afastem-se deles.

[[v45-16-18]]

^<<v45-16-18,18>>^ Porque homens como esses não são escravos de Cristo, nosso Senhor, mas dos seus próprios desejos,^&#42;1^ e, com conversa suave e bajulação, seduzem o coração dos ingênuos.

[NOTE]
====
. Ou: “do seu próprio ventre”.
====

[[v45-16-19]]

^<<v45-16-19,19>>^ A obediência de vocês se tornou conhecida por todos, e eu me alegro por sua causa. Mas quero que vocês sejam sábios quanto ao que é bom, porém inocentes quanto ao que é mau.

[[v45-16-20]]

^<<v45-16-20,20>>^ O Deus que dá paz esmagará em breve a Satanás debaixo dos pés de vocês. Que a bondade imerecida do nosso Senhor Jesus esteja com vocês.

[[v45-16-21]]

^<<v45-16-21,21>>^ Timóteo, meu colaborador, manda-lhes saudações, e também Lúcio, Jasão e Sosípatro, meus parentes.

[[v45-16-22]]

^<<v45-16-22,22>>^ Eu, Tércio, que escrevi esta carta, mando-lhes saudações no Senhor.

[[v45-16-23]]

^<<v45-16-23,23>>^ Gaio, que hospeda a mim e a toda a congregação, envia saudações a vocês. Erasto, o tesoureiro^&#42;1^ da cidade, envia-lhes saudações, e também Quarto, irmão dele.

[NOTE]
====
. Ou: “mordomo”.
====

[[v45-16-24]]

^<<v45-16-24,24>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v45-16-25]]

^<<v45-16-25,25>>^ Àquele que pode fazê-los firmes, de acordo com as boas novas que eu declaro e com a pregação sobre Jesus Cristo, segundo a revelação do segredo sagrado que foi mantido em silêncio por tempos de longa duração

[[v45-16-26]]

^<<v45-16-26,26>>^ — mas que agora foi revelado^&#42;1^ e dado a conhecer entre todas as nações por meio das Escrituras proféticas, de acordo com a ordem do Deus eterno, para promover a obediência pela fé —,

[NOTE]
====
. Ou: “manifestado”.
====

[[v45-16-27]]

^<<v45-16-27,27>>^ a Deus, que é o único sábio, seja dada a glória por meio de Jesus Cristo para sempre. Amém.

'''

xref:045-romanos/045-romanos-015.adoc#v45-15-0[&#60; Capítulo Anterior] | <<v45-16-0,Topo>> | xref:046-1-corintios/046-1-corintios-001.adoc#v46-1-0[Próximo Capítulo &#62;]