include::./index.adoc[]

[[v45-12-0]]
=== Aos Romanos, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-12-1]]

^<<v45-12-1,1>>^ Portanto, eu lhes suplico, irmãos, pelas compaixões de Deus, que apresentem o seu corpo como sacrifício vivo, santo e aceitável a Deus, prestando assim um serviço sagrado com a sua faculdade de raciocínio.

[[v45-12-2]]

^<<v45-12-2,2>>^ E parem de se amoldar a este mundo,^&#42;1^ mas sejam transformados, renovando a sua mente, a fim de comprovar por si mesmos a boa, aceitável e perfeita vontade de Deus.

[NOTE]
====
. Ou: “este sistema de coisas; esta época”. Veja o Glossário.
====

[[v45-12-3]]

^<<v45-12-3,3>>^ Pois, por meio da bondade imerecida que me foi concedida, digo a cada um de vocês que não pense de si mesmo mais do que é necessário pensar, mas que cada um pense de um modo que revele bom senso, conforme a medida de fé que Deus lhe deu.^&#42;1^

[NOTE]
====
. Ou: “repartiu; distribuiu”.
====

[[v45-12-4]]

^<<v45-12-4,4>>^ Pois, assim como temos muitos membros em um só corpo, mas os membros não têm todos a mesma função,

[[v45-12-5]]

^<<v45-12-5,5>>^ assim também nós, embora muitos, somos um só corpo em união com Cristo, mas, individualmente, somos membros que pertencem uns aos outros.

[[v45-12-6]]

^<<v45-12-6,6>>^ Temos dons que diferem segundo a bondade imerecida que nos foi concedida; sendo assim, se o dom é o de profecia, profetizemos conforme a nossa fé;

[[v45-12-7]]

^<<v45-12-7,7>>^ se é o de servir, sirvamos;^&#42;1^ aquele que tem o dom do ensino, que ensine;

[NOTE]
====
. Ou: “se é um ministério, ministremos”.
====

[[v45-12-8]]

^<<v45-12-8,8>>^ aquele que tem o dom de encorajar,^&#42;1^ que encoraje;^&#42;2^ aquele que distribui,^&#42;3^ faça-o generosamente; aquele que preside,^&#42;4^ faça-o com diligência;^&#42;5^ aquele que mostra misericórdia, faça-o com alegria.

[NOTE]
====
. Ou: “exortar”.
. Ou: “exorte”.
. Ou: “contribui”.
. Ou: “toma a liderança”.
. Ou: “seriedade”.
====

[[v45-12-9]]

^<<v45-12-9,9>>^ Que o amor de vocês seja sem hipocrisia. Abominem o que é mau; agarrem-se ao que é bom.

[[v45-12-10]]

^<<v45-12-10,10>>^ Com amor fraternal, tenham ternos sentimentos uns pelos outros. Tomem a iniciativa em honrar uns aos outros.

[[v45-12-11]]

^<<v45-12-11,11>>^ Sejam diligentes,^&#42;1^ não preguiçosos.^&#42;2^ Sejam fervorosos no espírito.^&#42;3^ Trabalhem como escravos para Jeová.^&#42;4^

[NOTE]
====
. Ou: “trabalhadores; zelosos”.
. Ou: “Não sejam preguiçosos nas suas atividades.”
. Pelo visto se refere ao espírito de Deus.
. Veja Ap. A5.
====

[[v45-12-12]]

^<<v45-12-12,12>>^ Alegrem-se na esperança. Perseverem sob tribulação. Perseverem em oração.

[[v45-12-13]]

^<<v45-12-13,13>>^ Partilhem com os santos o que vocês têm, segundo as necessidades deles. Sempre mostrem hospitalidade.

[[v45-12-14]]

^<<v45-12-14,14>>^ Abençoem os que perseguem vocês; abençoem, e não amaldiçoem.

[[v45-12-15]]

^<<v45-12-15,15>>^ Alegrem-se com os que se alegram; chorem com os que choram.

[[v45-12-16]]

^<<v45-12-16,16>>^ Tenham para com os outros a mesma atitude que vocês têm para consigo mesmos; não fixem a mente em coisas grandiosas,^&#42;1^ mas deixem-se guiar pelas coisas humildes. Não sejam sábios aos seus próprios olhos.

[NOTE]
====
. Ou: “não cultivem ideias grandiosas”.
====

[[v45-12-17]]

^<<v45-12-17,17>>^ Não retribuam a ninguém mal com mal. Preocupem-se com o que é bom aos olhos^&#42;1^ de todas as pessoas.

[NOTE]
====
. Ou: “diante”.
====

[[v45-12-18]]

^<<v45-12-18,18>>^ Se possível, no que depender de vocês, sejam pacíficos com todos.

[[v45-12-19]]

^<<v45-12-19,19>>^ Não se vinguem, amados, mas deem lugar à ira;^&#42;1^ pois está escrito: “‘A vingança é minha; eu retribuirei’, diz Jeová.”^&#42;2^

[NOTE]
====
. Isto é, à ira de Deus.
. Veja Ap. A5.
====

[[v45-12-20]]

^<<v45-12-20,20>>^ Mas, “se o seu inimigo estiver com fome, dê-lhe algo para comer; se ele estiver com sede, dê-lhe algo para beber; pois, fazendo isso, você amontoará brasas vivas sobre a cabeça dele”.^&#42;1^

[NOTE]
====
. Isto é, abrandará a pessoa e dissolverá a sua dureza.
====

[[v45-12-21]]

^<<v45-12-21,21>>^ Não se deixe vencer pelo mal, mas continue vencendo o mal com o bem.

'''

xref:045-romanos/045-romanos-011.adoc#v45-11-0[&#60; Capítulo Anterior] | <<v45-12-0,Topo>> | xref:045-romanos/045-romanos-013.adoc#v45-13-0[Próximo Capítulo &#62;]