include::./index.adoc[]

[[v45-11-0]]
=== Aos Romanos, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-11-1]]

^<<v45-11-1,1>>^ Pergunto, então: Será que Deus rejeitou o seu povo? De modo algum! Pois eu também sou israelita, da descendência^&#42;1^ de Abraão, da tribo de Benjamim.

[NOTE]
====
. Lit.: “semente”.
====

[[v45-11-2]]

^<<v45-11-2,2>>^ Deus não rejeitou o seu povo, a quem primeiro deu consideração.^&#42;1^ Vocês não sabem o que certa passagem das Escrituras diz sobre Elias, quando ele clamou perante Deus contra Israel?

[NOTE]
====
. Ou: “primeiro reconheceu”.
====

[[v45-11-3]]

^<<v45-11-3,3>>^ “Jeová,^&#42;1^ mataram os teus profetas, derrubaram os teus altares, e só eu sobrei, e agora estão tentando tirar a minha vida.”^&#42;2^

[NOTE]
====
. Veja Ap. A5.
. Ou: “alma”.
====

[[v45-11-4]]

^<<v45-11-4,4>>^ No entanto, o que a proclamação divina disse a ele? “Ainda tenho 7.000 homens que não se ajoelharam diante de Baal.”

[[v45-11-5]]

^<<v45-11-5,5>>^ Do mesmo modo, também na época atual há um restante, segundo uma escolha por meio da bondade imerecida.

[[v45-11-6]]

^<<v45-11-6,6>>^ Ora, se é por bondade imerecida, não é mais por meio de obras; senão, a bondade imerecida não seria mais bondade imerecida.

[[v45-11-7]]

^<<v45-11-7,7>>^ O que diremos então? Aquilo que Israel tanto busca, não obteve, mas os escolhidos obtiveram. Os outros ficaram insensíveis,

[[v45-11-8]]

^<<v45-11-8,8>>^ assim como está escrito: “Deus lhes deu um espírito de profundo sono, olhos que não veem e ouvidos que não ouvem, até o dia de hoje.”

[[v45-11-9]]

^<<v45-11-9,9>>^ Também, Davi diz: “Que a mesa deles se torne laço, armadilha, pedra de tropeço e retribuição para eles.

[[v45-11-10]]

^<<v45-11-10,10>>^ Que os olhos deles se escureçam para que não consigam ver, e que tu lhes encurves as costas continuamente.”

[[v45-11-11]]

^<<v45-11-11,11>>^ Então, pergunto: Será que eles tropeçaram e caíram definitivamente? Certamente que não! Mas por causa do passo em falso deles há salvação para pessoas das nações, para provocá-los ao ciúme.

[[v45-11-12]]

^<<v45-11-12,12>>^ Ora, se o passo em falso deles significa riquezas para o mundo, e a sua diminuição significa riquezas para pessoas das nações, quanto mais riquezas o pleno número deles significará!

[[v45-11-13]]

^<<v45-11-13,13>>^ Agora falo a vocês que são pessoas das nações. Visto que sou apóstolo para as nações, glorifico^&#42;1^ o meu ministério

[NOTE]
====
. Ou: “exalto”.
====

[[v45-11-14]]

^<<v45-11-14,14>>^ para ver se de algum modo posso provocar meu próprio povo^&#42;1^ ao ciúme e salvar alguns deles.

[NOTE]
====
. Lit.: “minha carne”.
====

[[v45-11-15]]

^<<v45-11-15,15>>^ Pois, se o fato de eles terem sido rejeitados significa reconciliação para o mundo, o que significará o fato de serem aceitos, senão vida para os que estavam mortos?

[[v45-11-16]]

^<<v45-11-16,16>>^ Além disso, se a parte da massa considerada como primícias é santa, a massa inteira também é santa; e, se a raiz é santa, os ramos também são.

[[v45-11-17]]

^<<v45-11-17,17>>^ No entanto, se alguns dos ramos foram arrancados, e você, apesar de ser oliveira silvestre, foi enxertado entre eles e se tornou participante da riqueza da raiz da oliveira,

[[v45-11-18]]

^<<v45-11-18,18>>^ não trate os ramos com arrogância.^&#42;1^ Se, porém, você os tratar com arrogância,^&#42;2^ lembre-se de que você não sustenta a raiz, mas a raiz o sustenta.

[NOTE]
====
. Ou: “não se gabe à custa dos ramos”.
. Ou: “você se gabar à custa deles”.
====

[[v45-11-19]]

^<<v45-11-19,19>>^ Você dirá, então: “Alguns ramos foram arrancados para que eu fosse enxertado.”

[[v45-11-20]]

^<<v45-11-20,20>>^ Muito bem! Foram arrancados porque não tiveram fé, mas você está de pé pela fé. Não seja arrogante, mas tenha temor.

[[v45-11-21]]

^<<v45-11-21,21>>^ Pois, se Deus não poupou os ramos naturais, também não poupará você.

[[v45-11-22]]

^<<v45-11-22,22>>^ Considere, portanto, a bondade e a severidade de Deus. Há severidade para com aqueles que caíram, mas para com você há a bondade de Deus, desde que permaneça na Sua bondade; senão, você também será cortado fora.

[[v45-11-23]]

^<<v45-11-23,23>>^ E eles também, se deixarem de ser pessoas sem fé, serão enxertados, pois Deus é capaz de enxertá-los novamente.

[[v45-11-24]]

^<<v45-11-24,24>>^ Pois, se você foi cortado da oliveira que é silvestre por natureza e foi enxertado numa oliveira cultivada, o que é contrário à natureza, quanto mais serão os ramos naturais enxertados de volta na sua própria oliveira!

[[v45-11-25]]

^<<v45-11-25,25>>^ Pois não quero, irmãos, que vocês desconheçam este segredo sagrado, a fim de que não se tornem sábios aos seus próprios olhos: parte de Israel ficou insensível até que entrasse o pleno número de pessoas das nações,

[[v45-11-26]]

^<<v45-11-26,26>>^ e dessa maneira todo o Israel será salvo. Assim como está escrito: “O libertador^&#42;1^ sairá de Sião e afastará de Jacó as práticas ímpias.

[NOTE]
====
. Ou: “salvador”.
====

[[v45-11-27]]

^<<v45-11-27,27>>^ E este é o pacto que farei com eles quando eu tirar os seus pecados.”

[[v45-11-28]]

^<<v45-11-28,28>>^ É verdade que, com respeito às boas novas, eles são inimigos para o benefício de vocês; mas, com respeito à escolha de Deus, são amados por causa dos antepassados deles.

[[v45-11-29]]

^<<v45-11-29,29>>^ Pois as dádivas e a chamada de Deus são coisas nas quais ele não voltará atrás.

[[v45-11-30]]

^<<v45-11-30,30>>^ Pois, assim como antes vocês eram desobedientes a Deus, mas agora foram tratados com misericórdia por causa da desobediência deles,

[[v45-11-31]]

^<<v45-11-31,31>>^ assim também eles agora têm sido desobedientes resultando em misericórdia para vocês, para que eles também sejam agora tratados com misericórdia.

[[v45-11-32]]

^<<v45-11-32,32>>^ Pois Deus fez de todos eles prisioneiros da desobediência, a fim de tratar a todos eles com misericórdia.

[[v45-11-33]]

^<<v45-11-33,33>>^ Como são profundas as riquezas, a sabedoria e o conhecimento de Deus! Como são insondáveis os seus julgamentos, e impenetráveis os seus caminhos!

[[v45-11-34]]

^<<v45-11-34,34>>^ Pois “quem chegou a conhecer a mente de Jeová,^&#42;1^ ou quem se tornou seu conselheiro”?

[NOTE]
====
. Veja Ap. A5.
====

[[v45-11-35]]

^<<v45-11-35,35>>^ Ou “quem primeiro deu algo a ele, de modo que ele lhe deva retribuir”?

[[v45-11-36]]

^<<v45-11-36,36>>^ Porque todas as coisas são dele, e por ele, e para ele. Glória a ele para sempre. Amém.

'''

xref:045-romanos/045-romanos-010.adoc#v45-10-0[&#60; Capítulo Anterior] | <<v45-11-0,Topo>> | xref:045-romanos/045-romanos-012.adoc#v45-12-0[Próximo Capítulo &#62;]