include::./index.adoc[]

[[v45-7-0]]
=== Aos Romanos, 7
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-7-1]]

^<<v45-7-1,1>>^ Será que vocês não sabem, irmãos (pois estou falando aos que têm conhecimento de leis), que a Lei domina sobre o homem enquanto ele vive?

[[v45-7-2]]

^<<v45-7-2,2>>^ Por exemplo, a mulher casada está amarrada por lei ao seu marido enquanto ele viver; mas, se o marido morrer, ela ficará livre da lei do seu marido.

[[v45-7-3]]

^<<v45-7-3,3>>^ Por isso, enquanto o seu marido viver, ela será chamada de adúltera caso se torne de outro homem. Mas, se o marido morrer, ela ficará livre da lei dele, de modo que não será adúltera caso se torne de outro homem.

[[v45-7-4]]

^<<v45-7-4,4>>^ Assim, meus irmãos, vocês também morreram para a Lei, por meio do corpo do Cristo, para pertencerem a outro, àquele que foi levantado dentre os mortos, a fim de produzirmos fruto para Deus.

[[v45-7-5]]

^<<v45-7-5,5>>^ Pois, quando vivíamos de acordo com a carne, os desejos pecaminosos despertados pela Lei agiam em nosso corpo^&#42;1^ para produzir frutos que levam à morte.

[NOTE]
====
. Lit.: “nossos membros”.
====

[[v45-7-6]]

^<<v45-7-6,6>>^ Mas agora fomos libertados da Lei, porque morremos para aquilo que nos restringia, a fim de sermos escravos num novo sentido, por meio do espírito, e não no velho sentido, por meio do código escrito.

[[v45-7-7]]

^<<v45-7-7,7>>^ O que diremos então? Será que a Lei é pecado? Certamente que não! Na verdade, eu não teria conhecido o pecado se não fosse a Lei. Por exemplo, eu não teria conhecido a cobiça se a Lei não dissesse: “Não cobice.”

[[v45-7-8]]

^<<v45-7-8,8>>^ Mas o pecado, aproveitando-se da oportunidade dada pelo mandamento, produziu em mim todo tipo de cobiça, pois sem lei o pecado estava morto.

[[v45-7-9]]

^<<v45-7-9,9>>^ De fato, antes, sem lei, eu estava vivo. No entanto, ao chegar o mandamento, o pecado voltou a viver, mas eu morri.

[[v45-7-10]]

^<<v45-7-10,10>>^ E o mandamento que era para levar à vida, descobri que levava à morte.

[[v45-7-11]]

^<<v45-7-11,11>>^ Pois o pecado, aproveitando-se da oportunidade dada pelo mandamento, me seduziu e, por meio deste, me matou.

[[v45-7-12]]

^<<v45-7-12,12>>^ Assim, a Lei em si mesma é santa, e o mandamento é santo, justo e bom.

[[v45-7-13]]

^<<v45-7-13,13>>^ Portanto, será que o que é bom causou a minha morte? Certamente que não! Mas o pecado fez isso, para que fosse exposto como pecado, produzindo em mim a morte por meio do que é bom, de modo que, por meio do mandamento, o pecado se tornasse muito mais pecaminoso.

[[v45-7-14]]

^<<v45-7-14,14>>^ Pois sabemos que a Lei é espiritual, mas eu sou carnal, vendido como escravo ao pecado.

[[v45-7-15]]

^<<v45-7-15,15>>^ Pois não entendo por que ajo assim. Pois não pratico o que quero, mas faço aquilo que odeio.

[[v45-7-16]]

^<<v45-7-16,16>>^ No entanto, se faço aquilo que não quero, concordo que a Lei é boa.

[[v45-7-17]]

^<<v45-7-17,17>>^ Mas então não sou mais eu quem está agindo; é o pecado que mora em mim.

[[v45-7-18]]

^<<v45-7-18,18>>^ Porque eu sei que em mim, isto é, na minha carne, não mora nada de bom; pois tenho o desejo de fazer o que é bom, mas não tenho a capacidade de realizá-lo.

[[v45-7-19]]

^<<v45-7-19,19>>^ Pois não faço o bem que quero, mas o mal que não quero é o que pratico.

[[v45-7-20]]

^<<v45-7-20,20>>^ Se, então, faço o que não quero, já não sou eu quem o faz; é o pecado que mora em mim.

[[v45-7-21]]

^<<v45-7-21,21>>^ Percebo assim a seguinte lei no meu caso: quando quero fazer o que é certo, está presente em mim o que é mau.

[[v45-7-22]]

^<<v45-7-22,22>>^ Eu realmente tenho prazer na lei de Deus segundo o homem que sou no íntimo,

[[v45-7-23]]

^<<v45-7-23,23>>^ mas vejo em meu corpo^&#42;1^ outra lei guerreando contra a lei da minha mente e me levando cativo à lei do pecado que está no meu corpo.^&#42;2^

[NOTE]
====
. Lit.: “meus membros”.
. Lit.: “meus membros”.
====

[[v45-7-24]]

^<<v45-7-24,24>>^ Homem miserável que eu sou! Quem me livrará do corpo que é submetido a essa morte?

[[v45-7-25]]

^<<v45-7-25,25>>^ Dou graças a Deus, por meio de Jesus Cristo, nosso Senhor! Assim, com a minha mente, eu mesmo sou escravo da lei de Deus, mas, com a minha carne, escravo da lei do pecado.

'''

xref:045-romanos/045-romanos-006.adoc#v45-6-0[&#60; Capítulo Anterior] | <<v45-7-0,Topo>> | xref:045-romanos/045-romanos-008.adoc#v45-8-0[Próximo Capítulo &#62;]