include::./index.adoc[]

[[v45-13-0]]
=== Aos Romanos, 13
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-13-1]]

^<<v45-13-1,1>>^ Todos estejam sujeitos^&#42;1^ às autoridades superiores, pois não há autoridade sem a permissão de Deus; as autoridades existentes foram colocadas por Deus em suas posições relativas.

[NOTE]
====
. Ou: “Todas as almas estejam sujeitas”.
====

[[v45-13-2]]

^<<v45-13-2,2>>^ Portanto, quem toma posição contra a autoridade toma posição contra a ordem estabelecida por Deus;^&#42;1^ os que tomam posição contra ela trarão condenação sobre si mesmos.

[NOTE]
====
. Ou: “o arranjo de Deus”.
====

[[v45-13-3]]

^<<v45-13-3,3>>^ Pois os governantes não são temidos por aqueles que praticam boas ações, mas por aqueles que praticam más ações. Você quer ficar livre do medo da autoridade? Faça sempre o bem, e receberá louvor dela;

[[v45-13-4]]

^<<v45-13-4,4>>^ pois ela é serva^&#42;1^ de Deus para você, para o seu bem. Mas, se você faz o que é mau, tenha medo, porque não é sem motivo que a autoridade traz a espada. Ela está a serviço^&#42;2^ de Deus, para executar vingança e expressar ira^&#42;3^ contra quem pratica o que é mau.

[NOTE]
====
. Ou: “é ministra”.
. Ou: “é ministra”.
. Ou: “trazer punição”.
====

[[v45-13-5]]

^<<v45-13-5,5>>^ Portanto, é necessário que vocês estejam em sujeição, não somente por causa dessa ira, mas também por causa da sua consciência.

[[v45-13-6]]

^<<v45-13-6,6>>^ É por isso também que vocês pagam impostos; porque eles estão a serviço^&#42;1^ de Deus e prestam esse serviço constantemente.

[NOTE]
====
. Ou: “são servos públicos”.
====

[[v45-13-7]]

^<<v45-13-7,7>>^ Deem a todos o que lhes é devido: a quem exigir imposto, o imposto; a quem exigir tributo, o tributo; a quem exigir temor, tal temor; a quem exigir honra, tal honra.

[[v45-13-8]]

^<<v45-13-8,8>>^ Não devam nada a ninguém, a não ser amar uns aos outros, pois quem ama o seu próximo cumpre a Lei.

[[v45-13-9]]

^<<v45-13-9,9>>^ Pois os mandamentos — “não cometa adultério, não assassine, não furte, não cobice”, e qualquer outro mandamento que exista — se resumem nestas palavras: “Ame o seu próximo como a si mesmo.”

[[v45-13-10]]

^<<v45-13-10,10>>^ O amor não faz o mal contra o próximo; portanto, o amor é o cumprimento da lei.

[[v45-13-11]]

^<<v45-13-11,11>>^ E façam isso porque vocês sabem em que época estamos, que já é hora de despertarem do sono, pois agora a nossa salvação está mais próxima do que quando nos tornamos crentes.

[[v45-13-12]]

^<<v45-13-12,12>>^ A noite está bem avançada; o dia está próximo. Portanto, rejeitemos as obras da escuridão e revistamo-nos das armas da luz.

[[v45-13-13]]

^<<v45-13-13,13>>^ Andemos decentemente, como em pleno dia, não em festas descontroladas^&#42;1^ e bebedeiras, nem em relações sexuais imorais e conduta insolente,^&#42;2^ nem em brigas e ciúmes.

[NOTE]
====
. Ou: “em farras”.
. Ou: “atos de conduta desavergonhada”. Plural da palavra grega asélgeia. Veja o Glossário.
====

[[v45-13-14]]

^<<v45-13-14,14>>^ Mas revistam-se do Senhor Jesus Cristo e não fiquem premeditando como satisfazer os desejos da carne.

'''

xref:045-romanos/045-romanos-012.adoc#v45-12-0[&#60; Capítulo Anterior] | <<v45-13-0,Topo>> | xref:045-romanos/045-romanos-014.adoc#v45-14-0[Próximo Capítulo &#62;]