include::./index.adoc[]

[[v45-3-0]]
=== Aos Romanos, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-3-1]]

^<<v45-3-1,1>>^ Qual é então a vantagem do judeu, ou qual é o valor da circuncisão?

[[v45-3-2]]

^<<v45-3-2,2>>^ Grande, em todos os sentidos. Em primeiro lugar, aos judeus foram confiadas as proclamações sagradas de Deus.

[[v45-3-3]]

^<<v45-3-3,3>>^ O que acontece então? Se alguns não tiveram fé, será que a falta de fé deles anulará a fidelidade de Deus?

[[v45-3-4]]

^<<v45-3-4,4>>^ Certamente que não! Mas seja Deus verdadeiro, mesmo que todo homem seja mentiroso, assim como está escrito: “Para que fique provado que és justo nas tuas palavras e venças quando fores julgado.”

[[v45-3-5]]

^<<v45-3-5,5>>^ No entanto, o que diremos, se a nossa injustiça ressalta a justiça de Deus? Será que Deus é injusto quando expressa a sua ira? (Estou falando em termos humanos.)

[[v45-3-6]]

^<<v45-3-6,6>>^ De modo algum! Senão, como Deus julgará o mundo?

[[v45-3-7]]

^<<v45-3-7,7>>^ Mas, se pela minha mentira a verdade de Deus tem sido ainda mais destacada para a glória dele, por que, então, eu sou condenado como pecador?

[[v45-3-8]]

^<<v45-3-8,8>>^ E por que não dizer, assim como alguns falsamente afirmam que dizemos: “Façamos coisas más, para que venham coisas boas”? A condenação desses homens está de acordo com a justiça.

[[v45-3-9]]

^<<v45-3-9,9>>^ Então, o que concluímos? Estamos em melhor situação? De jeito nenhum! Pois já provamos que tanto os judeus como os gregos estão todos debaixo do pecado,

[[v45-3-10]]

^<<v45-3-10,10>>^ assim como está escrito: “Não há nenhum justo, nem sequer um;

[[v45-3-11]]

^<<v45-3-11,11>>^ não há quem tenha entendimento;^&#42;1^ não há quem procure a Deus.

[NOTE]
====
. Ou: “perspicácia”.
====

[[v45-3-12]]

^<<v45-3-12,12>>^ Todos se desviaram, todos eles se tornaram inúteis; não há quem mostre bondade, nem mesmo um só.”

[[v45-3-13]]

^<<v45-3-13,13>>^ “Sua garganta é uma sepultura aberta; eles enganam com sua língua.” “Há veneno de serpente atrás dos seus lábios.”

[[v45-3-14]]

^<<v45-3-14,14>>^ “E sua boca está cheia de maldições e de amargura.”

[[v45-3-15]]

^<<v45-3-15,15>>^ “Seus pés são velozes para derramar sangue.”

[[v45-3-16]]

^<<v45-3-16,16>>^ “Há ruína e desgraça nos seus caminhos,

[[v45-3-17]]

^<<v45-3-17,17>>^ e não conhecem o caminho da paz.”

[[v45-3-18]]

^<<v45-3-18,18>>^ “Não há temor de Deus diante dos seus olhos.”

[[v45-3-19]]

^<<v45-3-19,19>>^ Ora, nós sabemos que tudo o que a Lei diz, ela dirige aos que estão debaixo da Lei, a fim de que toda boca se cale, e o mundo inteiro fique sujeito à punição diante de Deus.

[[v45-3-20]]

^<<v45-3-20,20>>^ Portanto, ninguém será declarado justo^&#42;1^ diante dele por obras exigidas por lei, pois o que vem por meio da Lei é a plena consciência^&#42;2^ do pecado.

[NOTE]
====
. Ou: “nenhuma carne será declarada justa”.
. Ou: “o conhecimento exato”.
====

[[v45-3-21]]

^<<v45-3-21,21>>^ Mas agora, sem depender de lei, foi revelada a justiça de Deus, da qual a Lei e os Profetas dão testemunho,

[[v45-3-22]]

^<<v45-3-22,22>>^ sim, a justiça de Deus por meio da fé em Jesus Cristo, para todos os que têm fé. Porque não há distinção.

[[v45-3-23]]

^<<v45-3-23,23>>^ Pois todos pecaram e não atingem a glória de Deus,

[[v45-3-24]]

^<<v45-3-24,24>>^ e é como dádiva^&#42;1^ que são declarados justos pela Sua bondade imerecida, por meio do livramento pelo resgate pago por Cristo Jesus.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v45-3-25]]

^<<v45-3-25,25>>^ Deus apresentou Cristo como oferta para propiciação^&#42;1^ por meio da fé no seu sangue. Deus fez isso para demonstrar sua própria justiça, pois, na sua tolerância,^&#42;2^ estava perdoando os pecados cometidos no passado.

[NOTE]
====
. Ou: “expiação; reconciliação”.
. Ou: “indulgência”.
====

[[v45-3-26]]

^<<v45-3-26,26>>^ Fez isso para demonstrar a sua justiça no presente, de modo que ele fosse justo também ao declarar justo o homem que tem fé em Jesus.

[[v45-3-27]]

^<<v45-3-27,27>>^ Onde está então o motivo para se orgulhar? Foi eliminado. Por meio de que lei? A das obras? Não! Por meio da lei da fé.

[[v45-3-28]]

^<<v45-3-28,28>>^ Pois nós concluímos que o homem é declarado justo pela fé, sem depender de obras exigidas por lei.

[[v45-3-29]]

^<<v45-3-29,29>>^ Ou será que Deus é somente Deus dos judeus? Não é também Deus de pessoas das nações? Sim, também de pessoas das nações.

[[v45-3-30]]

^<<v45-3-30,30>>^ Visto que Deus é um só, ele declarará justos os circuncisos em resultado da fé, e os incircuncisos por meio da sua fé.

[[v45-3-31]]

^<<v45-3-31,31>>^ Então, abolimos a lei por meio da nossa fé? De modo algum! Pelo contrário, confirmamos a lei.

'''

xref:045-romanos/045-romanos-002.adoc#v45-2-0[&#60; Capítulo Anterior] | <<v45-3-0,Topo>> | xref:045-romanos/045-romanos-004.adoc#v45-4-0[Próximo Capítulo &#62;]