include::./index.adoc[]

[[v45-1-0]]
=== Aos Romanos, 1
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

_A CARTA AOS ROMANOS_

[[v45-1-1]]

^<<v45-1-1,1>>^ Paulo, escravo de Cristo Jesus e chamado para ser apóstolo, separado para proclamar as boas novas de Deus,

[[v45-1-2]]

^<<v45-1-2,2>>^ que ele havia prometido por meio de seus profetas nas Escrituras sagradas,

[[v45-1-3]]

^<<v45-1-3,3>>^ a respeito do seu Filho, que veio da descendência^&#42;1^ de Davi segundo a carne,

[NOTE]
====
. Lit.: “semente”.
====

[[v45-1-4]]

^<<v45-1-4,4>>^ mas que, com poder, foi declarado Filho de Deus segundo o espírito de santidade, por meio da ressurreição dentre os mortos (sim, Jesus Cristo, nosso Senhor,

[[v45-1-5]]

^<<v45-1-5,5>>^ por intermédio de quem recebemos bondade imerecida e um apostolado, para que haja obediência pela fé entre todas as nações com respeito ao seu nome,

[[v45-1-6]]

^<<v45-1-6,6>>^ nações entre as quais vocês também foram chamados para pertencer a Jesus Cristo),

[[v45-1-7]]

^<<v45-1-7,7>>^ a todos os que estão em Roma como amados de Deus, chamados para ser santos:
Que vocês tenham bondade imerecida e paz da parte de Deus, nosso Pai, e do Senhor Jesus Cristo.

[[v45-1-8]]

^<<v45-1-8,8>>^ Em primeiro lugar, por meio de Jesus Cristo, agradeço ao meu Deus por todos vocês, porque se fala da sua fé no mundo inteiro.

[[v45-1-9]]

^<<v45-1-9,9>>^ Pois Deus, a quem presto serviço sagrado com o meu espírito, proclamando as boas novas a respeito do seu Filho, é minha testemunha de que eu menciono vocês sem cessar nas minhas orações,

[[v45-1-10]]

^<<v45-1-10,10>>^ rogando que, se de todo possível, eu agora consiga finalmente ir visitá-los, se essa for a vontade de Deus.

[[v45-1-11]]

^<<v45-1-11,11>>^ Pois desejo muito vê-los, para lhes transmitir algum dom espiritual a fim de que vocês sejam firmados;

[[v45-1-12]]

^<<v45-1-12,12>>^ ou melhor, para nos encorajarmos mutuamente por meio da nossa fé, tanto a sua como a minha.

[[v45-1-13]]

^<<v45-1-13,13>>^ Mas não quero que vocês fiquem sem saber, irmãos, que muitas vezes quis visitá-los para conseguir alguns frutos também entre vocês, assim como entre as demais nações; no entanto, fui impedido até agora.

[[v45-1-14]]

^<<v45-1-14,14>>^ Sou devedor tanto a gregos como a estrangeiros,^&#42;1^ tanto aos instruídos como aos sem instrução;

[NOTE]
====
. Ou: “não gregos”. Lit.: “bárbaros”.
====

[[v45-1-15]]

^<<v45-1-15,15>>^ assim, estou ansioso para declarar as boas novas também a vocês que estão em Roma.

[[v45-1-16]]

^<<v45-1-16,16>>^ Pois eu não me envergonho das boas novas. Elas são, de fato, o poder de Deus para a salvação de todo aquele que tem fé, primeiro do judeu, e também do grego.

[[v45-1-17]]

^<<v45-1-17,17>>^ Pois nelas a justiça^&#42;1^ de Deus é revelada pela fé e para a fé, assim como está escrito: “Mas o justo viverá em razão da fé.”

[NOTE]
====
. Veja o Glossário.
====

[[v45-1-18]]

^<<v45-1-18,18>>^ Pois a ira de Deus se revela desde o céu contra toda a impiedade e injustiça dos homens que suprimem a verdade de modo injusto,

[[v45-1-19]]

^<<v45-1-19,19>>^ porque o que se pode saber sobre Deus é bem claro entre eles, visto que Deus o tornou claro a eles.

[[v45-1-20]]

^<<v45-1-20,20>>^ Pois as suas qualidades invisíveis — isto é, seu poder eterno e Divindade — são claramente vistas desde a criação do mundo, porque são percebidas por meio das coisas feitas, de modo que eles não têm desculpa.

[[v45-1-21]]

^<<v45-1-21,21>>^ Porque, embora conhecessem a Deus, não o glorificaram como Deus, nem lhe agradeceram, mas os seus raciocínios se tornaram fúteis, e o seu coração insensato ficou obscurecido.

[[v45-1-22]]

^<<v45-1-22,22>>^ Embora afirmassem ser sábios, tornaram-se tolos

[[v45-1-23]]

^<<v45-1-23,23>>^ e transformaram a glória do Deus imortal^&#42;1^ em algo semelhante à imagem do homem perecível, bem como de aves, de quadrúpedes e de répteis.^&#42;2^

[NOTE]
====
. Ou: “imperecível”.
. Ou: “animais rasteiros”.
====

[[v45-1-24]]

^<<v45-1-24,24>>^ Portanto Deus, em harmonia com os desejos do coração deles, os entregou à impureza, para que desonrassem o seu próprio corpo.

[[v45-1-25]]

^<<v45-1-25,25>>^ Eles trocaram a verdade de Deus pela mentira, e veneraram^&#42;1^ e prestaram serviço sagrado à criação em vez de ao Criador, que é louvado para sempre. Amém.

[NOTE]
====
. Ou: “adoraram”.
====

[[v45-1-26]]

^<<v45-1-26,26>>^ É por isso que Deus os entregou à paixão vergonhosa,^&#42;1^ pois tanto as mulheres entre eles trocaram o uso natural de si mesmas por outro contrário à natureza,

[NOTE]
====
. Ou: “ao apetite sexual vergonhoso”.
====

[[v45-1-27]]

^<<v45-1-27,27>>^ como também os homens abandonaram o uso natural da^&#42;1^ mulher e ficaram violentamente inflamados de paixão uns pelos outros, homens com homens, praticando o que é obsceno e recebendo em si mesmos a plena punição^&#42;2^ pelo seu erro.

[NOTE]
====
. Ou: “as relações naturais com a”.
. Ou: “recompensa”.
====

[[v45-1-28]]

^<<v45-1-28,28>>^ Como não quiseram reconhecer a Deus,^&#42;1^ Deus os entregou a um estado mental reprovado, para fazerem coisas que não deviam fazer.

[NOTE]
====
. Ou: “Como rejeitaram o conhecimento exato de Deus”.
====

[[v45-1-29]]

^<<v45-1-29,29>>^ E eles estavam cheios de todo tipo de injustiça, impiedade, ganância^&#42;1^ e maldade, cheios de inveja, assassinato, briga, engano e malícia, eram cochichadores,^&#42;2^

[NOTE]
====
. Ou: “cobiça”.
. Ou: “fofoqueiros”.
====

[[v45-1-30]]

^<<v45-1-30,30>>^ caluniadores, tinham ódio de Deus, eram insolentes, arrogantes, presunçosos, inventores de coisas más,^&#42;1^ desobedientes aos pais,

[NOTE]
====
. Ou: “planejadores de coisas prejudiciais”.
====

[[v45-1-31]]

^<<v45-1-31,31>>^ sem entendimento, desleais nos acordos, desnaturados e sem misericórdia.

[[v45-1-32]]

^<<v45-1-32,32>>^ Embora eles conheçam muito bem o justo decreto de Deus, de que os que praticam essas coisas merecem a morte, não somente continuam a fazê-las, mas também aprovam os que as praticam.

'''

xref:044-atos/044-atos-028.adoc#v44-28-0[&#60; Capítulo Anterior] | <<v45-1-0,Topo>> | xref:045-romanos/045-romanos-002.adoc#v45-2-0[Próximo Capítulo &#62;]