include::./index.adoc[]

[[v45-14-0]]
=== Aos Romanos, 14
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v45-14-1]]

^<<v45-14-1,1>>^ Acolham o homem que tem fraquezas na fé, mas não façam julgamentos sobre opiniões divergentes.^&#42;1^

[NOTE]
====
. Ou, possivelmente: “questionamentos subjetivos”.
====

[[v45-14-2]]

^<<v45-14-2,2>>^ Um homem tem fé para comer de tudo, mas o homem que é fraco só come verduras.

[[v45-14-3]]

^<<v45-14-3,3>>^ Quem come não menospreze aquele que não come, e quem não come não julgue aquele que come, pois Deus o acolheu.

[[v45-14-4]]

^<<v45-14-4,4>>^ Quem é você para julgar o servo de outro? É para o seu próprio senhor que ele fica de pé ou cai. De fato, ele ficará de pé, pois Jeová^&#42;1^ pode fazê-lo ficar de pé.

[NOTE]
====
. Veja Ap. A5.
====

[[v45-14-5]]

^<<v45-14-5,5>>^ Uma pessoa considera um dia mais importante que outro, ao passo que outra pessoa considera todos os dias iguais; que cada um esteja plenamente convencido na sua própria mente.

[[v45-14-6]]

^<<v45-14-6,6>>^ Quem guarda o dia, guarda-o para Jeová.^&#42;1^ E quem come, come para Jeová,^&#42;2^ pois agradece a Deus; e quem não come, deixa de comer para Jeová,^&#42;3^ e mesmo assim agradece a Deus.

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v45-14-7]]

^<<v45-14-7,7>>^ De fato, nenhum de nós vive somente para si mesmo, e ninguém morre somente para si mesmo.

[[v45-14-8]]

^<<v45-14-8,8>>^ Pois, se vivemos, vivemos para Jeová;^&#42;1^ se morremos, morremos para Jeová.^&#42;2^ Portanto, quer vivamos, quer morramos, pertencemos a Jeová.^&#42;3^

[NOTE]
====
. Veja Ap. A5.
. Veja Ap. A5.
. Veja Ap. A5.
====

[[v45-14-9]]

^<<v45-14-9,9>>^ Pois com este objetivo Cristo morreu e voltou a viver: para ser Senhor tanto dos mortos como dos vivos.

[[v45-14-10]]

^<<v45-14-10,10>>^ Mas por que você julga o seu irmão? E você, por que menospreza o seu irmão? Pois todos nós compareceremos perante o tribunal de Deus.

[[v45-14-11]]

^<<v45-14-11,11>>^ Porque está escrito: “‘Tão certo como eu vivo’, diz Jeová,^&#42;1^ ‘diante de mim todo joelho se dobrará, e toda língua reconhecerá abertamente a Deus’.”

[NOTE]
====
. Veja Ap. A5.
====

[[v45-14-12]]

^<<v45-14-12,12>>^ Assim, cada um de nós prestará contas de si mesmo a Deus.

[[v45-14-13]]

^<<v45-14-13,13>>^ Portanto, não julguemos mais uns aos outros, mas, em vez disso, estejam determinados a não pôr uma pedra de tropeço ou um obstáculo diante de um irmão.

[[v45-14-14]]

^<<v45-14-14,14>>^ (Sei e estou convencido no Senhor Jesus que nada é impuro em si mesmo; somente quando alguém considera algo como impuro, então para ele é impuro.)

[[v45-14-15]]

^<<v45-14-15,15>>^ Pois, se o seu irmão se ofende por causa de um alimento, você não está mais andando de acordo com o amor. Não arruíne,^&#42;1^ pelo seu alimento, aquele pelo qual Cristo morreu.

[NOTE]
====
. Ou: “Não destrua”.
====

[[v45-14-16]]

^<<v45-14-16,16>>^ Portanto, não deixem que se fale mal do bem que vocês fazem.

[[v45-14-17]]

^<<v45-14-17,17>>^ Pois o Reino de Deus não tem a ver com comida e bebida, mas com justiça, paz e alegria no espírito santo.

[[v45-14-18]]

^<<v45-14-18,18>>^ Pois quem trabalha dessa forma como escravo para Cristo agrada a Deus e tem a aprovação dos homens.

[[v45-14-19]]

^<<v45-14-19,19>>^ Assim, empenhemo-nos pelas coisas que promovem a paz e pelas coisas que edificam uns aos outros.

[[v45-14-20]]

^<<v45-14-20,20>>^ Parem de demolir a obra de Deus só por causa do alimento. É verdade que todas as coisas são puras; mas é prejudicial^&#42;1^ para o homem comer se isso for causar tropeço.

[NOTE]
====
. Ou: “errado”.
====

[[v45-14-21]]

^<<v45-14-21,21>>^ É melhor não comer carne, nem beber vinho, nem fazer nada que leve o seu irmão a tropeçar.

[[v45-14-22]]

^<<v45-14-22,22>>^ A fé que você tem, guarde-a para si diante de Deus. Feliz é aquele que não condena a si mesmo por aquilo que aprova.

[[v45-14-23]]

^<<v45-14-23,23>>^ Mas, se alguém tem dúvidas e come, já está condenado, porque não come com base na fé. E tudo o que não se baseia na fé é pecado.

'''

xref:045-romanos/045-romanos-013.adoc#v45-13-0[&#60; Capítulo Anterior] | <<v45-14-0,Topo>> | xref:045-romanos/045-romanos-015.adoc#v45-15-0[Próximo Capítulo &#62;]