include::./index.adoc[]

[[v44-14-0]]
=== Atos dos Apóstolos, 14
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-14-1]]

^<<v44-14-1,1>>^ Em Icônio, eles entraram juntos na sinagoga dos judeus e falaram de tal maneira que uma grande multidão, tanto de judeus como de gregos, se tornou crente.

[[v44-14-2]]

^<<v44-14-2,2>>^ Mas os judeus que não creram atiçaram as pessoas^&#42;1^ das nações, instigando-as contra os irmãos.

[NOTE]
====
. Ou: “as almas das pessoas”.
====

[[v44-14-3]]

^<<v44-14-3,3>>^ Portanto, Paulo e Barnabé passaram bastante tempo falando corajosamente com a autoridade de Jeová;^&#42;1^ e Ele confirmava a^&#42;2^ mensagem sobre a sua bondade imerecida concedendo que ocorressem sinais e milagres^&#42;3^ por meio deles.

[NOTE]
====
. Veja Ap. A5.
. Ou: “dava testemunho da”.
. Ou: “portentos”.
====

[[v44-14-4]]

^<<v44-14-4,4>>^ No entanto, a multidão da cidade estava dividida: alguns eram a favor dos judeus, e outros a favor dos apóstolos.

[[v44-14-5]]

^<<v44-14-5,5>>^ Então, as pessoas das nações junto com os judeus e seus líderes resolveram maltratá-los e apedrejá-los.

[[v44-14-6]]

^<<v44-14-6,6>>^ Ao serem informados disso, fugiram para Listra e Derbe, cidades da Licaônia, e para a região ao redor.

[[v44-14-7]]

^<<v44-14-7,7>>^ Ali continuaram a declarar as boas novas.

[[v44-14-8]]

^<<v44-14-8,8>>^ Em Listra, havia um homem que tinha os pés aleijados; ele era manco de nascença, nunca tinha andado. Ele estava sentado,

[[v44-14-9]]

^<<v44-14-9,9>>^ escutando Paulo falar. Paulo, olhando para ele atentamente e vendo que ele tinha fé para ficar bom,

[[v44-14-10]]

^<<v44-14-10,10>>^ disse bem alto: “Levante-se e fique de pé.” Então o homem deu um salto e começou a andar.

[[v44-14-11]]

^<<v44-14-11,11>>^ Quando as multidões viram o que Paulo tinha feito, gritaram na língua licaônica: “Os deuses tomaram forma humana e desceram a nós!”

[[v44-14-12]]

^<<v44-14-12,12>>^ Eles começaram a chamar Barnabé de Zeus e Paulo de Hermes, pois era ele que lhes dirigia a palavra.

[[v44-14-13]]

^<<v44-14-13,13>>^ O sacerdote de Zeus, cujo templo ficava na entrada da cidade, levou touros e grinaldas^&#42;1^ até os portões, e queria oferecer sacrifícios com as multidões.

[NOTE]
====
. Ou: “coroas de flores”.
====

[[v44-14-14]]

^<<v44-14-14,14>>^ Quando os apóstolos Barnabé e Paulo souberam disso, rasgaram suas roupas, correram para o meio da multidão e gritaram:

[[v44-14-15]]

^<<v44-14-15,15>>^ “Homens, por que estão fazendo isso? Nós também somos humanos e temos as mesmas fraquezas que vocês. E estamos declarando as boas novas a vocês para que abandonem essas coisas vãs e se convertam ao Deus vivente, que fez o céu, a terra, o mar e tudo que há neles.

[[v44-14-16]]

^<<v44-14-16,16>>^ Em gerações passadas, ele permitiu que todas as nações andassem nos seus próprios caminhos,

[[v44-14-17]]

^<<v44-14-17,17>>^ embora não tenha deixado de dar testemunho de si mesmo, pois demonstrou sua bondade dando-lhes chuvas do céu e épocas de colheita abundante, satisfazendo-os com alimentos e enchendo seu coração de alegria.”

[[v44-14-18]]

^<<v44-14-18,18>>^ Mesmo dizendo essas coisas, foi muito difícil impedir que as multidões lhes oferecessem sacrifícios.

[[v44-14-19]]

^<<v44-14-19,19>>^ Mas chegaram judeus de Antioquia e de Icônio que persuadiram as multidões; então apedrejaram Paulo e o arrastaram para fora da cidade, imaginando que ele estivesse morto.

[[v44-14-20]]

^<<v44-14-20,20>>^ No entanto, quando os discípulos se juntaram em volta dele, ele se levantou e entrou na cidade. No dia seguinte partiu com Barnabé para Derbe.

[[v44-14-21]]

^<<v44-14-21,21>>^ Depois de declararem as boas novas àquela cidade e fazerem um bom número de discípulos, voltaram a Listra, Icônio e Antioquia.

[[v44-14-22]]

^<<v44-14-22,22>>^ Ali, fortaleceram os discípulos,^&#42;1^ encorajando-os a permanecer na fé e dizendo-lhes: “Temos de passar por muitas dificuldades para entrar no Reino de Deus.”

[NOTE]
====
. Ou: “as almas dos discípulos”.
====

[[v44-14-23]]

^<<v44-14-23,23>>^ Além disso, designaram anciãos para eles em cada congregação, fazendo orações e jejuando, e os entregaram aos cuidados de Jeová,^&#42;1^ em quem tinham passado a crer.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-14-24]]

^<<v44-14-24,24>>^ Então passaram pela Pisídia, entraram na Panfília

[[v44-14-25]]

^<<v44-14-25,25>>^ e, depois de proclamar a palavra em Perge, desceram para Atália.

[[v44-14-26]]

^<<v44-14-26,26>>^ Dali navegaram para Antioquia, onde haviam sido entregues à bondade imerecida de Deus para a obra que agora tinham completado.

[[v44-14-27]]

^<<v44-14-27,27>>^ Depois de chegarem e reunirem a congregação, contaram as muitas coisas que Deus tinha feito por meio deles e como ele tinha aberto para as nações a porta da fé.

[[v44-14-28]]

^<<v44-14-28,28>>^ Assim, passaram bastante tempo com os discípulos.

'''

xref:044-atos/044-atos-013.adoc#v44-13-0[&#60; Capítulo Anterior] | <<v44-14-0,Topo>> | xref:044-atos/044-atos-015.adoc#v44-15-0[Próximo Capítulo &#62;]