include::./index.adoc[]

[[v44-5-0]]
=== Atos dos Apóstolos, 5
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-5-1]]

^<<v44-5-1,1>>^ No entanto, um homem chamado Ananias, junto com Safira, sua esposa, vendeu uma propriedade.

[[v44-5-2]]

^<<v44-5-2,2>>^ Mas ele secretamente ficou com parte do valor, com o conhecimento de sua esposa. Então, pegou o restante e o colocou aos pés dos apóstolos.

[[v44-5-3]]

^<<v44-5-3,3>>^ Mas Pedro disse: “Ananias, como Satanás levou você a mentir de forma descarada ao espírito santo e ficar secretamente com parte do valor do campo?

[[v44-5-4]]

^<<v44-5-4,4>>^ O campo não era seu antes de você o vender? E, depois de ter sido vendido, o valor não ficou sob o seu controle? Por que você tramou no coração fazer uma coisa dessas? Você mentiu não a homens, mas a Deus.”

[[v44-5-5]]

^<<v44-5-5,5>>^ Ao ouvir essas palavras, Ananias caiu e morreu. E todos os que souberam disso ficaram com muito medo.

[[v44-5-6]]

^<<v44-5-6,6>>^ Então os mais jovens se levantaram e o enrolaram em panos; em seguida o levaram para fora e o enterraram.

[[v44-5-7]]

^<<v44-5-7,7>>^ Cerca de três horas depois, a esposa dele entrou, sem saber o que tinha acontecido.

[[v44-5-8]]

^<<v44-5-8,8>>^ Pedro lhe perguntou: “Diga-me: Vocês dois venderam o campo por tanto?” Ela respondeu: “Sim, por esse valor.”

[[v44-5-9]]

^<<v44-5-9,9>>^ Assim, Pedro lhe disse: “Por que vocês dois concordaram em pôr à prova o espírito de Jeová?^&#42;1^ Os pés daqueles que enterraram seu marido estão à porta; eles a levarão para fora.”

[NOTE]
====
. Veja Ap. A5.
====

[[v44-5-10]]

^<<v44-5-10,10>>^ Ela caiu instantaneamente aos pés dele e morreu. Quando os jovens entraram, encontraram-na morta; então a levaram para fora e a enterraram ao lado do marido.

[[v44-5-11]]

^<<v44-5-11,11>>^ Assim, toda a congregação e todos os que ouviram falar sobre isso ficaram com muito medo.

[[v44-5-12]]

^<<v44-5-12,12>>^ Além disso, pelas mãos dos apóstolos continuavam a ocorrer muitos sinais e milagres^&#42;1^ entre o povo; e todos se reuniam no Pórtico^&#42;2^ de Salomão.

[NOTE]
====
. Ou: “portentos”.
. Ou: “na Colunata”.
====

[[v44-5-13]]

^<<v44-5-13,13>>^ É verdade que nenhum dos outros tinha coragem de se juntar a eles, mas o povo falava muito bem deles.

[[v44-5-14]]

^<<v44-5-14,14>>^ Não só isso: um grande número de homens e mulheres passavam a crer no Senhor e eram acrescentados a eles.

[[v44-5-15]]

^<<v44-5-15,15>>^ Até mesmo levavam os doentes para fora, às ruas principais, e os deitavam em pequenas camas e em esteiras, para que, quando Pedro passasse, pelo menos a sua sombra tocasse alguns deles.

[[v44-5-16]]

^<<v44-5-16,16>>^ Também, vinham multidões das cidades vizinhas de Jerusalém, trazendo os doentes e os afligidos por espíritos impuros, e todos eles eram curados.

[[v44-5-17]]

^<<v44-5-17,17>>^ No entanto, o sumo sacerdote e todos os que estavam com ele, que eram da seita dos saduceus, se levantaram cheios de ciúme.

[[v44-5-18]]

^<<v44-5-18,18>>^ Então eles agarraram^&#42;1^ os apóstolos e os puseram na cadeia pública.

[NOTE]
====
. Ou: “prenderam”.
====

[[v44-5-19]]

^<<v44-5-19,19>>^ Mas, durante a noite, o anjo de Jeová^&#42;1^ abriu as portas da prisão, levou-os para fora e disse:

[NOTE]
====
. Veja Ap. A5.
====

[[v44-5-20]]

^<<v44-5-20,20>>^ “Vão, apresentem-se no templo e continuem falando ao povo toda a mensagem a respeito da vida.”

[[v44-5-21]]

^<<v44-5-21,21>>^ Depois de ouvirem essas palavras, entraram no templo ao amanhecer e começaram a ensinar.
Quando chegaram o sumo sacerdote e os que estavam com ele, convocaram o Sinédrio e toda a assembleia dos anciãos dos filhos de Israel, e mandaram trazer da cadeia os apóstolos.

[[v44-5-22]]

^<<v44-5-22,22>>^ No entanto, quando os guardas^&#42;1^ chegaram à prisão, não os acharam. Assim, voltaram e relataram o seguinte:

[NOTE]
====
. Ou: “guardas do templo”.
====

[[v44-5-23]]

^<<v44-5-23,23>>^ “Encontramos a cadeia trancada com toda a segurança, e os guardas estavam parados às portas, mas, quando a abrimos, não achamos ninguém dentro.”

[[v44-5-24]]

^<<v44-5-24,24>>^ Ao ouvirem isso, o capitão do templo e os principais sacerdotes ficaram perplexos, perguntando-se o que aconteceria a seguir.

[[v44-5-25]]

^<<v44-5-25,25>>^ Mas alguém chegou e lhes disse: “Os homens que vocês puseram na prisão estão no templo, ensinando o povo!”

[[v44-5-26]]

^<<v44-5-26,26>>^ Então o capitão foi buscá-los com os seus guardas, mas sem violência, porque tinham medo de ser apedrejados pelo povo.

[[v44-5-27]]

^<<v44-5-27,27>>^ Assim, eles os trouxeram e os puseram diante do Sinédrio. E o sumo sacerdote os interrogou

[[v44-5-28]]

^<<v44-5-28,28>>^ e disse: “Nós lhes demos ordens expressas para que não ensinassem nesse nome, mas, vejam só! Vocês encheram Jerusalém com os seus ensinamentos, e estão decididos a trazer o sangue desse homem sobre nós.”

[[v44-5-29]]

^<<v44-5-29,29>>^ Pedro e os outros apóstolos responderam: “Temos de obedecer a Deus como governante em vez de a homens.

[[v44-5-30]]

^<<v44-5-30,30>>^ O Deus de nossos antepassados levantou dentre os mortos Jesus, a quem vocês mataram pendurando-o num madeiro.^&#42;1^

[NOTE]
====
. Ou: “numa árvore”.
====

[[v44-5-31]]

^<<v44-5-31,31>>^ Deus o enalteceu à sua direita como Agente Principal e Salvador, para dar arrependimento a Israel e perdão de pecados.

[[v44-5-32]]

^<<v44-5-32,32>>^ Nós somos testemunhas dessas coisas, e o espírito santo, que Deus deu aos que lhe obedecem como governante, também é.”

[[v44-5-33]]

^<<v44-5-33,33>>^ Quando ouviram isso, ficaram furiosos^&#42;1^ e quiseram matá-los.

[NOTE]
====
. Ou: “sentiram-se feridos”.
====

[[v44-5-34]]

^<<v44-5-34,34>>^ Mas se levantou no Sinédrio um fariseu chamado Gamaliel, instrutor da Lei estimado por todo o povo, e ele mandou que levassem os homens para fora por um momento.

[[v44-5-35]]

^<<v44-5-35,35>>^ Então lhes disse: “Homens de Israel, tomem cuidado com o que vão fazer com esses homens.

[[v44-5-36]]

^<<v44-5-36,36>>^ Por exemplo, um tempo atrás apareceu Teudas, dizendo ser alguém, e alguns homens, cerca de 400, se juntaram a ele. Mas ele foi morto, e todos os que o seguiam foram espalhados, e seus planos acabaram em nada.

[[v44-5-37]]

^<<v44-5-37,37>>^ Depois dele, nos dias do recenseamento, apareceu Judas, o galileu, e juntou seguidores atrás de si. Esse homem também morreu, e todos os que o seguiam foram espalhados.

[[v44-5-38]]

^<<v44-5-38,38>>^ Por isso, diante das circunstâncias, digo-lhes: Não se metam com esses homens; deixem-nos em paz. Porque, se esse plano ou essa obra for de homens, será derrubada;

[[v44-5-39]]

^<<v44-5-39,39>>^ mas, se for de Deus, vocês não poderão derrubá-los. Senão, pode ser que vocês estejam até mesmo lutando contra o próprio Deus.”

[[v44-5-40]]

^<<v44-5-40,40>>^ Então aceitaram o seu conselho. Mandaram chamar os apóstolos e, depois de os açoitarem,^&#42;1^ lhes ordenaram que parassem de falar em nome de Jesus e os soltaram.

[NOTE]
====
. Ou: “espancarem”.
====

[[v44-5-41]]

^<<v44-5-41,41>>^ Assim, eles saíram do Sinédrio, alegres porque tinham sido considerados dignos de ser desonrados por causa do nome dele.

[[v44-5-42]]

^<<v44-5-42,42>>^ E todo dia, no templo e de casa em casa, continuavam, sem parar, a ensinar e a declarar as boas novas a respeito do Cristo, Jesus.

'''

xref:044-atos/044-atos-004.adoc#v44-4-0[&#60; Capítulo Anterior] | <<v44-5-0,Topo>> | xref:044-atos/044-atos-006.adoc#v44-6-0[Próximo Capítulo &#62;]