include::./index.adoc[]

[[v44-11-0]]
=== Atos dos Apóstolos, 11
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-11-1]]

^<<v44-11-1,1>>^ Então, os apóstolos e os irmãos que estavam na Judeia ouviram que pessoas das nações também tinham aceitado a palavra de Deus.

[[v44-11-2]]

^<<v44-11-2,2>>^ Assim, quando Pedro subiu a Jerusalém, os que apoiavam a circuncisão começaram a criticá-lo,^&#42;1^

[NOTE]
====
. Ou: “discutir com ele”.
====

[[v44-11-3]]

^<<v44-11-3,3>>^ dizendo: “Você entrou na casa de homens incircuncisos e comeu com eles.”

[[v44-11-4]]

^<<v44-11-4,4>>^ Em vista disso, Pedro começou a lhes explicar os detalhes do que havia acontecido:

[[v44-11-5]]

^<<v44-11-5,5>>^ “Eu estava na cidade de Jope orando e, num transe, tive uma visão de algo semelhante a um grande lençol de linho descendo do céu, preso pelas suas quatro pontas, e ele veio até perto de mim.

[[v44-11-6]]

^<<v44-11-6,6>>^ Olhei atentamente para dentro dele e vi quadrúpedes da terra, animais selvagens, répteis^&#42;1^ e aves do céu.

[NOTE]
====
. Ou: “animais rasteiros”.
====

[[v44-11-7]]

^<<v44-11-7,7>>^ Também ouvi uma voz me dizer: ‘Levante-se, Pedro, mate e coma!’

[[v44-11-8]]

^<<v44-11-8,8>>^ Mas eu disse: ‘De jeito nenhum, Senhor, porque na minha boca nunca entrou nada aviltado ou impuro.’

[[v44-11-9]]

^<<v44-11-9,9>>^ A voz do céu falou então pela segunda vez: ‘Pare de chamar de impuras as coisas que Deus purificou.’

[[v44-11-10]]

^<<v44-11-10,10>>^ Isso ocorreu pela terceira vez, e tudo foi puxado de volta para o céu.

[[v44-11-11]]

^<<v44-11-11,11>>^ Além disso, naquele instante, três homens que haviam sido enviados de Cesareia à minha procura chegaram à casa onde estávamos.

[[v44-11-12]]

^<<v44-11-12,12>>^ Então o espírito me disse que eu fosse com eles sem hesitar. Estes seis irmãos também foram comigo, e nós entramos na casa do homem.

[[v44-11-13]]

^<<v44-11-13,13>>^ “Ele nos contou que tinha visto um anjo aparecer na sua casa e dizer: ‘Envie homens a Jope e mande chamar Simão, que é conhecido como Pedro,

[[v44-11-14]]

^<<v44-11-14,14>>^ e ele lhe dirá as coisas pelas quais você e todos os da sua casa podem ser salvos.’

[[v44-11-15]]

^<<v44-11-15,15>>^ Quando comecei a falar, o espírito santo desceu sobre eles, da mesma forma como tinha descido sobre nós no princípio.

[[v44-11-16]]

^<<v44-11-16,16>>^ Em vista disso eu me lembrei das palavras do Senhor; ele dizia: ‘João batizou com água, mas vocês serão batizados com espírito santo.’

[[v44-11-17]]

^<<v44-11-17,17>>^ Portanto, se Deus deu a eles a mesma dádiva^&#42;1^ que deu a nós, que cremos no Senhor Jesus Cristo, quem era eu para poder impedir a Deus?”^&#42;2^

[NOTE]
====
. Ou: “dádiva gratuita”.
. Ou: “poder me opor a Deus”.
====

[[v44-11-18]]

^<<v44-11-18,18>>^ Quando ouviram essas coisas, não apresentaram mais objeções^&#42;1^ e glorificaram a Deus, dizendo: “Então, Deus também concedeu a pessoas das nações o arrependimento que leva à vida.”

[NOTE]
====
. Lit.: “eles ficaram em silêncio”.
====

[[v44-11-19]]

^<<v44-11-19,19>>^ Os que tinham sido espalhados pela perseguição que surgiu por causa de Estêvão foram até a Fenícia, Chipre e Antioquia, mas falavam a palavra apenas aos judeus.

[[v44-11-20]]

^<<v44-11-20,20>>^ No entanto, alguns homens entre eles que eram de Chipre e de Cirene foram a Antioquia e começaram a falar às pessoas de língua grega, declarando as boas novas do Senhor Jesus.

[[v44-11-21]]

^<<v44-11-21,21>>^ E a mão de Jeová^&#42;1^ estava com eles, e muitos se tornaram crentes e se converteram ao Senhor.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-11-22]]

^<<v44-11-22,22>>^ As notícias sobre eles chegaram aos ouvidos da congregação em Jerusalém, e enviaram então Barnabé a Antioquia.

[[v44-11-23]]

^<<v44-11-23,23>>^ Quando ele chegou e viu a bondade imerecida de Deus, alegrou-se e começou a encorajar todos a continuarem no Senhor com firmeza de coração,

[[v44-11-24]]

^<<v44-11-24,24>>^ pois era um homem bom, cheio de espírito santo e de fé. E uma multidão considerável passou a crer no Senhor.

[[v44-11-25]]

^<<v44-11-25,25>>^ De modo que ele foi a Tarso a fim de procurar cuidadosamente por Saulo.

[[v44-11-26]]

^<<v44-11-26,26>>^ Depois de achá-lo, levou-o a Antioquia. Assim, por um ano inteiro, reuniram-se com a congregação e ensinaram uma numerosa multidão. E foi primeiro em Antioquia que os discípulos, por direção divina, foram chamados de cristãos.

[[v44-11-27]]

^<<v44-11-27,27>>^ Naqueles dias alguns profetas desceram de Jerusalém para Antioquia.

[[v44-11-28]]

^<<v44-11-28,28>>^ Um deles, chamado Ágabo, levantou-se e predisse, por meio do espírito, que uma grande fome estava para vir sobre toda a terra habitada. De fato, ela ocorreu no tempo de Cláudio.

[[v44-11-29]]

^<<v44-11-29,29>>^ Assim, os discípulos resolveram, cada um de acordo com as suas possibilidades, enviar ajuda^&#42;1^ aos irmãos que moravam na Judeia.

[NOTE]
====
. Ou: “uma subministração de socorros”.
====

[[v44-11-30]]

^<<v44-11-30,30>>^ E fizeram isso, enviando-a aos anciãos pelas mãos de Barnabé e de Saulo.

'''

xref:044-atos/044-atos-010.adoc#v44-10-0[&#60; Capítulo Anterior] | <<v44-11-0,Topo>> | xref:044-atos/044-atos-012.adoc#v44-12-0[Próximo Capítulo &#62;]