include::./index.adoc[]

[[v44-28-0]]
=== Atos dos Apóstolos, 28
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-28-1]]

^<<v44-28-1,1>>^ Quando já estávamos a salvo, soubemos que a ilha se chamava Malta.

[[v44-28-2]]

^<<v44-28-2,2>>^ Os nativos da ilha^&#42;1^ nos mostraram extraordinária bondade.^&#42;2^ Acenderam uma fogueira e receberam bem a todos nós, pois estava chovendo e fazia frio.

[NOTE]
====
. Ou: “As pessoas de língua estrangeira”.
. Ou: “humanidade”.
====

[[v44-28-3]]

^<<v44-28-3,3>>^ Paulo reuniu um feixe de gravetos e, quando o colocou no fogo, saiu uma víbora por causa do calor e se prendeu à mão dele.

[[v44-28-4]]

^<<v44-28-4,4>>^ Ao verem a cobra venenosa pendurada na sua mão, os nativos começaram a dizer uns aos outros: “Certamente este homem é um assassino; embora tenha conseguido se salvar do mar, a Justiça^&#42;1^ não permitiu que ele continuasse vivo.”

[NOTE]
====
. Em grego, Díke, provavelmente uma referência à deusa da justiça vingadora, ou à justiça em sentido abstrato.
====

[[v44-28-5]]

^<<v44-28-5,5>>^ No entanto, ele sacudiu o animal para dentro do fogo e não sofreu mal nenhum.

[[v44-28-6]]

^<<v44-28-6,6>>^ Mas esperavam que ele fosse ficar inchado ou cair morto de repente. Depois de esperarem por muito tempo e verem que nada de ruim tinha lhe acontecido, mudaram de ideia e começaram a dizer que ele era um deus.

[[v44-28-7]]

^<<v44-28-7,7>>^ Ali na vizinhança havia terras que pertenciam ao homem principal da ilha, chamado Públio; ele, de modo hospitaleiro, nos recebeu e nos hospedou por três dias.

[[v44-28-8]]

^<<v44-28-8,8>>^ Aconteceu que o pai de Públio estava de cama, doente, com febre e disenteria. Então Paulo foi vê-lo; orou, colocou as mãos sobre ele e o curou.

[[v44-28-9]]

^<<v44-28-9,9>>^ Depois que isso aconteceu, os outros doentes da ilha começaram a vir procurá-lo, e também eram curados.

[[v44-28-10]]

^<<v44-28-10,10>>^ Além disso, eles nos honraram com muitos presentes e, quando estávamos para embarcar, nos deram tudo que necessitávamos.

[[v44-28-11]]

^<<v44-28-11,11>>^ Três meses depois, partimos em um navio que tinha como figura de proa os “Filhos de Zeus”. O navio era de Alexandria e havia passado o inverno na ilha.

[[v44-28-12]]

^<<v44-28-12,12>>^ Aportamos em Siracusa e permanecemos ali três dias.

[[v44-28-13]]

^<<v44-28-13,13>>^ Dali seguimos viagem e chegamos a Régio. Um dia depois começou a soprar um vento sul, e chegamos a Putéoli no segundo dia.

[[v44-28-14]]

^<<v44-28-14,14>>^ Ali encontramos alguns irmãos, que insistiram que ficássemos com eles sete dias. E assim fomos para Roma.

[[v44-28-15]]

^<<v44-28-15,15>>^ Quando os irmãos de lá ouviram as notícias sobre nós, foram até a Praça de Ápio e as Três Tavernas para nos encontrar. Ao vê-los, Paulo agradeceu a Deus e se sentiu encorajado.

[[v44-28-16]]

^<<v44-28-16,16>>^ Quando por fim entramos em Roma, permitiu-se que Paulo morasse sozinho, com um soldado para vigiá-lo.

[[v44-28-17]]

^<<v44-28-17,17>>^ Três dias depois, ele convocou os homens mais importantes dos judeus. Quando se reuniram, ele lhes disse: “Homens, irmãos, embora eu não tivesse feito nada contra o povo ou contra os costumes de nossos antepassados, fui preso em Jerusalém e entregue às mãos dos romanos.

[[v44-28-18]]

^<<v44-28-18,18>>^ Depois de me interrogarem, eles quiseram me soltar, pois não havia nenhum motivo para me condenar à morte.

[[v44-28-19]]

^<<v44-28-19,19>>^ No entanto, como os judeus se opuseram, fui obrigado a apelar para César, mas não por eu ter alguma acusação contra a minha nação.

[[v44-28-20]]

^<<v44-28-20,20>>^ Foi por isso que pedi para ver vocês e lhes falar, pois é por causa da esperança de Israel que estou preso com esta corrente.”

[[v44-28-21]]

^<<v44-28-21,21>>^ Eles lhe disseram: “Nós não recebemos cartas da Judeia a seu respeito, e nenhum dos irmãos que vieram de lá nos relatou ou falou algo mau sobre você.

[[v44-28-22]]

^<<v44-28-22,22>>^ Mas achamos correto ouvir de você o que pensa, porque, na verdade, o que sabemos dessa seita é que em toda a parte se fala contra ela.”

[[v44-28-23]]

^<<v44-28-23,23>>^ Assim, combinaram um dia para se encontrar com ele e foram num grupo ainda maior ao lugar onde estava morando. E, desde a manhã até a noite, ele lhes deu explicações por meio de um testemunho cabal sobre o Reino de Deus, procurando persuadi-los a respeito de Jesus com base na Lei de Moisés e nos Profetas.

[[v44-28-24]]

^<<v44-28-24,24>>^ Alguns acreditaram nas coisas que ele dizia; outros se recusavam a acreditar.

[[v44-28-25]]

^<<v44-28-25,25>>^ Assim, como houve desacordo entre eles, começaram a ir embora, e Paulo fez este único comentário:
“O espírito santo falou apropriadamente aos antepassados de vocês, por meio de Isaías, o profeta:

[[v44-28-26]]

^<<v44-28-26,26>>^ ‘Vá a este povo e diga: “Vocês realmente ouvirão, mas de modo algum entenderão; e realmente olharão, mas de modo algum verão.

[[v44-28-27]]

^<<v44-28-27,27>>^ Pois o coração deste povo ficou insensível, eles taparam os ouvidos e fecharam os olhos, para que nunca vissem com os olhos, nem ouvissem com os ouvidos, nem entendessem com o coração e dessem meia-volta, e eu os curasse.”’

[[v44-28-28]]

^<<v44-28-28,28>>^ Portanto, saibam que essa salvação por Deus foi enviada às nações, e elas certamente a escutarão.”

[[v44-28-29]]

^<<v44-28-29,29>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v44-28-30]]

^<<v44-28-30,30>>^ Assim, ele permaneceu ali por dois anos inteiros, na casa que alugou, e recebia bondosamente a todos os que iam vê-lo,

[[v44-28-31]]

^<<v44-28-31,31>>^ pregando-lhes o Reino de Deus e ensinando a respeito do Senhor Jesus Cristo com toda a coragem,^&#42;1^ sem nenhum impedimento.

[NOTE]
====
. Ou: “liberdade no falar”.
====

'''

xref:044-atos/044-atos-027.adoc#v44-27-0[&#60; Capítulo Anterior] | <<v44-28-0,Topo>> | xref:045-romanos/045-romanos-001.adoc#v45-1-0[Próximo Capítulo &#62;]