include::./index.adoc[]

[[v44-4-0]]
=== Atos dos Apóstolos, 4
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-4-1]]

^<<v44-4-1,1>>^ Enquanto os dois estavam falando com o povo, aproximaram-se deles os sacerdotes, o capitão do templo e os saduceus.

[[v44-4-2]]

^<<v44-4-2,2>>^ Eles estavam irritados porque os apóstolos estavam ensinando o povo e declarando abertamente a ressurreição de Jesus dentre os mortos.^&#42;1^

[NOTE]
====
. Ou: “a ressurreição dentre os mortos no caso de Jesus”.
====

[[v44-4-3]]

^<<v44-4-3,3>>^ Então os agarraram^&#42;1^ e os puseram na cadeia até o dia seguinte, pois já tinha anoitecido.

[NOTE]
====
. Ou: “prenderam”.
====

[[v44-4-4]]

^<<v44-4-4,4>>^ No entanto, muitos que tinham escutado o discurso acreditaram, e o número de homens chegou a cerca de 5.000.

[[v44-4-5]]

^<<v44-4-5,5>>^ No dia seguinte, as autoridades, os anciãos e os escribas se reuniram em Jerusalém,

[[v44-4-6]]

^<<v44-4-6,6>>^ junto com Anás, que era o principal sacerdote, Caifás, João, Alexandre e todos os que eram parentes do principal sacerdote.

[[v44-4-7]]

^<<v44-4-7,7>>^ Colocaram Pedro e João no meio deles e os interrogaram: “Com que poder ou em nome de quem vocês fizeram isso?”

[[v44-4-8]]

^<<v44-4-8,8>>^ Então Pedro, cheio de espírito santo, lhes disse:
“Líderes do povo e anciãos,

[[v44-4-9]]

^<<v44-4-9,9>>^ se estamos sendo interrogados hoje por causa de uma boa ação feita a um homem aleijado, e se querem saber quem fez esse homem ficar bom,

[[v44-4-10]]

^<<v44-4-10,10>>^ saibam os senhores e todo o povo de Israel que é em nome de Jesus Cristo, o Nazareno, aquele que os senhores executaram numa estaca, mas que Deus levantou dentre os mortos, sim, é por meio dele que este homem está aqui curado, diante dos senhores.

[[v44-4-11]]

^<<v44-4-11,11>>^ Esse Jesus é ‘a pedra que não foi levada em conta por vocês, construtores, e que se tornou a principal pedra angular’.^&#42;1^

[NOTE]
====
. Lit.: “a cabeça do cunhal”.
====

[[v44-4-12]]

^<<v44-4-12,12>>^ Além disso, não há salvação em mais ninguém, pois não há outro nome debaixo do céu, que tenha sido dado aos homens, pelo qual devamos ser salvos.”

[[v44-4-13]]

^<<v44-4-13,13>>^ Quando viram a coragem^&#42;1^ de Pedro e de João, e notaram que eles eram homens comuns e sem instrução,^&#42;2^ ficaram admirados. E perceberam que eles haviam estado com Jesus.

[NOTE]
====
. Ou: “franqueza”.
. Ou: “e indoutos”, isto é, que não tinham estudado nas escolas rabínicas. Mas isso não significa que eram analfabetos.
====

[[v44-4-14]]

^<<v44-4-14,14>>^ Eles ficaram sem resposta, pois estavam vendo ali entre eles o homem que tinha sido curado.

[[v44-4-15]]

^<<v44-4-15,15>>^ Assim, ordenaram-lhes que saíssem do Sinédrio e começaram a discutir o assunto entre si;

[[v44-4-16]]

^<<v44-4-16,16>>^ diziam: “O que faremos com esses homens? Porque, realmente, por meio deles ocorreu um sinal notável, que ficou conhecido por todos os habitantes de Jerusalém, e não podemos negá-lo.

[[v44-4-17]]

^<<v44-4-17,17>>^ Para que isso não se espalhe ainda mais entre o povo, vamos ameaçá-los e dizer-lhes que não falem mais a ninguém à base desse nome.”

[[v44-4-18]]

^<<v44-4-18,18>>^ Então eles os chamaram e lhes ordenaram que não falassem nada nem ensinassem em nome de Jesus.

[[v44-4-19]]

^<<v44-4-19,19>>^ Mas Pedro e João lhes responderam: “Julguem os senhores mesmos se é certo, à vista de Deus, obedecer aos senhores em vez de a Deus.

[[v44-4-20]]

^<<v44-4-20,20>>^ Quanto a nós, não podemos parar de falar das coisas que vimos e ouvimos.”

[[v44-4-21]]

^<<v44-4-21,21>>^ Assim, depois de ameaçá-los ainda mais, eles os soltaram por não terem achado nenhuma base para puni-los e também por causa do povo, porque todos estavam glorificando a Deus pelo que tinha acontecido.

[[v44-4-22]]

^<<v44-4-22,22>>^ Pois o homem que havia sido curado por esse milagre^&#42;1^ tinha mais de 40 anos.

[NOTE]
====
. Ou: “sinal”.
====

[[v44-4-23]]

^<<v44-4-23,23>>^ Depois de serem soltos, foram ao encontro dos outros discípulos^&#42;1^ e contaram o que os principais sacerdotes e os anciãos lhes haviam dito.

[NOTE]
====
. Ou: “do seu próprio povo”.
====

[[v44-4-24]]

^<<v44-4-24,24>>^ Ao ouvirem isso, unidos, levantaram a voz a Deus, dizendo:
“Soberano Senhor, tu és aquele que fez o céu, a terra, o mar e tudo que há neles,

[[v44-4-25]]

^<<v44-4-25,25>>^ e quem, por espírito santo, disse por meio de nosso antepassado Davi, teu servo: ‘Por que as nações ficaram agitadas e os povos meditaram em coisas vãs?

[[v44-4-26]]

^<<v44-4-26,26>>^ Os reis da terra tomaram a sua posição, e os governantes se uniram contra Jeová^&#42;1^ e contra o seu ungido.’^&#42;2^

[NOTE]
====
. Veja Ap. A5.
. Ou: “seu Cristo”.
====

[[v44-4-27]]

^<<v44-4-27,27>>^ De fato, Herodes e Pôncio Pilatos se reuniram nesta cidade com homens das nações e com povos de Israel contra o teu santo servo Jesus, a quem ungiste,

[[v44-4-28]]

^<<v44-4-28,28>>^ para fazerem aquilo que o teu poder e a tua vontade^&#42;1^ predeterminaram que ocorresse.

[NOTE]
====
. Ou: “o teu conselho”.
====

[[v44-4-29]]

^<<v44-4-29,29>>^ E agora, Jeová,^&#42;1^ dá atenção às ameaças deles e concede que os teus escravos continuem a falar a tua palavra com toda a coragem,

[NOTE]
====
. Veja Ap. A5.
====

[[v44-4-30]]

^<<v44-4-30,30>>^ ao passo que estendes a mão para curar e ao passo que ocorrem sinais e milagres^&#42;1^ por meio do nome do teu santo servo Jesus.”

[NOTE]
====
. Ou: “portentos”.
====

[[v44-4-31]]

^<<v44-4-31,31>>^ Depois de terem feito a súplica,^&#42;1^ o lugar onde estavam reunidos tremeu, e todos ficaram cheios de espírito santo e começaram a falar a palavra de Deus com coragem.

[NOTE]
====
. Ou: “orado fervorosamente”.
====

[[v44-4-32]]

^<<v44-4-32,32>>^ Além disso, a multidão dos que creram era de um só coração e uma só alma,^&#42;1^ e nenhum deles dizia que as coisas que possuía eram suas, mas compartilhavam tudo que tinham.

[NOTE]
====
. Veja o Glossário.
====

[[v44-4-33]]

^<<v44-4-33,33>>^ E os apóstolos continuavam, de forma poderosa, a dar testemunho a respeito da ressurreição do Senhor Jesus, e todos eles eram grandemente abençoados com bondade imerecida.

[[v44-4-34]]

^<<v44-4-34,34>>^ De fato, ninguém entre eles passava necessidade, porque todos os que possuíam campos ou casas os vendiam, traziam o dinheiro da venda

[[v44-4-35]]

^<<v44-4-35,35>>^ e o colocavam aos pés dos apóstolos. Depois, fazia-se a distribuição, conforme a necessidade de cada um.

[[v44-4-36]]

^<<v44-4-36,36>>^ Assim fez José, a quem os apóstolos chamavam de Barnabé (que traduzido significa “filho do consolo”), um levita, natural de Chipre,

[[v44-4-37]]

^<<v44-4-37,37>>^ que possuía um pedaço de terra; ele o vendeu, trouxe o dinheiro e o colocou aos pés dos apóstolos.

'''

xref:044-atos/044-atos-003.adoc#v44-3-0[&#60; Capítulo Anterior] | <<v44-4-0,Topo>> | xref:044-atos/044-atos-005.adoc#v44-5-0[Próximo Capítulo &#62;]