include::./index.adoc[]

[[v44-27-0]]
=== Atos dos Apóstolos, 27
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-27-1]]

^<<v44-27-1,1>>^ Como foi decidido que navegaríamos para a Itália, Paulo e alguns outros prisioneiros foram entregues a um oficial do exército chamado Júlio, do regimento de Augusto.

[[v44-27-2]]

^<<v44-27-2,2>>^ Embarcamos em um navio de Adramítio, que estava prestes a partir para portos ao longo da costa da província da Ásia, e começamos a viagem; Aristarco, um macedônio de Tessalônica, estava conosco.

[[v44-27-3]]

^<<v44-27-3,3>>^ No dia seguinte, fizemos escala em Sídon; e Júlio tratou Paulo com bondade,^&#42;1^ permitindo que ele visitasse seus amigos e recebesse o cuidado deles.

[NOTE]
====
. Ou: “humanidade”.
====

[[v44-27-4]]

^<<v44-27-4,4>>^ Partindo dali, navegamos sob o abrigo de Chipre, porque os ventos eram contrários.

[[v44-27-5]]

^<<v44-27-5,5>>^ Então atravessamos o mar aberto ao longo da Cilícia e da Panfília, e aportamos em Mirra, na Lícia.

[[v44-27-6]]

^<<v44-27-6,6>>^ Ali o oficial do exército encontrou um navio de Alexandria que estava indo para a Itália, e nos fez embarcar nele.

[[v44-27-7]]

^<<v44-27-7,7>>^ Depois de navegarmos vagarosamente por muitos dias, chegamos com dificuldade a Cnido. Visto que o vento não nos permitia continuar naquela direção, navegamos sob o abrigo de Creta, à altura de Salmone.

[[v44-27-8]]

^<<v44-27-8,8>>^ E, costeando com dificuldade, chegamos a um lugar chamado Bons Portos, que ficava perto da cidade de Laseia.

[[v44-27-9]]

^<<v44-27-9,9>>^ Havia passado bastante tempo e agora era perigoso navegar, porque até mesmo o dia do jejum^&#42;1^ já tinha passado. Então Paulo os advertiu:

[NOTE]
====
. Isto é, do jejum do Dia da Expiação, que ocorria no mês de tisri, o início da época de chuvas e de mares agitados.
====

[[v44-27-10]]

^<<v44-27-10,10>>^ “Homens, vejo que esta viagem vai resultar em danos e em grandes perdas, não só da carga e do navio, mas também de nossas vidas.”^&#42;1^

[NOTE]
====
. Ou: “almas”.
====

[[v44-27-11]]

^<<v44-27-11,11>>^ Mas o oficial do exército, em vez de ouvir o que Paulo dizia, ouviu o piloto e o dono do navio.

[[v44-27-12]]

^<<v44-27-12,12>>^ Visto que o porto não era adequado para passar o inverno, a maioria foi da opinião de que partissem dali para ver se de algum modo conseguiam chegar a Fênix, um porto de Creta que dá para o nordeste e para o sudeste; ali poderiam passar o inverno.

[[v44-27-13]]

^<<v44-27-13,13>>^ Quando o vento sul soprou suavemente, acharam que seu objetivo já estava alcançado; então levantaram âncora e foram navegando ao longo de Creta, próximo ao litoral.

[[v44-27-14]]

^<<v44-27-14,14>>^ Porém, pouco tempo depois, veio do lado da ilha um vento violento, conhecido como euraquilão,^&#42;1^

[NOTE]
====
. Isto é, um vento nordeste.
====

[[v44-27-15]]

^<<v44-27-15,15>>^ que arrastou o navio com violência, de modo que não era possível manter a proa contra o vento; assim, desistimos e deixamos que o vento nos levasse.

[[v44-27-16]]

^<<v44-27-16,16>>^ Passamos então sob o abrigo de uma pequena ilha chamada Cauda; mesmo assim, mal conseguimos controlar o bote^&#42;1^ que trazíamos a reboque.

[NOTE]
====
. Bote auxiliar que podia servir como bote salva-vidas.
====

[[v44-27-17]]

^<<v44-27-17,17>>^ Depois de o içarem a bordo, começaram a reforçar o casco do navio, amarrando-o; então, com medo de encalhar em Sirte,^&#42;1^ arriaram o aparelho,^&#42;2^ e assim o navio foi levado pelo vento.

[NOTE]
====
. Veja o Glossário.
. Pelo visto se refere aos cabos e às vergas usados para levantar e sustentar as velas.
====

[[v44-27-18]]

^<<v44-27-18,18>>^ Como estávamos sendo violentamente sacudidos pela tempestade, no dia seguinte começaram a jogar a carga no mar.

[[v44-27-19]]

^<<v44-27-19,19>>^ E, no terceiro dia, com as próprias mãos lançaram ao mar a armação do navio.

[[v44-27-20]]

^<<v44-27-20,20>>^ Por muitos dias, o sol e as estrelas não apareceram, e uma violenta^&#42;1^ tempestade se abatia sobre nós. Então, por fim começou a desaparecer toda a esperança de sermos salvos.

[NOTE]
====
. Lit.: “não pequena”.
====

[[v44-27-21]]

^<<v44-27-21,21>>^ Depois de passarem muito tempo sem comer nada, Paulo se levantou no meio deles e disse: “Homens, certamente vocês deviam ter aceitado o meu conselho e não ter partido de Creta; assim não teriam sofrido esses danos e perdas.

[[v44-27-22]]

^<<v44-27-22,22>>^ Ainda assim, eu os incentivo agora a ter coragem, pois nenhum^&#42;1^ de vocês morrerá, apenas o navio se perderá.

[NOTE]
====
. Ou: “nenhuma alma”.
====

[[v44-27-23]]

^<<v44-27-23,23>>^ Na noite passada apareceu ao meu lado um anjo do Deus a quem pertenço e a quem presto serviço sagrado;

[[v44-27-24]]

^<<v44-27-24,24>>^ ele disse: ‘Não tenha medo, Paulo. Você tem de comparecer perante César; além disso, Deus lhe concedeu a vida de todos os que navegam com você.’

[[v44-27-25]]

^<<v44-27-25,25>>^ Portanto, homens, tenham coragem, pois eu acredito em Deus que acontecerá exatamente assim como me foi dito.

[[v44-27-26]]

^<<v44-27-26,26>>^ No entanto, devemos ser lançados em uma ilha.”

[[v44-27-27]]

^<<v44-27-27,27>>^ Era a décima quarta noite, e nós estávamos sendo jogados de um lado para o outro no mar de Ádria, quando, à meia-noite, os marinheiros começaram a suspeitar que estávamos chegando perto de terra.

[[v44-27-28]]

^<<v44-27-28,28>>^ Sondaram a profundidade e descobriram que era de 20 braças.^&#42;1^ Assim, prosseguiram por uma curta distância, sondaram-na de novo e viram que era de 15 braças.^&#42;2^

[NOTE]
====
. Cerca de 36 m. Veja Ap. B14.
. Cerca de 27 m. Veja Ap. B14.
====

[[v44-27-29]]

^<<v44-27-29,29>>^ Como estavam com medo de encalharmos nos rochedos, lançaram quatro âncoras da popa, ansiosos para que o dia amanhecesse.

[[v44-27-30]]

^<<v44-27-30,30>>^ Mas, quando os marinheiros, tentando escapar do navio, baixaram o bote ao mar com o pretexto de lançar âncoras da proa,

[[v44-27-31]]

^<<v44-27-31,31>>^ Paulo disse ao oficial do exército e aos soldados: “A menos que esses homens permaneçam no navio, vocês não poderão ser salvos.”

[[v44-27-32]]

^<<v44-27-32,32>>^ Os soldados cortaram então os cabos do bote e o deixaram cair.

[[v44-27-33]]

^<<v44-27-33,33>>^ Perto do amanhecer, Paulo encorajou todos a se alimentar, dizendo: “Hoje é o décimo quarto dia que vocês estão esperando ansiosamente, e ainda não comeram nada.

[[v44-27-34]]

^<<v44-27-34,34>>^ Assim, aconselho que se alimentem; isso é para o seu próprio bem, pois não se perderá nem um único fio de cabelo de vocês.”

[[v44-27-35]]

^<<v44-27-35,35>>^ Depois de dizer isso, ele pegou um pão, deu graças a Deus diante de todos eles, partiu-o e começou a comer.

[[v44-27-36]]

^<<v44-27-36,36>>^ Assim, todos tomaram coragem e também começaram a se alimentar.

[[v44-27-37]]

^<<v44-27-37,37>>^ Ao todo, éramos 276 pessoas^&#42;1^ no navio.

[NOTE]
====
. Ou: “almas”.
====

[[v44-27-38]]

^<<v44-27-38,38>>^ Depois de comerem o suficiente, aliviaram o navio, lançando o trigo ao mar.

[[v44-27-39]]

^<<v44-27-39,39>>^ Quando o dia amanheceu, não reconheceram aquela terra, mas viram uma baía com uma praia e decidiram que, se possível, encalhariam o navio ali.

[[v44-27-40]]

^<<v44-27-40,40>>^ Assim, cortaram os cabos das âncoras, deixaram-nas cair no mar e, ao mesmo tempo, soltaram as amarras dos lemes;^&#42;1^ depois de içarem ao vento a vela da frente, seguiram em direção à praia.

[NOTE]
====
. Ou: “remos que serviam de leme”.
====

[[v44-27-41]]

^<<v44-27-41,41>>^ Então bateram em um banco de areia que era banhado pelo mar em ambos os lados, e o navio encalhou; a proa se prendeu e ficou imóvel, mas a popa começou a ser despedaçada pelas ondas.

[[v44-27-42]]

^<<v44-27-42,42>>^ Com isso, os soldados decidiram matar os prisioneiros para que ninguém fugisse nadando.

[[v44-27-43]]

^<<v44-27-43,43>>^ Mas o oficial do exército estava determinado a salvar Paulo e os impediu de executar o plano. Ele mandou que os que sabiam nadar saltassem primeiro ao mar para alcançarem a terra

[[v44-27-44]]

^<<v44-27-44,44>>^ e que os demais fossem atrás: alguns em tábuas e outros em pedaços do navio. Assim, todos chegaram a terra sãos e salvos.

'''

xref:044-atos/044-atos-026.adoc#v44-26-0[&#60; Capítulo Anterior] | <<v44-27-0,Topo>> | xref:044-atos/044-atos-028.adoc#v44-28-0[Próximo Capítulo &#62;]