include::./index.adoc[]

[[v44-12-0]]
=== Atos dos Apóstolos, 12
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-12-1]]

^<<v44-12-1,1>>^ Naquela época, o rei Herodes começou a maltratar alguns da congregação.

[[v44-12-2]]

^<<v44-12-2,2>>^ Ele mandou matar à espada Tiago, irmão de João.

[[v44-12-3]]

^<<v44-12-3,3>>^ Ao ver que isso agradava aos judeus, prendeu também Pedro. (Isso aconteceu nos dias dos Pães sem Fermento.)

[[v44-12-4]]

^<<v44-12-4,4>>^ Ele o prendeu e o pôs na prisão, entregando-o aos cuidados de quatro turnos de soldados, com quatro soldados cada um, com a intenção de apresentá-lo ao^&#42;1^ povo depois da Páscoa.

[NOTE]
====
. Ou: “trazê-lo a julgamento diante do”.
====

[[v44-12-5]]

^<<v44-12-5,5>>^ De modo que Pedro ficou detido na prisão, mas a congregação orava intensamente a Deus por ele.

[[v44-12-6]]

^<<v44-12-6,6>>^ Herodes estava para apresentar Pedro; naquela noite, ele estava dormindo, preso com duas correntes, entre dois soldados, e em frente à porta havia guardas que vigiavam a prisão.

[[v44-12-7]]

^<<v44-12-7,7>>^ Mas, de repente, o anjo de Jeová^&#42;1^ apareceu, e uma luz brilhou na cela da prisão. Ele tocou no lado de Pedro e o acordou, dizendo: “Levante-se depressa!” E as correntes caíram das mãos dele.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-12-8]]

^<<v44-12-8,8>>^ O anjo lhe disse: “Vista-se^&#42;1^ e calce as sandálias”, e Pedro fez isso. Por fim, ele lhe disse: “Ponha a sua capa e siga-me.”

[NOTE]
====
. Ou: “Cinja-se”.
====

[[v44-12-9]]

^<<v44-12-9,9>>^ Então ele saiu e o seguiu, mas não sabia que era real aquilo que estava acontecendo por meio do anjo. Na verdade, ele achou que estava tendo uma visão.

[[v44-12-10]]

^<<v44-12-10,10>>^ Passaram pelo primeiro posto de guarda, pelo segundo, e chegaram ao portão de ferro que dava para a cidade. Ele se abriu sozinho. Depois de saírem, seguiram por uma rua e então, de repente, o anjo o deixou.

[[v44-12-11]]

^<<v44-12-11,11>>^ Pedro, percebendo o que estava acontecendo, disse: “Agora sei, sem nenhuma dúvida, que Jeová^&#42;1^ enviou seu anjo e me livrou das mãos de Herodes e de tudo o que o povo judeu esperava que acontecesse.”

[NOTE]
====
. Veja Ap. A5.
====

[[v44-12-12]]

^<<v44-12-12,12>>^ Depois que ele entendeu isso, foi à casa de Maria, mãe de João, conhecido como Marcos, onde muitos estavam reunidos, orando.

[[v44-12-13]]

^<<v44-12-13,13>>^ Quando bateu no portão de entrada, uma serva chamada Rode foi atender.

[[v44-12-14]]

^<<v44-12-14,14>>^ Ao reconhecer a voz de Pedro, ela ficou tão contente que não abriu o portão, mas correu para dentro e contou que Pedro estava no portão.

[[v44-12-15]]

^<<v44-12-15,15>>^ Disseram-lhe: “Você está louca.” Mas ela insistia que era verdade. E eles diziam: “É o anjo dele.”

[[v44-12-16]]

^<<v44-12-16,16>>^ Mas Pedro continuou ali, batendo. Quando abriram, viram-no e ficaram pasmados.

[[v44-12-17]]

^<<v44-12-17,17>>^ Então ele lhes fez sinal com a mão para que ficassem calados, contou-lhes em detalhes como Jeová^&#42;1^ o havia tirado da prisão e disse: “Contem essas coisas a Tiago e aos irmãos.” Assim, ele saiu e foi para outro lugar.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-12-18]]

^<<v44-12-18,18>>^ Quando amanheceu, houve grande confusão entre os soldados, que se perguntavam o que teria acontecido com Pedro.

[[v44-12-19]]

^<<v44-12-19,19>>^ Herodes o procurou cuidadosamente e, como não o achou, interrogou os guardas e mandou que fossem levados para punição; depois desceu da Judeia para Cesareia e passou algum tempo ali.

[[v44-12-20]]

^<<v44-12-20,20>>^ Ele estava furioso^&#42;1^ com o povo de Tiro e de Sídon. Estes, então, de comum acordo foram ao encontro dele e, depois de convencerem Blasto, o administrador da casa do rei,^&#42;2^ pediram termos de paz, porque o país do rei supria a região deles de alimento.

[NOTE]
====
. Ou: “disposto a brigar”.
. Lit.: “aquele que estava sobre o dormitório do rei”.
====

[[v44-12-21]]

^<<v44-12-21,21>>^ Num determinado dia, Herodes vestiu a roupa real, sentou-se no tribunal e começou a fazer um discurso público.

[[v44-12-22]]

^<<v44-12-22,22>>^ Então o povo que estava reunido começou a gritar: “É a voz de um deus e não de um homem!”

[[v44-12-23]]

^<<v44-12-23,23>>^ Instantaneamente o anjo de Jeová^&#42;1^ o feriu, porque não deu glória a Deus. E ele morreu comido por vermes.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-12-24]]

^<<v44-12-24,24>>^ Mas a palavra de Jeová^&#42;1^ crescia e se espalhava.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-12-25]]

^<<v44-12-25,25>>^ Quanto a Barnabé e Saulo, depois de terem terminado seu trabalho de prestar ajuda em Jerusalém, voltaram e levaram consigo João, que também era conhecido como Marcos.

'''

xref:044-atos/044-atos-011.adoc#v44-11-0[&#60; Capítulo Anterior] | <<v44-12-0,Topo>> | xref:044-atos/044-atos-013.adoc#v44-13-0[Próximo Capítulo &#62;]