include::./index.adoc[]

[[v44-24-0]]
=== Atos dos Apóstolos, 24
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-24-1]]

^<<v44-24-1,1>>^ Cinco dias depois, o sumo sacerdote Ananias desceu com alguns anciãos e um orador^&#42;1^ chamado Tértulo, e eles apresentaram ao governador queixa contra Paulo.

[NOTE]
====
. Ou: “advogado”.
====

[[v44-24-2]]

^<<v44-24-2,2>>^ Ao ser chamado, Tértulo começou a acusação, dizendo:
“Desfrutamos de grande paz por meio de Vossa Excelência, e pela sua prudência se realizam reformas nesta nação;

[[v44-24-3]]

^<<v44-24-3,3>>^ em todas as ocasiões e também em todos os lugares, nós reconhecemos isso, Excelentíssimo Félix, com muita gratidão.

[[v44-24-4]]

^<<v44-24-4,4>>^ Mas, para não tomar mais do seu tempo, solicito que, na sua bondade, nos ouça brevemente.

[[v44-24-5]]

^<<v44-24-5,5>>^ Pois nós constatamos que este homem é uma praga^&#42;1^ e atiça sedições entre todos os judeus, por toda a terra habitada, e ele é um dos líderes da seita dos nazarenos.

[NOTE]
====
. Ou: “um agitador”. Lit.: “uma peste”.
====

[[v44-24-6]]

^<<v44-24-6,6>>^ Ele também tentou profanar o templo; então nós o agarramos.

[[v44-24-7]]

^<<v44-24-7,7>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v44-24-8]]

^<<v44-24-8,8>>^ Vossa Excelência, quando o interrogar, verificará todas essas coisas de que o acusamos.”

[[v44-24-9]]

^<<v44-24-9,9>>^ Então os judeus também apoiaram a acusação, garantindo que essas coisas eram verdade.

[[v44-24-10]]

^<<v44-24-10,10>>^ Quando o governador lhe acenou com a cabeça para que falasse, Paulo respondeu:
“Sabendo muito bem que esta nação o tem como juiz há muitos anos, falo prontamente em minha defesa.

[[v44-24-11]]

^<<v44-24-11,11>>^ Como Vossa Excelência pode verificar por si mesmo, não faz mais de 12 dias que subi para adorar em Jerusalém.

[[v44-24-12]]

^<<v44-24-12,12>>^ E eles não me encontraram discutindo com ninguém no templo, nem atiçando uma turba nas sinagogas ou em outro lugar da cidade.

[[v44-24-13]]

^<<v44-24-13,13>>^ Nem podem lhe provar as acusações que estão fazendo contra mim agora.

[[v44-24-14]]

^<<v44-24-14,14>>^ Mas eu admito o seguinte: é segundo o caminho que eles chamam de seita que eu presto serviço sagrado ao Deus dos meus antepassados, crendo em tudo que está declarado na Lei e que está escrito nos Profetas.

[[v44-24-15]]

^<<v44-24-15,15>>^ E eu tenho esperança em Deus, esperança que esses homens também têm, de que haverá uma ressurreição tanto de justos como de injustos.

[[v44-24-16]]

^<<v44-24-16,16>>^ Por causa disso, eu sempre me esforço para manter uma consciência limpa^&#42;1^ diante de Deus e dos homens.

[NOTE]
====
. Ou: “irrepreensível”.
====

[[v44-24-17]]

^<<v44-24-17,17>>^ Depois de vários anos, vim a Jerusalém para trazer uma contribuição^&#42;1^ à minha nação e fazer ofertas.

[NOTE]
====
. Ou: “trazer dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-24-18]]

^<<v44-24-18,18>>^ Enquanto eu cuidava desses assuntos, eles me encontraram cerimonialmente puro no templo, mas não com uma multidão nem causando tumulto. No entanto, lá havia alguns judeus da província da Ásia

[[v44-24-19]]

^<<v44-24-19,19>>^ que deviam estar presentes diante de Vossa Excelência para me acusar, se realmente tivessem algo contra mim.

[[v44-24-20]]

^<<v44-24-20,20>>^ Ou, que estes homens aqui digam que crime acharam em mim quando eu estava perante o Sinédrio.

[[v44-24-21]]

^<<v44-24-21,21>>^ A não ser que se trate desta única frase que clamei quando estava no meio deles: ‘É por causa da ressurreição dos mortos que hoje estou sendo julgado diante dos senhores!’”

[[v44-24-22]]

^<<v44-24-22,22>>^ No entanto, visto que Félix estava bem informado a respeito desse Caminho, adiou a questão, dizendo: “Quando Lísias, o comandante militar, descer, decidirei essas questões de vocês.”

[[v44-24-23]]

^<<v44-24-23,23>>^ Ele ordenou então ao oficial do exército que o mantivesse preso, mas que lhe desse certa liberdade e permitisse que os do seu povo cuidassem de suas necessidades.

[[v44-24-24]]

^<<v44-24-24,24>>^ Alguns dias depois, Félix veio com Drusila, sua esposa, que era judia; mandou buscar Paulo e o ouviu falar sobre a crença em Cristo Jesus.

[[v44-24-25]]

^<<v44-24-25,25>>^ Mas, quando Paulo começou a falar sobre a justiça, o autodomínio e o julgamento por vir, Félix ficou com medo e disse: “Por enquanto, pode se retirar, mas, quando eu tiver uma oportunidade, mandarei buscá-lo novamente.”

[[v44-24-26]]

^<<v44-24-26,26>>^ Ao mesmo tempo, esperava que Paulo lhe desse dinheiro. Por isso mandava buscá-lo ainda mais frequentemente e conversava com ele.

[[v44-24-27]]

^<<v44-24-27,27>>^ Mas, passados dois anos, Félix foi sucedido por Pórcio Festo; e, visto que desejava ganhar o favor dos judeus, Félix deixou Paulo na prisão.

'''

xref:044-atos/044-atos-023.adoc#v44-23-0[&#60; Capítulo Anterior] | <<v44-24-0,Topo>> | xref:044-atos/044-atos-025.adoc#v44-25-0[Próximo Capítulo &#62;]