include::./index.adoc[]

[[v44-21-0]]
=== Atos dos Apóstolos, 21
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-21-1]]

^<<v44-21-1,1>>^ Quando finalmente conseguimos nos separar deles e embarcar, navegamos diretamente para Cós; no dia seguinte fomos para Rodes e dali para Pátara.

[[v44-21-2]]

^<<v44-21-2,2>>^ Ao acharmos um navio que ia fazer a travessia para a Fenícia, embarcamos e seguimos viagem.

[[v44-21-3]]

^<<v44-21-3,3>>^ Depois de avistarmos a ilha de Chipre e passarmos por ela à nossa esquerda,^&#42;1^ navegamos para a Síria e fizemos escala em Tiro, onde o navio ia descarregar.

[NOTE]
====
. Ou: “a bombordo”.
====

[[v44-21-4]]

^<<v44-21-4,4>>^ Procuramos os discípulos e os encontramos, e permanecemos ali sete dias. Mas, por meio do espírito, eles diziam repetidas vezes a Paulo que não pisasse em Jerusalém.

[[v44-21-5]]

^<<v44-21-5,5>>^ Assim, quando terminou nosso tempo ali, partimos e continuamos nossa viagem; e todos eles, junto com as mulheres e as crianças, nos acompanharam até fora da cidade. Então, ajoelhados na praia, oramos

[[v44-21-6]]

^<<v44-21-6,6>>^ e nos despedimos uns dos outros. Depois embarcamos no navio, e eles voltaram para casa.

[[v44-21-7]]

^<<v44-21-7,7>>^ Completamos então a viagem, navegando de Tiro até chegarmos a Ptolemaida; cumprimentamos os irmãos e ficamos um dia com eles.

[[v44-21-8]]

^<<v44-21-8,8>>^ Partimos no dia seguinte e chegamos a Cesareia; ali, entramos na casa de Filipe, o evangelizador, que era um dos sete homens, e ficamos com ele.

[[v44-21-9]]

^<<v44-21-9,9>>^ Esse homem tinha quatro filhas solteiras^&#42;1^ que profetizavam.

[NOTE]
====
. Lit.: “virgens”.
====

[[v44-21-10]]

^<<v44-21-10,10>>^ Depois de ficarmos ali muitos dias, um profeta chamado Ágabo desceu da Judeia.

[[v44-21-11]]

^<<v44-21-11,11>>^ Ele veio ao nosso encontro, pegou o cinto de Paulo, amarrou seus próprios pés e mãos, e disse: “Assim diz o espírito santo: ‘O homem a quem pertence este cinto será amarrado assim pelos judeus em Jerusalém, e eles o entregarão às mãos de pessoas das nações.’”

[[v44-21-12]]

^<<v44-21-12,12>>^ Quando ouvimos isso, tanto nós como os que estavam ali começamos a lhe implorar que não subisse a Jerusalém.

[[v44-21-13]]

^<<v44-21-13,13>>^ Paulo respondeu então: “O que estão fazendo, chorando e tentando enfraquecer a minha determinação?^&#42;1^ Estejam certos de que estou pronto não só para ser amarrado, mas também para morrer em Jerusalém pelo nome do Senhor Jesus.”

[NOTE]
====
. Ou: “o meu coração”.
====

[[v44-21-14]]

^<<v44-21-14,14>>^ Como não conseguimos convencê-lo, paramos de insistir^&#42;1^ e dissemos: “Seja feita a vontade de Jeová.”^&#42;2^

[NOTE]
====
. Lit.: “ficamos em silêncio”.
. Veja Ap. A5.
====

[[v44-21-15]]

^<<v44-21-15,15>>^ Então, depois daqueles dias, fizemos os preparativos e começamos a viagem para Jerusalém.

[[v44-21-16]]

^<<v44-21-16,16>>^ Alguns dos discípulos de Cesareia foram junto conosco e nos levaram à casa de Menasom, de Chipre, um dos primeiros discípulos; nós ficaríamos hospedados ali.

[[v44-21-17]]

^<<v44-21-17,17>>^ Ao chegarmos a Jerusalém, os irmãos nos receberam com alegria.

[[v44-21-18]]

^<<v44-21-18,18>>^ No dia seguinte, Paulo foi conosco encontrar Tiago, e todos os anciãos estavam presentes.

[[v44-21-19]]

^<<v44-21-19,19>>^ Ele os cumprimentou e fez um relatório detalhado sobre as coisas que Deus tinha feito entre as nações por meio do ministério dele.

[[v44-21-20]]

^<<v44-21-20,20>>^ Depois de ouvirem isso, eles começaram a glorificar a Deus, mas lhe disseram: “Você sabe, irmão, quantos milhares de judeus se tornaram crentes, e todos eles têm zelo pela Lei.

[[v44-21-21]]

^<<v44-21-21,21>>^ Mas eles ouviram falar que você está ensinando todos os judeus que vivem entre as nações a abandonar a Lei de^&#42;1^ Moisés, dizendo-lhes que não circuncidem seus filhos nem sigam os costumes estabelecidos.

[NOTE]
====
. Ou: “entre as nações uma apostasia contra”.
====

[[v44-21-22]]

^<<v44-21-22,22>>^ O que devemos fazer, então, a respeito disso? Eles certamente ficarão sabendo que você chegou.

[[v44-21-23]]

^<<v44-21-23,23>>^ Portanto, faça o que vamos lhe dizer: Há conosco quatro homens que têm um voto a cumprir.

[[v44-21-24]]

^<<v44-21-24,24>>^ Leve esses homens com você, purifique-se cerimonialmente junto com eles e cuide das despesas deles, para que tenham a cabeça raspada. Assim, todos saberão que não é verdade o que se fala sobre você, mas que você está andando corretamente e também está obedecendo à Lei.

[[v44-21-25]]

^<<v44-21-25,25>>^ Quanto aos crentes dentre as nações, enviamos a eles por escrito a nossa decisão de que devem se abster do que é sacrificado a ídolos, bem como de sangue, do que foi estrangulado^&#42;1^ e de imoralidade sexual.”^&#42;2^

[NOTE]
====
. Ou: “do que foi morto sem ser sangrado”.
. Em grego, porneía. Veja o Glossário.
====

[[v44-21-26]]

^<<v44-21-26,26>>^ Então, no dia seguinte, Paulo levou os homens consigo e se purificou cerimonialmente junto com eles; depois entrou no templo para avisar quando se completariam os dias da purificação cerimonial e seria apresentada a oferta em favor de cada um deles.

[[v44-21-27]]

^<<v44-21-27,27>>^ Quando os sete dias estavam chegando ao fim, os judeus da Ásia, vendo-o no templo, agitaram toda a multidão e o agarraram,

[[v44-21-28]]

^<<v44-21-28,28>>^ gritando: “Homens de Israel, ajudem-nos! Este é o homem que ensina a todos, em toda a parte, coisas contra o nosso povo, contra a nossa Lei e contra este lugar. E, além disso, ele até mesmo trouxe gregos ao templo e profanou este lugar santo.”

[[v44-21-29]]

^<<v44-21-29,29>>^ Pois antes tinham visto Trófimo, o efésio, na cidade com ele, e pensaram que Paulo o havia levado ao templo.

[[v44-21-30]]

^<<v44-21-30,30>>^ Toda a cidade ficou em alvoroço, e as pessoas vieram correndo em massa, agarraram Paulo, arrastaram-no para fora do templo, e, imediatamente, as portas foram fechadas.

[[v44-21-31]]

^<<v44-21-31,31>>^ Enquanto tentavam matá-lo, o comandante do regimento recebeu a notícia de que toda a cidade de Jerusalém estava em confusão.

[[v44-21-32]]

^<<v44-21-32,32>>^ Imediatamente ele pegou soldados e oficiais do exército, e desceu correndo até a multidão. Quando as pessoas viram o comandante militar e os soldados, pararam de espancar Paulo.

[[v44-21-33]]

^<<v44-21-33,33>>^ Então o comandante se aproximou, o prendeu, e mandou que ele fosse amarrado com duas correntes; depois perguntou quem era ele e o que tinha feito.

[[v44-21-34]]

^<<v44-21-34,34>>^ Mas alguns da multidão gritavam uma coisa, e outros gritavam outra. Assim, como não conseguia saber nada ao certo por causa do tumulto, mandou que ele fosse levado ao quartel.

[[v44-21-35]]

^<<v44-21-35,35>>^ Quando chegou à escada, ele teve de ser carregado pelos soldados, por causa da violência da multidão,

[[v44-21-36]]

^<<v44-21-36,36>>^ pois uma multidão de pessoas o seguia, gritando: “Matem-no!”

[[v44-21-37]]

^<<v44-21-37,37>>^ Quando estava prestes a ser levado para dentro do quartel, Paulo perguntou ao comandante: “É permitido que eu lhe diga algo?” Ele disse: “Você sabe falar grego?

[[v44-21-38]]

^<<v44-21-38,38>>^ Então você não é o egípcio que algum tempo atrás atiçou uma sedição e levou os 4.000 assassinos^&#42;1^ para o deserto?”

[NOTE]
====
. Ou: “faquistas”.
====

[[v44-21-39]]

^<<v44-21-39,39>>^ Paulo respondeu: “Na realidade, sou judeu, cidadão de Tarso, uma cidade importante da Cilícia. Portanto, peço-lhe que me permita falar ao povo.”

[[v44-21-40]]

^<<v44-21-40,40>>^ Depois de ele dar permissão, Paulo, de pé na escada, fez sinal com a mão para o povo. Fez-se um grande silêncio, e então ele se dirigiu a eles no idioma hebraico, dizendo:

'''

xref:044-atos/044-atos-020.adoc#v44-20-0[&#60; Capítulo Anterior] | <<v44-21-0,Topo>> | xref:044-atos/044-atos-022.adoc#v44-22-0[Próximo Capítulo &#62;]