include::./index.adoc[]

[[v44-8-0]]
=== Atos dos Apóstolos, 8
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-8-1]]

^<<v44-8-1,1>>^ Saulo, por sua vez, aprovava o assassinato dele.
Naquele dia começou uma grande perseguição contra a congregação em Jerusalém, e todos, exceto os apóstolos, foram espalhados pelas regiões da Judeia e de Samaria.

[[v44-8-2]]

^<<v44-8-2,2>>^ Homens devotos levaram Estêvão embora para o enterrar e fizeram grande lamentação por ele.

[[v44-8-3]]

^<<v44-8-3,3>>^ Mas Saulo começou a devastar a congregação. Ele invadia uma casa após outra, arrastando para fora tanto homens como mulheres e entregando-os à prisão.

[[v44-8-4]]

^<<v44-8-4,4>>^ No entanto, os que tinham sido espalhados saíram por aquela região declarando as boas novas da palavra.

[[v44-8-5]]

^<<v44-8-5,5>>^ Filipe desceu à cidade^&#42;1^ de Samaria e começou a pregar a eles o Cristo.

[NOTE]
====
. Ou, possivelmente: “a uma cidade”.
====

[[v44-8-6]]

^<<v44-8-6,6>>^ As multidões, unânimes, prestavam atenção ao que Filipe dizia; elas o escutavam e viam os sinais que ele realizava.

[[v44-8-7]]

^<<v44-8-7,7>>^ Pois muitos tinham espíritos impuros, e estes gritavam e saíam. Além disso, muitos paralíticos e mancos foram curados.

[[v44-8-8]]

^<<v44-8-8,8>>^ De modo que houve muita alegria naquela cidade.

[[v44-8-9]]

^<<v44-8-9,9>>^ E na cidade havia um homem chamado Simão, que antes disso havia praticado artes mágicas; ele havia deixado admirada a nação de Samaria, dizendo ser alguém grande.

[[v44-8-10]]

^<<v44-8-10,10>>^ Todos, desde o menor até o maior, davam-lhe atenção e diziam: “Este homem é o Poder de Deus, o chamado Grande Poder.”

[[v44-8-11]]

^<<v44-8-11,11>>^ Davam atenção a ele porque durante muito tempo os havia impressionado com suas artes mágicas.

[[v44-8-12]]

^<<v44-8-12,12>>^ Mas acreditaram em Filipe quando ele lhes declarou as boas novas a respeito do Reino de Deus e do nome de Jesus Cristo, e tanto homens como mulheres foram batizados.

[[v44-8-13]]

^<<v44-8-13,13>>^ O próprio Simão também se tornou crente e, depois de ser batizado, continuou com Filipe. E ele se admirava ao ver sinais e grandes obras poderosas.

[[v44-8-14]]

^<<v44-8-14,14>>^ Quando os apóstolos em Jerusalém ouviram dizer que Samaria havia aceitado a palavra de Deus, enviaram para lá Pedro e João,

[[v44-8-15]]

^<<v44-8-15,15>>^ e estes desceram e oraram para que os samaritanos recebessem espírito santo.

[[v44-8-16]]

^<<v44-8-16,16>>^ Porque o espírito santo ainda não tinha vindo sobre nenhum deles, mas eles só haviam sido batizados em nome do Senhor Jesus.

[[v44-8-17]]

^<<v44-8-17,17>>^ Então lhes impuseram as mãos, e eles começaram a receber espírito santo.

[[v44-8-18]]

^<<v44-8-18,18>>^ Quando Simão viu que o espírito era dado pela imposição das mãos dos apóstolos, ofereceu-lhes dinheiro,

[[v44-8-19]]

^<<v44-8-19,19>>^ dizendo: “Deem essa autoridade também a mim, para que todo aquele sobre quem eu impuser as mãos receba espírito santo.”

[[v44-8-20]]

^<<v44-8-20,20>>^ Mas Pedro lhe disse: “Pereça com você a sua prata, porque você pensou que poderia obter o dom^&#42;1^ de Deus com dinheiro.

[NOTE]
====
. Ou: “a dádiva gratuita”.
====

[[v44-8-21]]

^<<v44-8-21,21>>^ Você não pode ter nenhuma participação nisso, porque o seu coração não é reto à vista de Deus.

[[v44-8-22]]

^<<v44-8-22,22>>^ Portanto, arrependa-se dessa sua maldade e suplique a Jeová^&#42;1^ que, se possível, a má intenção do seu coração seja perdoada,

[NOTE]
====
. Veja Ap. A5.
====

[[v44-8-23]]

^<<v44-8-23,23>>^ pois vejo que você é um veneno amargo^&#42;1^ e um escravo da injustiça.”

[NOTE]
====
. Lit.: “fel de amargura”.
====

[[v44-8-24]]

^<<v44-8-24,24>>^ Simão respondeu a eles: “Façam súplicas a Jeová^&#42;1^ por mim, para que nenhuma dessas coisas que vocês disseram venha sobre mim.”

[NOTE]
====
. Veja Ap. A5.
====

[[v44-8-25]]

^<<v44-8-25,25>>^ Portanto, depois de darem testemunho de forma cabal e falarem a palavra de Jeová,^&#42;1^ partiram de volta para Jerusalém, declarando as boas novas a muitas aldeias dos samaritanos.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-8-26]]

^<<v44-8-26,26>>^ No entanto, o anjo de Jeová^&#42;1^ disse a Filipe: “Prepare-se e vá para o sul, para a estrada que desce de Jerusalém a Gaza.” (Essa é a estrada do deserto.)

[NOTE]
====
. Veja Ap. A5.
====

[[v44-8-27]]

^<<v44-8-27,27>>^ Em vista disso, ele se preparou e foi; encontrou então um eunuco^&#42;1^ etíope, alto funcionário de Candace, rainha dos etíopes, encarregado de todo o tesouro dela. Ele tinha ido a Jerusalém para adorar

[NOTE]
====
. Ou: “oficial da corte”.
====

[[v44-8-28]]

^<<v44-8-28,28>>^ e estava voltando e, sentado no seu carro, lia em voz alta o profeta Isaías.

[[v44-8-29]]

^<<v44-8-29,29>>^ De modo que o espírito disse a Filipe: “Vá, aproxime-se desse carro.”

[[v44-8-30]]

^<<v44-8-30,30>>^ Filipe correu ao lado do carro e ouviu o eunuco lendo o profeta Isaías em voz alta. Perguntou então: “O senhor entende o que está lendo?”

[[v44-8-31]]

^<<v44-8-31,31>>^ Ele respondeu: “Na verdade, como posso entender a menos que alguém me oriente?” E pediu que Filipe subisse e se sentasse com ele.

[[v44-8-32]]

^<<v44-8-32,32>>^ A passagem das Escrituras que ele estava lendo em voz alta era: “Como uma ovelha, ele foi levado ao abate e, como um cordeiro que fica em silêncio diante do seu tosquiador, ele não abre a boca.

[[v44-8-33]]

^<<v44-8-33,33>>^ Durante a sua humilhação, negaram-lhe a justiça. Quem contará os detalhes da sua geração?^&#42;1^ Porque a sua vida é eliminada da terra.”

[NOTE]
====
. Ou: “origem”.
====

[[v44-8-34]]

^<<v44-8-34,34>>^ O eunuco disse então a Filipe: “Por favor, diga-me: De quem o profeta está falando? De si mesmo ou de outro homem?”

[[v44-8-35]]

^<<v44-8-35,35>>^ Filipe começou a falar e, partindo daquela passagem das Escrituras, declarou-lhe as boas novas a respeito de Jesus.

[[v44-8-36]]

^<<v44-8-36,36>>^ Ao seguirem pela estrada, chegaram a um lugar onde havia água, e o eunuco disse: “Veja! Aqui há água! O que me impede de ser batizado?”

[[v44-8-37]]

^<<v44-8-37,37>>^ ^&#42;1^——

[NOTE]
====
. Veja Ap. A3.
====

[[v44-8-38]]

^<<v44-8-38,38>>^ Assim, mandou parar o carro, e tanto Filipe como o eunuco desceram à água; e ele o batizou.

[[v44-8-39]]

^<<v44-8-39,39>>^ Depois de saírem da água, o espírito de Jeová^&#42;1^ rapidamente levou Filipe embora dali, e o eunuco não voltou a vê-lo, mas seguiu caminho cheio de alegria.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-8-40]]

^<<v44-8-40,40>>^ Filipe, no entanto, foi parar em Asdode e, ao passar por aquela região, continuou a declarar as boas novas a todas as cidades, até chegar a Cesareia.

'''

xref:044-atos/044-atos-007.adoc#v44-7-0[&#60; Capítulo Anterior] | <<v44-8-0,Topo>> | xref:044-atos/044-atos-009.adoc#v44-9-0[Próximo Capítulo &#62;]