include::./index.adoc[]

[[v44-9-0]]
=== Atos dos Apóstolos, 9
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-9-1]]

^<<v44-9-1,1>>^ Saulo, porém, respirando ainda ameaça e morte contra os discípulos do Senhor, foi ao sumo sacerdote

[[v44-9-2]]

^<<v44-9-2,2>>^ e lhe pediu cartas dirigidas às sinagogas em Damasco, a fim de que pudesse levar amarrados para Jerusalém todos os que encontrasse que pertenciam ao Caminho, tanto homens como mulheres.

[[v44-9-3]]

^<<v44-9-3,3>>^ Durante a viagem, quando ele se aproximava de Damasco, de repente brilhou em volta dele uma luz vinda do céu,

[[v44-9-4]]

^<<v44-9-4,4>>^ e ele caiu no chão e ouviu uma voz lhe dizer: “Saulo, Saulo, por que você me persegue?”

[[v44-9-5]]

^<<v44-9-5,5>>^ Ele perguntou: “Quem é o senhor?” Ele respondeu: “Eu sou Jesus, a quem você persegue.

[[v44-9-6]]

^<<v44-9-6,6>>^ Mas levante-se, entre na cidade, e lá dirão a você o que deve fazer.”

[[v44-9-7]]

^<<v44-9-7,7>>^ E os homens que viajavam com ele ficaram parados sem fala e realmente ouviram o som de uma voz, mas não viram ninguém.

[[v44-9-8]]

^<<v44-9-8,8>>^ Saulo então se levantou do chão, e, embora seus olhos estivessem abertos, não conseguia ver nada. De modo que o pegaram pela mão e o levaram a Damasco.

[[v44-9-9]]

^<<v44-9-9,9>>^ Ele não viu nada por três dias, e não comeu nem bebeu.

[[v44-9-10]]

^<<v44-9-10,10>>^ Em Damasco havia um discípulo chamado Ananias, e o Senhor lhe disse numa visão: “Ananias!” Ele respondeu: “Aqui estou, Senhor.”

[[v44-9-11]]

^<<v44-9-11,11>>^ O Senhor lhe disse: “Prepare-se e vá à rua chamada Direita; na casa de Judas, procure um homem chamado Saulo, de Tarso. Pois agora mesmo ele está orando

[[v44-9-12]]

^<<v44-9-12,12>>^ e, numa visão, viu um homem chamado Ananias entrar e pôr as mãos sobre ele, para que recuperasse a vista.”

[[v44-9-13]]

^<<v44-9-13,13>>^ Mas Ananias respondeu: “Senhor, eu ouvi muitos falarem desse homem, de todo o mal que ele fez aos seus santos em Jerusalém.

[[v44-9-14]]

^<<v44-9-14,14>>^ E aqui ele tem autoridade dada pelos principais sacerdotes para prender^&#42;1^ a todos os que invocam o nome do senhor.”

[NOTE]
====
. Lit.: “acorrentar; pôr em correntes”.
====

[[v44-9-15]]

^<<v44-9-15,15>>^ Mas o Senhor lhe disse: “Vá, porque esse homem é para mim um vaso escolhido para levar o meu nome às nações, bem como a reis e aos filhos de Israel.

[[v44-9-16]]

^<<v44-9-16,16>>^ Pois eu mostrarei claramente a ele quantas coisas ele terá de sofrer pelo meu nome.”

[[v44-9-17]]

^<<v44-9-17,17>>^ Assim, Ananias foi; entrou na casa, pôs as mãos sobre ele e disse: “Saulo, irmão, o Senhor Jesus, que lhe apareceu na estrada por onde você vinha, me enviou para que você recupere a vista e fique cheio de espírito santo.”

[[v44-9-18]]

^<<v44-9-18,18>>^ Imediatamente caíram dos olhos dele o que pareciam escamas, e ele recuperou a vista. Ele então se levantou, foi batizado,

[[v44-9-19]]

^<<v44-9-19,19>>^ se alimentou e recuperou as forças.
Ele ficou alguns dias com os discípulos em Damasco

[[v44-9-20]]

^<<v44-9-20,20>>^ e imediatamente, nas sinagogas, começou a pregar sobre Jesus, que ele é o Filho de Deus.

[[v44-9-21]]

^<<v44-9-21,21>>^ Mas todos os que o ouviam ficavam pasmados, e diziam: “Não é este o homem que perseguia ferozmente em Jerusalém os que invocavam esse nome? Ele não veio para cá com o objetivo de prendê-los e levá-los^&#42;1^ aos principais sacerdotes?”

[NOTE]
====
. Lit.: “de levá-los acorrentados”.
====

[[v44-9-22]]

^<<v44-9-22,22>>^ No entanto, Saulo se fortalecia cada vez mais e deixava perplexos os judeus que moravam em Damasco, ao provar de forma lógica que Jesus é o Cristo.

[[v44-9-23]]

^<<v44-9-23,23>>^ Então, depois de se passarem muitos dias, os judeus tramaram matá-lo.

[[v44-9-24]]

^<<v44-9-24,24>>^ No entanto, Saulo ficou sabendo dessa trama contra ele. Eles também vigiavam atentamente os portões, dia e noite, a fim de matá-lo.

[[v44-9-25]]

^<<v44-9-25,25>>^ De modo que seus discípulos o levaram e, de noite, o fizeram descer num cesto por uma abertura na muralha.

[[v44-9-26]]

^<<v44-9-26,26>>^ Ao chegar a Jerusalém, ele tentou se juntar aos discípulos, mas todos estavam com medo dele, porque não acreditavam que fosse discípulo.

[[v44-9-27]]

^<<v44-9-27,27>>^ De modo que Barnabé foi ajudá-lo e o levou aos apóstolos; então lhes contou em detalhes como, na estrada, Saulo tinha visto o Senhor, como o Senhor tinha falado com ele, e como em Damasco Saulo havia falado corajosamente no nome de Jesus.

[[v44-9-28]]

^<<v44-9-28,28>>^ Então Saulo permaneceu com eles, andando livremente^&#42;1^ em Jerusalém e falando corajosamente no nome do Senhor.

[NOTE]
====
. Lit.: “entrando e saindo”.
====

[[v44-9-29]]

^<<v44-9-29,29>>^ Ele falava e discutia com os judeus de língua grega, mas estes tentavam matá-lo.

[[v44-9-30]]

^<<v44-9-30,30>>^ Quando os irmãos descobriram isso, levaram-no para baixo, a Cesareia, e o enviaram a Tarso.

[[v44-9-31]]

^<<v44-9-31,31>>^ Então a congregação por toda a Judeia, Galileia e Samaria entrou num período de paz, e era edificada. E, como andava no temor de Jeová^&#42;1^ e no consolo do espírito santo, se multiplicava.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-9-32]]

^<<v44-9-32,32>>^ Visto que Pedro estava viajando por toda a região, desceu também para visitar os santos que moravam em Lida.

[[v44-9-33]]

^<<v44-9-33,33>>^ Ali ele encontrou um homem chamado Eneias, que já por oito anos estava confinado à cama, pois era paralítico.

[[v44-9-34]]

^<<v44-9-34,34>>^ Pedro lhe disse: “Eneias, Jesus Cristo cura você. Levante-se e arrume a sua cama.” Ele se levantou imediatamente.

[[v44-9-35]]

^<<v44-9-35,35>>^ Quando todos os que moravam em Lida e na planície de Sarom o viram, converteram-se ao Senhor.

[[v44-9-36]]

^<<v44-9-36,36>>^ Em Jope havia uma discípula chamada Tabita, nome que traduzido é Dorcas.^&#42;1^ Eram muitas as boas obras que ela fazia e a ajuda que dava aos pobres.^&#42;2^

[NOTE]
====
. Tanto o nome grego Dorcas como o nome aramaico Tabita significam “gazela”.
. Ou: “e as suas dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-9-37]]

^<<v44-9-37,37>>^ Mas naqueles dias ela adoeceu e morreu. Então a lavaram e a colocaram numa sala do andar de cima.

[[v44-9-38]]

^<<v44-9-38,38>>^ Como Jope ficava perto de Lida, quando os discípulos ouviram que Pedro estava nesta cidade, enviaram a ele dois homens para lhe pedir: “Por favor, venha sem demora.”

[[v44-9-39]]

^<<v44-9-39,39>>^ Em vista disso, Pedro se aprontou e foi com eles. Ao chegar, levaram-no à sala do andar de cima, e todas as viúvas o rodearam, chorando e mostrando muitas capas^&#42;1^ e outras roupas que Dorcas havia feito enquanto estava com elas.

[NOTE]
====
. Ou: “roupas exteriores”.
====

[[v44-9-40]]

^<<v44-9-40,40>>^ Pedro mandou então que todos saíssem e, ajoelhando-se, orou. Depois, virando-se para o corpo, disse: “Tabita, levante-se!” Ela abriu os olhos e, ao ver Pedro, se sentou.

[[v44-9-41]]

^<<v44-9-41,41>>^ Pegando-a pela mão, ele a levantou; então chamou os santos e as viúvas, e a apresentou viva.

[[v44-9-42]]

^<<v44-9-42,42>>^ Toda a cidade de Jope soube disso, e muitos se tornaram crentes no Senhor.

[[v44-9-43]]

^<<v44-9-43,43>>^ E ele ficou muitos dias em Jope, com um curtidor de couro chamado Simão.

'''

xref:044-atos/044-atos-008.adoc#v44-8-0[&#60; Capítulo Anterior] | <<v44-9-0,Topo>> | xref:044-atos/044-atos-010.adoc#v44-10-0[Próximo Capítulo &#62;]