include::./index.adoc[]

[[v44-3-0]]
=== Atos dos Apóstolos, 3
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-3-1]]

^<<v44-3-1,1>>^ Pedro e João estavam subindo ao templo para a hora da oração, a nona hora,^&#42;1^

[NOTE]
====
. Isto é, por volta das 3 h da tarde.
====

[[v44-3-2]]

^<<v44-3-2,2>>^ e um homem manco de nascença estava sendo carregado. Todos os dias ele era colocado perto do portão do templo chamado Portão Belo, para que pudesse pedir esmolas^&#42;1^ aos que entravam no templo.

[NOTE]
====
. Ou: “dádivas de misericórdia”. Veja o Glossário, “Dádivas de misericórdia”.
====

[[v44-3-3]]

^<<v44-3-3,3>>^ Quando ele viu Pedro e João entrando no templo, começou a pedir esmolas.

[[v44-3-4]]

^<<v44-3-4,4>>^ Mas Pedro e João olharam diretamente para ele, e Pedro disse: “Olhe para nós.”

[[v44-3-5]]

^<<v44-3-5,5>>^ De modo que ele fixou a atenção neles, esperando receber alguma coisa.

[[v44-3-6]]

^<<v44-3-6,6>>^ No entanto, Pedro disse: “Não possuo prata nem ouro, mas o que tenho é o que lhe dou. Em nome de Jesus Cristo, o Nazareno, ande!”

[[v44-3-7]]

^<<v44-3-7,7>>^ Assim, ele o segurou pela mão direita e o levantou. Instantaneamente os seus pés e os seus tornozelos ficaram firmes,

[[v44-3-8]]

^<<v44-3-8,8>>^ e num salto ele se pôs de pé, começou a andar e entrou com eles no templo, andando, pulando e louvando a Deus.

[[v44-3-9]]

^<<v44-3-9,9>>^ E todos o viram andando e louvando a Deus.

[[v44-3-10]]

^<<v44-3-10,10>>^ E eles o reconheceram como o homem que se sentava esperando por esmolas no Portão Belo do templo, e foram tomados de admiração e êxtase com o que lhe tinha acontecido.

[[v44-3-11]]

^<<v44-3-11,11>>^ O homem ainda segurava Pedro e João quando toda a multidão, extremamente surpresa, correu ao encontro deles no chamado Pórtico^&#42;1^ de Salomão.

[NOTE]
====
. Ou: “na chamada Colunata”.
====

[[v44-3-12]]

^<<v44-3-12,12>>^ Quando Pedro viu isso, disse à multidão: “Homens de Israel, por que vocês estão tão admirados com isso e por que estão olhando para nós como se o tivéssemos feito andar por meio de nosso próprio poder ou de nossa devoção a Deus?

[[v44-3-13]]

^<<v44-3-13,13>>^ O Deus de Abraão, de Isaque e de Jacó, o Deus de nossos antepassados, glorificou o seu Servo, Jesus, aquele que vocês entregaram e negaram diante de Pilatos, embora ele tivesse decidido soltá-lo.

[[v44-3-14]]

^<<v44-3-14,14>>^ Sim, vocês negaram aquele homem santo e justo; pediram que fosse entregue a vocês um homem que era assassino,

[[v44-3-15]]

^<<v44-3-15,15>>^ ao passo que mataram o Agente Principal da vida. Mas Deus o levantou dentre os mortos, e disso nós somos testemunhas.

[[v44-3-16]]

^<<v44-3-16,16>>^ E foi por meio do nome dele, e pela nossa fé no nome dele, que este homem que vocês veem e conhecem ficou forte. A fé que vem por meio de Jesus tornou este homem completamente são diante de todos vocês.

[[v44-3-17]]

^<<v44-3-17,17>>^ E agora, irmãos, sei que vocês agiram em ignorância, como também os seus líderes.

[[v44-3-18]]

^<<v44-3-18,18>>^ Mas desse modo Deus cumpriu o que anunciou antecipadamente pela boca de todos os profetas: o seu Cristo havia de sofrer.

[[v44-3-19]]

^<<v44-3-19,19>>^ “Arrependam-se, portanto, e deem meia-volta, a fim de que os seus pecados sejam apagados, para que venham tempos de refrigério da parte de Jeová^&#42;1^

[NOTE]
====
. Lit.: “da parte da face de Jeová”. Veja Ap. A5.
====

[[v44-3-20]]

^<<v44-3-20,20>>^ e ele envie o Cristo que lhes foi designado, Jesus.

[[v44-3-21]]

^<<v44-3-21,21>>^ A este, o céu tem de reter até o tempo do restabelecimento de todas as coisas, das quais Deus falou pela boca dos seus santos profetas da antiguidade.

[[v44-3-22]]

^<<v44-3-22,22>>^ Realmente Moisés disse: ‘Jeová,^&#42;1^ seu Deus, fará surgir para vocês, dentre os seus irmãos, um profeta semelhante a mim. Escutem tudo que ele lhes disser.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-3-23]]

^<<v44-3-23,23>>^ Sim, todo aquele^&#42;1^ que não escutar esse Profeta será completamente destruído dentre o povo.’

[NOTE]
====
. Ou: “toda alma”.
====

[[v44-3-24]]

^<<v44-3-24,24>>^ E todos os profetas que falaram, desde Samuel em diante, também anunciaram claramente estes dias.

[[v44-3-25]]

^<<v44-3-25,25>>^ Vocês são filhos dos profetas e do pacto que Deus fez com os antepassados de vocês, quando disse a Abraão: ‘E todas as famílias da terra serão abençoadas por meio do seu descendente.’^&#42;1^

[NOTE]
====
. Lit.: “semente”.
====

[[v44-3-26]]

^<<v44-3-26,26>>^ Depois de fazer surgir o seu Servo, Deus o enviou primeiro a vocês para abençoá-los, ao afastar cada um de vocês das suas ações más.”

'''

xref:044-atos/044-atos-002.adoc#v44-2-0[&#60; Capítulo Anterior] | <<v44-3-0,Topo>> | xref:044-atos/044-atos-004.adoc#v44-4-0[Próximo Capítulo &#62;]