include::./index.adoc[]

[[v44-25-0]]
=== Atos dos Apóstolos, 25
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-25-1]]

^<<v44-25-1,1>>^ Então, três dias depois de chegar à província e assumir o governo, Festo subiu de Cesareia a Jerusalém.

[[v44-25-2]]

^<<v44-25-2,2>>^ E os principais sacerdotes e os homens mais importantes dos judeus lhe apresentaram acusações contra Paulo. Começaram a pedir insistentemente a Festo

[[v44-25-3]]

^<<v44-25-3,3>>^ que lhes fizesse o favor^&#42;1^ de mandar trazer Paulo para Jerusalém. Mas eles estavam armando uma emboscada para matá-lo na estrada.

[NOTE]
====
. Lit.: “pedindo um favor contra ele”.
====

[[v44-25-4]]

^<<v44-25-4,4>>^ No entanto, Festo respondeu que Paulo deveria continuar detido em Cesareia e que ele mesmo voltaria para lá em breve.

[[v44-25-5]]

^<<v44-25-5,5>>^ “Portanto”, disse ele, “desçam comigo alguns dos líderes de vocês e o acusem, se é que o homem fez alguma coisa errada”.

[[v44-25-6]]

^<<v44-25-6,6>>^ Assim, depois de passar não mais do que oito ou dez dias entre eles, ele desceu a Cesareia e, no dia seguinte, se sentou no tribunal e mandou que trouxessem Paulo.

[[v44-25-7]]

^<<v44-25-7,7>>^ Quando Paulo entrou, os judeus que tinham descido de Jerusalém o rodearam, fazendo muitas acusações graves contra ele, que não podiam provar.

[[v44-25-8]]

^<<v44-25-8,8>>^ Mas Paulo disse em sua defesa: “Não cometi nenhum pecado contra a Lei dos judeus, nem contra o templo, nem contra César.”

[[v44-25-9]]

^<<v44-25-9,9>>^ Festo, querendo ganhar o favor dos judeus, disse a Paulo, em resposta: “Você deseja subir a Jerusalém e ser julgado ali, diante de mim, a respeito dessas coisas?”

[[v44-25-10]]

^<<v44-25-10,10>>^ Mas Paulo disse: “Estou perante o tribunal de César, onde devo ser julgado. Não fiz nada de errado contra os judeus, como Vossa Excelência está percebendo muito bem.

[[v44-25-11]]

^<<v44-25-11,11>>^ Se eu sou realmente criminoso e fiz algo que mereça a morte, não me recuso a morrer; mas, se as acusações que esses homens fazem contra mim são infundadas, ninguém tem o direito de me entregar a eles como um favor. Apelo para César!”

[[v44-25-12]]

^<<v44-25-12,12>>^ Então, depois de falar com o grupo de conselheiros, Festo respondeu: “Você apelou para César, para César irá.”

[[v44-25-13]]

^<<v44-25-13,13>>^ Depois de alguns dias, o rei Agripa e Berenice chegaram a Cesareia para fazer uma visita de cortesia a Festo.

[[v44-25-14]]

^<<v44-25-14,14>>^ Visto que iam passar vários dias ali, Festo apresentou ao rei o caso de Paulo, dizendo:
“Há um homem que Félix deixou como prisioneiro;

[[v44-25-15]]

^<<v44-25-15,15>>^ quando estive em Jerusalém, os principais sacerdotes e os anciãos dos judeus me trouxeram informações sobre ele e pediram que ele fosse condenado.

[[v44-25-16]]

^<<v44-25-16,16>>^ Mas eu lhes respondi que não é procedimento romano entregar um acusado antes que ele se encontre face a face com os seus acusadores e tenha a oportunidade de se defender da acusação.

[[v44-25-17]]

^<<v44-25-17,17>>^ Assim, quando chegaram aqui, no dia seguinte sem demora sentei no tribunal e mandei que trouxessem o homem.

[[v44-25-18]]

^<<v44-25-18,18>>^ Quando os acusadores se levantaram para falar, não o acusaram de nenhuma das coisas más que eu havia imaginado.

[[v44-25-19]]

^<<v44-25-19,19>>^ Eles simplesmente tinham divergências com ele sobre a sua própria religião^&#42;1^ e sobre um homem chamado Jesus, que morreu, mas que Paulo insistia que estava vivo.

[NOTE]
====
. Ou: “adoração da divindade”.
====

[[v44-25-20]]

^<<v44-25-20,20>>^ Sem saber como lidar com essa controvérsia, eu perguntei se ele gostaria de ir a Jerusalém e ser julgado ali a respeito dessas questões.

[[v44-25-21]]

^<<v44-25-21,21>>^ Mas, quando Paulo apelou para continuar em detenção e aguardar a decisão de Augusto,^&#42;1^ mandei que ele ficasse preso até que eu o enviasse a César.”

[NOTE]
====
. Título do imperador romano.
====

[[v44-25-22]]

^<<v44-25-22,22>>^ Então Agripa disse a Festo: “Eu mesmo gostaria de ouvir o homem.” “Amanhã o ouvirá”, disse ele.

[[v44-25-23]]

^<<v44-25-23,23>>^ Assim, no dia seguinte, Agripa e Berenice chegaram com grande pompa e entraram na sala de audiências, junto com comandantes militares e homens importantes da cidade. E, quando Festo deu a ordem, trouxeram Paulo.

[[v44-25-24]]

^<<v44-25-24,24>>^ Festo disse: “Rei Agripa e todos os aqui presentes, podem ver este homem a respeito de quem toda a comunidade judaica fez petições a mim, tanto em Jerusalém como aqui, gritando que ele não deveria mais viver.

[[v44-25-25]]

^<<v44-25-25,25>>^ Mas eu percebi que ele não tinha feito nada que merecesse a morte. Assim, quando ele mesmo apelou para Augusto, decidi enviá-lo.

[[v44-25-26]]

^<<v44-25-26,26>>^ Mas não tenho nada definido para escrever ao meu Senhor a respeito dele. Portanto, eu o trouxe diante dos senhores, e especialmente de Vossa Majestade, rei Agripa, para que, depois do interrogatório, eu tenha algo para escrever.

[[v44-25-27]]

^<<v44-25-27,27>>^ Pois não me parece razoável enviar um prisioneiro sem indicar também as acusações contra ele.”

'''

xref:044-atos/044-atos-024.adoc#v44-24-0[&#60; Capítulo Anterior] | <<v44-25-0,Topo>> | xref:044-atos/044-atos-026.adoc#v44-26-0[Próximo Capítulo &#62;]