include::./index.adoc[]

[[v44-16-0]]
=== Atos dos Apóstolos, 16
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-16-1]]

^<<v44-16-1,1>>^ Então ele chegou a Derbe e a Listra. Havia ali um discípulo chamado Timóteo, filho de uma mulher judia crente, mas de pai grego,

[[v44-16-2]]

^<<v44-16-2,2>>^ e os irmãos em Listra e em Icônio falavam bem dele.

[[v44-16-3]]

^<<v44-16-3,3>>^ Paulo quis que Timóteo o acompanhasse e o circuncidou por causa dos judeus daqueles lugares, pois todos sabiam que seu pai era grego.

[[v44-16-4]]

^<<v44-16-4,4>>^ Ao viajarem pelas cidades, transmitiam aos irmãos as decisões tomadas pelos apóstolos e pelos anciãos em Jerusalém, para que obedecessem a esses decretos.

[[v44-16-5]]

^<<v44-16-5,5>>^ Assim, as congregações eram fortalecidas na fé e cresciam a cada dia.

[[v44-16-6]]

^<<v44-16-6,6>>^ Eles viajaram pela Frígia e pela região da Galácia, porque o espírito santo os havia proibido de falar a palavra na província da Ásia.

[[v44-16-7]]

^<<v44-16-7,7>>^ Além disso, quando desceram à Mísia, tentaram entrar na Bitínia, mas o espírito de Jesus não lhes permitiu fazer isso.

[[v44-16-8]]

^<<v44-16-8,8>>^ De modo que passaram pela^&#42;1^ Mísia e desceram a Trôade.

[NOTE]
====
. Ou: “atravessaram a”.
====

[[v44-16-9]]

^<<v44-16-9,9>>^ Durante a noite, Paulo teve uma visão: um macedônio estava em pé suplicando-lhe: “Venha para a Macedônia e ajude-nos.”

[[v44-16-10]]

^<<v44-16-10,10>>^ Logo depois que ele teve a visão, procuramos ir à Macedônia, concluindo que Deus havia nos chamado para lhes declarar as boas novas.

[[v44-16-11]]

^<<v44-16-11,11>>^ Assim, embarcamos em Trôade e fomos diretamente para a Samotrácia, mas, no dia seguinte, fomos para Neápolis;

[[v44-16-12]]

^<<v44-16-12,12>>^ dali fomos para Filipos, colônia romana e cidade principal da região da Macedônia. Ficamos nessa cidade por alguns dias.

[[v44-16-13]]

^<<v44-16-13,13>>^ No dia de sábado, saímos pelo portão da cidade e fomos para junto de um rio, pois pensávamos que ali havia um lugar de oração. Então nos sentamos e começamos a falar com as mulheres que haviam se reunido ali.

[[v44-16-14]]

^<<v44-16-14,14>>^ Uma mulher estava escutando: ela se chamava Lídia, era vendedora de púrpura, da cidade de Tiatira, e adoradora de Deus. E Jeová^&#42;1^ lhe abriu amplamente o coração para prestar atenção ao que Paulo estava falando.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-16-15]]

^<<v44-16-15,15>>^ Então, depois que ela e os da sua casa foram batizados, ela insistiu: “Se vocês me consideram fiel a Jeová,^&#42;1^ venham ficar na minha casa.” E ela simplesmente nos fez ir.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-16-16]]

^<<v44-16-16,16>>^ Um dia, quando íamos para o lugar de oração, veio ao nosso encontro uma serva que tinha um espírito, um demônio de adivinhação. Ela dava muito lucro aos seus senhores adivinhando o futuro.^&#42;1^

[NOTE]
====
. Ou: “praticando a arte da predição”.
====

[[v44-16-17]]

^<<v44-16-17,17>>^ Essa moça seguia Paulo e a nós, gritando: “Estes homens são escravos do Deus Altíssimo e estão proclamando a vocês o caminho da salvação.”

[[v44-16-18]]

^<<v44-16-18,18>>^ Ela fez isso por muitos dias. Por fim, Paulo ficou cansado daquilo, virou-se e disse ao espírito: “Ordeno-lhe em nome de Jesus Cristo que saia dela.” E o espírito saiu na mesma hora.

[[v44-16-19]]

^<<v44-16-19,19>>^ Quando os senhores dela viram que sua esperança de lucro havia acabado, agarraram Paulo e Silas e os arrastaram até a praça principal,^&#42;1^ às autoridades.

[NOTE]
====
. Área aberta usada como centro de compras e vendas e como local de reuniões públicas.
====

[[v44-16-20]]

^<<v44-16-20,20>>^ Levaram-nos aos magistrados civis e disseram: “Estes homens estão perturbando muito a nossa cidade. São judeus

[[v44-16-21]]

^<<v44-16-21,21>>^ e estão divulgando costumes que não nos é permitido^&#42;1^ adotar ou praticar, visto que somos romanos.”

[NOTE]
====
. Ou: “lícito”.
====

[[v44-16-22]]

^<<v44-16-22,22>>^ E toda a multidão se levantou contra eles; então os magistrados civis lhes arrancaram as roupas e mandaram que fossem espancados com varas.

[[v44-16-23]]

^<<v44-16-23,23>>^ Depois de lhes baterem muito, os lançaram na prisão e ordenaram ao carcereiro que os guardasse com segurança.

[[v44-16-24]]

^<<v44-16-24,24>>^ Recebendo essa ordem, ele os lançou na prisão interior e prendeu os pés deles no tronco.

[[v44-16-25]]

^<<v44-16-25,25>>^ Mas, por volta da meia-noite, Paulo e Silas estavam orando e louvando a Deus com cânticos, e os prisioneiros os ouviam.

[[v44-16-26]]

^<<v44-16-26,26>>^ De repente, houve um terremoto tão grande que os alicerces da cadeia foram abalados. Nesse instante, todas as portas se abriram e as correntes de todos se soltaram.

[[v44-16-27]]

^<<v44-16-27,27>>^ Quando o carcereiro acordou e viu que as portas da prisão estavam abertas, ele puxou sua espada e ia se matar, pensando que os prisioneiros tinham escapado.

[[v44-16-28]]

^<<v44-16-28,28>>^ Mas Paulo gritou: “Não faça nenhum mal a si mesmo, pois estamos todos aqui!”

[[v44-16-29]]

^<<v44-16-29,29>>^ Assim, ele pediu que lhe trouxessem uma luz, entrou correndo e, tremendo, prostrou-se diante de Paulo e Silas.

[[v44-16-30]]

^<<v44-16-30,30>>^ Ele os levou para fora e perguntou: “Senhores, o que tenho de fazer para ser salvo?”

[[v44-16-31]]

^<<v44-16-31,31>>^ Eles responderam: “Creia no Senhor Jesus e será salvo, você e os da sua casa.”

[[v44-16-32]]

^<<v44-16-32,32>>^ E falaram a palavra de Jeová^&#42;1^ a ele e a todos os da sua casa.

[NOTE]
====
. Veja Ap. A5.
====

[[v44-16-33]]

^<<v44-16-33,33>>^ Ele os levou consigo naquela hora da noite e lavou seus ferimentos. Então ele e todos os da sua casa foram batizados sem demora.

[[v44-16-34]]

^<<v44-16-34,34>>^ Ele os levou à sua casa e pôs a mesa para eles, e ele e todos os da sua casa se alegraram muito por terem crido em Deus.

[[v44-16-35]]

^<<v44-16-35,35>>^ Quando o dia amanheceu, os magistrados civis enviaram os guardas^&#42;1^ para dizer ao carcereiro: “Solte esses homens.”

[NOTE]
====
. Ou: “lictores”.
====

[[v44-16-36]]

^<<v44-16-36,36>>^ O carcereiro transmitiu essas palavras a Paulo; disse: “Os magistrados civis mandaram soltar vocês dois. Então, saiam agora e vão em paz.”

[[v44-16-37]]

^<<v44-16-37,37>>^ Mas Paulo lhes disse: “Eles nos açoitaram publicamente sem termos sido julgados,^&#42;1^ embora sejamos romanos, e nos lançaram na prisão. Agora nos mandam embora secretamente? Não! Que venham eles próprios e nos levem para fora.”

[NOTE]
====
. Ou: “sem um processo formal”.
====

[[v44-16-38]]

^<<v44-16-38,38>>^ Os guardas comunicaram então essas palavras aos magistrados civis. Estes ficaram com medo quando ouviram que os homens eram romanos.

[[v44-16-39]]

^<<v44-16-39,39>>^ Assim, foram até lá e lhes pediram desculpas, e, depois de levá-los para fora, pediram-lhes que partissem da cidade.

[[v44-16-40]]

^<<v44-16-40,40>>^ Mas Paulo e Silas, ao saírem da prisão, foram à casa de Lídia. Quando viram os irmãos, os encorajaram; depois partiram.

'''

xref:044-atos/044-atos-015.adoc#v44-15-0[&#60; Capítulo Anterior] | <<v44-16-0,Topo>> | xref:044-atos/044-atos-017.adoc#v44-17-0[Próximo Capítulo &#62;]