include::./index.adoc[]

[[v44-2-0]]
=== Atos dos Apóstolos, 2
// nwt 2015, nwt - Tradução do Novo Mundo da Bíblia Sagrada

[[v44-2-1]]

^<<v44-2-1,1>>^ Então, durante o dia da Festividade de Pentecostes, todos eles estavam juntos no mesmo lugar.

[[v44-2-2]]

^<<v44-2-2,2>>^ De repente, veio do céu um barulho, bem semelhante ao de uma forte rajada de vento, e encheu toda a casa onde estavam sentados.

[[v44-2-3]]

^<<v44-2-3,3>>^ E eles começaram a ver o que pareciam ser línguas de fogo, e elas se espalharam e pousaram, uma sobre cada um deles;

[[v44-2-4]]

^<<v44-2-4,4>>^ e todos ficaram cheios de espírito santo e começaram a falar em línguas, assim como o espírito os capacitava.

[[v44-2-5]]

^<<v44-2-5,5>>^ Naquela ocasião estavam em Jerusalém judeus devotos, de toda nação debaixo do céu.

[[v44-2-6]]

^<<v44-2-6,6>>^ Assim, quando se ouviu aquele som, uma multidão se ajuntou e ficou surpresa, porque cada um ouviu os discípulos falar no seu próprio idioma.

[[v44-2-7]]

^<<v44-2-7,7>>^ Realmente, ficaram muito espantados e disseram: “Não são galileus todos esses que estão falando?

[[v44-2-8]]

^<<v44-2-8,8>>^ Como é que cada um de nós está ouvindo a sua língua nativa?^&#42;1^

[NOTE]
====
. Ou: “a língua do seu nascimento”.
====

[[v44-2-9]]

^<<v44-2-9,9>>^ Entre nós há partos, medos e elamitas, habitantes da Mesopotâmia, da Judeia e da Capadócia, de Ponto e da província da Ásia,

[[v44-2-10]]

^<<v44-2-10,10>>^ da Frígia e da Panfília, do Egito e das regiões da Líbia próximas a Cirene, visitantes vindos de Roma, tanto judeus como prosélitos,

[[v44-2-11]]

^<<v44-2-11,11>>^ cretenses e também árabes. Nós os ouvimos falar em nossas línguas sobre as coisas magníficas de Deus.”

[[v44-2-12]]

^<<v44-2-12,12>>^ Sim, todos ficaram admirados e perplexos, e diziam uns aos outros: “O que significa isso?”

[[v44-2-13]]

^<<v44-2-13,13>>^ No entanto, outros zombavam deles e diziam: “Estão cheios de vinho doce.”^&#42;1^

[NOTE]
====
. Ou: “vinho novo”.
====

[[v44-2-14]]

^<<v44-2-14,14>>^ Mas Pedro se pôs de pé com os Onze e lhes falou bem alto: “Homens da Judeia e todos vocês, habitantes de Jerusalém, prestem atenção e ouçam bem as minhas palavras:

[[v44-2-15]]

^<<v44-2-15,15>>^ Na verdade, estas pessoas não estão bêbadas, como vocês supõem, pois é a terceira hora^&#42;1^ do dia.

[NOTE]
====
. Isto é, por volta das 9 h da manhã.
====

[[v44-2-16]]

^<<v44-2-16,16>>^ Ao contrário, isto é o que foi dito por meio do profeta Joel:

[[v44-2-17]]

^<<v44-2-17,17>>^ ‘“Nos últimos dias”, diz Deus, “derramarei do meu espírito sobre todo tipo de pessoas,^&#42;1^ e os filhos e as filhas de vocês profetizarão, os jovens entre vocês terão visões e os homens idosos entre vocês terão sonhos,

[NOTE]
====
. Lit.: “sobre toda carne”.
====

[[v44-2-18]]

^<<v44-2-18,18>>^ e até mesmo sobre os meus escravos e sobre as minhas escravas derramarei do meu espírito naqueles dias, e eles profetizarão.

[[v44-2-19]]

^<<v44-2-19,19>>^ E realizarei milagres^&#42;1^ em cima, no céu, e sinais embaixo, na terra: sangue, fogo e nuvens de fumaça.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-2-20]]

^<<v44-2-20,20>>^ O sol será transformado em escuridão e a lua em sangue, antes de vir o grande e glorioso dia de Jeová.^&#42;1^

[NOTE]
====
. Veja Ap. A5.
====

[[v44-2-21]]

^<<v44-2-21,21>>^ E todo aquele que invocar o nome de Jeová^&#42;1^ será salvo.”’

[NOTE]
====
. Veja Ap. A5.
====

[[v44-2-22]]

^<<v44-2-22,22>>^ “Homens de Israel, ouçam estas palavras: Jesus, o Nazareno, foi um homem que Deus aprovou diante de vocês com obras poderosas, milagres^&#42;1^ e sinais que Deus fez por meio dele entre vocês, conforme sabem.

[NOTE]
====
. Ou: “portentos”.
====

[[v44-2-23]]

^<<v44-2-23,23>>^ Esse homem, que foi entregue pela estabelecida vontade^&#42;1^ e presciência de Deus, vocês pregaram numa estaca pelas mãos de transgressores e o mataram.

[NOTE]
====
. Ou: “pelo estabelecido conselho”.
====

[[v44-2-24]]

^<<v44-2-24,24>>^ Mas Deus o ressuscitou, livrando-o das dores^&#42;1^ da morte, porque não era possível que ela o mantivesse preso.

[NOTE]
====
. Ou, possivelmente: “cordas”.
====

[[v44-2-25]]

^<<v44-2-25,25>>^ Pois Davi diz a respeito dele: ‘Mantenho Jeová^&#42;1^ constantemente diante de mim,^&#42;2^ pois ele está à minha direita para que eu nunca seja abalado.

[NOTE]
====
. Veja Ap. A5.
. Ou: “diante dos meus olhos”.
====

[[v44-2-26]]

^<<v44-2-26,26>>^ Por essa razão, meu coração ficou animado e minha língua se alegrou muito. E eu viverei^&#42;1^ em esperança;

[NOTE]
====
. Lit.: “a minha carne morará”.
====

[[v44-2-27]]

^<<v44-2-27,27>>^ porque não me deixarás^&#42;1^ na Sepultura^&#42;2^ nem permitirás que o teu leal conheça a decomposição.

[NOTE]
====
. Ou: “não deixarás a minha alma”.
. Ou: “no Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v44-2-28]]

^<<v44-2-28,28>>^ Tu me fizeste conhecer os caminhos da vida; tu me encherás de alegria na tua presença.’^&#42;1^

[NOTE]
====
. Ou: “diante da tua face”.
====

[[v44-2-29]]

^<<v44-2-29,29>>^ “Homens, irmãos, permitam-me falar-lhes com franqueza sobre o patriarca Davi: ele morreu e foi enterrado, e seu túmulo está entre nós até o dia de hoje.

[[v44-2-30]]

^<<v44-2-30,30>>^ Visto que era profeta e sabia que Deus lhe havia jurado que faria um dos seus descendentes^&#42;1^ se sentar no seu trono,

[NOTE]
====
. Lit.: “um procedente do fruto dos seus lombos”.
====

[[v44-2-31]]

^<<v44-2-31,31>>^ ele previu a ressurreição do Cristo e falou sobre ela, que ele não seria abandonado na Sepultura^&#42;1^ e que a sua carne não conheceria a decomposição.

[NOTE]
====
. Ou: “no Hades”, isto é, a sepultura comum da humanidade. Veja o Glossário.
====

[[v44-2-32]]

^<<v44-2-32,32>>^ Deus ressuscitou a esse Jesus, e disso todos nós somos testemunhas.

[[v44-2-33]]

^<<v44-2-33,33>>^ Portanto, visto que ele foi enaltecido à direita de Deus e recebeu do Pai o prometido espírito santo, derramou o que vocês estão vendo e ouvindo.

[[v44-2-34]]

^<<v44-2-34,34>>^ Pois Davi não subiu aos céus, mas ele diz: ‘Jeová^&#42;1^ disse ao meu Senhor: “Sente-se à minha direita

[NOTE]
====
. Veja Ap. A5.
====

[[v44-2-35]]

^<<v44-2-35,35>>^ até que eu ponha os seus inimigos debaixo dos seus pés.”’^&#42;1^

[NOTE]
====
. Ou: “como escabelo para os seus pés”.
====

[[v44-2-36]]

^<<v44-2-36,36>>^ Portanto, que toda a casa de Israel tenha a plena certeza de que Deus o fez Senhor e Cristo, a esse Jesus, que vocês mataram numa estaca.”

[[v44-2-37]]

^<<v44-2-37,37>>^ Quando ouviram isso, ficaram com o coração aflito e disseram a Pedro e aos outros apóstolos: “Homens, irmãos, o que devemos fazer?”

[[v44-2-38]]

^<<v44-2-38,38>>^ Pedro lhes disse: “Arrependam-se, e cada um de vocês seja batizado em nome de Jesus Cristo, para o perdão dos seus pecados, e vocês receberão a dádiva^&#42;1^ do espírito santo.

[NOTE]
====
. Ou: “dádiva gratuita”.
====

[[v44-2-39]]

^<<v44-2-39,39>>^ Porque a promessa é para vocês e para os seus filhos, e para todos os que estão longe, todos os que Jeová,^&#42;1^ nosso Deus, chamar para si.”

[NOTE]
====
. Veja Ap. A5.
====

[[v44-2-40]]

^<<v44-2-40,40>>^ E ele dava um testemunho cabal e os exortava com muitas outras palavras, dizendo: “Sejam salvos desta geração pervertida.”

[[v44-2-41]]

^<<v44-2-41,41>>^ Assim, os que aceitaram com alegria as suas palavras foram batizados, e naquele dia cerca de 3.000 pessoas^&#42;1^ se juntaram a eles.

[NOTE]
====
. Ou: “almas”.
====

[[v44-2-42]]

^<<v44-2-42,42>>^ Dedicavam-se assim aos ensinamentos dos apóstolos, à convivência^&#42;1^ uns com os outros, a tomar refeições juntos e às orações.

[NOTE]
====
. Ou: “a partilhar”.
====

[[v44-2-43]]

^<<v44-2-43,43>>^ Realmente, todos^&#42;1^ ficaram com medo, e muitos milagres^&#42;2^ e sinais começaram a ocorrer por meio dos apóstolos.

[NOTE]
====
. Ou: “todas as almas”.
. Ou: “portentos”.
====

[[v44-2-44]]

^<<v44-2-44,44>>^ Todos os que se tornaram crentes estavam juntos e compartilhavam todas as coisas uns com os outros;

[[v44-2-45]]

^<<v44-2-45,45>>^ vendiam seus bens e propriedades e repartiam entre todos o valor recebido, de acordo com a necessidade de cada um.

[[v44-2-46]]

^<<v44-2-46,46>>^ Estavam constantemente no templo, dia após dia, unidos no mesmo propósito; tomavam as refeições nas casas uns dos outros e compartilhavam seu alimento com grande alegria e sinceridade de coração,

[[v44-2-47]]

^<<v44-2-47,47>>^ louvando a Deus e cativando a simpatia de todo o povo. Ao mesmo tempo, Jeová^&#42;1^ diariamente continuava a lhes acrescentar os que estavam sendo salvos.

[NOTE]
====
. Veja Ap. A5.
====

'''

xref:044-atos/044-atos-001.adoc#v44-1-0[&#60; Capítulo Anterior] | <<v44-2-0,Topo>> | xref:044-atos/044-atos-003.adoc#v44-3-0[Próximo Capítulo &#62;]